maxwell_3d: fix out of bounds array access in size estimation
yuzu-emu/yuzu pull request #10069
Opened 2023-04-20 03:26 UTC by liamwhite

4 is a possible value for byte_size, which is out of bounds of an array of size 4. This seems to have intended to use the log2 of byte_size to index the array.

2023-04-20 10:27 UTC, vonchenplus requested changes

2023-04-20 10:27 UTC, vonchenplus commented on src/video_core/engines/maxwell_3d.cpp
>          std::numeric_limits<u32>::max(), std::numeric_limits<u32>::max()};
```suggestion
        std::numeric_limits<u32>::max()};
```

2023-04-21 01:22 UTC, vonchenplus approved these changes

2023-04-22 12:45 UTC, FernandoS27 approved these changes

2023-04-22 12:47 UTC, FernandoS27 submitted a review, later dismissed

2023-04-22 12:47 UTC, FernandoS27 commented on src/video_core/engines/maxwell_3d.cpp
> +    const size_t log2_byte_size = Common::Log2Floor64(byte_size);
Should be Ceil, not floor

2023-04-22 14:12 UTC, liamwhite commented on src/video_core/engines/maxwell_3d.cpp
> +    const size_t log2_byte_size = Common::Log2Floor64(byte_size);
Are you sure? The only inputs are 1, 2, and 4, which are all powers of two so ceil and floor are the same.

2023-04-22 14:22 UTC, FernandoS27 commented on src/video_core/engines/maxwell_3d.cpp
> +    const size_t log2_byte_size = Common::Log2Floor64(byte_size);
> 

in case we evr deal with size 3 or some not power of 2.

2023-04-24 10:36 UTC, FernandoS27 approved these changes

2023-04-24 10:36 UTC, merged