Allow fully customised controller hotkeys
yuzu-emu/yuzu pull request #10107
Opened 2023-04-28 01:25 UTC by grimkor

This PR moves away from prefixing `Home+` on all controller hotkey keybinds and instead allows for fully customisable mapping.

Things to note are:
- Work has gone into protecting the TAS functionality from triggering controller hotkeys.
- I moved away from a separate Home/Screenshot button, it looked like the main purpose of this was for protecting against TAS inputs which I have found a method to do without needing to single out these buttons.
- This is my first time working with C++ and I am very open that I have gaps in better ways of doing some of this work.

Unrelated to the work but there is an issue I found where you can record while in playback mode that probably deserves its own issue.

Closes  #10093.

2023-04-28 16:55 UTC, grimkor commented on src/yuzu/configuration/configure_hotkeys.cpp
> +    (*input_setter)(button, cancel);
Moved above so lines 159-160 work

2023-04-28 17:01 UTC, grimkor commented
Updated the PR based on feedback from @german77 regarding npad state order and how I can't just tack on to it.

The only thing I would like help to figure out with this PR is that the line linked below has to be there otherwise Home/Capture buttons get stuck after binding them and I could not figure out where that's being caused.

https://github.com/yuzu-emu/yuzu/pull/10107/files#diff-9dcf85d028051089f92291485b82cf879ecbbe41d5121ab88a5deb2afc195448R191

2023-04-30 11:36 UTC, grimkor commented
Upon feedback I've changed the listener for binding a shortcut to require a Home or Capture button rather than any NPad button, this puts the restriction to requiring 2 buttons, one of which MUST be a Capture or Home button.

Interestingly I've noticed that in mainline if you hold Capture and press any button on the controller it'll re-trigger the held button's hotkey (in this case trigger a screenshot). This makes sense given how it currently looks for hotkeys but might be something to look at.

I'm new to this and was wondering if we could take a list of inputs in a given polling period (eg 200ms) and trigger the hotkey with the highest number of buttons required? This won't completely remove the problem but it would stop things like Screenshot+X triggering both Screenshot  and Screenshot+X bindings unless they were pressed pretty far apart.

2023-04-30 15:11 UTC, FearlessTobi requested changes
I've only reviewed the code itself.
For the input-specific stuff, @german77 please take a look.

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> +        bool is_home_pressed = this->controller->GetHomeButtons().home != 0;
```suggestion
        const auto home_pressed = this->controller->GetHomeButtons().home != 0;
```

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> +        bool is_capture_pressed = this->controller->GetCaptureButtons().capture != 0;
```suggestion
        const auto capture_pressed = this->controller->GetCaptureButtons().capture != 0;
```

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> +QString ConfigureHotkeys::GetButtonCombinationName(Core::HID::NpadButton button, bool home = false,
```suggestion
QString ConfigureHotkeys::GetButtonCombinationName(Core::HID::NpadButton button, const bool home_pressed, const bool capture_pressed) const { 
```

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> +    QString some_string = QStringLiteral("");
```suggestion
    QString button_combination;
```

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> -    return tr("Invalid");
I don't see why this needed to be changed here

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> -
this newline shouldn't have been removed

2023-04-30 15:11 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +        return action_name.toStdString() == "TAS Record";
Does this work when the UI is in a language different from English?

2023-05-02 08:17 UTC, MonsterDruide1 commented
By the way, recording during TAS playback is more or less intended. It's a positive side effect that can be used to "extend" existing TASes, by playing back the existing file, then taking over and doing more inputs manually.

2023-05-07 10:04 UTC, grimkor commented on src/yuzu/main.cpp
> +        return action_name.toStdString() == "TAS Record";
I checked again and while it does work on all languages I think your question is legitimate and this is a weak solution. What do you think if instead I change `LinkActionShortcut()` to the following:

`void LinkActionShortcut(QAction* action, const QString& action_name, bool tas_allowed);`

And it defaults to `false` to save putting in a value every time?

@german77 maybe a question for you?

2023-05-07 10:12 UTC, grimkor commented
> By the way, recording during TAS playback is more or less intended. It's a positive side effect that can be used to "extend" existing TASes, by playing back the existing file, then taking over and doing more inputs manually.

Cool I'll make sure that functionality stays intact then, thanks for letting me know.

2023-05-07 14:19 UTC, FearlessTobi requested changes
Some of my older comments also have not been addressed yet.

2023-05-07 14:19 UTC, FearlessTobi commented on src/yuzu/configuration/configure_hotkeys.cpp
> +        const QString button_string =
```suggestion
        const QString button_string = GetButtonCombinationName(button, home_pressed, capture_pressed);
```

2023-05-07 14:19 UTC, FearlessTobi commented on src/yuzu/main.cpp
> -
should not have been changed

2023-05-07 14:19 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +
should not have been changed

2023-05-07 14:19 UTC, FearlessTobi commented on src/yuzu/main.cpp
> -    // Disable system buttons to prevent TAS from recording a hotkey
should not have been changed

2023-05-07 15:23 UTC, grimkor commented
> Some of my older comments also have not been addressed yet.

Sorry mate I'll get that fixed, thought I had them all.

2023-05-07 15:53 UTC, grimkor commented on src/yuzu/configuration/configure_hotkeys.cpp
> -    return tr("Invalid");
Moved it back to `tr()`, if you are asking about the change to the whole method then it allows for more complex hotkeys to be bound such as `Home+Screenshot+L+R` , which would be nice for some shortcuts like restarting/stopping emulation making it harder to fumble and easier to trigger on purpose.

2023-05-10 16:51 UTC, german77 commented on src/yuzu/main.cpp
> +#include <regex>
This isn't used anymore

2023-05-11 03:23 UTC, german77 approved these changes

2023-05-16 14:06 UTC, merged