yuzu-qt: Track play time
yuzu-emu/yuzu pull request #10519
Opened 2023-05-31 09:09 UTC by mariv1k

In this PR I wanted to try adding a time played timer for games. The time is displayed in the main window as an extra column on the far right, which can be toggled.

![Screenshot_2023-05-31_10 22 24](https://github.com/yuzu-emu/yuzu/assets/66087392/888f432e-65a8-47ed-9159-9ec96286f424)

The data is stored in the Yuzu config directory inside the `play_time.bin` file as two `u64`, one for the `program_id` and one for the seconds of play time.

![image](https://github.com/yuzu-emu/yuzu/assets/66087392/648ccbbd-68a4-4b6d-8f40-98102eb337c4)

I have implemented this my way so it is far from perfect and some extra code may be unwanted.

2023-05-31 13:24 UTC, bm01 commented
May I suggest adding a way to clear it? Some users might want to be able to do so between two playthroughs for example, or after months / years of not playing a game.
In fact, why not save it to user profiles instead of globally, and allow different profiles to track different play times?

2023-05-31 14:44 UTC, mariv1k commented
> May I suggest adding a way to clear it on a per game basis? Some users might want to be able to do so between two playthroughs for example, or after months / years of not playing a game. In fact, why not save it to user profiles instead of globally, and allow different profiles to track different play times?

That'd be nice. I'll get to it

2023-05-31 18:26 UTC, german77 commented
I often close yuzu while playing a game. This doesn't seem to register any time unless I explicitly hit the stop button first. Can you address that issue. 

Also some games crash after a few hours of game play. Maybe implement something to update the counter every 15 minutes or so. So the time tracked is somewhat accurate.

2023-05-31 20:01 UTC, FearlessTobi submitted a review, later dismissed
A few suggestions.
From looking at the code, this also seems to ignore pausing the game?

2023-05-31 20:01 UTC, FearlessTobi commented on src/yuzu/uisettings.h
> +    // Play time
this is pretty self explanatory. just put this setting directly below the other ones

2023-06-03 16:52 UTC, Tachi107 commented on src/yuzu/play_time.cpp
> +constexpr char PlayTimeFilename[] = "play_time.bin";
Nit: this should probably be `static constexpr`

2023-06-07 23:44 UTC, german77 commented on src/common/fs/fs_paths.h
> +#define PLAY_TIME_DIR "play_time"
Should be in lexicographical order

2023-06-07 23:44 UTC, german77 commented on src/common/fs/path_util.cpp
> +        GenerateYuzuPath(YuzuPath::PlayTimeDir, yuzu_path / PLAY_TIME_DIR);
ditto

2023-06-07 23:44 UTC, german77 commented on src/common/fs/path_util.h
> +    PlayTimeDir,    // Where play time data is stored.
ditto

2023-06-07 23:49 UTC, german77 commented on src/yuzu/main.h
> +#include "yuzu/play_time.h"
This was marked as resolved but is not using a forward declaration.

2023-06-07 23:55 UTC, german77 commented
Can you rebase against latest master. With the android changes CI broke and didn't provide the artifacts.

2023-06-08 14:02 UTC, german77 commented on src/yuzu/main.h
> +#include "yuzu/play_time.h"
Seems like it's now forward declared. This line needs to be removed from the header and added to the cpp instead

2023-06-09 16:21 UTC, german77 commented on src/yuzu/play_time.h
> +#include <thread>
`#include <optional>`
Needs to be added.

2023-06-11 11:47 UTC, mariv1k commented
If the remaining check passes then this should be good and ready to use

2023-06-11 12:23 UTC, v1993 commented
Please rebase on master instead of merging it into branch (see [Typical Git Workflow](https://github.com/yuzu-emu/yuzu/wiki/Typical-Git-Workflow) on yuzu wiki for future reference). Interactive rebase is your friend here.

2023-06-11 21:38 UTC, german77 approved these changes

2023-06-17 02:10 UTC, liamwhite commented on src/yuzu/play_time.h
> +    std::thread play_time_thread;
jthread (use common/polyfill_thread.h)

2023-06-17 02:10 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +    cv.wait_for(lock, duration, [this] { return interrupt.load(); });
Seems like much of this functionality may a clone of StoppableTimedWait?
```cpp
void PlayTimeManager::Start() {
    UpdateTimestamp();
    interrupt.store(false);
    play_time_thread = std::jthread{&PlayTimeManager::AutoTimestamp, this};
}

void PlayTimeManager::Stop() {
    play_time_thread.request_stop();
    play_time_thread.join();
    Save();
}

void PlayTimeManager::AutoTimestamp(std::stop_token stop_token) {
    while (Common::StoppableTimedWait(stop_token, std::chrono::seconds{30})) {
        Save();
    }
}
```
and then you could get rid of the boolean entirely, if I'm understanding this correctly.

2023-06-17 02:10 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +    const auto duration = 5min;
IIRC, games send prepos every 30 seconds or so; that might be a more optimal sleep duration.

2023-06-17 02:10 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +        play_time_elements.at(it - play_time_elements.begin()).play_time += add_play_time;
```
it->play_time += add_play_time
```
Maybe a flat_map would be a better data structure for this?

2023-06-17 02:10 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +    if (Common::FS::Exists(filename.value())) {
You shouldn't need to check this as you tried to open in the previous step; if it's open, it surely exists?

2023-06-17 02:11 UTC, liamwhite commented
(also, apologies for the delay - we have a lot of new contributors, and are barely keeping up)

2023-06-19 00:07 UTC, griky15 commented
So how do i get that on my yuzu?

2023-06-20 19:39 UTC, Moqxi commented
Does this work ? i have been trying to find a way to see my game hours on zelda totk. I just want to know how to use this

2023-06-25 22:01 UTC, gidoly commented
can you resolve pr reviews?

2023-07-02 15:46 UTC, liamwhite commented
We are still waiting for you to resolve review comments

2023-07-02 17:43 UTC, mariv1k commented on src/yuzu/play_time.cpp
> +    if (Common::FS::Exists(filename.value())) {
Well, I was playing with this a little bit and this worked better for me, maybe I'm wrong.

2023-07-02 21:27 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +void PlayTimeManager::AutoTimestamp() {
This should take the stop_token as an argument. It should not be a class member.
```cpp
void PlayTimeManager::Start() {
    UpdateTimestamp();
    play_time_thread = std::jthread([&](std::stop_token token) { AutoTimestamp(stop_token); });
}

2023-07-02 21:27 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +    if (Common::FS::Exists(filename.value())) {
Worked better in what sense?

2023-07-03 17:22 UTC, liamwhite commented on src/yuzu/play_time.cpp
> +void PlayTimeManager::AutoTimestamp() {
This was marked as resolved, but the issue was not resolved - you can follow the sample for direction.

2023-07-24 02:05 UTC, benjamimgois commented
I was looking for this feature.  Hope it got merged soon

2023-07-24 02:34 UTC, liamwhite commented
We are waiting for an update from the author.

2023-08-14 15:27 UTC, KantoGreen commented
any updates when this will be merged?

2023-08-27 18:26 UTC, lat9nq approved these changes

2023-08-27 21:17 UTC, FearlessTobi requested changes

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +    game_list->PopulateAsync(UISettings::values.game_dirs);
Reloading the game list every time a game is stopped is really not a great solution.

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +    this->running_program_id = program_id;
```suggestion
    running_program_id = program_id;
```

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +inline void PlayTimeManager::UpdateTimestamp() {
does this need to be inline?

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +        play_time_elements.at(it - play_time_elements.begin()).play_time += add_play_time;
why do we need to subtract `play_time_elements.begin()` here?

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +        return QLatin1String("");
```suggestion
        return {};
```

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +    static constexpr std::array units{"m", "h"};
doesn't seem like this indirection with another array is needed here if it's only used in one place?

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +    inline bool operator==(const PlayTimeElement& other) const {
should also provide != operator for logical equality.
also does this need to be inline?

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +    inline bool operator==(const u64 _program_id) const {
not sure if we need this since we have the other comparison just above this and checking u64 for equality is trivial

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +#include "core/core.h"
is this needed?

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +public:
this is already public

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +public:
dito

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +bool UpdatePlayTime(u64 program_id, u64 add_play_time);
should probably be nodiscord as well then

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.cpp
> +
```suggestion
```

2023-08-27 21:17 UTC, FearlessTobi commented on src/yuzu/play_time.h
> +#include <mutex>
is this used?

2023-09-05 23:43 UTC, LuluGrande commented
Is there a way to edit the playtime?

2023-09-14 04:27 UTC, karasuhebi commented
I'm confused. Is this part of mainline yuzu or not? It was featured and linked to in the progress report but I don't see it anywhere.

2023-09-19 00:41 UTC, german77 commented
Closes: #4018

2023-10-02 08:42 UTC, mr-sihc commented
guys, I hate to bump... But this looks like it has been inactive for soo long, can anyone please finish it? Its been open since march...

2023-10-08 21:11 UTC, merged

2023-10-10 16:07 UTC, RecentRunner commented
Just wanted to say, thank you for your work <3