Add UI to import firmware and share logs
yuzu-emu/yuzu pull request #10578
Opened 2023-06-02 19:08 UTC by PabloG02

2023-06-02 20:01 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                .show()
Please place the logic for this dialog in a dedicated DialogFragment. I'd also like to see the coroutine that unzips the file placed into a viewmodel so we don't crash on configuration change.

2023-06-02 20:02 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
> +                if (!entryFile.canonicalPath.startsWith(destDir.canonicalPath + File.separator)) {
I should have caught this before but could you match the pattern that we use here for catching zip exploits?
https://github.com/yuzu-emu/yuzu/blob/38728555470d7157176be744cb8c9d62c88b73bc/src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GpuDriverHelper.kt#L39

2023-06-02 20:02 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
> +                if (!entryFile.canonicalPath.startsWith(destDir.canonicalPath + File.separator)) {
Additionally, make sure that you catch this error and make sure the app doesn't crash as a result

2023-06-02 20:03 UTC, t895 commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="firmware_installed_failure_description">Check that the ZIP contains a firmware.</string>
```suggestion
    <string name="firmware_installed_failure_description">Check that the ZIP contains firmware.</string>
```

2023-06-03 09:07 UTC, bunnei commented
@PabloG02 apologies -- Lime was rebased on master. Do you mind rebasing this PR on lime?
(We'll merge lime to master this weekend, so hopefully not an issue going forward!)

2023-06-03 10:40 UTC, PabloG02 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
> +                if (!entryFile.canonicalPath.startsWith(destDir.canonicalPath + File.separator)) {
I think I've matched it, though as I'm not sure I'll let you judge first before resolving

2023-06-03 10:43 UTC, PabloG02 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                .show()
I've tried to move it to a dedicated DialogFragment, but for some reason I'm not able to dismiss it if I rotate the phone. I'm getting a `Fragment not associated with a fragment manager`. Regarding moving the coroutine to a viewmodel, I still lack the knowledge to do it that way. I don't really know much about Android dev :/

2023-06-03 12:23 UTC, AbandonedCart commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                .show()
Are you trying to dismiss the fragment or the dialog object inside it?

2023-06-03 15:40 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
> +                if (!entryFile.canonicalPath.startsWith(destDir.canonicalPath + File.separator)) {
It looks good, but would you also mind throwing a `SecurityException` instead?

2023-06-03 15:49 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                .show()
> Regarding moving the coroutine to a viewmodel, I still lack the knowledge to do it that way. I don't really know much about Android dev :/

There's a few ways you could handle communication between fragments. Using a viewmodel is probably the best way to in this case.

Try following what I have set up in these files.
https://github.com/dolphin-emu/dolphin/blob/master/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/dialogs/TaskDialog.kt

https://github.com/dolphin-emu/dolphin/blob/master/Source/Android/app/src/main/java/org/dolphinemu/dolphinemu/model/TaskViewModel.kt

Here the dialog triggers the start action in the view model, if the user starts a config change the dialog can restart without the job starting again, and when it's complete, just dismiss the dialog by watching the LiveData variable that marks the task as complete.

2023-06-03 16:05 UTC, AbandonedCart commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                    Toast.makeText(applicationContext, getString(R.string.fatal_error), Toast.LENGTH_LONG)
This needs to be wrapped in a `withContext(Dispatchers.Main)` or posted with a Handler.

2023-06-03 16:29 UTC, AbandonedCart commented
<img width="332" alt="Screen Shot 2023-06-03 at 12 28 10 PM" src="https://github.com/yuzu-emu/yuzu/assets/1173913/ed93cfb1-f33c-447e-8000-ca47dd69e0a5">

Looks like the folder structure got a bit messed up. There is a second `src/android` inside `src/android` where your additions ended up.

2023-06-04 05:47 UTC, Schplee requested changes
A few changes to the wording

2023-06-04 05:47 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="firmware_installed_failure">Firmware installation failed.</string>
```suggestion
    <string name="firmware_installed_failure">Firmware installation failed</string>
```

2023-06-04 05:47 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="firmware_installed_failure_description">Check that the ZIP contains firmware.</string>
```suggestion
    <string name="firmware_installed_failure_description">Verify that the ZIP contains valid firmware and try again.</string>
```

2023-06-04 05:47 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_firmware_description">Required to boot some games</string>
```suggestion
    <string name="install_firmware_description">Firmware must be in a ZIP archive and is needed to boot some games</string>
```

2023-06-04 05:47 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="share_log">Share log</string>
```suggestion
    <string name="share_log">Share debug logs</string>
```

2023-06-04 05:47 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="share_log_description">Share the log file</string>
```suggestion
    <string name="share_log_description">Share yuzu's log file to debug issues</string>
```

2023-06-04 05:59 UTC, AbandonedCart commented
Appears if the process works, everything is fine. If the zip fails (accidentally tested with an incomplete zip), you get the fatal error toast and the dialog is locked in place until the entire app is closed. Probably needs some variation of dismiss at that toast.

2023-06-04 14:06 UTC, PabloG02 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                .show()
What I've done seems to work, though I don't know to what extent it is right. I might have overdone trying to make it as generic as possible 😅

2023-06-04 14:27 UTC, PabloG02 commented
I have to investigate the Fatal Error because I also have zips with save files that worked before, but now don't. If I had to guess, it is probably due to the change in the pattern to capture zip exploits, so I might need to revert to the original one I had.

2023-06-04 23:04 UTC, t895 reviewed
Just an extra comment. What would you think about adding a dialog somewhere to clarify how to zip your firmware to be imported here? @Schplee any thoughts?

2023-06-04 23:04 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
> +                messageToShow
Lift out assignment
```suggestion
                    messageToShow = if (unfilteredNumOfFiles != filteredNumOfFiles) {
                        MessageDialogFragment.newInstance(
                            R.string.firmware_installed_failure,
                            R.string.firmware_installed_failure_description
                        )
                    } else {
                        firmwarePath.deleteRecursively()
                        cacheFirmwareDir.copyRecursively(firmwarePath, true)
                        getString(R.string.save_file_imported_success)
                    }
                } catch (e: Exception) {
                    messageToShow = getString(R.string.fatal_error)
                } finally {
                    cacheFirmwareDir.deleteRecursively()
                }
                messageToShow
```

2023-06-05 06:47 UTC, PabloG02 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/IndeterminateProgressDialogFragment.kt
> +        }
I couldn't do it like that, because it was throwing `IllegalStateException: Fragment IndeterminateProgressDialogFragment not attached to an activity`, but I managed to remove the unckecked cast doing it in a different manner.

2023-06-05 18:39 UTC, t895 commented
> It would be best if a dialog box was generated and had 3 button options: "Learn more" which would link to a guide on the yuzu website

I should probably think about writing a general guide with golden and you or something then

2023-06-05 23:17 UTC, t895 commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
> +            startActivity(Intent.createChooser(intent, "Share log"))
(I'm surprised that I missed this)
Please use a string resource.

2023-06-05 23:17 UTC, t895 approved these changes
Besides the comment I just left, this looks great! Thanks again!

2023-06-06 00:33 UTC, Schplee approved these changes

2023-06-06 00:41 UTC, bunnei commented on src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
> +            startActivity(Intent.createChooser(intent, "Share log"))
Addressed this so we can merge today.

2023-06-06 00:41 UTC, merged