android: Add update and DLC support
yuzu-emu/yuzu pull request #10705
Opened 2023-06-10 23:20 UTC by german77

Allows installing game updates and DLC on Android. There's no way to check if the game has an update other than by checking in-game. Hopefully, once the per-game info is completed, you will be able to confirm which updates you have installed.

2023-06-11 02:04 UTC, Schplee requested changes

2023-06-11 02:04 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_success_overwrite">Update or DLC were overwritten successfully</string>
```suggestion
    <string name="install_game_update_success">Game content installed successfully</string>
    <string name="install_game_update_success_overwrite">Game content overwritten successfully</string>
```

2023-06-11 02:04 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_failure_base">To avoid possible conflicts, we discourage users from installing base games to the NAND</string>
```suggestion
    <string name="install_game_update_failure">Error installing file to NAND</string>
    <string name="install_game_update_failure_description">Update or DLC installation failed</string>
    <string name="install_game_update_failure_base">To avoid possible conflicts, we discourage users from installing base games to the NAND</string>
```
Errors should be a dialog box with reason for error and next steps. Will discuss specifics in Discord

2023-06-11 03:19 UTC, Schplee requested changes

2023-06-11 03:19 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_failure_file_extension">The file provided is not supported</string>
```suggestion
    <string name="install_game_update_failure_file_extension">The selected file type is not supported. Only NSP and XCI content is supported for this action. Please verify the game content is valid.</string>
```
In this prompt, can we also have a "Learn more" button on the left of the dialog box that links to https://yuzu-emu.org/help/quickstart/#dumping-installed-updates

2023-06-11 03:19 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_success_overwrite">Game content were overwritten successfully</string>
```suggestion
    <string name="install_game_update_success_overwrite">Game content was overwritten successfully</string>
```

2023-06-11 03:19 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_failure_base">To avoid possible conflicts, we discourage users from installing base games to the NAND</string>
```suggestion
    <string name="install_game_update_failure_base">Installation of base games isn't permitted in order to avoid possible conflicts. Please select an update or DLC instead.</string>
```

2023-06-11 03:19 UTC, Schplee commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="install_game_update_failure_description">Update or DLC installation failed</string>
```suggestion
    <string name="install_game_update_failure_description">Game content installation failed. Please ensure content is valid and that the prod.keys file is installed.</string>
```
In this prompt, can we also have a "Learn more" button on the left of the dialog box that links to https://yuzu-emu.org/help/quickstart/#dumping-installed-updates

2023-06-11 07:18 UTC, Schplee approved these changes

2023-06-11 16:22 UTC, liamwhite commented on src/android/app/src/main/jni/native.cpp
> +        const auto qt_raw_copy = [](const FileSys::VirtualFile& src,
```suggestion
        const auto copy_func = [](const FileSys::VirtualFile& src,
```

2023-06-11 20:03 UTC, brujo5 commented
and will there be an option to remove the updates and dlc as well?  it would be simpler to add support to read updates and dlc inside an XCI like eggy

2023-06-11 20:19 UTC, AbandonedCart commented
> Otherwise it is a waste of memory in the phone as the storage is limited in android

It installs to folders stored on external storage. To minimize storage use, you would install the update, then remove the source file, not unlike an actual Switch. The alternative you requested is to eat up a ton of RAM and other resources to do ongoing reads from a compressed file.

2023-06-11 20:24 UTC, brujo5 commented
> > Otherwise it is a waste of memory in the phone as the storage is limited in android
> 
> It installs to folders stored on external storage. To minimize storage use, you would install the update, then remove the source file, not unlike an actual Switch. The alternative you requested is to eat up a ton of RAM and other resources to do ongoing reads from a compressed file.

Excellent explanation, I didn't know that, seeing it that way you are absolutely right. Thx

2023-06-13 00:03 UTC, bunnei approved these changes

2023-06-13 00:03 UTC, merged