general: Reimplement per-game configurations
yuzu-emu/yuzu pull request #10839
Opened 2023-06-18 21:30 UTC by lat9nq

Rework of #4098

This is part of a grander plan to support either downloadable or compiled configs with settings specific to different titles. To reach that goal, I wanted to be able to iterate through all of the settings in a container. The implications of having a container to manipulate all of the settings, however, spiraled into a long-needed rework of all things settings and configurations.

This does a few things:
- Settings are now registered to a map when they are initialized, organized by category.
- Frontend configurations can iterate over the map to read or write all of the settings per category.
- The Qt frontend saw an extensive rework of per-game settings, opting to replace the existing compiled Qt widgets with widgets generated at runtime off of the map.

Some noteworthy changes in common including using explicit instantiation to declare the separate Setting types. We also now can log all of the settings using written name of each enum through the use of some macros. The logging changes also indicated if a setting was [M]odified or if it is [C]ustom (or if nothing was touched, just `--`).

The SDL2 and Qt frontends were modestly modified to take advantage of the map of settings. I couldn't take full advantage of translating the category to a string here in the Qt frontend, but we still now can get rid of a ton of repeated work by just sending the container to a for_each. Between the changes here as well as the SDL2 frontend, it is now much more difficult for a spontaneous new setting to be forgotten in either frontend. For instance, even if the developer forgets to add the description for the setting in `default_ini.h`, the new setting will still be read if the user manually adds it.

The Android frontend was mostly not touched with respect to this, since I'm not sure what the implications are of reading settings there that shouldn't be. @bunnei or @t895 let me know if I can do the same thing to it as I did the SDL2 frontend.

I'm most excited by the UI changes in the Qt frontend. I've rid of the semi-tristate checkboxes and its other highlighted cronies by adding a clear button by the side of each setting. Whenever a setting is modified, the clear button becomes visible. This indicates that the setting is active for per-game settings. Clicking it will clear the custom state. This behavior is inspired by the configuration in [Lutris](https://lutris.net/), and was originally what I wanted to do for per-game settings in the first followup.

The UI changes in the Qt frontend are possible by removing the existing data in the `.ui` files for those settings, then creating a system to generate those widgets. Each type of widget (e.g. QCheckBox, QLineEdit) has a specific function that defines how the widget is created, read from, and cleared. Those functions are passed around in the configuration code to define when and how to use them.

Translation data has been moved to shared_translation.cpp now. I tried very hard to move everything as closely as possible as they were represented before, but manually opening the old config files and copy-pasting is very error-prone. I'd appreciate another pair of eyes going over those.

There are major disadvantages to this approach compared to before. This relies heavily on the reintroduced BasicSetting class, which is now an abstract class that defines a lot of identification functions, as well as notably a lot of code for interacting with the setting data through **strings**. The base class cannot be a template for purposes of placing settings in a container. For interacting with config files, this is fine since realistically we're interacting with strings anyway. For the Qt configuration, unfortunately this means a lot of string operations have to occur in order to manipulate the settings. In practice, the computation time penalty did not seem significant (time changed from 0.2 sec to 0.3 sec on an ancient Core 2 Quad Q9650 to open the game properties window, within error on my Core i5-11600k), but maybe fresh eyes can shed light on any possible optimizations.

Another disadvantage is that implementing a complex setting in the Qt frontend can possibly be more convoluted than before. Since the widget handles need to come from the widget builder, there has to be code in the builder loop to get the handles out from, which adds considerable size to the loop.  A new boolean or enum class setting is probably easiest to add from this change, while a new complex setting (like VSync mode) will probably not feel much better to implement. There is probably room for improvement with the widget builder interactions.

As a bit of cleanup, I tried to make the Settings enums follow our coding guidelines a bit more closely, cleaning up a lot of I suspect my own sins over the years here.

With these changes, if a developer wanted to add a new boolean setting with per-game support, they'd modify common/settings.h to include the new setting, add the translation for it in yuzu/configuration/shared_translation.cpp, and be off implementing the setting wherever it's needed.

A new enum class setting needs a bit extra work, adding the enum to common/settings_enums.h and then make sure the combobox translation exists in shared_translation.cpp.

Other kinds of settings will need to make use of splitting off the relevant builder loop and specifying the various parameters that are passed to the Widget.

Lastly, some of the settings in the General tab were moved to various other tabs. Limit Speed Percent is now in Graphics. Multi-core is now in System under the Core group, where Unsafe memory was also moved to. In game properties, this left the General tab empty, so it was removed. The Astc async and accelerate options were condensed into one drop-down option in Graphics. A bug was fixed in Limit Speed Percent, and it now allows modifying it in per-game settings when a game is not running (#10307). A bug was fixed in Custom RTC, and it is now a working setting in per-game settings (#6321).

2023-06-19 11:50 UTC, Squall-Leonhart commented
> Limit Speed Percent is now in Graphics

Speed is not just a factor of graphics.

2023-06-19 19:41 UTC, lat9nq commented
> Speed is not just a factor of graphics.

I'd like to hear opinions about moving it to core. I wanted to put it there, but it felt like it was having more effects in graphics-type files than core ones.

It is currently used here:
```
core/perf_stats
core/hle/service/nvnflinger
```

perf_stats is only really using it for single-core (multi-core enabled set to off). nvnflinger is using it for multi-core, which is the typical use case, but nvnflinger to me is sort of its own area of graphics code since it is interacting with the emulated display.

2023-06-20 18:10 UTC, liamwhite reviewed
I know you touched on this a little bit in your original comment, but one thing I am feeling iffy about in this changeset is that we have some dependent settings and settings that have a slightly different configuration method (like DateTime instead of LineEdit for RTC, for example). Is there a way we could maybe define these dependencies in data instead of needing to write code to handle every case?

2023-06-20 18:10 UTC, liamwhite commented on src/yuzu/configuration/configure_general.cpp
> +            delete widget;
Any reason not to use `widget->deleteLater()`?

2023-06-20 18:10 UTC, liamwhite commented on src/yuzu/configuration/configure_graphics_advanced.cpp
> +            delete widget;
ditto

2023-06-20 18:10 UTC, liamwhite commented on src/yuzu/configuration/configure_system.cpp
> +            delete widget;
ditto

2023-06-20 18:17 UTC, liamwhite commented on src/common/settings_enums.h
> +static const std::map<std::type_index, std::map<std::string, u32>> canonicalizations = {
You could probably even eliminate the map and make the whole lookup constexpr, actually.

2023-06-20 23:13 UTC, lat9nq commented on src/common/settings.cpp
> +        return "UI";
Unfortunately this is how it exists in current configurations: https://github.com/yuzu-emu/yuzu/blob/a67bdeb2c244419c5b50fc3975d4efefcdfcc855/src/yuzu/configuration/config.cpp#L864

I am trying to maintain some semblance of compatibility with current configs in this PR, so sins like this need to be propagated at least once more.

2023-06-20 23:16 UTC, lat9nq commented on src/yuzu/configuration/configuration_shared.h
> +    std::shared_ptr<std::forward_list<Tab*>> group;
This is vestigial code from the mentioned end goal beyond this PR. It should probably be removed for the time being.

2023-06-20 23:22 UTC, lat9nq commented on src/yuzu/configuration/configure_general.cpp
> +            delete widget;
I guess not, but I don't exactly understand why I should use `deleteLater()` either?

From here: https://forum.qt.io/topic/91180/delete-vs-deletelater, since I'm already using delete, and it isn't causing problems, it doesn't seem like we gain anything from `deleteLater()`?

2023-06-21 19:21 UTC, lat9nq commented
> I know you touched on this a little bit in your original comment, but one thing I am feeling iffy about in this changeset is that we have some dependent settings and settings that have a slightly different configuration method (like DateTime instead of LineEdit for RTC, for example). Is there a way we could maybe define these dependencies in data instead of needing to write code to handle every case?

I've tried to address this in the last few commits, starting at [configuration: Use a builder to create widgets](https://github.com/yuzu-emu/yuzu/pull/10839/commits/8f56aa4b1ace0cf196a75542e86c5df23afa435f). I'm happier with where it's at now than before, but that information mostly went to common/settings.h. Please take a look.

2023-06-21 20:14 UTC, liamwhite commented on src/common/settings_common.h
> +    explicit BasicSetting(Linkage& linkage, const std::string& name, enum Category category_,
```suggestion
    explicit BasicSetting(Linkage& linkage, const std::string& name, Category category_,
```
`enum class`es are typenames in C++, so I don't think you need to specifically say it's an enum when declaring a variable with it?

2023-06-21 23:14 UTC, liamwhite commented on src/common/settings_common.cpp
> +BasicSetting::BasicSetting(Linkage& linkage, const std::string& name, enum Category category_,
```suggestion
BasicSetting::BasicSetting(Linkage& linkage, const std::string& name, Category category_,
```

2023-06-21 23:14 UTC, liamwhite commented on src/common/settings_common.h
> +    [[nodiscard]] enum Category Category() const;
```suggestion
    [[nodiscard]] Category Category() const;
```

2023-06-21 23:14 UTC, liamwhite commented on src/common/settings_common.h
> +    const enum Category category; ///< The setting's category AKA INI group
```suggestion
    const Category category; ///< The setting's category AKA INI group
```

2023-06-21 23:14 UTC, liamwhite commented on src/common/settings_setting.h
> +                     enum Category category_, u32 specialization_ = Specialization::Default,
```suggestion
                     Category category_, u32 specialization_ = Specialization::Default,
```

2023-06-21 23:14 UTC, liamwhite commented on src/common/settings_setting.h
> +                     const Type& max_val, const std::string& name, enum Category category_,
```suggestion
                     const Type& max_val, const std::string& name, Category category_,
```

2023-06-22 00:03 UTC, lat9nq commented on src/common/settings_common.cpp
> +BasicSetting::BasicSetting(Linkage& linkage, const std::string& name, enum Category category_,
All of these marked are compiler errors on clang. The method Category exists, so `enum` must be specified to refer to the type in these scopes.

2023-06-22 00:17 UTC, liamwhite commented on src/yuzu/configuration/shared_translation.cpp
> +    translations->insert({typeid(Settings::AstcDecodeMode),
As with the enum declarations, can you remove the use of typeid here?

2023-06-22 01:41 UTC, lat9nq commented on src/yuzu/configuration/shared_translation.cpp
> +    translations->insert({typeid(Settings::AstcDecodeMode),
I wasn't able to be as elegant as we were in settings_enums. The difference between here and in settings_enums is that we could still tell what the type was at compile-time. These translations need to be accessible even when we don't know directly know what the type is.

To at least get around relying on the hash from a typeid (I assume that's the underlying issue in these reviews), I've modified settings_enums to give us an Index for each enum. Please take a look.

2023-06-22 02:24 UTC, liamwhite approved these changes

2023-06-22 02:30 UTC, Morph1984 commented on src/CMakeLists.txt
> +        /Zc:preprocessor # Use standards-conforming preprocessor
Place the comment above add_compile_options

```suggestion
        /Zc:preprocessor
```

2023-06-22 03:18 UTC, lat9nq commented on src/CMakeLists.txt
> +        /Zc:preprocessor # Use standards-conforming preprocessor
Sorry, Reading: 100. Give me a minute

2023-07-18 18:06 UTC, Morph1984 commented on src/common/settings_setting.h
> +        return std::is_enum<Type>::value;
```suggestion
        return std::is_enum_v<Type>;
```

2023-07-18 18:06 UTC, Morph1984 commented on src/common/settings_setting.h
> +        if constexpr (std::is_same<Type, std::string>()) {
```suggestion
        if constexpr (std::is_same_v<Type, std::string>) {
```

2023-07-18 18:06 UTC, Morph1984 commented on src/common/settings_setting.h
> +        } else if constexpr (std::is_same<Type, AudioEngine>()) {
This seems out of place, is this intentional?

2023-07-18 18:06 UTC, Morph1984 commented on src/common/settings_setting.h
> +    virtual const Type& operator=(const Type& val) {
Some usages of "virtual" here are confusing, are they meant to be overriden by another class, or is this class "final"

2023-07-18 18:06 UTC, Morph1984 commented on src/common/settings_setting.h
> +    virtual std::type_index TypeId() const override {
drop virtual

2023-07-18 18:17 UTC, Morph1984 commented on src/common/settings_common.h
> +enum Specialization : u8 {
```suggestion
enum class Specialization : u8 {
```

2023-07-18 18:25 UTC, liamwhite commented on src/common/settings_common.h
> +    [[nodiscard]] enum Category Category() const;
The method would have to be renamed to GetCategory for this to work

2023-07-18 18:50 UTC, lat9nq commented on src/common/settings_common.cpp
> +static bool configuring_global = true;
I don't understand what you mean by internal linkage?

That being said these Global functions like should never have been moved to this file. Rather I should have left them in settings.cpp

2023-07-18 19:04 UTC, lat9nq commented on src/common/settings_common.h
> +    std::map<Category, std::forward_list<BasicSetting*>> by_category{};
I was using it since it's a linked list. Insertion is constant time and only happens at the beginning of the program, and it only takes the space it needs. As of writing we don't need backwards pointers. Every time it is used, we are just iterating through everything in it doing some operation over the settings. It didn't feel like there was any need to make it a vector since ideally we never access just one element in the list -- the setting would be accessed directly in this case.

I guess the main consideration is if the storage for all the forward pointers is worth the possible performance gain from the initialization, and if the vector can efficiently store the values without too much unused space. I'm not sure which is better here. I did not benchmark this.

2023-07-18 19:04 UTC, lat9nq commented on src/common/settings_common.h
> +    [[nodiscard]] enum Category Category() const;
Would we prefer GetCategory here?

2023-07-18 19:08 UTC, lat9nq commented on src/common/settings_setting.h
> +        } else if constexpr (std::is_same<Type, AudioEngine>()) {
This is for compatibility with existing configs, since the related setting was a string previously.

2023-07-18 19:18 UTC, lat9nq commented on src/common/settings_setting.h
> +    virtual const Type& operator=(const Type& val) {
The one you marked here is supposed to be overriden in SwitchableSetting. I've addressed a few others that were unnecessarily marked virtual.

2023-07-18 19:26 UTC, liamwhite commented on src/common/settings_common.h
> +    [[nodiscard]] enum Category Category() const;
I think so, yes.

2023-07-18 19:37 UTC, lat9nq commented on src/common/settings_common.h
> +enum Specialization : u8 {
I want to be able to bitwise-or the values in this enumeration. Is this a code-style issue?

2023-07-19 16:38 UTC, Morph1984 commented on src/common/settings_common.h
> +    std::map<Category, std::forward_list<BasicSetting*>> by_category{};
More so regarding memory usage, a non-intrusive singly linked list has an overhead of 2 pointers per node

2023-07-20 22:50 UTC, liamwhite commented
Needs a rebase and then ready to tag imo

2023-07-22 11:46 UTC, cathyjf commented
This pull request is incompatible with Qt 6 because the pull request uses `QRegExp`, which was apparently removed from from Qt 6. However, Qt 6 appears to offer a Qt 5 compatibility module (which includes `QRegExp`) that you could link against to solve this problem: https://doc.qt.io/qt-6/qtcore5-index.html

I don't have an opinion on whether linking to the compatibility module is the best way to address the incompatibility. Another option suggested by the Qt documentation is to use `QRegularExpression` instead, which the documentation implies is supported by both Qt 5 and Qt 6 (_see_ https://doc.qt.io/qt-6/qregexp.html#porting-to-qregularexpression). Note: I don't know much about Qt.

2023-07-23 05:34 UTC, bunnei approved these changes

2023-07-23 20:01 UTC, lat9nq commented
There is a bug with the Renderer backend and shader backend selectors causing an errant button to appear. This needs to be addressed before merge.

2023-07-26 00:44 UTC, FearlessTobi requested changes
Very likely causing https://github.com/yuzu-emu/yuzu/issues/11137.
Blocking

2023-07-26 00:50 UTC, FearlessTobi commented
It also breaks all translations for our settings.

2023-07-26 00:54 UTC, FearlessTobi commented
Looking at this more, it also disables settings when emulation is running that could be changed before.
(e.g. Hide Mouse on inactivity)

2023-07-26 02:56 UTC, lat9nq commented
> It also breaks almost all translations for our settings.

It appears the way I did translations doesn't carry over old ones. Please remember that this PR is starting with a blank Qt widget and rebuilds the UI on restart. Check src/yuzu/configuration/shared_translation.cpp

I'm not sure what would be the best way to repair this, since I am very unfamiliar with our translation services.

2023-07-26 03:29 UTC, lat9nq commented
> Looking at this more, it also disables settings when emulation is running that could be changed before. (e.g. Hide Mouse on inactivity)
> 
> Some can even still be toggled in the title bar

You're going to need to be a lot more specific. I'm not aware of any settings that are configurable from the title bar. The ***menu*** bar has some settings, but none of those are configurable in `Emulation -> Configure...`, so the generated UI pages wouldn't touch them. And the status bar settings are correct to my knowledge. Remember that the `runtime_modifiable` field in a Setting is a suggestion to a frontend implementation that is used during UI generation. Enforcing this field in the Setting would necessitate additional communication between core and common in multiple locations and feels unnecessary at the end of it all.

The settings in System are not configurable during emulation. I suppose in the past you could change that setting during emulation, but it would not cause any change in the active guest until after shutdown. This is inconsistent with all the other settings in the configuration dialog.

Last commit should address the remaining ones in General and Audio.

2023-07-27 16:48 UTC, lat9nq commented
> Very likely causing #11137. Blocking

Linked issue is closed.

2023-08-02 18:25 UTC, merged