desktop shortcut support for windows
yuzu-emu/yuzu pull request #11344
Opened 2023-08-21 19:57 UTC by roenyroeny

implemented the windows path for desktop shortcut creation of titles.

Icons are saved in the yuzu appdata folder under /icons

2023-08-22 15:18 UTC, FearlessTobi requested changes

2023-08-22 15:18 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +    hres = pPersistFile->Save(wshortcut_path.data(), TRUE);
dito

2023-08-22 15:18 UTC, FearlessTobi commented on src/yuzu/util/util.cpp
> +#endif
needs a newline here

2023-08-22 15:18 UTC, FearlessTobi commented on src/yuzu/util/util.cpp
> +#include <Windows.h>
this include should be defined at the top of the file

2023-08-22 15:18 UTC, FearlessTobi commented
Please also fix clang-format.

2023-08-24 06:14 UTC, roenyroeny commented on src/yuzu/main.cpp
> -                    .arg(QString::fromStdString(target_directory)),
target_directory is a std::filesystem::path which cannot implicitly be converted to a std::string in MSVC

2023-09-14 20:09 UTC, DanielSvoboda commented
Take a look at my version, I hadn't seen what you had started doing, it's fully functional

https://github.com/yuzu-emu/yuzu/compare/master...DanielSvoboda:yuzu:master

Some details:

remove_special_characters
Removes all characters that Windows does not accept: '\\', '/', ':', '?', '"', '<', '>', '|'
Not just the ':' as it currently is
std::replace(title.begin(), title.end(), ':', '-');

savePixmapsToICO
This code implements a custom function to convert PNG to ICO and save using QPixmap.
The code has a lot of additional details to handle various situations and ensure that images are saved correctly in the .ico file
Save the icons in the AppData\Roaming\yuzu\icons folder, an equivalent to the path used in Linux

Uses the Windows API function SHGetFolderPath to get the path of the current desktop directory.
Accept directories with accents like my case, where in my language the desktop is called "Área de trabalho"
It uses the COM (Component Object Model) interfaces `IShellLink` and `IPersistFile` to create a shortcut (file.lnk)

2023-09-29 00:54 UTC, boludoz commented
> Please review my version. I had not seen what you had started working on, but it is fully functional.
> 
> Some details:
> 
> ```
> remove_special_characters removes all characters that Windows does not accept, not just the colon (:).
> This code implements a custom function to convert PNG to ICO and save it using QPixmap.
> The code has many additional details to handle various situations and ensure that images are saved correctly in the .ico file.
> ```
> 
> Here is the complete code: [master...DanielSvoboda:yuzu:shortcut](https://github.com/yuzu-emu/yuzu/compare/master...DanielSvoboda:yuzu:shortcut)

Give the guy a chance, he's a software engineer, his code seems good and neat, with good support for characters.

2023-09-29 01:00 UTC, boludoz commented
> Please review my version. I had not seen what you had started working on, but it is fully functional.
> 
> Some details:
> 
> ```
> remove_special_characters removes all characters that Windows does not accept, not just the colon (:).
> This code implements a custom function to convert PNG to ICO and save it using QPixmap.
> The code has many additional details to handle various situations and ensure that images are saved correctly in the .ico file.
> ```
> 
> Here is the complete code: [master...DanielSvoboda:yuzu:shortcut](https://github.com/yuzu-emu/yuzu/compare/master...DanielSvoboda:yuzu:shortcut)

Give him a chance, he is an excellent coder and knows what he is doing since he is a software engineer with work experience.

2023-09-29 10:07 UTC, roenyroeny commented
> Please review my version. I had not seen what you had started working on, but it is fully functional.
> 
> Some details:
> 
> ```
> remove_special_characters removes all characters that Windows does not accept, not just the colon (:).
> This code implements a custom function to convert PNG to ICO and save it using QPixmap.
> The code has many additional details to handle various situations and ensure that images are saved correctly in the .ico file.
> ```
> 
> Here is the complete code: [master...DanielSvoboda:yuzu:shortcut](https://github.com/yuzu-emu/yuzu/compare/master...DanielSvoboda:yuzu:shortcut)

Looks alright to me. Do you want to merge in your remove_special_characters and merge this PR as yours is closed ?
Excuse the delay btw, i haven't had much time to look at this lately

2023-09-29 17:03 UTC, DanielSvoboda commented
you can use any part of my code

2023-09-29 22:12 UTC, boludoz commented
I recommend giving full support for u8string

2023-09-29 23:12 UTC, FearlessTobi commented
Looks much better now, however to forgot to address a few of my review comments.

2023-09-30 03:30 UTC, boludoz commented
```
// Illgal and null characters remover for name: Windows, MacOS and Linux
// 1. Full u8string support
// 2. Remember: dont use prohibited chars in ReplaceString
void NameSantizer(std::u8string &u8filename, std::u8string ReplaceString = u8"_") {
  std::u8string u8path_santized;

  for (auto &c : u8filename) {
    if (c == u8'\\' || c == u8'/' || c == u8':' || c == u8'*' || c == u8'?' ||
        c == u8'\"' || c == u8'<' || c == u8'>' || c == u8'|' || c == u8'\0') {
      u8path_santized += ReplaceString;
      continue;
    }

    if (c == u8'.') {
      u8path_santized += ReplaceString;
      continue;
    }

    [[likely]]u8path_santized += c;
  }

  // Delete all spaces and dots at the end
  while (u8path_santized.back() == u8' ' || u8path_santized.back() == u8'.') {
    u8path_santized.pop_back();
  }

  if (u8path_santized.empty()) {
    throw std::runtime_error("[NameSantizer] Empty filename or all chars are wrong");
  }

  u8filename = u8path_santized;

}
```

2023-09-30 03:32 UTC, boludoz commented
And [DanielSvoboda](https://github.com/DanielSvoboda) made a very good function with qt for ico files, that has better cross-platform support.

2023-09-30 05:05 UTC, boludoz commented
`#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

// Illgal and null characters remover for name: Windows, MacOS and Linux
// Special case for ':' in games
// 1. Full u8string support
// 2. Remember: dont use prohibited chars in ReplaceString
void NameSantizer(std::u8string &u8filename) {
  std::u8string u8path_santized;

  u8path_santized = u8filename;

  int eSizeSanitized = u8path_santized.size();

  // Special case for ":", for example: 'Pepe: La secuela' --> 'Pepe - La
  // secuela' or 'Pepe : La secuela' --> 'Pepe - La secuela'
  for (size_t i = 0; i < eSizeSanitized; i++) {

    switch (u8path_santized[i]) {
    case u8':':
      if (i == 0 || i == eSizeSanitized - 1) {
        u8path_santized.replace(i, 1, u8"_");
      } else if (u8path_santized[i - 1] == u8' ') {
        u8path_santized.replace(i, 1, u8"-");
      } else {
        u8path_santized.replace(i, 1, u8" -");
        eSizeSanitized++;
      }
      break;
    case u8'\\':
      [[fallthrough]];
    case u8'/':
      [[fallthrough]];
    case u8'*':
      [[fallthrough]];
    case u8'?':
      [[fallthrough]];
    case u8'\"':
      [[fallthrough]];
    case u8'<':
      [[fallthrough]];
    case u8'>':
      [[fallthrough]];
    case u8'|':
      [[fallthrough]];
    case u8'\0':
      u8path_santized.replace(i, 1, u8"_");
      break;
    default:
      break;
    }
  }

  // Delete duplicated spaces || Delete duplicated dots (MacOS i think)
  for (size_t i = 0; i < eSizeSanitized; i++) {
    if ((u8path_santized[i] == u8' ' && u8path_santized[i + 1] == u8' ') ||
        (u8path_santized[i] == u8'.' && u8path_santized[i + 1] == u8'.')) {
      u8path_santized.erase(i, 1);
      i--;
    }
  }

  // Delete all spaces and dots at the end (Windows almost)
  while (u8path_santized.back() == u8' ' || u8path_santized.back() == u8'.') {
    u8path_santized.pop_back();
  }

  if (u8path_santized.empty()) {
    throw std::runtime_error(
        "[NameSantizer] Empty filename or all chars are wrong");
  }

  u8filename = u8path_santized;
}

int main() {
  std::u8string utf8String =
      u8"Pepe: la secuela"; // Tu cadena de texto en formato u8string
  NameSantizer(utf8String);
  std::filesystem::path filePath = utf8String;
  std::ofstream outputFile(filePath, std::ios::binary);

  if (!outputFile) {
    return 1;
  }
  std::string utf8StringAsStdString(utf8String.begin(), utf8String.end());
  outputFile.write(utf8StringAsStdString.c_str(), utf8StringAsStdString.size());
  outputFile.close();
  return 0;
}
`
Hello sir, I made a code to fix all special and null characters, it just doesn't take into account the case of special Windows names, but don't worry, that will never happen.
Additionally, correct the names of the games so that they look prettier if they contain ':', if you give me permission I can try to implement it in your code.

2023-10-04 20:08 UTC, boludoz commented
Please, I ask for your authorization and I apologize if I use any of your code without authorization, you can review #11665 and you are free to use my code, you and anyone else, as I ask for your permission to use your code.

2023-10-08 21:16 UTC, liamwhite commented
Superseded by #11705

2023-10-08 21:16 UTC, closed without merging