Create shortcuts on Windows
yuzu-emu/yuzu pull request #11489
Opened 2023-09-13 03:22 UTC by DanielSvoboda

Add the ability to create a shortcut in Windows.
Use ffmpeg to convert PNG to ICO, however you need to include ffmpeg.exe in the yuzu directory, or find another solution to convert.
![print](https://github.com/yuzu-emu/yuzu/assets/28203966/0aa1941c-450d-4342-b988-5d2b2923d798)

2023-09-13 03:27 UTC, liamwhite commented
Probably a duplicate of #11344?

2023-09-13 06:17 UTC, v1993 requested changes

2023-09-13 06:17 UTC, v1993 commented on src/yuzu/main.cpp
> +    std::string command = "ffmpeg -y -i " + png_path.string() + " " + ico_path.string();
Please, please don't do this. From unicode to spaces in filenames this is just bound to cause problems (fairly sure you can make it run arbitrary code with well-crafted filename). Sure, you can remove those from icon file name, but not from path leading to it

Yuzu already uses ffmpeg *libraries*, so you can look into using them instead of calling a standalone executable. And, as far as launching terminal commands goes,  please use QProcess next time instead of concatenating cmd line manually.

2023-09-13 15:39 UTC, liamwhite commented
Closing in favor of #11344 for now

2023-09-13 15:39 UTC, closed without merging

2023-09-14 02:10 UTC, DanielSvoboda commented on src/yuzu/main.cpp
> +    std::string command = "ffmpeg -y -i " + png_path.string() + " " + ico_path.string();
ok, i removed ffmpeg and converting icon to code only

2023-09-29 00:58 UTC, boludoz commented
The code is very good and very organized, perhaps they closed it because of the support for characters, I would have used u8 or something like that there, which is the most modern and supports all systems except Windows, but it can be handled.