Check that the Extent3D TileShift only operates on a 3D ASTC Texture …
yuzu-emu/yuzu pull request #11528
Opened 2023-09-17 18:16 UTC by Squall-Leonhart

…by checking Mip count is 1.

It appears that previously the Extent3D Tileshift could apply to Mip 0 of 2D Textures in some cases, this is responsible for breaking Asterix and Obelix, the Recall animation in TOTK and an older version of the Tanslation pack for Tsukihime -A Piece of Blue Glass Moon.

I'm open to someone with a better explanation for why these changes fix things, while not regressing TOTKs gloom.

Fixes #11252 #10493 #10456

2023-09-17 18:41 UTC, FernandoS27 approved these changes

2023-09-17 18:49 UTC, GPUCode commented
Where is num_levels being set, cause it looks like it's always zero?

2023-09-17 19:54 UTC, Squall-Leonhart commented
> Where is num_levels being set, cause it looks like it's always zero?

The idea was really to only apply the Extent3D tileshift if there was only mip level 0,  it seems there is a lot more involved here then i thought, fully reverting the changes in https://github.com/yuzu-emu/yuzu/commit/01c4568786631515ea13ec8cf991d534272e87b7 would return asterix to normal from

![image](https://github.com/yuzu-emu/yuzu/assets/1098176/c374b20b-ce9e-41c9-9feb-a3b95aab15b6)


 and make it look like

![image](https://github.com/yuzu-emu/yuzu/assets/1098176/b859e9d6-a570-4864-866d-0c268f80c654)

but i've only managed to prevent the texture corruption with what i've changed, shadows are still glitchy.
![image](https://github.com/yuzu-emu/yuzu/assets/1098176/6952dbd3-7902-4960-9e41-5289e12d5e3a)

needs more work, or someone else to collab, i'm basically working on a theory that seems atleast partly correct, and with assistance from AI, not really a C++ dev beyond tinkering.

2023-09-17 20:21 UTC, Squall-Leonhart commented
Disregard the final Asterix image, the glitching shadows are fixed in combination with https://github.com/yuzu-emu/yuzu/pull/11258

2023-09-17 20:43 UTC, liamwhite requested changes

2023-09-17 20:43 UTC, liamwhite commented on src/video_core/texture_cache/util.cpp
> +    u32 num_levels;
This doesn't seem to be assigned by anything at runtime

2023-09-17 22:13 UTC, Squall-Leonhart commented on src/video_core/texture_cache/util.cpp
> +    u32 num_levels;
fixed

2023-09-17 22:15 UTC, v1993 commented on src/video_core/texture_cache/util.cpp
> +                                                u32 tile_width_spacing, const ImageInfo& info) {
```suggestion
                                                u32 tile_width_spacing, s32 num_levels) {
```

Since this is how other parameters are already handled.

2023-09-17 22:46 UTC, Squall-Leonhart commented on src/video_core/texture_cache/util.cpp
> +                                                u32 tile_width_spacing, const ImageInfo& info) {
With this nightmare code, that can't work as then info becomes undefined.

2023-09-17 22:49 UTC, v1993 commented on src/video_core/texture_cache/util.cpp
> +                                                u32 tile_width_spacing, const ImageInfo& info) {
Yes, this is indeed not the only line you need to change, but the required modification is borderline trivial.

2023-09-17 23:06 UTC, Squall-Leonhart commented on src/video_core/texture_cache/util.cpp
> +                                                u32 tile_width_spacing, const ImageInfo& info) {
think i found a way

2023-09-18 00:25 UTC, gidoly commented
doesn't seems to fix recall animation on totk on nvidia

2023-09-18 00:47 UTC, Squall-Leonhart commented
> doesn't seems to fix recall animation on totk on nvidia

yeah, the initial pr did but it wasn't initializing num_levels, now that it does the animation is a circle again.

2023-09-18 03:15 UTC, FernandoS27 commented on src/video_core/texture_cache/util.cpp
> +    if (level == 0 && info.num_levels == 1) {
Just remove the full if block and see if it fixes all 4 things.

2023-09-18 12:42 UTC, Squall-Leonhart commented on src/video_core/texture_cache/util.cpp
> +    if (level == 0 && info.num_levels == 1) {
It does, but i had thought this was needed for some case within TOTK?

From testing so far, the Gloom puddle fix was actually

```
        .depth = level == 0
                     ? block_size.depth
                     : AdjustMipBlockSize<GOB_SIZE_Z>(num_tiles.depth, block_size.depth, level),
```

2023-09-18 14:13 UTC, Squall-Leonhart commented
Closing in lieu of https://github.com/yuzu-emu/yuzu/pull/11534

2023-09-18 14:13 UTC, closed without merging