Tessil/robin-map implemented instead unordered_map
yuzu-emu/yuzu pull request #11532
Opened 2023-09-18 01:05 UTC by boludoz

Robin map and robin set implemented, like Skyline, for more performance.

2023-09-18 01:10 UTC, AliciaBurrito commented
@boludoz Do you have any examples of the improved performance? eg. games to test, or what numbers you got?

2023-09-18 01:33 UTC, FearlessTobi commented
Blindly replacing every unordered_map with robin_map, without providing any performance numbers will not get accepted here.

2023-09-18 01:34 UTC, boludoz commented
> Blindly replacing every unordered_map with robin_map, without providing any performance numbers will not get accepted here.

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/b2076c2f-f901-4b51-adbd-991972303647)

2023-09-18 01:36 UTC, boludoz commented
```
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include "tsl/robin_map.h"
#include "tsl/robin_set.h"
#include <chrono>

int main() {
    std::unordered_map<int, int> unorderedMap;
    tsl::robin_map<int, int> robinMap;
    std::unordered_set<int> unorderedSet;
    tsl::robin_set<int> robinSet;

    auto start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < 1000000; ++i) {
        unorderedMap[i] = i * 2;
    }

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed_seconds = end - start;

    std::cout << "Time to insert into std::unordered_map: " << elapsed_seconds.count() << " seconds" << std::endl;
    
    start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < 1000000; ++i) {
        robinMap[i] = i * 2;
    }

    end = std::chrono::high_resolution_clock::now();
    elapsed_seconds = end - start;

    std::cout << "Time to insert into tsl::robin_map: " << elapsed_seconds.count() << " seconds" << std::endl;

    start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < 1000000; ++i) {
        unorderedSet.insert(i);
    }

    end = std::chrono::high_resolution_clock::now();
    elapsed_seconds = end - start;

    std::cout << "Time to insert into std::unordered_set: " << elapsed_seconds.count() << " seconds" << std::endl;

    start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < 1000000; ++i) {
        robinSet.insert(i);
    }

    end = std::chrono::high_resolution_clock::now();
    elapsed_seconds = end - start;
    std::cout << "Time to insert into tsl::robin_set: " << elapsed_seconds.count() << " seconds" << std::endl;
    return 0;
}

```

2023-09-18 01:39 UTC, boludoz commented
> Blindly replacing every unordered_map with robin_map, without providing any performance numbers will not get accepted here.

I ask you to please reconsider your opinion, perhaps the performance is not too much but it can help. It is a grain of sand that makes the mountain. 30 % more performance in tsl::robin_set for example.

2023-09-18 01:42 UTC, boludoz commented
> @boludoz Do you have any examples of the improved performance? eg. games to test, or what numbers you got?

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/9c3dd8b4-5f4a-40f6-a4c8-ce4b041219a4)
I don't give explanations to xenophobic people.

2023-09-18 03:22 UTC, FernandoS27 commented
I'm sorry our moderators are morons who cannot respect someone's hard work and put you in the hard position of going through benchmarks and stuffs without much necessity. 

Please feel free to reopen.

2023-09-18 03:27 UTC, FernandoS27 commented
Oh fix clamg format.

2023-09-18 03:47 UTC, gidoly commented
i can check if this pr makes difference in games after ci passed. even if doesn't make big difference it is nice to have

2023-09-18 04:57 UTC, boludoz commented
> i can check if this pr makes difference in games after ci passed. even if doesn't make big difference it is nice to have

I think the order is fixed there.

2023-09-18 09:56 UTC, gidoly commented
getting compiling error on visual studio
![devenv_WUDBhnoVfD](https://github.com/yuzu-emu/yuzu/assets/66776795/9ba73df5-5dee-404d-8cb4-7ef6ba1bcfbb)
i think it is because missing external file as cmake gives me this error
![WindowsTerminal_Oe3nlNFJNb](https://github.com/yuzu-emu/yuzu/assets/66776795/54da8a58-576a-44d8-ba62-f9fed56d349d)

2023-09-18 10:35 UTC, Tachi107 commented on externals/CMakeLists.txt
> +add_subdirectory(robin-map)
Could you please add `find_package(tsl-robin-map CONFIG)` to the top-level CMakeLists.txt and change this to the following:

```suggestion
if (NOT TARGET tsl::robin_map)
    add_subdirectory(robin-map)
endif()
```

Also, you don't seem to use the `tsl::robin_map` target anywhere in the CMake files, you should probably add `target_link_libraries(<target-name> PRIVATE tsl::robin_map)` in the relevant place(s).

2023-09-18 17:41 UTC, v1993 commented on .gitmodules
> +	url = https://github.com/Tessil/robin-map
```suggestion
	url = https://github.com/Tessil/robin-map.git
```

2023-09-18 17:46 UTC, boludoz commented on .gitmodules
> +	url = https://github.com/Tessil/robin-map
Thanks sir.

2023-09-18 17:53 UTC, v1993 commented on .gitmodules
> +	url = https://github.com/Tessil/robin-map
Looks like this was not committed?

2023-09-18 18:36 UTC, v1993 requested changes
`.gitmodules` still not fixed

2023-09-18 18:43 UTC, boludoz commented
> `.gitmodules` still not fixed

Sorry, pushed now.

2023-09-18 18:54 UTC, v1993 reviewed
Benchmarking aside - it's worth noting that robin-map has [some differences](https://github.com/Tessil/robin-map#differences-compared-to-stdunordered_map) in its API compared to vanilla `unordered_map`. While most are covered by compile-time checks, a few differences in iterator invalidation should be verified manually to not affect code in question.

2023-09-18 18:54 UTC, v1993 reviewed
Benchmarking aside - it's worth noting that robin-map has [some differences](https://github.com/Tessil/robin-map#differences-compared-to-stdunordered_map) in its API compared to vanilla `unordered_map`. While most are covered by compile-time checks, a few differences in iterator invalidation should be verified manually to not affect code in question.

2023-09-18 20:30 UTC, boludoz commented
Fixed submodule

2023-09-18 21:56 UTC, boludoz commented
If anyone wants to help, I'm having a hard time adding a simple library.

2023-09-18 22:56 UTC, Kelebek1 commented
I don't know if there's a way to make an external available to all projects by default, but I think you need to add robin map to each project's `target_link_libraries` in their cmake file. 
E.g src/common/cmakelists.txt has
```cmake
target_link_libraries(common PUBLIC Boost::context Boost::headers fmt::fmt microprofile Threads::Threads)
target_link_libraries(common PRIVATE lz4::lz4 zstd::zstd LLVM::Demangle)
```
You'll want robin-map in there, in the public one I guess? And repeat for each project that you're having use it.

2023-09-18 22:58 UTC, FearlessTobi requested changes
You need to provide actual performance comparsions from games for this to have a chance to get approved.

2023-09-18 22:58 UTC, FearlessTobi commented on src/yuzu/multiplayer/chat_room.h
> +    tsl::robin_set<std::string> block_list;
this is not performance critical at all.
dito for many other places

2023-09-19 00:08 UTC, boludoz commented
For my part, there is nothing more to contribute, if anyone wants to solve the problem, welcome...

2023-09-19 00:08 UTC, closed without merging