Full shortcut Windows support with unicode support & question for fullscreen mode shortcut
yuzu-emu/yuzu pull request #11665
Opened 2023-10-03 23:23 UTC by boludoz

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/8d1f2fed-0807-4f78-acf8-e32a74d7ef2e)
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/7ae4994e-25a6-47a8-bc0e-5a1abfecd654)
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/f65d6d8e-3711-404d-b7e3-384d2fd95980)

2023-10-03 23:26 UTC, boludoz commented
Inspired in [@DanielSvoboda]https://github.com/DanielSvoboda & [@roenyroeny]https://github.com/roenyroeny code

2023-10-04 00:10 UTC, FearlessTobi requested changes
I'm not even going to bother with a full review, so I will just leave some questions:

1. Did you actually ask the other people if you could take their code? Why is there no attribution in the commit messages?
2. Why is there huge walls of commented out code?
3. Why are there random comments in Spanish?
4. Why did you not address my review comments when taking the code from the original PR?
5. Why is this modifying our fs util functions without any reason given?

2023-10-04 01:27 UTC, boludoz commented
> I'm not even going to bother with a full review, so I will just leave some questions:
> 
> 1. Did you actually ask the other people if you could take their code? Why is there no attribution in the commit messages?
> 2. Why is there huge walls of commented out code?
> 3. Why are there random comments in Spanish?
> 4. Why did you not address my review comments when taking the code from the original PR?
> 5. Why is this modifying our fs util functions without any reason given?

I'm sorry, I don't know how to do it.

2023-10-04 14:03 UTC, FearlessTobi commented
You did not answer my questions though.
Have you asked the original creators for permission? If you take someone elses code, you should make them the author of the git commit and not yourself.

Also we have a minimum standard of quality, even for draft PRs.
You did not even bother to address my review comments when copying the code over from the original Pull Request.

2023-10-04 14:21 UTC, boludoz commented
> You did not answer my questions though.
> Have you asked the original creators for permission? If you take someone elses code, you should make them the author of the git commit and not yourself.
> 
> Also we have a minimum standard of quality, even for draft PRs.
> You did not even bother to address my review comments when copying the code over from the original Pull Request.

ask Microsoft for permission then.

2023-10-04 19:00 UTC, boludoz commented
> You did not answer my questions though. Have you asked the original creators for permission? If you take someone elses code, you should make them the author of the git commit and not yourself.
> 
> Also we have a minimum standard of quality, even for draft PRs. You did not even bother to address my review comments when copying the code over from the original Pull Request.

Please, I am a shy person, can you help me? Excuse me, but what functions do you consider I should copy to replace them or request authorization?
What modifications remain?

2023-10-04 19:11 UTC, boludoz commented
> Inspired in [@DanielSvoboda]https://github.com/DanielSvoboda & [@roenyroeny]https://github.com/roenyroeny code

In this comment I declare that I have looked at other codes as a reference and I thank their respective authors.

2023-10-04 19:33 UTC, boludoz commented
> You did not answer my questions though. Have you asked the original creators for permission? If you take someone elses code, you should make them the author of the git commit and not yourself.
> 
> Also we have a minimum standard of quality, even for draft PRs. You did not even bother to address my review comments when copying the code over from the original Pull Request.

Complain silently for now and just compile the code. We will fix those problems in the end. I see you too tense, aren't there issues of xenophobia or racism there?

2023-10-04 19:54 UTC, boludoz commented
> You did not answer my questions though. Have you asked the original creators for permission? If you take someone elses code, you should make them the author of the git commit and not yourself.
> 
> Also we have a minimum standard of quality, even for draft PRs. You did not even bother to address my review comments when copying the code over from the original Pull Request.

Authors' response:

My code is completely different, if you look at the git history you can see that I did not apply any patch, I am just experimenting, when I tried to compile the other author's code it did not even compile, also my management of the environment variables and string is completely different, I'm making this support any language and you can even add emojis to folders for example. Also, if you look at my code, it adds the option to add the game to the list of applications.

2023-10-04 19:56 UTC, boludoz commented
If you think I'm copying myself, when all the builds are functional, we can upload a proposal to any author's code. I promise to do it.

2023-10-04 20:06 UTC, boludoz commented
https://drive.google.com/file/d/1lGhDx1sdq4wsaYPTWcSAe4wnH63SClfD/view?usp=sharing

I invite you to try it for yourself, I also recommend that Yuzu starts in administrator mode by default in Windows.

2023-10-05 00:41 UTC, goldenx86 commented
> `Why are there random comments in Spanish?` I see you too tense, aren't there issues of xenophobia or racism there?, There is not a single comment in my code that is in Spanish (It seems that this worries you too much, more so that the code is functional). You have behaved strangely in other comments.

boludoz, Argentinian team member here. Chill, please. The only one introducing friction here is you.

2023-10-05 02:20 UTC, boludoz commented
[archive.zip](https://github.com/yuzu-emu/yuzu/files/12811621/archive.zip)

2023-10-05 04:17 UTC, DanielSvoboda commented
Yes, you can use my code. Is there anything else missing? Is everything functional now?

2023-10-05 07:26 UTC, v1993 requested changes
Not a comprehensive review but covers some basic issues. Please also fix missing newlines at the end of some files; github's review interface indicates those.

2023-10-05 07:26 UTC, v1993 commented on src/yuzu/main.cpp
> +#include <shobjidl.h>
Please keep includes at top of the file.

2023-10-05 07:26 UTC, v1993 commented on src/yuzu/main.cpp
> +    CoUninitialize();
This does not get called on error execution paths. Use yuzu's `SCOPE_EXIT` macro to fix this.

2023-10-05 07:26 UTC, v1993 commented on src/yuzu/main.cpp
> +            [[fallthrough]];
No need for `[[fallthrough]]` on empty cases.

2023-10-05 07:26 UTC, v1993 commented on src/common/fs/fs_util.cpp
> + */
It's unclear to what exact functionality this comment relates since it's at top of the file rather than attached to any specific code. Besides, it appears to be unrelated to overall changes of this PR? Might be better as an issue report, assuming this indeed causes issues in practice.

(Also, I presume cannon was supposed to refer to the process of Canonicalization? Don't shoot the utf8-encoded message...)

2023-10-05 07:26 UTC, v1993 commented on src/yuzu/main.cpp
> +    if (CreateShortcut(shortcut_path.string(), title, comment, icon_path.string(),
Regarding this change: I think it would be a good idea to have the same signature for shortcut creation method on all platforms. This would also remove the need for `is_success` variable.

2023-10-05 07:26 UTC, v1993 commented on src/yuzu/util/util.cpp
> +#include <Windows.h>
Again, includes at top of the file.

But also - can't this section be fairly simply rewritten to be cross-platform? The only windows-specific stuff is struct definitions and a few constants.

2023-10-05 16:59 UTC, boludoz commented
> const std::filesystem::path

Yes Sir, all functional. I really liked that you used Qt to create the icon, I'm going to do more research on that soon. I really liked that you used Qt to create the icon. I'll do more research on that soon to provide cross-platform support.

2023-10-05 17:00 UTC, boludoz commented
> Yes, you can use my code. Is there anything else missing? Is everything functional now?

Yes Sir, all functional. I really liked that you used Qt to create the icon, I'm going to do more research on that soon. I really liked that you used Qt to create the icon. I'll do more research on that soon to provide cross-platform support.

2023-10-05 17:02 UTC, boludoz commented on src/yuzu/main.cpp
> +#include <shobjidl.h>
Okay, maybe soon I will eliminate everything related to Windows and start using Qt to ensure cross-platform.

2023-10-05 17:03 UTC, boludoz commented on src/yuzu/main.cpp
> +    const std::filesystem::path IconPath{};
A typo, thanks.

2023-10-05 17:12 UTC, boludoz commented on src/yuzu/main.cpp
> +    if (CreateShortcut(shortcut_path.string(), title, comment, icon_path.string(),
Yes, I'm working on it sir.

2023-10-05 17:16 UTC, boludoz commented on src/yuzu/main.cpp
> +    CoUninitialize();
Good detail to keep in mind.

2023-10-05 22:50 UTC, boludoz commented
Thank you for your review, try to apply everything I recommend, any new suggestions will be welcome or you can mention me if I forgot something.

2023-10-07 19:28 UTC, boludoz commented
@v1993 a final compilation sir

2023-10-08 21:18 UTC, liamwhite commented
I believe this was superseded by #11705?

2023-10-08 21:29 UTC, boludoz commented
> I believe this was superseded by #11705?

Honestly, my implementation has some better things and some worse things, but continue, they may be added in the future.

2023-10-08 23:46 UTC, FearlessTobi commented
Then please properly rebase your PR, so we can see what was changed.

2023-10-15 05:03 UTC, closed without merging