Improved shortcut: add games in applist for Windows, question for sta…
yuzu-emu/yuzu pull request #11792
Opened 2023-10-15 05:03 UTC by boludoz

…rt game at fullscreen & better unicode support for some Windows path funcs.

Replace of #11665.

2023-10-15 07:23 UTC, german77 commented
GetDesktopPath and GetAppsShortcutsPath where replaced by Qt equivalents. I heavily suggest using these because they already deal with OS and locale variants. 

https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L2876
https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L2883

2023-10-15 07:29 UTC, german77 commented on src/common/fs/path_util.h
> -
Also please revert all miscellaneous changes like these.

2023-10-15 07:29 UTC, german77 commented on src/yuzu/util/util.h
> +
Same here

2023-10-15 14:20 UTC, boludoz commented
> GetDesktopPath and GetAppsShortcutsPath where replaced by Qt equivalents. I heavily suggest using these because they already deal with OS and locale variants.
> 
> https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L2876 https://github.com/yuzu-emu/yuzu/blob/master/src/yuzu/main.cpp#L2883

Yes, the Qt function is also preserved.

2023-10-15 15:22 UTC, FearlessTobi requested changes

2023-10-15 15:22 UTC, FearlessTobi commented on src/common/fs/fs_util.cpp
> +std::u8string U8FilenameSantizer(const std::u8string_view u8filename) {
There is already code for handling this in main.cpp.
This function is not needed

2023-10-15 15:22 UTC, FearlessTobi commented on src/common/fs/path_util.cpp
> +fs::path GetDesktopPath() {
we already have a way to get these paths with QT

2023-10-15 15:22 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +            LOG_ERROR(Common, "[GMainWindow::CreateShortcutLink] Failed to create shortcut");
this is not how we do logging in yuzu, I suggested taking a look at other logging functions to see how to do it properly.
```suggestion
            LOG_ERROR(Frontend, "Failed to create shortcut");
```

2023-10-15 15:22 UTC, FearlessTobi commented on src/yuzu/main.cpp
> -bool GMainWindow::CreateShortcut(const std::string& shortcut_path, const std::string& title,
This function works fine, why rewrite it and move it somewhere else?
It just makes the PR harder to review.

2023-10-15 18:00 UTC, german77 commented on src/yuzu/util/util.h
> +
These changes are unrelated to this PR as well.

2023-10-15 18:02 UTC, german77 commented on src/common/fs/fs_util.h
> +[[nodiscard]] std::u8string U8FilenameSantizer(const std::u8string_view u8filename);
santized ==> sanitized

Same for bellow and comments

2023-10-15 23:01 UTC, boludoz commented on src/yuzu/main.cpp
> -bool GMainWindow::CreateShortcut(const std::string& shortcut_path, const std::string& title,
Because the name is repeated in another Qt function and it is confusing.

2023-10-15 23:02 UTC, boludoz commented on src/common/fs/path_util.cpp
> +fs::path GetDesktopPath() {
The function has already been removed.

2023-10-15 23:03 UTC, boludoz commented on src/yuzu/main.cpp
> +            LOG_ERROR(Common, "[GMainWindow::CreateShortcutLink] Failed to create shortcut");
I consider it a good way to debug the code but I can delete it.

2023-10-15 23:13 UTC, boludoz commented on src/common/fs/fs_util.cpp
> +std::u8string U8FilenameSantizer(const std::u8string_view u8filename) {
But my role is different and more complete, give it a chance and you'll see.

2023-10-15 23:34 UTC, boludoz commented on src/common/fs/fs_util.h
> +[[nodiscard]] std::u8string U8FilenameSantizer(const std::u8string_view u8filename);
Ops...

2023-10-16 00:41 UTC, boludoz commented on src/common/fs/fs_util.cpp
> +std::u8string U8FilenameSantizer(const std::u8string_view u8filename) {
Done sir

2023-10-16 03:20 UTC, liamwhite commented on src/common/fs/path_util.cpp
> +        CoTaskMemFree(appdata_roaming_path);
As above, no documented errata here...
```cpp
fs::path fs_appdata_roaming_path(appdata_roaming_path, fs::path::native_format);
CoTaskMemFree(appdata_roaming_path);

return fs_appdata_roaming_path.
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    // Replace characters that are illegal in Windows filenames
This comment doesn't describe the following action

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return shortcut_succeeded;
reut
```suggestion
        return false;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    LOG_ERROR(Frontend, "Create shortcut path: {}", shortcut_path_full.string());
Error log for non-error condition

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    // This desktop file template was writing referencing
```suggestion
    // Reference for the desktop file template:
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +            return shortcut_succeeded;
```suggestion
            return false;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        shortcut_stream.close();
This line is unreachable

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return shortcut_succeeded;
```suggestion
        return false;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        LOG_ERROR(Frontend, "Failed to create IShellLinkWinstance");
Move this up to `return false;` early if creating the IShellLinkW fails. Then you can unwrap the body of the if block.

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    bool shortcut_succeeded = false;
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +            hres = ps1->SetIconLocation(wicon_path.data(), 0);
All of these ifs should have braces on their bodies

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        IPersistFile* pPersistFile = nullptr;
```suggestion
        IPersistFile* persist_file = nullptr;
        SCOPE_EXIT({
            if (persist_file != nullptr) {
                persist_file->Release();
            }
        });
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        }
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    return shortcut_succeeded;
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +
```suggestion
        return result == QMessageBox::Yes;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +
```suggestion
        return true;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return (result == QMessageBox::StandardButton::Cancel) ? true : false;
```suggestion
        return result == QMessageBox::StandardButton::Ok;
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        LOG_ERROR(Frontend, "Cannot create shortcut in Apps. Restart yuzu as administrator.");
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        LOG_ERROR(Frontend, "Failed to create a shortcut to {}", title);
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +    return true;
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        icons_path = ""; // Reset path
```suggestion
        icons_path.clear();
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +                                      std::filesystem::path& icons_path) {
```suggestion
                                      std::filesystem::path& out_icon_path) {
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +bool GMainWindow::CreateShortcutMessagesGUI(QWidget* parent, const int& imsg,
```suggestion
bool GMainWindow::CreateShortcutMessagesGUI(QWidget* parent, int imsg,
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +                                                   "");
Missing title

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        HANDLE hProcess = GetCurrentProcess();
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +        CloseHandle(hProcess);
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.cpp
> +
```suggestion
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.h
> +    bool CreateShortcutMessagesGUI(QWidget* parent, const int& imsg, const std::string title);
```suggestion
    bool CreateShortcutMessagesGUI(QWidget* parent, int imsg, const QString& title);
```

2023-10-16 03:20 UTC, liamwhite commented on src/yuzu/main.h
> +                             std::filesystem::path& icons_path);
```suggestion
                             std::filesystem::path& out_icon_path);
```

2023-10-16 04:19 UTC, boludoz commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
That won't solve the problem, it's a protocol problem, C++ is not able to handle it. Try that:
```
#include <filesystem>
#include <iostream>
#include <string>
#include <windows.h>
int main() {
    // console UTF-8
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
    std::filesystem::path p{L"♻️"};
    std::cout << p.string() << '\n';
}
```
Or 

```
#include <filesystem>
#include <iostream>
#include <string>
#include <windows.h>
int main() {
    // console UTF-8
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
    std::filesystem::path p{L"♻️", std::filesystem::path::native_format};
    std::cout << p.string() << '\n';
}
```

2023-10-16 04:26 UTC, german77 commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
I decided to test with this special character on mainline. Seems to be already handled properly. Is this really needed?

![image](https://github.com/yuzu-emu/yuzu/assets/5944268/f8c71caf-c680-4738-839c-c4c41fdfae8a)

2023-10-16 05:03 UTC, boludoz commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
Your answer is misplaced because it has nothing to do with this.

2023-10-16 05:05 UTC, boludoz commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/cd256d30-0734-4145-9026-2172b15a96c0)

2023-10-16 05:07 UTC, boludoz commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
The strings become impossible to manipulate, suppose the user decides to put in their username something like ♻️ a username in another language.

2023-10-16 05:09 UTC, boludoz commented on src/common/fs/path_util.cpp
> +        return fs::path{Common::UTF16ToUTF8(wideExePath)}.parent_path();
Please if I missed something or am not understanding something let me know! 🙏

2023-10-16 05:56 UTC, boludoz commented on src/yuzu/main.cpp
> +        IPersistFile* pPersistFile = nullptr;
A genius.

2023-10-16 13:07 UTC, liamwhite commented on src/common/fs/path_util.cpp
> +        CoTaskMemFree(appdata_roaming_path);
Marked as resolved but name of variable not fixed.

2023-10-16 13:10 UTC, liamwhite commented on src/yuzu/main.h
> +    bool CreateShortcutMessagesGUI(QWidget* parent, const int& imsg, const std::string title);
Marked as resolved but signature remains incorrect.

2023-10-16 13:14 UTC, liamwhite commented on src/yuzu/main.cpp
> +        icons_path = ""; // Reset path
Variable name was changed but comment not resolved

2023-10-16 19:32 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return (result == QMessageBox::StandardButton::Cancel) ? true : false;
Comment was marked as resolved, but was not resolved.

2023-10-17 00:46 UTC, liamwhite commented on src/yuzu/main.cpp
> +            shortcut_stream.close();
The file will be flushed and closed when the destructor for the std::ofstream occurs here (RAII), so you don't need to call it explicitly
```suggestion
```

2023-10-17 00:47 UTC, liamwhite commented on src/yuzu/main.cpp
> +        if (shortcut_stream.is_open()) {
```suggestion
        if (!shortcut_stream.is_open()) {
            LOG_ERROR(Frontend, "Failed to create shortcut");
            return false;
        }
```

And then unindent the rest of the block

2023-10-17 00:47 UTC, liamwhite commented on src/yuzu/main.cpp
> +        shortcut_stream.close();
Closed when the destructor runs, so no need to call explicitly
```suggestion
```

2023-10-17 00:48 UTC, liamwhite commented on src/yuzu/main.cpp
> +        LOG_ERROR(Frontend, "Failed to create shortcut: {}", e.what());
Move to function catch block
```suggestion
```

2023-10-17 00:49 UTC, liamwhite commented on src/yuzu/main.cpp
> +
```suggestion
    if (!SUCCEEDED(hr)) {
        LOG_ERROR(Frontend, "CoInitialize failed");
        return false;
    }

```

And then unindent the rest of the block

2023-10-17 00:50 UTC, liamwhite commented on src/yuzu/main.cpp
> +        if (SUCCEEDED(hres)) {
```suggestion
        if (!SUCCEEDED(hres)) {
            LOG_ERROR(Frontend, "Failed to create CoCreateInstance");
            return false;
        }
```
And then unindent the rest of the block

2023-10-17 00:50 UTC, liamwhite commented on src/yuzu/main.cpp
> +}
Function catch block:
```suggestion
} catch (std::exception& e) {
    LOG_ERROR(Frontend, "Failed to create shortcut: {}", e.what());
    return false;
}
```

2023-10-17 00:51 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return (result == QMessageBox::Yes);
```suggestion
        return result == QMessageBox::Yes;
```

2023-10-17 00:51 UTC, liamwhite commented on src/yuzu/main.cpp
> +        return (result == QMessageBox::Ok);
```suggestion
        return result == QMessageBox::Ok;
```

2023-10-17 00:51 UTC, liamwhite commented on src/yuzu/main.cpp
> +    return false;
```suggestion
```

2023-10-17 00:52 UTC, liamwhite commented on src/yuzu/main.cpp
> +        break;
```suggestion
        return false;
```

2023-10-17 00:52 UTC, liamwhite commented on src/yuzu/main.cpp
> +        break;
```suggestion
        return false;
```

2023-10-17 00:52 UTC, liamwhite commented on src/yuzu/main.cpp
> +        break;
```suggestion
        return false;
```

2023-10-17 01:33 UTC, boludoz commented on src/yuzu/main.cpp
> +                                     const std::string& keywords, const std::string& name) {
Interesting, I didn't know it was possible to do that.

2023-10-18 01:08 UTC, german77 commented
I was testing the feature. Do we really need to run yuzu as admin? We normally don't enforce this due to security reasons. 

I also don't need any privilege to create shortcuts in the QStandardPaths::ApplicationsLocation path. It simply works on my PC.

2023-10-18 01:23 UTC, boludoz commented
> I was testing the feature. Do we really need to run yuzu as admin? We normally don't enforce this due to security reasons. 
> 
> I also don't need any privilege to create shortcuts in the QStandardPaths::ApplicationsLocation path. It simply works on my PC.

Hmm maybe it's a confusion, I'm using Windows 11.

2023-10-18 01:46 UTC, german77 commented
I will test on windows 11 in a few minutes. Yuzu installer also adds shortcuts without any admin privilege and as far as I know it works on both windows 10 and 11.

2023-10-18 01:55 UTC, german77 commented
No issues with windows 11 either. My suggestion is to remove the admin check and if it fails just display the error.

2023-10-18 02:11 UTC, boludoz commented
> No issues with windows 11 either. My suggestion is to remove the admin check and if it fails just display the error. 

Ok 👍

2023-10-18 04:22 UTC, boludoz commented
> No issues with windows 11 either. My suggestion is to remove the admin check and if it fails just display the error.

I checked my code again and it is not necessary to have an administrator now, maybe I got confused by an error in my previous code.

2023-10-18 04:50 UTC, boludoz commented
MacOS supports desktop shortcut or should we add a key to the function?

2023-10-18 05:35 UTC, boludoz commented
Added #if !defined to avoid compilation on Apple.

2023-10-18 05:41 UTC, german77 commented
Needs to be tested. Simply remove the UI elements. Other functions shouldn't need to be excluded from mac. Just to avoid those ifdef everywhere

2023-10-18 13:04 UTC, boludoz commented
> Needs to be tested. Simply remove the UI elements. Other functions shouldn't need to be excluded from mac. Just to avoid those ifdef everywhere 

I'll do it later.

2023-10-18 17:11 UTC, german77 commented
Actually since no official build for mac is released we can keep this feature enabled. Nothing bad will happen if it fails so there's no need to avoid displaying the feature.

2023-10-18 22:32 UTC, boludoz commented
> Actually since no official build for mac is released we can keep this feature enabled. Nothing bad will happen if it fails so there's no need to avoid displaying the feature.

Ok, I already reverted the changes and left only those in the game list (for Apple).

2023-10-18 22:35 UTC, boludoz commented
The criticisms are welcome, although it is never published, I find it useful.

2023-10-26 20:32 UTC, goldenx86 commented
Games with custom per-game settings try to load with NULL renderer and crash.

2023-10-26 23:16 UTC, boludoz commented
> Games with custom per-game settings try to load with NULL renderer and crash.

Could you provide more information if it is Windows, Linux. What do you mean by custom configuration?

2023-11-04 04:55 UTC, german77 commented
The bug reported doesn't seem related to this PR. This only creates shortcuts any crash related to launching from the shortcut is outside the scope of this PR. Please Rebase so we can add it again for general testing.

2023-11-06 17:49 UTC, german77 commented
Just in case you didn't notice, clang format didn't pass.

2023-11-08 21:05 UTC, boludoz commented
> Just in case you didn't notice, clang format didn't pass.

"Estoy cansado jefe"

2023-11-08 23:45 UTC, german77 commented on src/yuzu/main.cpp
> +}
Missing new line

2023-11-09 00:30 UTC, german77 commented on src/yuzu/main.cpp
> +    out_icon_path = Common::FS::GetYuzuPath(Common::FS::YuzuPath::ConfigDir) / "icons";
Why the icon path was changed?  `Common::FS::YuzuPath::IconsDir` was the dedicated folder for icons

2023-11-09 04:04 UTC, german77 commented on src/yuzu/main.cpp
> +    out_icon_path = Common::FS::YuzuPath::IconsDir;
out_icon_path = Common::FS::GetYuzuPath(Common::FS::YuzuPath::IconsDir);

2023-11-19 04:42 UTC, german77 approved these changes

2023-11-19 14:50 UTC, merged