Enable (Feral Interactive) Gamemode on Linux
yuzu-emu/yuzu pull request #11946
Opened 2023-11-02 16:54 UTC by flodavid

Rebase of #10599 by @xcfrg on master, using new settings.
Gamemode needs to be installed on the computer to be used, otherwise it runs without it and a warning is logged.

I set the setting has being disabled when a game is running, as I do not know if it is possible to enable/disable gamemode while running. But `SetGamemodeDisabled()` is called if the settings is changed, so we would only need to change from `false` to `true` in the Setting definition in settings.h

> This pull request adds [Feral Gamemode](https://github.com/FeralInteractive/gamemode) support to yuzu on linux, allowing for optimizations to the cpu governor, i/o and process priority, and if using a -ck or -pf kernel, the kernel scheduler.
> 
> Closes https://github.com/yuzu-emu/yuzu/issues/10078

2023-11-02 18:57 UTC, flodavid commented
Fixed Windows compilation (disabling gamemode was in the wrong configuration class).
By the way, I put the setting in System. I was not sure if it was better in General

2023-11-02 21:28 UTC, abouvier commented on externals/CMakeLists.txt
> +    target_include_directories(gamemode PUBLIC gamemode/include)
Why not put that in `externals/gamemode/CMakeLists.txt`?

2023-11-03 12:48 UTC, flodavid commented
I would agree, but "General -> General" is called UiGeneral in the code, and it contains only UI stuff maybe. This change is not UI specific.
Maybe those other options would better fit in "General -> UI". But then keeping the (kinda consufingly named) "General -> General" category just for Gamemode would be weird, so it would better fit where it is now.

2023-11-03 14:44 UTC, flodavid commented
I ended up creating a Linux dedicated sub-category in "System" settings.
This also fixes windows compilation

2023-11-03 14:58 UTC, flodavid commented on externals/CMakeLists.txt
> +    target_include_directories(gamemode PUBLIC gamemode/include)
I moved the target_include_directories in gamemode cmakelists, I guess this is what you wanted

2023-11-06 01:51 UTC, FearlessTobi requested changes
Thanks for picking this up!

2023-11-06 01:51 UTC, FearlessTobi commented on src/android/app/src/main/jni/default_ini.h
> +# Use gamemode
Is this used on Android?

2023-11-06 01:51 UTC, FearlessTobi commented on src/common/settings.cpp
> +        return "Linux";
I don't think this needs a seperate category, it can probably just live in the General tab.

2023-11-06 01:51 UTC, FearlessTobi commented on src/common/settings.h
> +    SwitchableSetting<bool> disable_gamemode{linkage, false, "disable_gamemode", Category::Linux};
```suggestion
    SwitchableSetting<bool> enable_gamemode{linkage, true, "enable_gamemode", Category::Linux};
```

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +#ifdef __linux__
we already have an ifdef for unix systems further above

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +    SetGamemodeDisabled(Settings::values.disable_gamemode.GetValue());
```suggestion
    SetGamemodeEnabled(Settings::values.enable_gamemode.GetValue());
```

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +#ifdef __linux__
```suggestion
#ifdef __unix__
```

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +    if (!Settings::values.disable_gamemode) {
The gamemode start/stop should be in their own functions.

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +#ifdef __linux__
dito

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/main.cpp
> +void GMainWindow::SetGamemodeDisabled([[maybe_unused]] bool state) {
if you wrap the entire function in the ifdef, you don't need to add the `[[maybe_unused]]` to the variable.

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu/uisettings.h
> +
```suggestion
```

2023-11-06 01:51 UTC, FearlessTobi commented on src/yuzu_cmd/default_ini.h
> +# Use gamemode
```suggestion
# Use gamemode (Linux only)
```

2023-11-08 00:40 UTC, flodavid commented on src/android/app/src/main/jni/default_ini.h
> +# Use gamemode
No. It’s  a mistake

2023-11-08 14:44 UTC, flodavid commented on src/yuzu/main.cpp
> +void GMainWindow::SetGamemodeDisabled([[maybe_unused]] bool state) {
Then I need to add an `ifndef __unix__` for every call right ?

2023-11-09 00:20 UTC, flodavid commented on src/yuzu_cmd/default_ini.h
> +# Use gamemode
done

2023-11-09 00:20 UTC, flodavid commented on src/yuzu/uisettings.h
> +
done

2023-11-09 00:22 UTC, flodavid commented on src/yuzu/main.cpp
> +void GMainWindow::SetGamemodeDisabled([[maybe_unused]] bool state) {
I ended up putting the function in new gamemode files in the new module common/linux. The include and the calls are wrapped in ifdef

2023-11-09 00:22 UTC, flodavid commented on src/yuzu/main.cpp
> +#ifdef __linux__
done

2023-11-09 00:22 UTC, flodavid commented on src/yuzu/main.cpp
> +    if (!Settings::values.disable_gamemode) {
done

2023-11-09 00:22 UTC, flodavid commented on src/yuzu/main.cpp
> +    SetGamemodeDisabled(Settings::values.disable_gamemode.GetValue());
done

2023-11-09 00:22 UTC, flodavid commented on src/yuzu/main.cpp
> +#ifdef __linux__
merged and use unix

2023-11-09 00:22 UTC, flodavid commented on src/common/settings.h
> +    SwitchableSetting<bool> disable_gamemode{linkage, false, "disable_gamemode", Category::Linux};
done

2023-11-09 00:23 UTC, flodavid commented on src/common/settings.cpp
> +        return "Linux";
I did just that

2023-11-09 00:23 UTC, flodavid commented on src/android/app/src/main/jni/default_ini.h
> +# Use gamemode
fixed

2023-11-09 00:24 UTC, flodavid commented
Thanks for the suggestions. I applied the fixes and created dedicated file for the gamemode functions

2023-11-10 21:30 UTC, FearlessTobi requested changes

2023-11-10 21:30 UTC, FearlessTobi commented on src/common/linux/gamemode.cpp
> +void tryStartLinuxGamemode() {
```suggestion
void StartGamemode() {
```

2023-11-10 21:30 UTC, FearlessTobi commented on src/common/linux/gamemode.cpp
> +void tryStopLinuxGamemode() {
```suggestion
void StopGamemode() {
```

2023-11-10 21:30 UTC, FearlessTobi commented on src/common/settings.cpp
> +        return "Linux";
Thanks, I think this code can be removed now.

2023-11-10 21:30 UTC, FearlessTobi commented on src/common/linux/gamemode.cpp
> +void setGamemodeState(bool state) {
```suggestion
void SetGamemodeState(bool state) {
```

2023-11-10 21:30 UTC, FearlessTobi commented on src/yuzu/configuration/config.cpp
> +void Config::ReadLinuxValues() {
I think this can be removed now.

2023-11-10 21:30 UTC, FearlessTobi commented on src/yuzu/configuration/config.cpp
> +void Config::SaveLinuxValues() {
dito

2023-11-10 21:30 UTC, FearlessTobi commented on src/yuzu/configuration/configure_general.cpp
> +    std::vector<Settings::BasicSetting*> settings;
Why does all of this need to be changed?
Can't you just conditionally show/hide the `LinuxGroupBox`?

2023-11-10 21:30 UTC, FearlessTobi commented on src/yuzu/configuration/configure_system.cpp
> +    auto& core_layout = *ui->core_widget->layout();
i dont see why this needs to be changed

2023-11-10 21:30 UTC, FearlessTobi commented on src/yuzu/configuration/configure_system.ui
> +      <widget class="QGroupBox" name="coreGroup">
dito

2023-11-12 21:24 UTC, flodavid commented on src/yuzu/configuration/configure_general.cpp
> +    std::vector<Settings::BasicSetting*> settings;
Yes, it is possible, it would mean that the sub-category and its elements are there, just hidden.
What's done now is that they do not even exist

2023-11-12 21:29 UTC, flodavid commented on src/yuzu/configuration/configure_system.ui
> +      <widget class="QGroupBox" name="coreGroup">
I changed the name for consistency with other ui files

2023-11-12 21:44 UTC, flodavid commented on src/yuzu/configuration/configure_general.cpp
> +    std::vector<Settings::BasicSetting*> settings;
I simplified it as you said

2023-11-12 21:45 UTC, flodavid commented on src/yuzu/configuration/config.cpp
> +void Config::ReadLinuxValues() {
Linux is now a Sub-category, but it's still declared as a Category, so it must read a write its values

2023-11-21 13:39 UTC, flodavid commented on src/common/settings.cpp
> +        return "Linux";
@FearlessTobi Linux is now a Sub-category of UiGeneral, but it must still be declared as a Category

2023-11-22 11:22 UTC, flodavid commented on src/yuzu/configuration/configure_system.cpp
> +
fixed it

2023-11-23 17:02 UTC, FearlessTobi commented on src/yuzu/configuration/configure_system.cpp
> +
This has not been addressed.

2023-11-23 17:03 UTC, FearlessTobi commented
Seems like compilation of this is broken now.

2023-11-25 16:26 UTC, flodavid commented
It needed a rebase. because of #11889

2023-11-25 21:08 UTC, liamwhite commented on src/yuzu/configuration/configure_general.cpp
> +#ifndef __unix__
Use __linux__ for all of the ifdefs instead of __unix__

2023-11-25 21:10 UTC, liamwhite approved these changes
nvm on previous review

2023-11-29 17:33 UTC, merged