dist: add udev rule to enable user hidraw access
yuzu-emu/yuzu pull request #12292
Opened 2023-12-06 11:42 UTC by HurricanePootis

On linux, whenever a device is connected to the system, the only user/group allowed to access is `root`. This is a problem, however, for the custom drivers for both the joycons and the pro controller. Therefore, I am making this PR to add a udev ruels in the `dist/` folder. 

This is helpful for both appimage/flaptak users and users who get their controller via a system package manager. For the former group, instead of the user having to go to the discord and either see the pinned post with an outdated method using `plugdev` (which, to my understanding, is a debian thing), the user can download this file from the github repo and install it at `/etc/udev/rules.d/99-yuzu-input.rules`. For the latter group, system packagers can automatically include this rule and have it installed at `/usr/udev/rules.d/99-yuzu-input.rules`

Now, I currently don't have access to any switch controllers as I am using a Wii U controller at the moment, but anyone who does and is on linux, please try it out and give me feedback! Hopefully, this PR will get accepted, and in the upcoming new yuzu wiki, linux users can be referred to this file.

2023-12-06 12:32 UTC, v1993 commented
You must prefix it with `72-`, `99-` will not work. See https://github.com/systemd/systemd/issues/4288.

2023-12-06 12:45 UTC, HurricanePootis commented
> You must prefix it with `72-`, `99-` will not work. See [systemd/systemd#4288](https://github.com/systemd/systemd/issues/4288).

done

2023-12-06 14:17 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +#Consult your distro if this is not the case
```suggestion
# Allow systemd-login to manage user access to hidraw with this file
# On most systems, this file should be installed to /etc/udev/rules.d/72-yuzu-input.rules
# Consult your distro if this is not the case
```

2023-12-06 14:17 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +#Nintendo's Switch Pro Controller and Pro Controller for Wired and Bluetooth
```suggestion
# Switch Pro Controller (USB/Bluetooth)
```

2023-12-06 14:17 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +KERNEL=="hidraw*", KERNELS=="*057e:2006*", MODE="0600", TAG+="uaccess"
```suggestion
# Joy-Con L (Bluetooth)
KERNEL=="hidraw*", KERNELS=="*057e:2006*", MODE="0600", TAG+="uaccess"
```

2023-12-06 14:17 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +KERNEL=="hidraw*", KERNELS=="*057e:2007*", MODE="0600", TAG+="uaccess"
```suggestion
# Joy-Con R (Bluetooth)
KERNEL=="hidraw*", KERNELS=="*057e:2007*", MODE="0600", TAG+="uaccess"

# Joy-Con Charging Grip (USB)
KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="200e", MODE="0600", TAG+="uaccess"
```

2023-12-06 14:45 UTC, HurricanePootis commented
Thanks for the suggestions @liamwhite

2023-12-06 15:54 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +# Allow systemd-login to manage user access to hidraw with this file
Add SPDX header

2023-12-06 15:54 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +# Allow systemd-login to manage user access to hidraw with this file
```suggestion
# Allow systemd-logind to manage user access to hidraw with this file
```

2023-12-06 18:44 UTC, kojq requested changes
None of these are functionally necessary, but these are suggestions:

- `*057e:2009*` can be changed to `0005:057e:2009.*` and so on for the remaining lines to be more explicit.

- Spacing out from the next comment as was done with `# Joy-Con Charging Grip (USB)` would make this file more readable.

- `Joy-Con L` can be changed to `Joy-Con (L)` and so on for consistent naming.

- `SUBSYSTEM=="hidraw"` can be included to be more explicit.

2023-12-06 18:48 UTC, liamwhite commented
@kojq the names of 057e:2006 and 057e:2007 in the [USB ID repository](http://www.linux-usb.org/usb-ids.html) are Joy-Con L and Joy-Con R -- no parentheses.

2023-12-06 18:59 UTC, kojq commented
@liamwhite ah, so we are using that for reference. Also, why is `MODE=` RWX permission different for the Pro Controller?

2023-12-06 19:04 UTC, liamwhite commented
That seems like a mistake, it shouldn't need +x.

2023-12-07 15:06 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +KERNEL=="hidraw*", KERNELS=="*057e:2009*", MODE="0660", TAG+="uaccess"
```suggestion
KERNEL=="hidraw*", KERNELS=="*057e:2009*", MODE="0660", TAG+="uaccess"

```

2023-12-07 15:06 UTC, liamwhite commented on dist/72-yuzu-input.rules
> +KERNEL=="hidraw*", KERNELS=="*057e:2006*", MODE="0660", TAG+="uaccess"
```suggestion
KERNEL=="hidraw*", KERNELS=="*057e:2006*", MODE="0660", TAG+="uaccess"

```

2023-12-07 21:48 UTC, liamwhite approved these changes

2023-12-08 04:12 UTC, merged