Core: Implement Device Mapping & GPU SMMU
yuzu-emu/yuzu pull request #12579
Opened 2024-01-04 19:16 UTC by FernandoS27

Memory in Tegra X1 works very differently to how it's currently emulated. Normally there's physical memory of (4Gb), a virtual memory address space used by processes (applications like games for example) and device virtual memory spaces used by peripherals (GPU, DSP, bluetooth, etc). This device memory space is normally called (SMMU) System Memory Management Unit or IOMMU. With this address space, the different devices can map over physical memory used by many different applications to one they can only see. This has the advantage that it allows sharing memory among many multiple processes in the OS with each device.

This PR implements a general simplified version of the SMMU and implements it for the GPU. With some differences, first, we use full 34 bits of the AS instead of just 32 bits for pinning memory, second, we use a common SMMU page file for every process in the GPU instead of switching it per channel.

Currently in yuzu., the GPU uses a memory model of GMMU (GPU's MMU) -> PMMU (the main application's virtual space) -> physical memory to handle memory overall. This is great when there is only one application using the GPU at a time and it's never shared with other processes. 95% of the time this is what happens in the switch. However, it is possible to have multiple processes running and rendering concurrently as is the case of overlays and applets like inline software keyboard. It's also possible to have an application suspended while another is running (an applet is running while the game is suspended). With the implementation of the SMMU, it is now possible to share the GPU resources without any issues whatsoever.

**Advantages of new SMMU:**

- Not perfect but more accurate than before.
- Uses less memory overall for tracking GPU memory.
- More optimizations possible, in the future.
- Multiprocess use of the emulated GPU.
- Other devices can use the device mapper in case it's needed or be extended through correct implementation of KDevicePageTable.

** Disadvantages of the new SMMU. **
- Harder tracking of resources.
- Complicated.
- More accurate than before but not perfectly accurate to avoid sacrificing performance.

Current issues:

- [ ] Pikmin 4 seems to get some vertex explosions after transitioning in many worlds.
- [ ] There's some memory leaking after closing an application.
- [ ] It's not working with 6Gb/8Gb memory layouts.
- [ ] Needs more cleanup.

2024-01-05 13:06 UTC, bylaws requested changes

2024-01-05 13:06 UTC, bylaws commented on src/core/hle/service/nvdrv/core/nvmap.cpp
> +                if (handle_description->allocated) {
This isn't correct to do, why exactly is it required?

2024-01-05 13:06 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvmap.cpp
> +    const auto result = file.AllocateHandle(params.handle, params.flags, params.align, params.kind,
The alloc ioctl isn't supposed to map memory onto the smmu here like this does, why is it done here?

2024-01-06 04:56 UTC, FernandoS27 commented on src/core/hle/service/nvdrv/devices/nvmap.cpp
> +    const auto result = file.AllocateHandle(params.handle, params.flags, params.align, params.kind,
oh that was reverted at some point.

2024-01-06 04:57 UTC, FernandoS27 commented on src/core/hle/service/nvdrv/core/nvmap.cpp
> +                if (handle_description->allocated) {
I think you are looking at an old commit.

2024-01-07 01:17 UTC, kkxiegouquan commented
l hope to test this feature

2024-01-07 03:53 UTC, FernandoS27 commented
> l hope to test this feature

this alone means almost nothing to users but it will allow a LOT of cool stuffs soon.

2024-01-07 15:25 UTC, kkxiegouquan reviewed
This feature should be great!!

2024-01-07 21:16 UTC, Slexer commented
How much work is left for a complete UMA implementation? Is SMMU a big chunk of it or just a little bit?

2024-01-07 21:43 UTC, FernandoS27 commented
> How much work is left for a complete UMA implementation? Is SMMU a big chunk of it or just a little bit?

For a real good and accurate UMA implementation; a lot of work. SMMU makes it easier for making the mirrors needed for DMI.

After that We'll do only DMI for downloads, which will improve things a bit.

Doing full DMI will be a challenge if we want to keep or even increase the compatibility we have. It will take a lot of time. I can't give an ETA.

2024-01-08 05:50 UTC, brujo5 commented
by DMI do they refer to direct memory import?  If yes, I remember that in Skyline they said that it only worked perfectly on a7xx and on a6xx you had to restart the phone or the games start to crash and it was a hardware bug, is that true?

2024-01-08 08:09 UTC, FernandoS27 commented
> by DMI do they refer to direct memory import? If yes, I remember that in Skyline they said that it only worked perfectly on a7xx and on a6xx you had to restart the phone or the games start to crash and it was a hardware bug, is that true?

Yes. It's true.

2024-01-09 16:18 UTC, kkxiegouquan approved these changes

2024-01-10 14:02 UTC, Hariu7 commented
How much fps it will boost

2024-01-10 15:09 UTC, liamwhite commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +    }
[sessions.erase(fd)](https://en.cppreference.com/w/cpp/container/unordered_map/erase)

2024-01-10 15:12 UTC, liamwhite commented on src/core/hle/service/nvdrv/nvdrv.cpp
> +        return std::make_shared<NVDRV>(system, module, "nvdrv:a");
nvdrv:s

2024-01-10 15:12 UTC, liamwhite commented on src/core/hle/service/nvdrv/nvdrv.cpp
> +    const auto NvdrvInterfaceFactory = [&, module] {
NvDrvInterfaceFactoryForTesting

2024-01-10 15:16 UTC, liamwhite commented on src/core/device_memory_manager.inc
> +    });
```cpp
std::unique_lock<std::mutex> lk(counter_guard, std::defer_lock);
const auto Lock = [&] {
    if (!lk) {
        lk.lock();
    }
};
```
and then the scope exit part is handled by the unique_lock so it's not needed to write it

2024-01-10 15:32 UTC, liamwhite commented on src/core/hle/service/nvdrv/core/container.cpp
> +            LOG_CRITICAL(Debug, "Preallocation created!");
Unnecessary critical log

2024-01-10 15:39 UTC, liamwhite commented on src/core/device_memory_manager.inc
> +    for (size_t i = num_pages; i > 0; i--) {
Wouldn't it make more sense to do this as a forward loop? Also it seems you are off by one...

2024-01-22 15:55 UTC, liamwhite approved these changes

2024-01-22 15:55 UTC, merged