Fix Just Dance 2023 not booting
yuzu-emu/yuzu pull request #13049
Opened 2024-02-18 00:01 UTC by Leystryku

**Issue:**
- Just Dance 2023 does not boot
- Cause is 2 missing stubs

**Solution:**
- Add a stub GetCacheStorageMax method which sets a cache size by default
- Add a stub FlushAccessLogOnSdCard method which returns success

**Outcome:**
- Game actually starts
![justdance2023_boots](https://github.com/yuzu-emu/yuzu/assets/6385154/b3cbeeac-74f3-40d5-ac8a-488fa4a37127)

2024-02-18 00:02 UTC, Leystryku commented
Only issue seems to be, that with the latest update (1.3.0) it still doesn't boot. But having the game be startable without the update is already a huge step up from not being able to play it at all.

[with_latest_update_1_3_0.txt](https://github.com/yuzu-emu/yuzu/files/14320570/with_latest_update_1_3_0.txt)

2024-02-18 00:03 UTC, Kelebek1 commented
Why 0xFFFFFF?

2024-02-18 00:03 UTC, liamwhite approved these changes

2024-02-18 00:07 UTC, Leystryku commented
> Why 0xFFFFFF?

I played around a bit with the maximum cache size and simply picked one with worked. I couldn't find any information regarding what maximum the actual switch console would normally return online

if you have experience with switch RE though and know the actual values the method should ideally return, I'd gladly change it to those

2024-02-18 00:15 UTC, liamwhite commented on src/core/hle/service/am/service/application_functions.cpp
> +Result IApplicationFunctions::GetCacheStorageMax(Out<u32> out_max_normal_size,
If you are interested in a correct (non-stub) implementation of this, the proper values are `out_cache_storage_index_max` and `out_cache_storage_data_and_journal_size_max`. and are [found](https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/am/service/library_applet_self_accessor.cpp#L160-L161) in the [NACP](https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/control_metadata.h#L66-L67). This may also fix your problem with the update.

2024-02-18 00:28 UTC, german77 commented on src/core/hle/service/filesystem/fsp/fsp_srv.cpp
> +} // namespace Service::FileSystem
missing newline

2024-02-18 00:59 UTC, FearlessTobi approved these changes
Looks good, apart from the two comments.

Thanks a lot for adding this!

2024-02-18 04:07 UTC, Leystryku commented on src/core/hle/service/am/service/application_functions.cpp
> +Result IApplicationFunctions::GetCacheStorageMax(Out<u32> out_max_normal_size,
Indeed, works. And quite wonderfully so - the update now boots up too and the IApplicationFunctions::CreateCacheStorage method is now actually being called (I believe, previously the game didn't call it).

2024-02-18 04:07 UTC, Leystryku commented on src/core/hle/service/filesystem/fsp/fsp_srv.cpp
> +} // namespace Service::FileSystem
done, added newline

2024-02-18 04:16 UTC, liamwhite requested changes

2024-02-18 04:16 UTC, liamwhite commented on src/core/hle/service/am/service/application_functions.cpp
> +     R_SUCCEED();
Take advantage of the behavior of R_TRY, and don't alias a u8* with a RawNACP*:
```suggestion
    FileSys::RawNACP raw_nacp{};
    std::vector<u8> nacp;
    R_TRY(system.GetARPManager().GetControlProperty(&nacp, m_applet->program_id));

    std::memcpy(&raw_nacp, nacp.data(), std::min(sizeof(raw_nacp), nacp.size()));

    *out_cache_storage_index_max = static_cast<u32>(raw_nacp->cache_storage_max_index);
    *out_max_journal_size = static_cast<u64>(raw_nacp->cache_storage_data_and_journal_max_size);

    R_SUCCEED();
```

Also, please fix the nacp [field](https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/control_metadata.h#L67) for cache_storage_max_index ... it is a u16 now as some fields adjacent to it have been [split](https://switchbrew.org/wiki/NACP#Structure) to expand the structure.

2024-02-18 05:05 UTC, liamwhite commented
Looks good now, just fix CI and you're set

2024-02-18 05:42 UTC, liamwhite commented on src/core/hle/service/am/service/application_functions.cpp
> +    std::unique_ptr<FileSys::RawNACP> raw_nacp(new FileSys::RawNACP{});
Why is this using a unique_ptr now?

2024-02-18 05:53 UTC, Leystryku commented on src/core/hle/service/am/service/application_functions.cpp
> +    std::unique_ptr<FileSys::RawNACP> raw_nacp(new FileSys::RawNACP{});
Without using a unique_ptr there'll be quite a lot of bytes being allocated on the stack (~16k); so I deemed it a safer idea to move this allocation to the heap

2024-02-18 05:55 UTC, liamwhite commented on src/core/hle/service/am/service/application_functions.cpp
> +    std::unique_ptr<FileSys::RawNACP> raw_nacp(new FileSys::RawNACP{});
Use std::make_unique, then

2024-02-18 06:06 UTC, liamwhite approved these changes

2024-02-18 15:25 UTC, merged

2024-02-18 16:40 UTC, JJRoyale commented
uh, yeah, this fixed the booting of the game but to mod songs (only way to play on emulators) you need folders called SD_Cache and they are stored in the profiles folder (which yuzu doesnt support) so basically its not useful to anything unless the function is implemented

2024-02-18 16:55 UTC, Leystryku commented
@JJRoyale If you can provide me with more info about this folder and it's nothing which requires too much changes to Yuzu (this was my first time modifying this huge code-base), I might be able to add support for that in a follow-up PR.

Iirc Yuzu already has support for emulating the SD Card, is SD_Cache just some folder which you put on the SD Card & then the game loads the songs from them or is it something with more complexity?

2024-02-18 16:56 UTC, JJRoyale commented
more complex, its where the saves are stored so you can only edit it on an modded switch

2024-02-18 17:09 UTC, german77 commented
Cache storage is defined here https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/savedata_factory.h#L35 and saved to this location https://github.com/yuzu-emu/yuzu/blob/master/src/core/file_sys/savedata_factory.cpp#L186

I think they work properly but since you can't download songs from nintendo for obvious reasons the user needs to put it manually. Providing a button to open the correct folder might be the solution. just like right clicking the game-> open save folder

2024-02-18 17:28 UTC, JJRoyale commented
yeah, that would be great

2024-02-23 21:29 UTC, ETE-Design commented
@Leystryku Would be so great to find a way to play it Offline

2024-02-23 22:50 UTC, Leystryku commented
So far my attempt at allowing the cache to be loaded/overwritten by a cache/ dir hasn't worked

I can get Yuzu to load the Just Dance Song Files, but the  game hangs hangs later on.  So far the reason has eluded me.

Maybe I will get it working when I have some time & feel like it, but worst case you guys might have to fix until someone with more time or more knowledge regarding Switch Emulation etc takes it up

2024-02-23 23:46 UTC, ETE-Design commented
@Leystryku Where do you place the song so Yuzu load them?

2024-02-24 11:17 UTC, Leystryku commented
I think I had to actually change some of the code to get it to load from Cache. If you wanna see my current attempt, you can pull it from my branch but as I said, when loading from cache - game hangs. So the songs can be loaded sure, but it leads to the game hanging without being able to i.e. pick a song

https://github.com/Leystryku/yuzu