input_common: First implementation of controller rumble
yuzu-emu/yuzu pull request #4291
Opened 2020-07-11 02:58 UTC by german77

This is an approach to implement a basic controller rumble. It enables vibrations on Pro Controllers that can use sdl_haptics. 
The first button of player settings is used as a reference to know which controller corresponds to which player.

From testing and debugging I found that controller_ids should be splitted into 4 bytes. The second rightmost byte always contains the player number.

Most of the code added should be changed with a better method. I'm looking to fix it until everyone it's happy with the code.

2020-07-11 02:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4291) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4291) before we can accept your contribution.<br/><hr/>**german** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=4291) it.</sub>

2020-07-11 09:10 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +        const auto byte0 = controller_ids[i] % 256; // posible motor direction?
Possible

2020-07-11 09:10 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +        const auto byte2 = (controller_ids[i] >> 16) % 256; // posible start/stop?
Ditto

2020-07-11 09:11 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                int joystick_index = connected_controllers[controller_pos].rumble_port;
```suggestion
                const int joystick_index = connected_controllers[controller_pos].rumble_port;
```

2020-07-11 09:12 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                //Amplitudes are to small, The motors can't spin with that little force
Comments should have a space after the `//`. Also `to` should be `too`.

2020-07-11 09:12 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                amplitude *= 6;
```suggestion
                amplitude *= 6.0f;
```

2020-07-11 09:13 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                if (amplitude > 1)
This and the following if statement can be collapsed into:

```cpp
amplitude = std::clamp(amplitude, 0.2f, 1.0f);
```

2020-07-11 09:13 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                    LOG_ERROR(Service_HID, "failed to open joystick {}", joystick_index);
```suggestion
                    LOG_ERROR(Service_HID, "Failed to open joystick {}", joystick_index);
```

2020-07-11 09:13 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                    LOG_INFO(Service_HID, "controller does not support haptics {}", joystick_index);
```suggestion
                    LOG_INFO(Service_HID, "Controller does not support haptics {}", joystick_index);
```

2020-07-11 09:14 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                //End of StartRumble
This comment is unnecessary.

2020-07-11 09:14 UTC, lioncash commented on src/input_common/sdl/sdl_impl.cpp
> +
This seems like an unnecessary change.

2020-07-11 09:15 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +            std::string find("port:");
```suggestion
            constexpr std::string_view find = "port:";
```

2020-07-11 09:17 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +                sscanf(button.c_str(), "%d", &port);
This can be [std::from_chars](https://en.cppreference.com/w/cpp/utility/from_chars). Which doesn't require you to make a substring, preventing an unnecessary copy.

2020-07-11 09:19 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +#include <regex>
This seems to be unused.

2020-07-11 09:21 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +#include <SDL.h>
I can't help but feel that the usage of SDL should be abstracted out into input-common, so the interface doesn't depend directly on a specific library, so that we can support other input libraries in the future if necessary (e.g. if we ever support Android way further down the line).

2020-07-11 14:34 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +        const u8 byte0 = controller_ids[i] % 256;         // possible motor direction?
```suggestion
        const u8 byte0 = static_cast<u8>(controller_ids[i] % 256);         // possible motor direction?
```

ditto for the other byte expressions, below this, otherwise this will cause type truncation warnings.

2020-07-12 07:07 UTC, legend800 commented
How do I set this up to test? Connect Nin. pro controller and configure buttons and try in game like SMO?

2020-07-12 22:14 UTC, german77 commented
> How do I set this up to test? Connect Nin. pro controller and configure buttons and try in game like SMO?

Yes, If the device supports haptics it should work without a problem. I have tested it with a xbox controller.

2020-07-16 14:03 UTC, ogniK5377 commented
Can confirm this works beautifully in SMO. It might be worse adding a feature to adjust the rumble strength though!

2020-07-16 20:05 UTC, legend800 commented
FWIW, Petergov also solved a similar perf issue recently on wiimote vibration in Cemu.

2020-07-16 20:41 UTC, german77 commented
> There have been reports of this PR killing FPS on Xbox One controllers when rumbling.
> I had the exact same issue when making an own implementation for rumble.
> Going to block this for the time being so we can look into whether this is a code or a driver/SDL issue.

Rumble is called up 16 times per frame. I will see if something can be done to fix it.

2020-07-17 07:36 UTC, legend800 commented
Test Results from latest build:

- It's not working in 3 games:  Streets of Rage 4, Ultra Street Fighter 2, Fast RMX (double checked settings)
- And as mentioned, the rumble is very strong, especially on an xone pad - like almost double expected. Someway to tone it down is needed. Until then, I gotta disable, it's just too annoying, despite being a huge fan of rumble since I got my first N64 rumble pak for Star Fox 64. :)

Tested Games with working rumble:
•	Bayonetta 2
•	Crash Team Racing
•	Donkey Kong Country TF
•	Mario Kart 8
•	Mario Tennis
•	Mother Russia
•	Smash Bros
•	Super Mario Maker 2
•	Super Mario Odyssey

2020-07-18 02:29 UTC, ogniK5377 commented on src/core/hle/service/hid/controllers/npad.cpp
> +            }
So I did some testing here for a few things, firstly the rumble should keep rumbling until a new rumble value is passed. That means an amplitude of 0 is considered value here. Passing `SDL_HAPTIC_INFINITY` as the time should be sufficient and dropping the amplitude > 0 check.

As for the scaling of the amplitude, a linear scale by multiplying by 6 tends to be a bit overkill in most games. I suggest replacing amplitude with something as follows
`const auto new_amplitude = pow(amplitude, 0.45f) * (3.0f - 2.0f * pow(amplitude, 0.225f));`

```suggestion
            const f32 amplitude = std::max(vibrations[0].amp_low, vibrations[0].amp_high);
            // Amplitudes are too small, The motors can't spin with that little force
            const auto new_amplitude =
                pow(amplitude, 0.45f) * (3.0f - 2.0f * pow(amplitude, 0.225f));

            using namespace Settings::NativeButton;
            const auto& button_state = buttons[controller_pos];
            button_state[A - BUTTON_HID_BEGIN]->SetRumblePlay(new_amplitude, SDL_HAPTIC_INFINITY);
```

2020-07-18 14:41 UTC, german77 commented
Rumble on Ultra Street Fighter 2 works you just need to enable in the control options.
Fast RMX is calling a stubbed function and is not sending any rumble signals, I'm trying to implement it but it may be in another PR.

Rumble strength should be better now.

I have tested rumble on different machines and controllers. I did not encounter any stutter. It looks like it's a driver issue.

2020-07-18 18:44 UTC, legend800 commented
Yeah, strength is better, still strong, but a future slider will address that. 

Can confirm USF2 has rumble - looks like it only does so on certain moves / last attack, which is why I missed it. Good luck with Fast RMX, SOR4 and other games that do funky things.

Does this add true HD rumble (for Switch controllers) or just generic rumble? I can't get my Pro controller to rumble at all to check, even with BetterJoy, but others don't have this issue. So some config thing on my side I guess.

Thanks for the follow-ups and great job on this!

2020-07-18 20:02 UTC, FearlessTobi commented on src/core/hle/service/hid/controllers/npad.cpp
> +        const u8 byte0 = static_cast<u8>(controller_ids[i] % 256); // possible motor direction?
Can't we use a Bitfield for extracting those values?
Also either way, those variables could have better naming in order to be able to omit those comments.

2020-07-18 23:42 UTC, german77 commented on src/core/hle/service/hid/controllers/npad.cpp
> +        const u8 byte0 = static_cast<u8>(controller_ids[i] % 256); // possible motor direction?
Could you check if what I did was right? I never used Bitfield before

2020-07-25 21:53 UTC, ExsertWizard commented
> I have tested rumble on different machines and controllers. I did not encounter any stutter. It looks like it's a driver issue.

No one has mentioned this so far but, I recently did some testing and the stutter only occurs on Xbox One Controllers connected over Bluetooth, it works perfectly when connected over USB.

It seems that some strange issue occurs only in SMO, performance is constantly capped to 10fps, even with the in-game rumble option off.
On the other hand, Super Smash Bros. Ultimate stutters only when rumble activity is present, with big dips in performance when the controller's heavy vibration motors are actuated, not so much with the light ones.

2020-07-25 22:44 UTC, german77 commented
Never tested with Bluetooth. SMO always rumble even when you feel nothing, SSBU only when It's necessary. I will take a look and see if I finally get that stutter and fix it. Worst case scenario rumble will be disabled with Bluetooth controllers.

2020-07-26 05:43 UTC, raven02 commented
@german77 I also got same lag issue in ACHN when jump using Xbox One Bluetooth controller . Looking forward to get it fixed or at least has option to enable/disable .

2020-07-26 16:17 UTC, bunnei commented
Untagging, since this seems to cause a major perf issue in SMO (maybe other games) with Xbox One controllers. @german77 can you take a look at this issue? Thank you!

2020-07-26 17:13 UTC, german77 commented
> Untagging, since this seems to cause a major perf issue in SMO (maybe other games) with Xbox One controllers. @german77 can you take a look at this issue? Thank you!

I'm tying to find a solution but no luck yet. It seems that this problems was present before 2017.  https://answers.microsoft.com/en-us/windows/forum/games_windows_10/xbox-one-s-controller-causing-major-performance/e69a5864-794f-4355-83d8-a018b7ade00f?page=7

2020-07-27 22:51 UTC, bunnei commented
Thanks for the quick turnaround @german77 ! Retagging for further testing :)

2020-07-28 15:40 UTC, raven02 commented
Retested latest commit on ACHN , SMO and MK8D , it works perfectly with Xbox One Bluetooth controller.

2020-07-30 15:02 UTC, ogniK5377 commented on src/input_common/sdl/sdl_impl.cpp
> +        printf("%d %d \n", raw_amp_low, raw_amp_high);
Unneeded printf

2020-08-03 01:35 UTC, legend800 commented
Looks like this breaks Mario Tennis loading. Crashes with rumble on, fine with it off in today's EA. Notice the last events logged were rumble actions.

Rumble On:
[yuzu_log(1).txt](https://github.com/yuzu-emu/yuzu/files/5013403/yuzu_log.1.txt)

Rumble Off:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5013404/yuzu_log.txt)
![2020-08-02 18_29_38-#patreon-general](https://user-images.githubusercontent.com/20983844/89137932-a132fe00-d4ee-11ea-8811-3808247950f5.png)

2020-08-05 01:51 UTC, bunnei commented
@german77 this needs a rebase when you get a chance. Thank you!

2020-08-05 01:53 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> -
Please do not remove this or change to LOG_TRACE

2020-08-05 07:12 UTC, Morph1984 commented
Also, squash your commits by running
`git rebase -i upstream/master`
Change all `pick` to `fixup` except the first commit

Then run: `git submodule update --recursive`

2020-08-05 17:24 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> +    LOG_TRACE(Service_HID, "called");
Leave the newline intact
```suggestion
    LOG_TRACE(Service_HID, "called");
    
```

2020-08-06 04:44 UTC, legend800 commented
Mario Tennis works great now! Overall rumble intensity feels about right now too. Great progress!

![2020-08-05 21_40_23-Window](https://user-images.githubusercontent.com/20983844/89491751-cf217800-d764-11ea-84b7-58bb1ad9d97a.png)

2020-08-06 15:41 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.h
> +    struct ControllerIds {
```suggestion
    struct ControllerID {
```

2020-08-06 18:07 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +void Controller_NPad::VibrateController(const std::vector<ControllerID>& controller_id,
the variable itself can remain as `controller_ids`, given it's a container holding several controller IDs.

2020-08-07 11:22 UTC, lioncash commented on src/input_common/sdl/sdl_impl.cpp
> +        std::chrono::time_point<std::chrono::system_clock> now;
```cpp
const auto now = std::chrono::system_clock::now();
```

Is a way more concise way of composing this line.

2020-08-07 11:22 UTC, lioncash commented on src/input_common/sdl/sdl_impl.cpp
> +            if (raw_amp_low + raw_amp_high == 0) {
```cpp
return raw_amp_low + raw_amp_high == 0;
```

Is more concise here.

2020-08-07 11:25 UTC, lioncash commented on src/input_common/sdl/sdl_impl.cpp
> +            if (!(raw_amp_low + raw_amp_high == 0 &&
Inverting the not allows this to be written without it needing to be present in the condition itself:

```suggestion
            if (raw_amp_low + raw_amp_high != 0 ||
                last_state_rumble_low + last_state_rumble_high == 0) {
```

2020-08-10 18:39 UTC, Shoegzer commented
@german77 Your PR works well!  The issues compiling as I had reported [here](https://github.com/yuzu-emu/yuzu/issues/4500) have been resolved and I was able to merge the PR and test, haven't encountered any issues performance or otherwise and rumble strength feels about right compared with the same games on my switch (though a slider would be good to have eventually).  Great work, and thank you for this nice feature.

Test system is linux mint 20, kernel 5.4, self-compiled with gcc 9.3.0.  Testing with Sony DS4 pad.

2020-08-15 19:48 UTC, v1993 commented
On topic of slowdown and stutter: make sure that you're using SDL2 at least 2.0.12. Its [changelog](https://www.libsdl.org/tmp/SDL/WhatsNew.txt) mentions:

```
* Fixed blocking game controller rumble calls when using the HIDAPI driver
```

Last SDL2 available in Ubuntu repos is 2.0.10, one potentially having this problem. Conan have updated version.

2020-09-11 14:00 UTC, v1993 commented
@legend800 This implements only basic rumble, but #4411 should allow proper HD Rumble functional on Switch controllers once done and merged, complete with fully accurate strength. HD Rumble is not that HD anyways, actually (there are only two acoustic actuators in entire Pro Controller).

2020-09-11 15:39 UTC, Shoegzer commented
@v1993 Thanks for pointing that out.  The rumble in this PR seemed sufficiently accurate to me in initial testing but perhaps I didn't test it enough to spot differences between HD vs. non-HD rumble.  Also, from what you say I assume the code in #4411 only provides HD rumble with native controllers and cannot approximate/simulate the feature with others such as the DS4?

2020-09-11 15:46 UTC, german77 commented
The current input engine do not allow HD rumble on other controllers even if they support it. This PR only uses amplitude and ignores the frequency of the rumble. For HD rumble to work on DS4 and other future controllers that support it. A new input engine will be needed.

2020-09-11 15:53 UTC, Shoegzer commented
Thanks @german77, and that's certainly fine.  Everything is iterative and evolutionary.  I appreciate your efforts either way.

2020-09-11 16:08 UTC, v1993 commented
@Shoegzer It is not possible to implement HD rumble using SDL2 and it is not even their fault. AFAIK it is not possible at all (at least) in Linux without directly accessing HID device like #4411 does (normal driver maps strength values to amplitude+frequency, for each side on procon). This means that one currently have to write low-lever driver in emulator to support rumble beyond left strength+right strength.

Proper solution would be to introduce a way to report rumble as two values per rumbler instead of one, but it would require additions both to SDL2 (somewhat trivial ones) and lower level stuff (less trivial ones). Long story short, it would need work far beyond bounds of yuzu.

P.S.: that PR looks abandoned, sadly, and I would expect it to have conflicts with existing driver at least on Linux.

2020-09-11 16:19 UTC, german77 commented
@v1993 #4411 is not abandoned at all. It has many changes that are not committed right now. It fully supports motion, button mapping, using two controllers as one and other things. I'm waiting for motion and this PR to get into mainline. Devs do not like when I start chaining PR to get a single one working.

2020-09-11 16:20 UTC, Shoegzer commented
@v1993 Thanks, that makes sense.  I would think SDL2 doesn't support such a feature because there hasn't been a need for it, at least until more recently with projects like this.  Perhaps someone on this team or others such as ryujinx who understands HID matters can contribute code upstream at some future point for more widespread benefit.

What makes you say the PR is abandoned?  It doesn't have recent activity but that's normal as I assuming development is being done in spare time when RL issues aren't in the way, and that's not predictable.  I'm sure it will come in time and with patience.  That said, I do certainly hope linux issues such as the one you raised are addressed and I'm sure they will.

2020-09-11 16:57 UTC, v1993 commented
@Shoegzer The thing is that SDL2 can't communicate to underlying driver to send HD Rumble command due to driver not exposing such interface.

2020-09-11 17:24 UTC, Shoegzer commented
@v1993 Thanks and yeah, I was thinking the development would have to progress on both low- and higher-level, was just focused on SDL2 when I wrote that.

2020-09-13 19:39 UTC, toccata10 commented
Thanks for this rumble feature. I'm working with Archlinux. 
I have rumble on my ds4v2 when connected on Usb, but not on bluetooth. I asked on Discord, and some guy said that "rumble over BT has never worked for me".

So I tested both usb and bluetooth with fftest: the rumble works fine. I also tried with rpcs3, with both "evdev" and the "Dualshock4" config: they all rumble with bluetooth. Same for cemu (with wine and xinput emulation).

On a side note, I also tried ds4drv-cemuhook. And: motion works with bluetooth (but no rumble) and doesn't with usb (but rumble).

2020-09-13 19:49 UTC, v1993 commented
@toccata10 This sounds interesting. From what I know, Wine uses SDL2 to implement joysticks and so does Yuzu. The difference might be that wine probably uses full Haptics API while Yuzu utilizes newer function that allows to send vibration easier.

2020-09-24 17:49 UTC, FearlessTobi requested changes

2020-09-30 11:24 UTC, merged

2020-09-30 16:31 UTC, Shoegzer commented
Getting no rumble with this PR as merged to mainline with [this](https://github.com/yuzu-emu/yuzu-mainline/commit/4d0ae1a17a031488eadfa9133dac157fb71900c0) commit.  To test, I connected a DS4 pad, selected "Pro Controller", reconfigured buttons and toggled the "Vibration" checkbox on and off but no rumble occurs.  I then entered games that feature rumble on the actual Switch but no rumble occurs there either.  Rumble worked with the unmerged PR as I had noted above.

@german77 any thoughts here?

Test system is linux mint 20, kernel 5.4 and a DS4 pad, compiled using gcc 9.3.0

2020-09-30 16:52 UTC, v1993 commented
@Shoegzer I doubt that it is a regression if rumble works in some games but not others. There were notes that some of methods games use to send vibrations aren't implemented by this PR.

2020-09-30 16:53 UTC, Morph1984 commented
@Shoegzer You literally scared me with that lol, but yes, there are some games where rumble does not work currently as @v1993 mentioned

2020-09-30 17:43 UTC, german77 commented
Please post any games where rumble is absent here #4738

2020-09-30 17:43 UTC, Shoegzer commented
Yeah, I was a bit concerned myself!  Sorry for the false alarm.

@v1993 I did notice that Pinball FX3's input options feature a toggle only for "HD Rumble", so it does make sense that the current rumble code doesn't expose any rumble in light of @german77's comment above:

> The current input engine do not allow HD rumble on other controllers even if they support it. This PR only uses amplitude and ignores the frequency of the rumble. For HD rumble to work on DS4 and other future controllers that support it. A new input engine will be needed.

PR https://github.com/yuzu-emu/yuzu/pull/4411 wouldn't help with use cases like this either, as that's for officail Joycon support rather than other pads such as the DS4 this test was done with.  It would be nice if support for approximating the HD rumble experience for non-official input devices could be added at some future point though.

2020-09-30 17:58 UTC, v1993 commented
@Shoegzer That's not really it. This PR reads HD Rumble as it's really the only sort of rumble Switch produces (but not all ways (HD) rumble can be triggered, which is your problem) and *converts it to simple rumble*. Your quote is about HD Rumble being played as simple rumble on supported controllers as opposed to HD Rumble as one might expect.

2020-09-30 20:54 UTC, Shoegzer commented
I appreciate the explanation @v1993. I wasn't familiar with how the Switch handles rumble so I assumed it had multiple modes but apparently not, it's just that the method of triggering HD rumble in Pinball FX3 is different from other titles that have been known to work with this PR.  Also it seems the DS4 _could_ actually handle HD rumble (with frequency as well as amplitude), so the feature could be replicated rather than approximated given a rewrite of the input enigne that might recognize it.