input_common: Add full motion to cemu hook
yuzu-emu/yuzu pull request #4609
Opened 2020-08-29 23:25 UTC by german77

This adds the necessary changes to have motion from cemu hook devices. Currently the only way to map it is by manually editing the config files. Needs PR #4594, #4570 to work properly

It has been tested with better joy, The values are in the correct order/scale/direction.

```
player_0_motionleft\default=false
player_0_motionleft="engine:cemuhookudp,address:127.0.0.1,port:26760,cx:0.0,pad_index:0,cy:0.0,cz:0.0,sensitivity:1.0"
```

2020-08-29 23:27 UTC, lioncash commented on src/input_common/udp/client.h
> +#include "input_common/motion_input.h"
This can likely be a forward declaration.

2020-08-29 23:28 UTC, lioncash commented on src/input_common/udp/client.cpp
> +    Common::Vec3f rawgyroscope = {data.gyro.pitch, data.gyro.roll, -data.gyro.yaw};
```suggestion
    Common::Vec3f raw_gyroscope = {data.gyro.pitch, data.gyro.roll, -data.gyro.yaw};
```

All variables here should be const if they're able to be.

2020-08-29 23:30 UTC, lioncash commented on src/input_common/udp/client.cpp
> +    motion = new InputCommon::MotionInput(0.3f, 0.005f, 0.0f);
Why does this need to be a pointer? This will currently cause a memory leak.

2020-08-30 02:57 UTC, FearlessTobi requested changes
Some big problems need to be worked out here before this is in a mergeable state.
(Also, it's pretty inconvenient for a reviewer when the code a PR depends on hasn't even been merged yet.)

2020-08-30 02:57 UTC, FearlessTobi commented on src/input_common/udp/client.cpp
> +    motion.SetGyroThreshold(0.0006f);
Where does this value come from? Has it been measured from hardware?

2020-08-30 02:57 UTC, FearlessTobi commented on src/input_common/udp/udp.cpp
> +class UDPMotionDevice final : public Input::RealMotionDevice {
Why was this changed? Dito for below

2020-08-30 02:57 UTC, FearlessTobi commented on src/yuzu/configuration/configure_input_player.cpp
> +    if (param.Get("engine", "") == "cemuhookudp") {
With https://github.com/yuzu-emu/yuzu/pull/4382 there's already an almost done UI for motion for yuzu.
I don't think this UI change is needed then.

2020-08-30 02:57 UTC, FearlessTobi commented on src/input_common/udp/client.h
> +    InputCommon::MotionInput motion{0.3f, 0.005f, 0.0f};
Why is this included in the protocol implementation?
Isn't CemuhookUdp the motion input itself?
Also again, those magic values should be explained somewhere.

2020-08-30 02:57 UTC, FearlessTobi commented on src/input_common/udp/client.cpp
> +    motion.SetGyroscope(raw_gyroscope / 312.0f);
Another magic value that should be explained.

2020-08-31 02:05 UTC, lioncash commented on src/input_common/main.cpp
> +        //auto udp_devices = udp->GetInputDevices();
We don't merge uncommented code like this.

2020-08-31 02:06 UTC, lioncash commented on src/input_common/udp/client.cpp
> +    for (std::size_t client = 0; client < clients.size(); client++) {
This can be a range for loop.

2020-08-31 02:06 UTC, lioncash commented on src/input_common/udp/client.h
> +    GyrX,
```suggestion
    GyroX,
```

etc. We don't need to mince words here.

2020-08-31 02:07 UTC, lioncash commented on src/input_common/udp/client.h
> +    /// Used for polling
Newline before this comment.

2020-08-31 02:07 UTC, lioncash commented on src/input_common/udp/client.h
> +    /// Close and relase the client
```suggestion
    /// Close and release the client
```

2020-08-31 02:07 UTC, lioncash commented on src/input_common/udp/client.h
> +    DeviceStatus& GetPadState(std::string ip, std::size_t port, std::size_t pad);
`ip` doesn't seem to be used at all. If it needs to be present, this should be a std::string_view.

2020-08-31 02:08 UTC, lioncash commented on src/input_common/udp/client.h
> +    struct Clients {
This should probably be named in terms of a singular object.

2020-08-31 02:08 UTC, lioncash commented on src/input_common/udp/client.h
> +    void UpdateYuzuSettings(std::size_t client, Common::Vec3<float> acc, Common::Vec3<float> gyro,
```suggestion
    void UpdateYuzuSettings(std::size_t client, const Common::Vec3<float>& acc, const Common::Vec3<float>& gyro,
```

2020-08-31 02:09 UTC, lioncash commented on src/input_common/udp/udp.cpp
> +        : ip(ip_), port(port_), pad(pad_), client(client_) {}
```suggestion
        : ip(std::move(ip_)), port(port_), pad(pad_), client(client_) {}
```

2020-09-04 04:35 UTC, german77 commented
This PR will be merged with #4594 to eliminate conflicts between both PR.

2020-09-04 04:35 UTC, closed without merging