Reduce the "shake" requirements when configuring UDP.
yuzu-emu/yuzu pull request #4727
Opened 2020-09-26 08:33 UTC by FrogTheFrog

Currently the Steam Controller can't be configured for motion as the "shake" requirements exceed the possible values for the said controller.

The maximum values that the SC produces are: `2.f` for accel and `~5.5f` for gyro. The old ranges will never be exceeded and the controller won't be usable :disappointed:. Therefore I propose to reduce the values a little (technically the `>=` and <=` changes are enough for accel, but it seems to be nicer this way).

2020-09-26 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4727) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=4727) it.</sub>

2020-09-29 05:10 UTC, FrogTheFrog commented on src/input_common/udp/client.cpp
> +    LOG_DEBUG(Input,
Done

2020-09-29 14:06 UTC, german77 approved these changes
All looks good. Just rebase your commits to one

2020-09-29 15:01 UTC, FrogTheFrog commented
@german77 Completely forgot how to properly use git after working with svn for 2 years. Tell me If I did something wrong and I will just create a new PR with a new fork 😄.

2020-09-30 05:09 UTC, Morph1984 approved these changes

2020-09-30 05:09 UTC, Morph1984 commented on src/input_common/udp/client.cpp
> +                  "UDP Controller (client: {}): gyro [{}, {}, {}], acc [{}, {}, {}], touch [{}].",
LGTM otherwise
```suggestion
                  "UDP Controller {}: gyro=({}, {}, {}), accel=({}, {}, {}), touch={}",
```

2020-09-30 11:24 UTC, ogniK5377 requested changes
Just a few nits

2020-09-30 11:25 UTC, ogniK5377 requested changes

2020-09-30 11:25 UTC, ogniK5377 commented on src/input_common/udp/client.cpp
> +    }
```suggestion
```

Is this intended or just left over from debugging

2020-09-30 12:18 UTC, FrogTheFrog commented on src/input_common/udp/client.cpp
> +    }
Intended.

I thought about removing it, but since this output is logged only when trying to assign motion device I decided that It would do more good than harm. It would have been very useful at least for me, since I would not have needed to compile the source code myself.

2020-10-06 22:29 UTC, bunnei approved these changes

2020-10-06 22:29 UTC, merged

2021-07-25 07:25 UTC, octoshrimpy commented
Any news on this?

2021-07-25 19:26 UTC, v1993 commented
Why would there be any updates on this? This change was merged a while ago and no issues have been raised since then.

2021-07-25 20:57 UTC, octoshrimpy commented
Apologies, that's what I get for trying to solve issues at 3am, lol. 

If anyone is following my breadcrumbs because it isn't working for them, I'll be working in the issue that mentioned this PR.