video_core: NVDEC Implementation
yuzu-emu/yuzu pull request #4729
Opened 2020-09-29 14:00 UTC by ameerj

## FFmpeg NVDEC Implementation
This PR aims to implement the NVDEC (Nvidia Decoder) functionality, with video frame decoding being handled by the FFmpeg library. 

Supersedes #1703.  Closes #2643 .

The process begins with Ioctl commands being sent to the NVDEC and VIC (Video Image Composer) emulated devices. These allocate the necessary GPU buffers for the frame data, along with providing information on the incoming video data.  A `Submit` command then signals the GPU to process and decode the frame data. 

The decoding process then determines the Codec of the encrypted video stream. Officially, Nintendo allows support for H264, H265, VP8, and VP9 video codecs. The current implementation supports the H264 and VP9 encoded streams, as in our testing, we did not encounter any titles utilizing any other codecs.

Once the video codec is determined, a corresponding frame header is manually constructed from the information provided by the GPU. The headers and frame data are then packaged and sent to FFmpeg for decoding. FFmpeg provides a tried and true abstraction for video decoding, along with the possibility to utilize HW accelerated decoding, which may be utilized to improve performance.

### H264
The H264 standard is ubiquitous and relatively well documented and understood. There are two header types, the SPS (Sequence Parameter Set) and PPS (Picture Parameter Set). These headers are constant for the entire video stream, and carry information such as the frame dimensions, along with frame transformation attributes and flags. 

Much of the H264 decoding remains from  @ogniK5377 's earlier attempt at an NVDEC implementation, which has been shown to work very well with the games tested.

### VP9
This was the more interesting and far more challenging video stream to decode. Much like H.264, VP9 frames carry with them two headers in order to be decoded. The compressed header contains probabilities used for prediction of the frame transformation modes, and the uncompressed header holds higher level data regarding the frame, most notably the reference frames. The construction of these headers is based on the details found in the [official specification](https://storage.googleapis.com/downloads.webmproject.org/docs/vp9/vp9-bitstream-specification-v0.6-20160331-draft.pdf)

Reference frames are previously decoded frames used to construct new frames. The four types of frames are the Altref (alternative reference), Golden, Last/previous frame, and Key frames. Key frames are *intra-only,* meaning they do not require prior reference frames in order to be accurately decoded, and in fact reset the reference frame context when encountered.

Golden and Altref frames are the challenging pair. Due to the limited information we're provided by NVDEC, some clever tricks needed to be made. This includes buffering two frames in advance, in order to determine if the current and next frames are hidden in order to instruct the decoder to construct a Golden reference. Some streams also update the reference frames during the stream with the only signal I have been made aware of being an update to the location of the reference frame offset in the GPU memory. However, this is not always accurate, and leads to noticeable visual glitches when this check is incorrect. 

VP9 decoding is still under analysis and investigation in order to improve decoding accuracy.

### Limitations and Known Issues
Currently, Asynchronous GPU emulation for NVDEC is not properly implemented. The decoding is completed synchronously for the time being.

Beside the occasional VP9 visual artifacting, the list of known issues is as follows:
* `The Legend of Zelda: Link's Awakening` and `Onimusha Warlords` do not provide the expected format for their video framebuffer memory address, as such, they do not render decoded videos.
* `The Legend of Heroes: Trails of Cold Steel III` and `Ni no Kuni Wrath: of the White Witch` contain pixel formats not yet supported.
* `Alien Isolation` has shown to be a very bad offender of VP9 videos.
* Multiple videos at once does not always render correctly.
* `Link's Awakening` and the `Pokemon Let's Go` games face a crash when using the Vulkan renderer. Users are asked to disable NVDEC for these games while a solution is worked out.

#### Special Mentions

* @ogniK5377  for the previous attempts at implementing NVDEC into yuzu, and guiding me along the way.
* @gdkchan  for their work implementing NVDEC in Ryujinx.
* @lat9nq  for assisting in Linux compilation errors and the addition of per-game configurations for the NVDEC toggle.

2020-09-29 15:13 UTC, bylaws reviewed
You sure these error codes are right? Normally nvdrv converts error codes before reporting to userspace and I don't see that being done here.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.cpp
> +            LOG_CRITICAL(Service_NVDRV, "avcodec_open2() Failed.");
error

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.cpp
> +        LOG_CRITICAL(Service_NVDRV, "Unknown video codec {}", static_cast<u32>(current_codec));
```suggestion
        LOG_ERROR(Service_NVDRV, "Unknown video codec {}", static_cast<u32>(current_codec));
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.h
> +#pragma once
Newline after this.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.h
> +    Codec(GPU& gpu);
```suggestion
    explicit Codec(GPU& gpu);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.h
> +    AVFrame* GetCurrentFrame() const;
Please preserve the constness of the pointer for the const variant of it. It's better to provide two overloads in this case.

```suggestion
    AVFrame* GetCurrentFrame();
    const AVFrame* GetCurrentFrame() const;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +H264::~H264() {}
```suggestion
H264::~H264() = default;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    s32 frame_number = (int)(context.h264_parameter_set.flags >> 46) & 0x1ffff;
```suggestion
    s32 frame_number = static_cast<s32>((context.h264_parameter_set.flags >> 46) & 0x1ffff);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        s32 chroma_format_idc = (context.h264_parameter_set.flags >> 12) & 0x3;
```suggestion
        const s32 chroma_format_idc = (context.h264_parameter_set.flags >> 12) & 0x3;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int order_cnt_type = (int)(context.h264_parameter_set.flags >> 14) & 0x3;
```suggestion
        const s32 order_cnt_type = static_cast<s32>((context.h264_parameter_set.flags >> 14) & 3);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        writer.WriteUe((int)(context.h264_parameter_set.flags >> 8) & 0xf);
```suggestion
        writer.WriteUe(static_cast<s32>((context.h264_parameter_set.flags >> 8) & 0xf));
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int pic_height = context.h264_parameter_set.pic_height_in_map_units /
```suggestion
        const int pic_height = context.h264_parameter_set.pic_height_in_map_units /
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        writer.WriteU((int)(context.h264_parameter_set.flags >> 32) & 0x3, 2);
static_cast

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int pic_init_qp = (int)(context.h264_parameter_set.flags >> 16) & 0x3f;
static_cast

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int chroma_qp_index_offset = (int)(context.h264_parameter_set.flags >> 22) & 0x1f;
static_cast

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        s32 chroma_qp_index_offset2 = (int)(context.h264_parameter_set.flags >> 27) & 0x1f;
static_cast

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        auto encoded_header = writer.GetByteArray();
```suggestion
        const auto& encoded_header = writer.GetByteArray();
```

Otherwise this copies the whole std::vector

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        last_scale = value;
This will cause a sign conversion warning since a u8 is being assigned to an int without an explicit cast.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        u8 value = list[start + scan[index]];
```suggestion
        const u8 value = list[start + scan[index]];
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    std::vector<u8>& scan = count == 16 ? zig_zag_scan : zig_zag_direct;
```suggestion
    const std::vector<u8>& scan = count == 16 ? zig_zag_scan : zig_zag_direct;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int free = GetFreeBufferBits();
```suggestion
        const int free = GetFreeBufferBits();
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +        int mask = (1 << copy_size) - 1;
This and the below values can be const.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    int sign = value <= 0 ? 0 : 1;
```suggestion
    const int sign = value <= 0 ? 0 : 1;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    int size = 32 - NvdecCommon::CountLeadingZeros((s32)value + 1);
```suggestion
    const int size = 32 - NvdecCommon::CountLeadingZeros((s32)value + 1);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    if (buffer_pos != 0) {
```suggestion
    if (buffer_pos == 0) {
        return;
    }
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.h
> +#pragma once
Newline after this

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.h
> +    std::vector<u8> zig_zag_direct{
These two luts can be static constexpr std::arrays to avoid needing to heap allocate.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.h
> +    std::vector<u8>& GetByteArray();
There should be a const variant of this.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +#include "vp9.h"
Newline after this

Also we use `<name.h>` for external libraries.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    bool update = new_prob != old_prob;
```suggestion
    const bool update = new_prob != old_prob;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    for (int offset = 0; offset < new_prob.size(); offset++) {
```suggestion
    for (std::size_t offset = 0; offset < new_prob.size(); offset++) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int delta = RemapProbability(new_prob, old_prob);
```suggestion
    const int delta = RemapProbability(new_prob, old_prob);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        const int size = 8;
```suggestion
        constexpr int size = 8;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int mask = (1 << size) - 191;
```suggestion
        const int mask = (1 << size) - 191;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int delta = value - mask;
```suggestion
        const int delta = value - mask;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    bool is_lt = value < test;
```suggestion
    const bool is_lt = value < test;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    auto needs_update = [&](int base_index) -> bool {
```suggestion
    const auto needs_update = [&](int base_index) -> bool {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int base_index = block_index * block_bytes;
```suggestion
        const int base_index = block_index * block_bytes;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        bool update = needs_update(base_index);
```suggestion
        const bool update = needs_update(base_index);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    for (int offset = 0; offset < new_prob.size(); offset += 4) {
```suggestion
    for (std::size_t offset = 0; offset < new_prob.size(); offset += 4) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    bool update = new_prob != old_prob;
```suggestion
    const bool update = new_prob != old_prob;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int sb64_cols = (frame_width + 63) / 64;
const (also look for all other occurrences, I've already typed this message a lot of times).

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +                                     std::vector<u8>& new_prob, std::vector<u8>& old_prob) {
```suggestion
                                     const std::vector<u8>& new_prob, const std::vector<u8>& old_prob) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +void VP9::WriteProbabilityUpdate(VpxRangeEncoder& writer, std::vector<u8>& new_prob,
Both vectors here can be const references

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +            for (int index = 0; index < info.ref_deltas.size(); index++) {
```suggestion
            for (std::size_t index = 0; index < info.ref_deltas.size(); index++) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +            for (int index = 0; index < info.mode_deltas.size(); index++) {
```suggestion
            for (std::size_t index = 0; index < info.mode_deltas.size(); index++) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +                for (int index = 0; index < info.ref_deltas.size(); index++) {
```suggestion
                for (std::size_t index = 0; index < info.ref_deltas.size(); index++) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +                for (int index = 0; index < info.mode_deltas.size(); index++) {
```suggestion
                for (std::size_t index = 0; index < info.mode_deltas.size(); index++) {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +Stream::Stream() {}
```suggestion
Stream::Stream() = default;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int srcShift = (bit_count - valuePos) - copySize;
```suggestion
        const int src_shift = (bit_count - valuePos) - copySize;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.h
> +#pragma once
Newline after this line.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.h
> +    std::vector<u8>& GetBuffer() {
There should be a const variant of this accessor.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.h
> +    bool WasFrameHidden() {
```suggestion
    bool WasFrameHidden() const {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +    std::vector<u8> y_mode_prob{65,  32,  18,  144, 162, 194, 41,  51, 98,  132, 68,  18, 165,
If aany of thise vectors are only read from, they should be static constexpr arrays.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +    Vp9PictureInfo Convert() {
```suggestion
    Vp9PictureInfo Convert() const {
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +    u32 BitDepth = (surface_params >> 1) & 0xf;
```suggestion
    u32 bit_depth = (surface_params >> 1) & 0xf;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +    /*
Commented out code without a reason for existing should be removed.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/host1x.cpp
> +#include "host1x.h"
This should have a relative path, like the other includes.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/host1x.cpp
> +    u32* state_offset = reinterpret_cast<u32*>(&state) + offset;
This needs to be a u8* to be well-defined behavior.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/host1x.h
> +#pragma once
Newline after this

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/host1x.h
> +        u32 IncrSyncpt;
These should all be following our `snake_case` format to follow our naming conventions.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.cpp
> +    codec = std::make_unique<Codec>(gpu);
This can be in the constructor initializer list.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.cpp
> +#include "nvdec.h"
This should have a relative include, like the other includes around it.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.h
> +#pragma once
Newline after this.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.h
> +extern "C" {
This inclusion doesn't seem to be necessary in this header.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.h
> +    Nvdec(GPU& gpu);
```suggestion
    explicit Nvdec(GPU& gpu);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec.h
> +    AVFrame* GetFrame() const;
There should be two overloads for this:

```cpp
AVFrame* GetFrame();
const AVFrame* GetFrame() const;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec_common.cpp
> +std::array<u8, 16> clz_nibble_table{4, 3, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0};
```suggestion
constexpr std::array<u8, 16> clz_nibble_table{4, 3, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0};
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec_common.cpp
> +s32 CountLeadingZeros(s32 value) {
We already have functions like these in `common/bit_util.h` (CountLeadingZeroes32/CountTrailingZeroes32)

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/nvdec_common.h
> +#pragma once
Newline after this

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/sync_manager.cpp
> +    for (int i = 0; i < increments.size(); i++) {
This can be collapsed into a find_if call.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/sync_manager.cpp
> +    int doneCount = 0;
```suggestion
    int done_count = 0;
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/sync_manager.h
> +#pragma once
Newline after this

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/sync_manager.h
> +        id = id;
All of these assignments should be moved into the constructor initializer list.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/sync_manager.h
> +    SyncptIncrManager(GPU& gpu);
```suggestion
    explicit SyncptIncrManager(GPU& gpu);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +    u32* state_offset = reinterpret_cast<u32*>(&vic_state) + offset;
This needs to be a `u8*` to be well-defined.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        uint8_t* rgb_frame_buffer = (uint8_t*)av_malloc(linear_size);
```suggestion
        u8* rgb_frame_buffer = static_cast<u8*>(av_malloc(linear_size));
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        uint8_t* rgb_frame_buf_addr[1] = {rgb_frame_buffer};
```suggestion
        std::array<u8*, 1> rgb_frame_buf_addr{rgb_frame_buffer};
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        int rgb_stride[1] = {frame->width * 4};
```suggestion
        std::array<int, 1> rgb_stride{frame->width * 4};
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.h
> +#pragma once
Newline after this

2020-09-29 17:35 UTC, lioncash commented on src/video_core/command_classes/vic.h
> +extern "C" {
Is this include actually necessary in this header?

2020-09-29 17:35 UTC, lioncash commented on src/video_core/gpu_asynch.cpp
> +    if (use_nvdec) {
```suggestion
    if (!use_nvdec) {
        return;
    }
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/gpu_synch.cpp
> +    if (use_nvdec) {
```suggestion
    if (!use_nvdec) {
        return;
    }
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/memory_manager.cpp
> +        // TODO: investigate.
This and the assert below should be resolved. This is extremely vague.

2020-09-29 17:35 UTC, lioncash commented on src/video_core/memory_manager.cpp
> +    if (it != pinned_map.end()) {
```suggestion
    if (it == pinned_map.end()) {
        return;
    }
    
    pinned_map.erase(it);
```

2020-09-29 17:35 UTC, lioncash commented on src/video_core/memory_manager.h
> +    GPUVAddr GpuAddressFromPinned(u32 pinned_address);
This should have `[[nodiscard]]` on it.

2020-09-29 17:37 UTC, lioncash commented
A lot of the new classes added also seem to lack Doxygen documentation comments explaining what their purpose is and any of their expectations (if relevant).

2020-09-29 17:45 UTC, lioncash commented
The main commit's message also contains an overwhelming lack of explanation for anything. I'd suggest formatting your PR message to go into that commit as its commit message.

2020-09-29 19:04 UTC, legend800 commented
Tested(works fine):
- Hotshot Racing
- Smash
- SMO
- MK8
- Ultra SF2

Still not working correctly:
- Streets of Rage 4 (h264 videos):
    - opening vid still doesn't show but it no longer hangs here with async if nvdec is turned on. Now we don't need any workaround mods (which only worked with 1.0) and we can use async for full speed
    - Episode intro videos run at 5fps. In Ryu, they're full speed (could be a non-nvdec issue here).
- DKCTP:  Game freezes after a few secs of playing vid. No stability issues with nvdec off.

2020-09-29 20:32 UTC, ReinUsesLisp requested changes
Marked some memory bugs found with `-fsanitize=address` running Link's Awakening.

2020-09-29 20:32 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
Unnecessary newline here.

2020-09-29 20:32 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +        if (command.group == 0) {
We generally encode these into their own `IoctlCommand` enum to avoid having magic numbers.

2020-09-29 20:32 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +            return MapBufferEx(input, output);
This call reads out of bounds from `input`, likely because it's using the wrong structure type.

2020-09-29 20:32 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +    std::memcpy(output.data(), &params, output.size());
This is reading out of bounds from `params`.
```
==3749==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f2dec880afc at pc 0x7f2f1ae7b2a6 bp 0x7f2dec8808d0 sp 0x7f2dec880078
READ of size 28 at 0x7f2dec880afc thread T42 (yuzu:CPUThread)
    #0 0x7f2f1ae7b2a5 in __interceptor_memcpy /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806
    #1 0x564ffc48c0e1 in Service::Nvidia::Devices::nvhost_nvdec::MapBuffer(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&) ../../src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:240
    #2 0x564ffc48e325 in Service::Nvidia::Devices::nvhost_nvdec::ioctl(Service::Nvidia::Devices::nvdevice::Ioctl, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<unsigned char, std::allocator<unsigned char> >&, Service::Nvidia::IoctlCtrl&, Service::Nvidia::IoctlVersion) ../../src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp:66
```

2020-09-29 21:17 UTC, bylaws commented
Also I'll note that in hardware the gpu, nvdec and vic address spaces are not shared, doing this would allow you to emulate the different address space sizes in a cleaner way too.

2020-09-29 22:31 UTC, lat9nq requested changes
Tried building on Fedora today and ran into a couple of issues. These should help build on there, too.

2020-09-29 22:31 UTC, lat9nq commented on src/video_core/command_classes/codecs/codec.h
> +}
```suggestion
extern "C" {
#ifndef _WIN32
#pragma GCC diagnostic ignored "-Wconversion"
#endif
#include <libavcodec/avcodec.h>
#ifndef _WIN32
#pragma GCC diagnostic pop
#endif
}
```

Prevents the compiler from throwing `-Werror=conversion` errors while reading FFmpeg headers.

2020-09-29 22:31 UTC, lat9nq commented on src/video_core/CMakeLists.txt
> +    target_link_libraries(video_core PRIVATE ${FFMPEG_LIBAVCODEC} ${FFMPEG_LIBAVUTIL} ${FFMPEG_LIBSWSCALE})
```suggestion
    target_include_directories(video_core PRIVATE ${FFMPEG_INCLUDE_DIR})
    target_link_libraries(video_core PRIVATE ${FFMPEG_LIBRARIES})
```
Uses the variables defined in FindFFmpeg.cmake, as well as properly telling the compiler where the headers are.

2020-09-30 09:23 UTC, v1993 commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +        if (command.group == 0) {
In addition, can't those three ifs (`command.cmd == 9`/`0xa`/`1`) be merged into single `switch` statement?

2020-09-30 09:34 UTC, v1993 commented on src/video_core/command_classes/codecs/codec.h
> +}
Shouldn't we test for GCC usage instead of target platform? GCC can be used on windows as well.

2020-09-30 20:44 UTC, lat9nq commented on src/video_core/command_classes/codecs/codec.h
> +}
Do you happen to know the variable that would test for GCC? Throw me a bone, here

2020-09-30 21:14 UTC, v1993 commented on src/video_core/command_classes/codecs/codec.h
> +}
`__GNUC__` macro should do the job here

2020-09-30 21:16 UTC, v1993 commented on src/video_core/command_classes/codecs/codec.h
> +}
I'd suggest testing for GCC or Clang with

```C++
#if defined(__GNUC__) || defined(__clang__)
```

Both of them support `#pragma GCC`

2020-09-30 22:29 UTC, gdkchan commented
Some portions of the code were taken from Ryujinx implementation. We changed our license to MIT last year, so in compliance with the license, I would like to ask for proper attribution for the code that was taken from Ryujinx. If you would like me to point out the files were I think the attribution would be appropriate, please let me know, thanks.

2020-09-30 22:32 UTC, lat9nq commented on src/video_core/command_classes/codecs/codec.h
> +}
Thanks, it's updated

2020-09-30 22:52 UTC, v1993 commented on src/video_core/command_classes/codecs/codec.h
> +}
There's sneaky extra space in first `#if`

2020-10-01 06:11 UTC, ameerj commented
@gdkchan Source files which contained Ryujinx code now contain the Ryujinx license and copyright headers in compliance with the MIT license.

2020-10-01 13:37 UTC, v1993 commented
I'm having issues building with latest update of this PR:

```c++
src/video_core/CMakeFiles/video_core.dir/cdma_pusher.cpp.o -c ../src/video_core/cdma_pusher.cpp
../src/video_core/cdma_pusher.cpp:178:13: error: no previous declaration for ‘std::string Tegra::HexDump(std::vector<unsigned char>&)’ [-Werror=missing-declarations]
  178 | std::string HexDump(std::vector<u8>& data) {
      |             ^~~~~~~
```

2020-10-01 14:09 UTC, CrazyMax commented on CMakeLists.txt
> +    set(FFMPEG_LIBRARY_DIR "${FFMPEG_PATH}/bin" CACHE PATH "Path to Unicorn library" FORCE)
```suggestion
    set(FFMPEG_LIBRARY_DIR "${FFMPEG_PATH}/bin" CACHE PATH "Path to FFmpeg library" FORCE)
```

2020-10-01 17:19 UTC, ameerj commented on src/video_core/command_classes/codecs/codec.h
> +}
@lat9nq this is addressed in the latest commit. Please let me know if there are still build issues in Fedora.

2020-10-03 09:24 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_vic.h
> +    struct IoctlSubmitStub {
```suggestion
    struct IoctlSubmit {
```

It's better to document what needs to be done to implement this, rather than naming it as a stub. This way when the proper implementation is done, no renaming needs to take place.

2020-10-03 09:24 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_vic.h
> +    u32 SubmitStub(const std::vector<u8>& input, std::vector<u8>& output);
Ditto for this and MapBufferStub.

2020-10-03 09:24 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_vic.h
> +#include <map>
`<array>` still needs to be included, as it's used within IoctlSubmitStub

2020-10-03 09:24 UTC, lioncash commented on src/video_core/cdma_pusher.cpp
> +
Unnecessary newline

2020-10-03 09:24 UTC, lioncash commented on src/video_core/cdma_pusher.cpp
> +std::string CDmaPusher::HexDump(std::vector<u8>& data) {
```suggestion
std::string CDmaPusher::HexDump(const std::vector<u8>& data) {
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/cdma_pusher.cpp
> +            data.resize(0);
This line isn't necessary. Clearing the vector already sets its size to zero.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/cdma_pusher.h
> +std::string HexDump(const std::vector<u8>& data);
This and DumpArgs' prototypes don't seem to be implemented and can be removed.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/cdma_pusher.h
> +    std::string HexDump(std::vector<u8>& data);
These prototypes can likely be removed and the implementation of these functions in the cpp file can likely be internally linked.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/codec.cpp
> +        avcodec_send_packet(av_codec_ctx, NULL);
```suggestion
        avcodec_send_packet(av_codec_ctx, nullptr);
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +#include "h264.h"
This should have a relative include like the other headers.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +/// Compose the H264 header of the frame for FFmpeg decoding
This should go on the functions prototype in the header, not in the cpp file.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    const s32 size = 32 - Common::CountLeadingZeroes32((s32)value + 1);
```suggestion
    const s32 size = 32 - Common::CountLeadingZeroes32(static_cast<s32>(value + 1));
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    value -= (1u << (size - 1)) - 1;
```suggestion
    value -= (1U << (size - 1)) - 1;
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/h264.cpp
> +    WriteBits((s32)value, size - 1);
static_cast

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9.cpp
> +    const s32 block_bytes = 2 * 2 * 6 * 6 * 4;
```suggestion
    constexpr s32 block_bytes = 2 * 2 * 6 * 6 * 4;
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +#pragma once
Missing newline after this

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +static constexpr Vp9EntropyProbs default_probs{
This should not be made static within the header. This means that every file that references this structure will get its own copy of the data, which can bloat the executable unnecessarily.

Prefer defining the data within a cpp file, and making the variable `extern const` in the header.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/codecs/vp9_types.h
> +enum class Ref { LAST, GOLDEN, ALTREF };
```suggestion
enum class Ref { Last, Golden, AltRef, };
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +#include "nvdec.h"
this and the vic include should have relative paths like the other includes.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        u8* rgb_frame_buffer = static_cast<u8*>(av_malloc(linear_size));
```suggestion
        using AVMallocPtr = std::unique_ptr<u8, decltype(&av_free)>;
        AVMallocPtr rgb_frame_buffer{static_cast<u8*>(av_malloc(linear_size)), av_free};
```

This way the code won't leak if any other exit paths are added in the future.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        const auto luma_ptr = frame->data[0];
```suggestion
        const auto* luma_ptr = frame->data[0];
```

Ditto for the others if they happen to be pointers as well.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        const auto frame = nvdec_processor->GetFrame();
```suggestion
        const auto* frame = nvdec_processor->GetFrame();
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/command_classes/vic.cpp
> +        const auto frame = nvdec_processor->GetFrame();
```suggestion
        const auto* frame = nvdec_processor->GetFrame();
```

2020-10-03 09:24 UTC, lioncash commented on src/video_core/gpu.h
> +    const Tegra::CDmaPusher& CDmaPusher() const;
This and the DmaPusher one should be placed underneath their respective non-const accessors above so they're easier to locate.

2020-10-03 09:24 UTC, lioncash commented on src/video_core/gpu_asynch.cpp
> +    // gpu_thread.SubmitCommandBuffer(std::move(entries));
If this is required to be here, it should be documented why it's commented out, otherwise it should be removed.

2020-10-09 11:50 UTC, v1993 commented
This now causes build to fail when merged into master. I strongly suspect that it's caused by commit 61b246a3a952e704549f3d3a191fcb7442420fb1. I think it's a good idea to rebase off master and fix those errors (they are caused by unused variables and should be trivially fixable).

2020-10-10 00:06 UTC, v1993 commented on src/video_core/command_classes/codecs/vp9_types.h
>  static_assert(sizeof(Segmentation) == 0x64, "Segmentation is an invalid size");
Here and for following asserts: "x have invalid size".

2020-10-14 12:08 UTC, v1993 commented
This currently fails to build (with recently enabled warnings):

```
../src/core/hle/service/nvdrv/devices/nvhost_vic.cpp: In member function ‘u32 Service::Nvidia::Devices::nvhost_vic::Submit(const std::vector<unsigned char>&, std::vector<unsigned char>&)’:
../src/core/hle/service/nvdrv/devices/nvhost_vic.cpp:130:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<Service::Nvidia::Devices::nvhost_vic::SyncptIncr>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  130 |     for (int i = 0; i < syncpt_increments.size(); i++) {
      |                     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```
Use `size_t` for loops where applicable.

2020-10-14 12:22 UTC, v1993 requested changes
Few remarks based on new warning from master

2020-10-14 12:22 UTC, v1993 commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
> +    for (int i = 0; i < syncpt_increments.size(); i++) {
`int` -> `size_t`

2020-10-14 12:22 UTC, v1993 commented on src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
> +    for (int i = 0; i < syncpt_increments.size(); i++) {
`int` -> `size_t`

2020-10-14 12:22 UTC, v1993 commented on src/video_core/command_classes/codecs/h264.cpp
> +    for (int index = 0; index < count; index++) {
`int` -> `size_t`... oh, wait

This function clearly threats its arguments as `size_t` values (e.g. `scan` creation), but they are signed. Is this intended? Same goes for few other methods in this class.

2020-10-14 12:22 UTC, v1993 commented on src/video_core/command_classes/codecs/vp9_types.h
> +        for (int i = 0; i < 4; i++) {
`int` -> `size_t` (for both loops)

2020-10-14 16:48 UTC, ameerj commented on src/video_core/command_classes/codecs/h264.cpp
> +    for (int index = 0; index < count; index++) {
Not necessary here

2020-10-14 16:49 UTC, ameerj commented on src/video_core/command_classes/codecs/vp9_types.h
> +        for (int i = 0; i < 4; i++) {
not necessary here

2020-10-14 16:49 UTC, ameerj commented on src/video_core/command_classes/codecs/vp9_types.h
>  static_assert(sizeof(Segmentation) == 0x64, "Segmentation is an invalid size");
Can you be more specific?

2020-10-18 10:03 UTC, ReinUsesLisp requested changes
Thanks for your work.

About the hack to fix Link's Awakening, I prefer to have that in a separate pull request to discuss is on a clean state and avoid merging it into master now. I left a note about something that might fix it, although I'm doubtful.

There's also a note for a linear search on a `std::map` that might cause performance issues on long running sessions. You can read the details in the note.

2020-10-18 10:48 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +            gpu.IncrementSyncPoint(fences[i].id);
The TRM provides a pretty good reference on how syncpoints work, but effectively they are all part of the Host1X block so shared between GPU and any Host1X clients like nvdec. When userspace submits to the FIFO it can put syncpoint increments at different points in the host1x command stream then wait on these async via nvhost-event. This is useful as a single command stream submitted in may perform many individual tasks,  userspace can wait on these individually rather than waiting for the whole thing.

I will not that I'm not all to sure about the correctness of the code here, generally syncpoints aren't incremented by the CPU.

2020-10-18 22:29 UTC, ameerj commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +            LOG_DEBUG(Service_NVDRV, "invalid offset=0x{:X} dma=0x{:X}", object->addr,
I accidentally deleted the comment during the `common` refactor. Indeed this occurs _very_ frequently, but does not seem to impact functionality.

2020-10-18 22:36 UTC, bylaws reviewed
Just a few comments, also it would probably be an idea to unify the {nvdec, VIC, GPU} device files into a single class, like Nvidia does for Linux, there is a lot of boilerplate otherwise

2020-10-18 22:36 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +        buffer_mappings.begin(), buffer_mappings.upper_bound(gpu_addr), [&](const auto& entry) {
Is there a specific reason for finding the upper bound and then iterating up to that? Surely `std::prev(buffer_mappings.upper_bound(gpu_addr))` would work and avoids the need for a loop.
I may be wrong on this though, ignore me if I am

2020-10-18 22:36 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
> +    case IoctlCommand::IocUnmapBuffer:
You should probably change this to match by the CMD id, UnmapBufferN are all the same aside from the permission mask

2020-10-18 22:36 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +    LOG_INFO(Service_NVDRV, "called GetWaitbase, unknown=0x{:X}", params.unknown);
This is purely used for output, downstream Linux calls it 'value', not really much point printing it

2020-10-18 22:36 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +            // We are mapping in the lower 32-bit address space
Maybe mention that in HW all channels have their own AS, with nvdec and VIC's being 32 bit - this is just a workaround in a way.

2020-10-18 22:36 UTC, bylaws commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +        buffer_mappings.begin(), buffer_mappings.upper_bound(gpu_addr), [&](const auto& entry) {
Same as I mentioned up top for nvdec

2020-10-19 00:04 UTC, ameerj commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +    const auto it = std::find_if(
In my analysis, the map never exceeds 20-30 elements at any given moment, ever, with less elements mapped by the vic than by the nvdec device. 
This is due to the fact that buffers are mapped, used, then unmapped. There is never any residual elements left unmapped unless there is an error with the emulated gpu.

2020-10-21 00:49 UTC, ogniK5377 requested changes

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/cdma_pusher.cpp
> +    u8* const state_offset = reinterpret_cast<u8*>(&state) + sizeof(u32) * offset;
```suggestion
    u8* state_offset = reinterpret_cast<u8*>(&state) + sizeof(u32) * offset;
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/cdma_pusher.h
> +};
```suggestion
struct ThiRegisters {
    u32_le increment_syncpt{};
    INSERT_PADDING_WORDS(1);
    u32_le increment_syncpt_error{};
    u32_le ctx_switch_incremement_syncpt{};
    INSERT_PADDING_WORDS(4);
    u32_le ctx_switch{};
    INSERT_PADDING_WORDS(1);
    u32_le ctx_syncpt_eof{};
    INSERT_PADDING_WORDS(5);
    u32_le method_0{};
    u32_le method_1{};
    INSERT_PADDING_WORDS(12);
    u32_le int_status{};
    u32_le int_mask{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/cdma_pusher.h
> +    SetMethod1 = offsetof(ThiRegisters, method_1) / 4,
```suggestion
    IncSyncpt = offsetof(ThiRegisters, increment_syncpt) / sizeof(u32),
    SetMethod0 = offsetof(ThiRegisters, method_0) / sizeof(u32),
    SetMethod1 = offsetof(ThiRegisters, method_1) / sizeof(u32),
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/cdma_pusher.h
> +    int mask{};
```suggestion
    s32 count{};
    s32 offset{};
    s32 mask{};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/codec.cpp
> +    LOG_DEBUG(Service_NVDRV, "Flushed avcontext");
Is this intended?

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/codec.cpp
> +    u8* const state_offset = reinterpret_cast<u8*>(&state) + offset * sizeof(u64);
```suggestion
    u8* state_offset = reinterpret_cast<u8*>(&state) + offset * sizeof(u64);
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/codec.cpp
> +        // Free allocated memory in preparation for new codec.
I noticed that 
```
    avcodec_send_packet(av_codec_ctx, nullptr);
    avcodec_receive_frame(av_codec_ctx, av_frame);
    avcodec_flush_buffers(av_codec_ctx);
```

isn't called here but is called in the deconstructor, is that intentional? Does it need to be called when codecs are being switched?

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/codec.cpp
> +        }
```suggestion
        const auto av_error = avcodec_open2(av_codec_ctx, av_codec, nullptr);
        if (av_error  < 0) {
            LOG_ERROR(Service_NVDRV, "avcodec_open2() failed. error={}", av_error);
        }
```
Should the codec still be considered initialized if this fails?

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/codec.h
> +    AVFrame* av_frame = nullptr;
```suggestion
    AVCodec* av_codec{nullptr};
    AVCodecContext* av_codec_ctx{nullptr};
    AVFrame* av_frame{nullptr};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/h264.cpp
> +    s32 frame_number = static_cast<s32>((context.h264_parameter_set.flags >> 46) & 0x1ffff);
```suggestion
    const s32 frame_number = static_cast<s32>((context.h264_parameter_set.flags >> 46) & 0x1ffff);
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/h264.cpp
> +        s32 delta_scale = static_cast<s32>(value - last_scale);
```suggestion
        const s32 delta_scale = static_cast<s32>(value - last_scale);
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int index;
```suggestion
    std::size_t index{};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +        temp.bit_stream = frame.bit_stream;
```suggestion
         Vp9FrameContainer temp{
            .info = frame.info,
            .bit_stream = frame.bit_stream
        };
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +            temp.bit_stream = frame.bit_stream;
```suggestion
        Vp9FrameContainer temp{
            .info = frame.info,
            .bit_stream = frame.bit_stream
        };
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +} // namespace Util
Should be moved to common

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int shift = norm_lut[local_range];
```suggestion
    s32 shift = norm_lut[local_range];
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int offset = shift - count;
```suggestion
        const s32 offset = shift - count;
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +    for (int index = 0; index < 32; index++) {
```suggestion
    for (std::size_t index = 0; index < 32; index++) {
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +    u8 value = static_cast<u8>(base_stream.ReadByte());
```suggestion
    const u8 value = static_cast<u8>(base_stream.ReadByte());
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int remaining = bit_count;
```suggestion
    s32 value_pos = 0;
    s32 remaining = bit_count;
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +        int copy_size = remaining;
```suggestion
        s32 copy_size = remaining;
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +        const int free = GetFreeBufferBits();
```suggestion
        const s32 free = GetFreeBufferBits();
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.cpp
> +        const int dst_shift = (buffer_size - buffer_pos) - copy_size;
```suggestion
        const s32 mask = (1 << copy_size) - 1;

        const s32 src_shift = (bit_count - value_pos) - copy_size;
        const s32 dst_shift = (buffer_size - buffer_pos) - copy_size;
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9.h
> +    std::vector<u8>& GetByteArray();
Add a const member variant for this as well

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +};
```suggestion
struct Vp9FrameDimensions {
    s16 width{};
    s16 height{};
    s16 luma_pitch{};
    s16 chroma_pitch{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +};
```suggestion
struct Segmentation {
    u8 enabled{};
    u8 update_map{};
    u8 temporal_update{};
    u8 abs_delta{};
    std::array<u32, 8> feature_mask{};
    std::array<std::array<s16, 4>, 8> feature_data{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +    std::array<s8, 2> mode_deltas;
```suggestion
    u8 mode_ref_delta_enabled{};
    std::array<s8, 4> ref_deltas{};
    std::array<s8, 2> mode_deltas{};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +};
```suggestion
struct Vp9PictureInfo {
    bool is_key_frame{};
    bool intra_only{};
    bool last_frame_was_key{};
    bool frame_size_changed{};
    bool error_resilient_mode{};
    bool last_frame_shown{};
    bool show_frame{};
    std::array<s8, 4> ref_frame_sign_bias{};
    s32 base_q_index{};
    s32 y_dc_delta_q{};
    s32 uv_dc_delta_q{};
    s32 uv_ac_delta_q{};
    bool lossless{};
    s32 transform_mode{};
    bool allow_high_precision_mv{};
    s32 interp_filter{};
    s32 reference_mode{};
    s8 comp_fixed_ref{};
    std::array<s8, 2> comp_var_ref{};
    s32 log2_tile_cols{};
    s32 log2_tile_rows{};
    bool segment_enabled{};
    bool segment_map_update{};
    bool segment_map_temporal_update{};
    s32 segment_abs_delta{};
    std::array<u32, 8> segment_feature_enable{};
    std::array<std::array<s16, 4>, 8> segment_feature_data{};
    bool mode_ref_delta_enabled{};
    bool use_prev_in_find_mv_refs{};
    std::array<s8, 4> ref_deltas{};
    std::array<s8, 2> mode_deltas{};
    Vp9EntropyProbs entropy{};
    Vp9FrameDimensions frame_size{};
    u8 first_level{};
    u8 sharpness_level{};
    u32 bitstream_size{};
    std::array<u64, 4> frame_offsets{};
    std::array<bool, 4> refresh_frame{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +    INSERT_PADDING_WORDS(3);
```suggestion
    INSERT_PADDING_WORDS(12);
    u32 bitstream_size{};
    INSERT_PADDING_WORDS(5);
    Vp9FrameDimensions last_frame_size{};
    Vp9FrameDimensions golden_frame_size{};
    Vp9FrameDimensions alt_frame_size{};
    Vp9FrameDimensions current_frame_size{};
    u32 vp9_flags{};
    std::array<s8, 4> ref_frame_sign_bias{};
    u8 first_level{};
    u8 sharpness_level{};
    u8 base_q_index{};
    u8 y_dc_delta_q{};
    u8 uv_ac_delta_q{};
    u8 uv_dc_delta_q{};
    u8 lossless{};
    u8 tx_mode{};
    u8 allow_high_precision_mv{};
    u8 interp_filter{};
    u8 reference_mode{};
    s8 comp_fixed_ref{};
    std::array<s8, 2> comp_var_ref{};
    u8 log2_tile_cols{};
    u8 log2_tile_rows{};
    Segmentation segmentation{};
    LoopFilter loop_filter{};
    INSERT_PADDING_BYTES(5);
    u32 surface_params{};
    INSERT_PADDING_WORDS(3);
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +};
```suggestion
struct RefPoolElement {
    s64 frame{};
    Ref ref{};
    bool refresh{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/codecs/vp9_types.h
> +};
```suggestion
struct FrameContexts {
    s64 from{};
    bool adapted{};
    Vp9EntropyProbs probs{};
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/host1x.h
> +    };
```suggestion
    struct Host1xClassRegisters {
        u32 incr_syncpt{};
        u32 incr_syncpt_ctrl{};
        u32 incr_syncpt_error{};
        INSERT_PADDING_WORDS(5);
        u32 wait_syncpt{};
        u32 wait_syncpt_base{};
        u32 wait_syncpt_incr{};
        u32 load_syncpt_base{};
        u32 incr_syncpt_base{};
        u32 clear{};
        u32 wait{};
        u32 wait_with_interrupt{};
        u32 delay_use{};
        u32 tick_count_high{};
        u32 tick_count_low{};
        u32 tick_ctrl{};
        INSERT_PADDING_WORDS(23);
        u32 ind_ctrl{};
        u32 ind_off2{};
        u32 ind_off{};
        std::array<u32, 31> ind_data{};
        INSERT_PADDING_WORDS(1);
        u32 load_syncpoint_payload32{};
        u32 stall_ctrl{};
        u32 wait_syncpt32{};
        u32 wait_syncpt_base32{};
        u32 load_syncpt_base32{};
        u32 incr_syncpt_base32{};
        u32 stall_count_high{};
        u32 stall_count_low{};
        u32 xref_ctrl{};
        u32 channel_xref_high{};
        u32 channel_xref_low{};
    };
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/nvdec_common.h
> +};
```suggestion
struct NvdecRegisters {
    INSERT_PADDING_WORDS(256);
    u64 set_codec_id{};
    INSERT_PADDING_WORDS(254);
    u64 set_platform_id{};
    u64 picture_info_offset{};
    u64 frame_bitstream_offset{};
    u64 frame_number{};
    u64 h264_slice_data_offsets{};
    u64 h264_mv_dump_offset{};
    INSERT_PADDING_WORDS(6);
    u64 frame_stats_offset{};
    u64 h264_last_surface_luma_offset{};
    u64 h264_last_surface_chroma_offset{};
    std::array<u64, 17> surface_luma_offset{};
    std::array<u64, 17> surface_chroma_offset{};
    INSERT_PADDING_WORDS(132);
    u64 vp9_entropy_probs_offset{};
    u64 vp9_backward_updates_offset{};
    u64 vp9_last_frame_segmap_offset{};
    u64 vp9_curr_frame_segmap_offset{};
    INSERT_PADDING_WORDS(2);
    u64 vp9_last_frame_mvs_offset{};
    u64 vp9_curr_frame_mvs_offset{};
    INSERT_PADDING_WORDS(2);
};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/vic.cpp
> +    u8* const state_offset = reinterpret_cast<u8*>(&vic_state) + offset * sizeof(u32);
```suggestion
    u8* state_offset = reinterpret_cast<u8*>(&vic_state) + offset * sizeof(u32);
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/vic.cpp
> +        LOG_DEBUG(Service_NVDRV, "Writing RGB Frame");
```suggestion
```
Is this just debugging? Is it intentional?

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/vic.cpp
> +        u8* const converted_frame_buf_addr{converted_frame_buffer.get()};
```suggestion
        const u8* converted_frame_buf_addr{converted_frame_buffer.get()};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/vic.h
> +    u32 chroma_v_offset;
```suggestion
    u32 luma_offset{};
    u32 chroma_u_offset{};
    u32 chroma_v_offset{};
```

2020-10-21 00:49 UTC, ogniK5377 commented on src/video_core/command_classes/vic.h
> +    INSERT_PADDING_WORDS(16);
```suggestion
    INSERT_PADDING_WORDS(64);
    u32 nop{};
    INSERT_PADDING_WORDS(15);
    u32 pm_trigger{};
    INSERT_PADDING_WORDS(47);
    u32 set_application_id{};
    u32 set_watchdog_timer{};
    INSERT_PADDING_WORDS(17);
    u32 context_save_area{};
    u32 context_switch{};
    INSERT_PADDING_WORDS(43);
    u32 execute{};
    INSERT_PADDING_WORDS(63);
    std::array<std::array<PlaneOffsets, 8>, 8> surfacex_slots{};
    u32 picture_index{};
    u32 control_params{};
    u32 config_struct_offset{};
    u32 filter_struct_offset{};
    u32 palette_offset{};
    u32 hist_offset{};
    u32 context_id{};
    u32 fce_ucode_size{};
    PlaneOffsets output_surface{};
    u32 fce_ucode_offset{};
    INSERT_PADDING_WORDS(4);
    std::array<u32, 8> slot_context_id{};
    INSERT_PADDING_WORDS(16);
```

2020-10-22 23:02 UTC, ameerj commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +        ASSERT(object);
Just a reminder to also look into `nvhost_ctrl` implementation this is based off of and update it accordingly.

2020-10-22 23:25 UTC, ameerj commented on src/video_core/command_classes/codecs/codec.cpp
> +        // Free allocated memory in preparation for new codec.
Good catch, now that I think about it, it shouldn't be possible to have a codec swap since we destroy the codec entirely when a video stream ends. I'll investigate on this further.

Side note: we can probably distinguish multiple streams this way as well, having distinct codec instances per stream for proper rending.

2020-10-22 23:36 UTC, ameerj commented on src/video_core/command_classes/codecs/vp9.cpp
> +    int index;
This is set to the return value of `RecenterNonNeg()`, which is an `s32`

2020-10-22 23:49 UTC, ameerj commented on src/video_core/command_classes/vic.cpp
> +        u8* const converted_frame_buf_addr{converted_frame_buffer.get()};
ptr addr is constant, but the underlying data is not constant, so the way it currently is is correct.

2020-10-23 04:00 UTC, ameerj commented on src/video_core/command_classes/vic.cpp
> +        LOG_DEBUG(Service_NVDRV, "Writing RGB Frame");
I left this just in case there's a buggy title in the future, as `RGB` formatted frames tended to be less straightforward compared to `YUV`.

2020-10-23 05:03 UTC, ameerj commented on src/video_core/command_classes/codecs/codec.cpp
> +        // Free allocated memory in preparation for new codec.
Confirmed that codec swaps are unneeded since I destroy the object when a video stream ends. So unless there's a title which has an h.264->vp9 video midstream, we should be fine :P

2020-10-23 09:38 UTC, v1993 commented
I'm currently having issues building this PR:

```
../src/common/stream.cpp: In member function ‘void Util::Stream::Seek(s32, s32)’:
../src/common/stream.cpp:12:19: error: ‘SEEK_SET’ was not declared in this scope
   12 |     if (origin == SEEK_SET) {
      |                   ^~~~~~~~
../src/common/stream.cpp:18:26: error: ‘SEEK_CUR’ was not declared in this scope
   18 |     } else if (origin == SEEK_CUR) {
      |                          ^~~~~~~~
../src/common/stream.cpp:20:26: error: ‘SEEK_END’ was not declared in this scope
   20 |     } else if (origin == SEEK_END) {
      |                          ^~~~~~~~
```

Looks like you forgot an include?

2020-10-23 16:58 UTC, ameerj commented
@v1993 should be fixed now, sorry about that.

2020-10-23 17:09 UTC, v1993 commented
Yes, fixed now, thanks.

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.cpp
> +        position++;
Dead code and potential bug. This should probably be `buffer[position++]`.

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.cpp
> +namespace Util {
```suggestion
namespace Common {
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.cpp
> +        return 0xff;
Is this intended? This should either assert or throw an exception. Preferably the later.

If this is indeed intended, it should be handled by the caller, not the generic "Stream" class.

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.cpp
> +
```cpp
#include "common/common_types.h"

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.h
> +namespace Util {
Missing new line.

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/common/stream.h
> +    Stream();
```suggestion
    explicit Stream();
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +            // This occurs quite frequently, however does not seem to effect functionality
```suggestion
            // This occurs quite frequently, however does not seem to affect functionality
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
> +
```suggestion
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
> +    virtual u32 ioctl(Ioctl command, const std::vector<u8>& input, const std::vector<u8>& input2,
Missing new line.
```suggestion

    virtual u32 ioctl(Ioctl command, const std::vector<u8>& input, const std::vector<u8>& input2,
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/command_classes/nvdec_common.h
> +namespace NvdecCommon {
```suggestion
namespace Tegra::NvdecCommon {
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/command_classes/sync_manager.cpp
> +
```suggestion
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/memory_manager.h
> +                                                        bool start_low = false) const;
If this is intended to be mapped on a 32 bit address, maybe `start_32bit_address` or something like that?

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/memory_manager.h
> +    static constexpr u64 address_space_start_low = 1UL << 16;
Ditto.
```suggestion
    static constexpr u64 address_space_start_low = 1ULL << 16;
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/memory_manager.cpp
> +template s64 MemoryManager::Read<s64>(GPUVAddr addr) const;
For consistency, all the other signed integer types should be added, or the caller of this function should use `Read<u64>` and cast it locally.

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/memory_manager.cpp
> +    }
```suggestion
    GPUVAddr gpu_addr{start_low ? address_space_start_low : address_space_start};
```

2020-10-27 01:30 UTC, ReinUsesLisp commented on src/video_core/memory_manager.h
> +    u32 Read32(VAddr addr);
This shouldn't be added. Use a `Core::Memory` reference instead of the GPU memory manager.

2020-10-27 01:52 UTC, ameerj commented on src/video_core/memory_manager.cpp
> +template s64 MemoryManager::Read<s64>(GPUVAddr addr) const;
Sorry old remnant, removed!

2020-10-27 05:39 UTC, ReinUsesLisp approved these changes

2020-10-27 05:42 UTC, ogniK5377 approved these changes

2020-10-27 06:02 UTC, bunnei approved these changes

2020-10-27 06:02 UTC, merged

2020-10-27 06:02 UTC, bunnei commented
Nice work!!