HID: Fixes rumble only in one controller
yuzu-emu/yuzu pull request #4762
Opened 2020-10-05 14:35 UTC by german77

Fixed regression by one of the last stages of #4291.
Handles multiple vibrations in one command fixing vibration on 1-2 switch.
If a controller is mapped as a left joycon it will switch the button to DDown.

2020-10-05 14:40 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +            std::size_t controller = (controllers[i] >> 8) & 0x7;
```suggestion
            const std::size_t controller = (controllers[i] >> 8) & 0x7;
```

2020-10-05 14:40 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +            std::size_t controller = i >> 1;
```suggestion
            const std::size_t controller = i / 2;
```

2020-10-05 14:40 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.cpp
> +    auto use_button = A;
```cpp
const auto use_button = controller_type == NPadControllerType::JoyLeft ? DDown : A;
```

A switch with only one case in it isn't very useful.

2020-10-05 14:40 UTC, lioncash commented on src/core/hle/service/hid/controllers/npad.h
> +    // Called from VibrateController and Vibrates a specific controller
Where it's called from isn't particularly important. This part of the comment can also become outdated in the future if code gets moved around.

2020-10-05 16:33 UTC, v1993 requested changes

2020-10-05 16:33 UTC, v1993 commented on src/core/hle/service/hid/controllers/npad.h
> +    bool VibratePhysicalController(std::size_t controllers, Vibration vibrations);
`controllers` -> `controller`

2020-10-08 18:51 UTC, closed without merging

2020-10-08 19:13 UTC, v1993 commented
What's the reason behind closing this?

2020-10-08 19:31 UTC, german77 commented
It will be superseded by a proper fix. Since this will not be merged or added to EA there is no point on keeping it open