Add Flatpak build
yuzu-emu/yuzu pull request #4773
Opened 2020-10-09 05:19 UTC by gal20

Based of #3770, I created a pipeline with an updated flatpak manifest that successfully builds the application. The Builds are found [here](https://dev.azure.com/gal20/gal20.yuzu/_build/results?buildId=66&view=results).
Note:
- I commented out all the encryption related commands because the necessary files don't exist in this environment. you'll have to uncomment the lines in exec.sh, docker.sh and finish.sh after the necessary files are created in your environment.
- I disabled the Cache Build System because it complained about missing directory (see the error [here](https://dev.azure.com/gal20/gal20.yuzu/_build/results?buildId=63&view=results)). You'll need to remove the condition line [here](https://github.com/gal20/yuzu/blob/d081f6d53cbce098789827eb2ca1d3dd94d145dc/.ci/templates/build-flatpak-single.yml#L11) to re-enable it.

2020-10-09 05:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4773) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=4773) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=4773) it.</sub>

2020-10-20 10:10 UTC, v1993 requested changes

2020-10-20 10:10 UTC, v1993 commented on .ci/scripts/linux-flatpak/finish.sh
> +rm -rf "$REPO_DIR" "/tmp/*" || true
Change this to

```bash
rm -r "$REPO_DIR" /tmp/* || true
```

It's no use to hide errors from log and quoting `/tmp/*` makes it fail. Try this out locally to see:

```bash
mkdir test
touch test/{1..3}
rm -r "test/*"
```

Result is `rm: cannot remove 'test/*': No such file or directory`.

2020-10-20 10:11 UTC, v1993 requested changes
A slight issue there

2021-02-28 07:34 UTC, soredake commented
https://github.com/flathub/org.citra_emu.citra

2021-06-15 10:17 UTC, soredake commented
https://flathub.org/apps/details/org.yuzu_emu.yuzu

2021-06-26 12:58 UTC, closed without merging