Add hotplug, rumble and fix 3rd party adapters for the GC adapter
yuzu-emu/yuzu pull request #4781
Opened 2020-10-12 23:17 UTC by german77

This PR has the changes from #4755, #4739.
Adds hotplug for GC adapters. No need to restart or connect the adapter before opening yuzu anymore. It's tolerant to communication errors and restarts the adapter automatically if the connection is lost.
Adds a rather basic output form of vibration for GC controllers
Allows offbrand GC adapters to work

2020-10-16 06:12 UTC, bunnei commented
@german77 needs a rebase when you get a chance

2020-10-16 19:07 UTC, lat9nq commented
On Linux, it fails to detect that the adapter was disconnected. Reconnecting it did not work afterward.

A lot of this in the log after disconnect:
`[ 136.286376] Input <Error> input_common/gcadapter/gc_adapter.cpp:Vibrate:458: Adapter libusb write failed: LIBUSB_ERROR_TIMEOUT`

But nothing that seems directly related to this PR that I could tell.

2020-10-16 19:31 UTC, ameerj requested changes
Not working on first party adapters.

2020-10-16 19:31 UTC, ameerj commented on src/input_common/gcadapter/gc_adapter.cpp
> +    while (adapter_scan_thread_running && !adapter_thread_running) {
This logic is wrong. This loop will exit after one iteration seeing as how `Setup()` will eventually set `adapter_thread_running = true;` once the adapter is detected. It will not redetect a disconnected adapter.

2020-10-16 19:31 UTC, ameerj commented on src/input_common/gcadapter/gc_adapter.cpp
> +                break;
We want to clear any intermediary libusb contexts if the adapter is disconnected.

2020-10-16 19:31 UTC, ameerj commented on src/input_common/gcadapter/gc_adapter.cpp
> +    if (adapter_scan_thread_running) {
I suggest breaking this function into two. `JoinThreads()` and `ClearLibusbContext()`. Both will be called by the destructor, but you will always clear libusb contexts when the adapter is disconnected to prepare for it reconnecting.

2020-10-18 04:03 UTC, Cavermendes commented
Is this going to fix Rumble in multiple controllers issue? Issue #4760

2020-10-18 04:11 UTC, german77 commented
No. A proper fix should be uploaded soon. I will ping your issue when it's up.

2020-10-18 22:28 UTC, Cavermendes commented
Ok, thx.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +bool Adapter::IsPayloadCorrect(std::array<u8, 37> adapter_payload, int payload_size) {
```suggestion
bool Adapter::IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, int payload_size) {
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +void Adapter::UpdateControllers(std::array<u8, 37> adapter_payload) {
```suggestion
void Adapter::UpdateControllers(const std::array<u8, 37>& adapter_payload) {
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    if (pads[port].type != pad_type) {
```suggestion
    if (pads[port].type == pad_type) {
        return;
    }
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +void Adapter::UpdateStateAxes(std::size_t port, std::array<u8, 37> adapter_payload) {
```suggestion
void Adapter::UpdateStateAxes(std::size_t port, const std::array<u8, 37>& adapter_payload) {
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    for (PadAxes axis : axes) {
```suggestion
    for (const PadAxes axis : axes) {
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +            for (size_t i = 0; i < pads.size(); ++i) {
This can be a ranged for loop.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    const u8 vibration_states = 8;
```suggestion
    constexpr u8 vibration_states = 8;
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    for (size_t i = 0; i < pads.size(); ++i) {
This can be a ranged for loop

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    const u8 raw_amp = static_cast<u8>(amplitude * 0x8);
```suggestion
    const auto raw_amp = static_cast<u8>(amplitude * 0x8);
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> +    const u8 THRESHOLD = 50;
This can be a constexpr value in the cpp file. This should likely also have a more informative name, since the comment no longer exists for it.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> -    void GetGCEndpoint(libusb_device* device);
Documentation comment should also explain what the return value represents.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> +    /// Resets all devices
Resets them in what sense. This should be elaborated more.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> +    /// Used for polling
This doesn't really provide any useful information. If this comment needs to exist, it should probably better explain what the function is doing and/or why it's doing what it does.

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> +struct GCControler {
```suggestion
struct GCController {
```

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.h
> +    Undefined = 0x0000,
The other enum members should also follow the casing here (e.g. ButtonLeft, TriggerZ, etc)

2020-10-18 22:40 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +        auto type = static_cast<ControllerTypes>(adapter_payload[offset] >> 4);
```suggestion
        const auto type = static_cast<ControllerTypes>(adapter_payload[offset] >> 4);
```

2020-10-18 23:47 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +    for (GCController pad : pads) {
```suggestion
    for (GCController& pad : pads) {
```

Otherwise this is a bug.

2020-10-18 23:47 UTC, lioncash commented on src/input_common/gcadapter/gc_adapter.cpp
> +            for (GCController pad : pads) {
```suggestion
            for (GCController& pad : pads) {
```

Otherwise this is a bug.

2020-10-19 01:53 UTC, ameerj requested changes

2020-10-19 01:53 UTC, ameerj commented on src/input_common/gcadapter/gc_poller.cpp
>      if (analog_x_axis != -1 && analog_y_axis != -1) {
When manually setting the analog stick, this if statement always fires, causing the axes and controller number to be set to `-1` (and causing a crash on launch due to an invalid port number)

2020-10-19 01:53 UTC, ameerj commented on src/input_common/gcadapter/gc_poller.cpp
> +            return axis_value < threshold;
This was set to negative on purpose. The bool `trigger_if_greater` was not the best name (borrowed from sdl impl) but the functionality is that if the direction is positive, you want to trigger the button after the positive threshold value. If the axis direction is negative, then you want to trigger if it's less than the negative threshold. Otherwise at rest, 0, it will trigger as being less than the trigger threshold.

2020-10-19 01:53 UTC, ameerj commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pads[port].set_axis_origin = false;
This should be moved into the `if` statement above. No need for it to fire more than once if the origin value is already stored.

2020-10-19 02:15 UTC, german77 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pads[port].set_axis_origin = false;
Set axis origin. Is a flag that sets all axis of the controller. If the flag is turned off inside the if statement it will only set the origin of the first axis

2020-10-19 02:34 UTC, ameerj commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pads[port].set_axis_origin = false;
Just an idea, but it may be worthwhile to instead initialize `axis_origin` values to 255, then check 
`if (pads[port].axis_origin[index] != 255)` and eliminate the need for `set_axis_origin`

2020-10-19 04:25 UTC, german77 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pads[port].set_axis_origin = false;
That worked well

2020-10-28 08:01 UTC, Morph1984 commented on src/input_common/gcadapter/gc_adapter.cpp
> +#include "core/settings.h"
remove this

2020-10-28 08:05 UTC, Morph1984 commented on src/input_common/gcadapter/gc_adapter.cpp
> +#include "core/settings.h"
and the Settings::values.vibration_enabled used below.

2020-10-28 13:24 UTC, ogniK5377 requested changes

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +                                  sizeof(adapter_payload), &payload_size, 16);
```suggestion
                                  adapter_payload.size(), &payload_size, 16);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +bool Adapter::IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, int payload_size) {
It might be worth adding a type definition above for adapter_payload

`using AdapterPayload = std::array<u8, 37>;`

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    if (payload_size != sizeof(adapter_payload) || adapter_payload[0] != LIBUSB_DT_HID) {
```suggestion
    if (payload_size != adapter_payload.size() || adapter_payload[0] != LIBUSB_DT_HID) {
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +bool Adapter::IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, int payload_size) {
```suggestion
bool Adapter::IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, s32 payload_size) {
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pads[port].buttons = 0;
Is port guaranteed to be < pads.size here?

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    pad_status.port = port;
```suggestion
    GCPadStatus pad_status = {
       .port = port
    };
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    for (size_t i = 0; i < pads[port].axis_values.size(); ++i) {
```suggestion
    for (std::size_t i = 0; i < pads[port].axis_values.size(); ++i) {
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    constexpr u8 vibration_states = 8;
What does 8 come from?

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    std::array<u8, 5> payload = {0x11, p1, p2, p3, p4};
What's 0x11 here? Can it be a named constexpr?

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +                                              sizeof(payload), &size, 16);
```suggestion
                                              payload.size(), &size, 16);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    int size = 0;
```suggestion
    s32 size{};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    const int control_transfer_error =
```suggestion
    const s32 control_transfer_error =
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +        libusb_control_transfer(usb_adapter_handle, 0x21, 11, 0x0001, 0, nullptr, 0, 1000);
Can these numbers be named constexprs?

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    for (size_t i = 0; i < pads.size(); ++i) {
```suggestion
    for (std::size_t i = 0; i < pads.size(); ++i) {
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
>          button_params.Set("axis", static_cast<int>(gcadapter_axis));
```suggestion
        button_params.Set("button", static_cast<s32>(PadButton::Stick));
        button_params.Set("axis", static_cast<s32>(gcadapter_axis));
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    return pads[port];
```suggestion
    return pads.at(port);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.cpp
> +    return pads[port];
```suggestion
    return pads.at(port);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    std::size_t port{0};
```suggestion
    std::size_t port{};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    s16 axis_value{0};
```suggestion
    s16 axis_value{};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    u8 axis_threshold = 50;
```suggestion
    u8 axis_threshold{50};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    std::array<u8, 6> axis_origin;
```suggestion
    ControllerTypes type{};
    bool enable_vibration{};
    u8 rumble_amplitude{};
    u16 buttons{};
    PadButton last_button{};
    std::array<s16, 6> axis_values{};
    std::array<u8, 6> axis_origin{};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    bool IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, int payload_size);
```suggestion
    bool IsPayloadCorrect(const std::array<u8, 37>& adapter_payload, s32 payload_size);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    int vibration_counter = 0;
```suggestion
    u8 input_endpoint{0};
    u8 output_endpoint{0};
    u8 input_error_counter{0};
    u8 output_error_counter{0};
    int vibration_counter{0};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    bool rumble_enabled = true;
```suggestion
    bool rumble_enabled{true};
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_adapter.h
> +    bool rumble_enabled = true;
Do this for the other members as well

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +    explicit GCButton(u32 port_, int button_, GCAdapter::Adapter* adapter)
```suggestion
    explicit GCButton(u32 port_, s32 button_, GCAdapter::Adapter* adapter)
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +            return gcadapter->GetPadState(port).buttons & button;
```suggestion
            return gcadapter->GetPadState(port).buttons & button != 0;
```
Makes it a bit more expressive on the intent

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +        const float amplitude = amp_high + amp_low > 2 ? 1.0f : (amp_high + amp_low) * 0.5f;
```suggestion
        const float amplitude = amp_high + amp_low > 2.0f ? 1.0f : (amp_high + amp_low) * 0.5f;
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +    constexpr int PAD_STICK_ID = static_cast<u16>(GCAdapter::PadButton::Stick);
```suggestion
    constexpr s32 PAD_STICK_ID = static_cast<s32>(GCAdapter::PadButton::Stick);
```

Any reason you're casting to u16 but storing it into an s32? Are you intending to clamp the value? If so, you should use std::clamp to avoid overflows and underflows

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +        params.Set("port", static_cast<int>(pad.port));
```suggestion
        params.Set("port", static_cast<s32>(pad.port));
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +            params.Set("port", static_cast<int>(pad.port));
```suggestion
            params.Set("port", static_cast<s32>(pad.port));
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +            controller_number = static_cast<int>(pad.port);
```suggestion
            controller_number = static_cast<s32>(pad.port);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +            controller_number = static_cast<int>(pad.port);
```suggestion
            controller_number = static_cast<s32>(pad.port);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +            controller_number = static_cast<int>(pad.port);
```suggestion
            controller_number = static_cast<s32>(pad.port);
```

2020-10-28 13:24 UTC, ogniK5377 commented on src/input_common/gcadapter/gc_poller.cpp
> +                   controller_number == static_cast<int>(pad.port)) {
```suggestion
                   controller_number == static_cast<s32>(pad.port)) {
```

2020-10-28 16:52 UTC, german77 commented on src/input_common/gcadapter/gc_adapter.cpp
> +        libusb_control_transfer(usb_adapter_handle, 0x21, 11, 0x0001, 0, nullptr, 0, 1000);
No, those are magic numbers taken from dolphin because of that the meaning of those numbers isn't clear.

2020-10-29 16:50 UTC, Morph1984 approved these changes

2020-10-29 17:27 UTC, bunnei approved these changes

2020-10-29 17:28 UTC, bunnei commented
Looks good, thank you! Please consider submitting a follow-up PR with a toggle for the GC adapter, unless you have found another way to avoid the hangs here.

2020-10-29 17:28 UTC, merged