Execute program
yuzu-emu/yuzu pull request #4799
Opened 2020-10-17 05:19 UTC by bunnei

This change refactors loader code to support booting an indexed program within the application container. For now, this supports booting a program NCA (by index) within an NSP or XCI file.

With this refactoring, we can implement IApplicationFunctions::ExecuteProgram within the AM service, which is used to boot another process. This is used by Super Mario 3D All-Stars to launch sub-titles (Super Mario 64, Super Mario Sunshine, etc.).

Since yuzu does not support multiple processes, we accomplish this by simply stopping the current process and launching the new process at the specified program index.

This allows Super Mario 3D All-Stars to mostly function (with the exception that the Mario games do not render, but that is unrelated to this change). Once we fix rendering, this should work.

2020-10-17 10:56 UTC, lioncash requested changes

2020-10-17 10:56 UTC, lioncash commented on src/yuzu_cmd/emu_window/emu_window_sdl2.h
> +    void ExecuteProgram(std::size_t /*program_index*/) override{};
```suggestion
    void ExecuteProgram(std::size_t /*program_index*/) override {}
```

2020-10-17 10:56 UTC, lioncash commented on src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
> +    void ExecuteProgram(std::size_t /*program_index*/) override{};
```suggestion
    void ExecuteProgram(std::size_t /*program_index*/) override {}
```

2020-10-17 10:56 UTC, lioncash commented on src/core/hle/service/am/am.cpp
> +    system.GPU().Renderer().GetRenderWindow().ExecuteProgram(program_index);
I'm not sure why this needs to be going through the renderer. Would it not be more straightforward to allow the frontend to register a callback with the system, which then gets called here?

I really don't think we should be coupling the video core ro the core library like this, even if it is a "fast and quick" way to get it working. We have several TODOs similar to this still in core that never got addressed, and I don't think adding another one like it to the mix is the way to go. If refactoring needs to be done to suit the design better, I think it should just be done and gotten over with.

2020-10-18 05:24 UTC, bunnei commented on src/core/hle/service/am/am.cpp
> +    system.GPU().Renderer().GetRenderWindow().ExecuteProgram(program_index);
Yep -- this PR was borderline "RFC" because I was not sure how I wanted to address this problem. We'll certainly do that before merging.

2020-11-24 22:44 UTC, bunnei commented on src/yuzu_cmd/emu_window/emu_window_sdl2.h
> +    void ExecuteProgram(std::size_t /*program_index*/) override{};
Against our clang-format rules

2020-11-24 22:44 UTC, bunnei commented on src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
> +    void ExecuteProgram(std::size_t /*program_index*/) override{};
Against our clang-format rules

2020-11-24 23:22 UTC, lioncash approved these changes

2020-11-24 23:27 UTC, merged