HID: Implement GC controller in game
yuzu-emu/yuzu pull request #4940
Opened 2020-11-18 06:39 UTC by german77

Implements the necessary for the GC controller to be detected in-game as a GC controller. Analog triggers are supported.

TODO:
- Change controller pictures for the GC equivalent
- Use the proper analog axis for analog triggers

2020-11-18 07:16 UTC, lioncash reviewed
Localization-only review

2020-11-18 07:16 UTC, lioncash commented on src/yuzu/configuration/configure_input_player.cpp
> +        tr("Game Cube"),
```suggestion
        tr("GameCube Controller"),
```

2020-11-18 09:20 UTC, Morph1984 reviewed
Review comments in addition to the ones discussed on discord

2020-11-18 09:20 UTC, Morph1984 commented on src/input_common/settings.h
>      Handheld,
```suggestion
    LeftJoycon,
    RightJoycon,
    Handheld,
    GameCube,
    Pokeball,
```

These should be placed below handheld to preserve compatibility

2020-11-18 09:20 UTC, Morph1984 commented on src/yuzu/applets/controller.cpp
> +        return Settings::ControllerType::GameCube;
ditto

2020-11-18 09:20 UTC, Morph1984 commented on src/yuzu/applets/controller.cpp
> +        return 5;
ditto

2020-11-18 09:20 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.cpp
> +        return Settings::ControllerType::GameCube;
ditto

2020-11-18 09:20 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.cpp
> +        return 5;
ditto

2020-11-18 09:20 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.cpp
> +        ui->buttonShoulderButtonsButtonZLGroup,
These should be disabled, not hidden

2020-11-18 09:21 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> +        LOG_ERROR(Service_HID, "called, npad_id_1={}",
Is this left over from debugging?

2020-11-18 09:22 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> +        case NPadControllerType::GameCube:
```suggestion
        case NPadControllerType::GameCube:
        case NPadControllerType::Pokeball:
```

2020-11-18 17:48 UTC, slashiee requested changes
There are duplicate icons appended with ` - copia`.

2020-11-18 18:00 UTC, german77 commented
> There are duplicate icons appended with ` - copia`.

I just separated the changes for this PR from my build. In a few hours I will properly remove all errors and test the build.  Please consider checking it tomorrow

2020-11-21 02:10 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> +        // GC controllers behave like pro controllers
```suggestion
        // The GC Controller behaves like a wired Pro Controller
```

2020-11-21 02:10 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.h
> +            BitField<9, 1, u32> lucia;        // TODO: Confirm when possible
These are confirmed by switchbrew, so they can be removed

2020-11-21 02:10 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.cpp
> +        // hide "Motion 1" and hide "Motion 2".
```suggestion
        // Hide both "Motion 1/2".
```

2020-11-21 02:10 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.h
> +    void UpdateControllerEnableButtons();
```suggestion
    void UpdateControllerEnabledButtons();
```

2020-11-26 15:06 UTC, Morph1984 commented on src/yuzu/applets/controller.cpp
>          case Settings::ControllerType::ProController:
minor nit, swap the 2
```suggestion
        case Settings::ControllerType::ProController:
        case Settings::ControllerType::GameCube:
```

2020-11-26 15:06 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.cpp
>          case Settings::ControllerType::ProController:
minor nit, swap the 2
```suggestion
        case Settings::ControllerType::ProController:
        case Settings::ControllerType::Pokeball:
```

2020-11-26 15:06 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_player.h
> +    /// Alters the button name based on the current controller type.
```suggestion
    /// Alters the button names based on the current controller type.
```

2020-11-26 17:09 UTC, v1993 commented
I've tracked down few bizarre issues to this PR and have to ask for its exclusion from EA merge.

Currently, there are two issues known to me:

1. Incorrect handling of ZL/ZR triggers, tested for Pro Controller input. Assigning buttons still interprets them as axles, causing weird results where assigned buttons don't work but unrelated axis does! This also breaks "default" configuration.
2. Right stick does not show informational prompt when being configured.

2020-12-19 22:14 UTC, ameerj commented on src/input_common/sdl/sdl_impl.cpp
> +            return {true, 1.0f};
Is the bool associated with a button?

2020-12-19 22:14 UTC, ameerj commented on src/input_common/sdl/sdl_impl.cpp
> +            if (direction_name == "up") {
maybe use a switch statement?

2020-12-19 22:14 UTC, ameerj commented on src/input_common/sdl/sdl_impl.cpp
> +            const float threshold = std::clamp(params.Get("threshold", 0.9f), 0.0f, 1.0f);
ditto about the threshold default value

2021-02-15 18:31 UTC, bunnei approved these changes

2021-02-15 18:32 UTC, merged