Disable analog joystick from buttons by default
yuzu-emu/yuzu pull request #5020
Opened 2020-11-27 03:00 UTC by german77

Since this setting adds delay to the input, some games like SSBU don't work as intended. This will disable the setting by default and add a checkbox under advanced settings to enable it.

2020-12-01 19:46 UTC, bunnei approved these changes

2020-12-02 13:15 UTC, Morph1984 requested changes

2020-12-02 13:15 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_advanced.ui
> +                     <string>Analog joystick button</string>
Is there something more descriptive that can be used to convey that this setting is **only** meant for 1. Keyboard users and 2. Is meant for games such as diablo 3

2020-12-06 04:50 UTC, Morph1984 commented on src/yuzu/configuration/configure_input_advanced.ui
> +                     <string>Analog joystick button</string>
I gave this a bit of thought, perhaps, "Emulate Analog with Keyboard Input"

2020-12-07 10:29 UTC, Morph1984 commented on src/core/settings.h
> +    bool analog_joystick_button;
Rename instances of `analog_joystick_button` to `emulate_analog_keyboard`

2020-12-08 02:26 UTC, Morph1984 approved these changes

2020-12-08 02:30 UTC, merged