HID: Stub set and get NpadCommunicationMode
yuzu-emu/yuzu pull request #5021
Opened 2020-11-27 03:22 UTC by german77

This functions are used by these games #4048. Making them playable. The enum posible values are unknown.

2020-11-27 03:33 UTC, Morph1984 commented on src/core/hle/service/hid/controllers/npad.cpp
> +
I would place these below the `NpadCommunicationMode` setters/getters, ditto for their prototypes and value in the header file

2020-11-28 12:40 UTC, ogniK5377 requested changes

2020-11-28 12:40 UTC, ogniK5377 commented on src/core/hle/service/hid/controllers/npad.h
> +        Unknown1 = 1,
```suggestion
        Communication5ms = 0,
        Communication10ms = 1,
        Communication15ms = 2,
        CommunicationUnknown = 3,
```

2020-11-28 13:40 UTC, ogniK5377 approved these changes

2020-11-28 23:22 UTC, bunnei approved these changes

2020-11-28 23:22 UTC, merged