buffer_queue: Skip and log out of range buffer slots
yuzu-emu/yuzu pull request #5284
Opened 2021-01-03 17:53 UTC by ameerj

This PR is an attempt to mitigate the undefined behavior of accessing indices outside of the range of `std::array`. When an attempt to access an element not within the `buffers` array range is encountered, it is skipped over and logged.

Hopefully this change will provide further details in logs to assist in finding the root cause of the error, as it occurs inconsistently.

2021-01-03 17:59 UTC, lioncash commented on src/core/hle/service/nvflinger/buffer_queue.cpp
> +            free_buffers.erase(f_itr++); // erase bad slot element and continue
Comments should go on top of the line rather than on the side (especially given in this case it applies to more than just this line).

2021-01-04 04:05 UTC, ReinUsesLisp requested changes
This is a data race. It has to be fixed with locks or other multithreading primitives, instead of hidden in a log that nobody will bother to fix in a month or so.

2021-01-04 06:00 UTC, ameerj commented
@ReinUsesLisp formally addressed the issue 👍

2021-01-04 06:17 UTC, ReinUsesLisp commented on src/core/hle/service/nvflinger/buffer_queue.cpp
> +    {
No need to introduce a new scope here.

2021-01-04 06:33 UTC, ReinUsesLisp approved these changes

2021-01-04 06:34 UTC, ReinUsesLisp commented
Squash the commits, it looks good to me.

2021-01-04 07:42 UTC, Morph1984 approved these changes

2021-01-04 07:42 UTC, merged