qt: Set DISPLAY env var when not present
yuzu-emu/yuzu pull request #5327
Opened 2021-01-10 18:17 UTC by AniLeo

Fixes web browser opening (Help > Open Mods Page, Help > Open Quickstart Guide)

```
$ ./yuzu-20210110-a8cc9db87-x86_64.AppImage 
Error: no DISPLAY environment variable specified
```

Same issue as https://github.com/RPCS3/rpcs3/issues/5959, same fix as https://github.com/RPCS3/rpcs3/pull/7461

2021-01-10 18:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=5327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=5327) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=5327) it.</sub>

2021-01-10 20:03 UTC, lat9nq commented
This does not work if the host session's DISPLAY is not `:0`.

2021-01-10 20:26 UTC, AniLeo commented
Is there any scenario where `:0` is not in use while another id is? `:0` is usually the main screen - https://www.xfree86.org/current/X.7.html#sect4

We never got any issue for that since adding this, but I am not aware of another way to go about this

2021-01-10 21:06 UTC, lat9nq commented
Well, for example, on my machine I have multiple GPUs inserted for testing. To use the NVIDIA GPUs in the subsequent slots, I need to give them dummy X screens. So the primary screen is `:0.0` and the NVIDIA GPUs get `:0.1` and `:0.2`. Essentially, my X server has multiple screens defined.

I am more than willing to try and change my xorg.conf to fix this issue, but I feel like an AppImage should be adapting to any scenario, not the user changing their machine to use the AppImage. This also wouldn't work on machines with multiple X servers running.

I was digging into this a day or so ago, and I came across something called `appimage-exec-wrapper`, which restores specified environment variables when `execve` and friends are called. It, however, seems to be deprecated. I'm not sure what has happened upstream that necessitates deprecating it.

2021-03-06 21:27 UTC, lat9nq commented
Can you confirm whether this is still an issue that needs resolving? I think we can merge it for now with a `// TODO (lat9nq): Find a better solution for starting external applications` if it's still affecting people. I currently cannot reproduce the issue on my machines nor any VMs, however. And since merging it and testing locally doesn't seem to break anything, seems fine to merge (again, if this still affects people).

2021-03-06 23:13 UTC, AniLeo commented
It still happens yes, just reproduced on the latest build. Note that this doesn't happen on the native compiled application, only on the AppImage version.

2021-03-06 23:50 UTC, lat9nq requested changes

2021-03-06 23:50 UTC, lat9nq commented on src/yuzu/main.cpp
> +    // Set the DISPLAY variable in order to open web browsers
```suggestion
    // Set the DISPLAY variable in order to open web browsers
    // TODO (lat9nq): Find a better solution for AppImages to start external applications 
```
Can you add this comment that points at me? (Making a suggestion so it's easier to add with GitHub)

2021-03-06 23:50 UTC, lat9nq commented on src/yuzu/main.cpp
> +#endif
```suggestion
    if (QString::fromLocal8Bit(qgetenv("DISPLAY")).isEmpty()) {
        qputenv("DISPLAY", ":0");
    }
#endif
```
Style consistency with the project.

2021-03-12 20:07 UTC, lat9nq approved these changes

2021-03-12 20:10 UTC, bunnei approved these changes

2021-03-12 20:10 UTC, merged