[OpenGL] Alternate depth mode test, signed atomic min/max, texelFetch offsets
yuzu-emu/yuzu pull request #5980
Opened 2021-02-21 21:30 UTC by Kelebek1

I didn't know how to really implement the atomics. I feel like this implementation is terrible, so if anyone has any ideas on how to better do it, let me know. I didn't want to always include the helpers as part of every shader, and I also needed mutliple versions depending on the variables used. 

I decided to just log if a particular helper was needed, and for atomic in paticular, the memory types seen during decompile. Forward-declare the functions at the top, and then implement them after decompiling the shader so I knew what was needed. I tried to make it in such a way that new helper functions can be added more easily in the future.

As part of that, I decided to rename shared memory from smem to shared_mem, to match the assembly shaders and Vulkan.

The alternate depth test should fix various games in OpenGL.

Before:
![old](https://user-images.githubusercontent.com/34639600/108639273-942a2c00-748b-11eb-9a8c-833709535af1.png)
After:
![new](https://user-images.githubusercontent.com/34639600/108639280-9a200d00-748b-11eb-9588-767c04cee452.png)

2021-02-22 00:15 UTC, ReinUsesLisp requested changes

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +        // The depth reg is unreliable as depth can change after initialisation,
If this was true, using the same logic on Vulkan wouldn't work, hence why I didn't port Ryujinx' hack.
Remove this change and push it on a separate pull request so it can be discussed in detail.

I am aware this "fixes" Link's Awakening, but it's still a hack coming from a perspective of "we must transform whatever state we have to what the game is doing in NVN" instead of "we must emulate the hardware".

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    std::string GetSharedMemory() const {
Any reason to have this on a function instead of a constant?

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        code.AddLine("int Helpers_Atomic{}(uint offset, int value, bool is_min);",
There are no atomics for local memory.

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    {{
```suggestion
    do {{
```

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +            if (std::get_if<SmemNode>(&*operation[0])) {
`std::holds_alternative`

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +                memory = GetLocalMemory();
This never happens.

2021-02-22 00:15 UTC, ReinUsesLisp commented on src/video_core/shader/decode/texture.cpp
> +            GetRegister(last && !aoffi_enabled ? last_coord_register : coord_register + i));
Add parenthesis here to make explicit if you want to do `(cond ? a : b) + 1` or `cond ? a : (b + 1)`

2021-02-22 00:39 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        expr += "(";
```suggestion
        expr += '(';
```

Ditto below for a few other character constants

2021-02-22 00:39 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    std::array<bool, HelperFunctions::Total> helper_functions_enabled;
This can be initialized in the class body like so:

```suggestion
    std::array<bool, HelperFunctions::Total> helper_functions_enabled{};
```

allowing the additions to the constructor initializer list to be removed. Similarly `atomic_memory_types`'s entry in the initializer list can be removed because it has its own constructor that always establishes its invariants.

2021-02-22 00:39 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +          helper_functions_enabled{}, atomic_memory_types{} {
These two additions aren't necessary. See a previous review comment for more details.

2021-02-22 00:39 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    std::string GetSharedMemory() const {
The constant could also be a constexpr std::string_view, as opposed to a std::string.

2021-02-22 00:39 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +enum HelperFunctions {
```suggestion
enum class HelperFunction {
```

We generally avoid regular enums, as they pollute the surrounding scope and are also implicitly convertible. The following private helpers can also be introduced:

```cpp
void SetHelperEnabled(HelperFunction hf, bool enabled) {
    helper_functions_enabled[static_cast<u32>(hf)] = enabled;
}

bool IsHelperEnabled(HelperFunction hf) const {
    return helper_functions_enabled[static_cast<u32>(hf)];
}
```

2021-02-22 08:03 UTC, Kelebek1 commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        code.AddLine("int Helpers_Atomic{}(uint offset, int value, bool is_min);",
Ah ok, I wasn't sure about this, which is why I did it this way. Can they only be used for shared memory then and nothing else?

2021-02-22 08:05 UTC, Kelebek1 commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    std::string GetSharedMemory() const {
I made it a function just to replicate GetLocalMemory, so there was a single source for changing the name later on.

2021-02-22 08:31 UTC, Kelebek1 commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +        // The depth reg is unreliable as depth can change after initialisation,
Removed from the PR, I'll open a new one.

2021-02-23 02:11 UTC, lioncash commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    };
Just noticed this, but this semicolon will cause a -Wextra-semi warning, since it's not necessary.

2021-02-23 21:16 UTC, Kelebek1 commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +    };
No problems! Fixed.

2021-02-27 20:03 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        code.AddLine("int Helpers_Atomic{}(uint offset, int value, bool is_min);",
They can also be used with global memory (storage buffers).

2021-02-27 20:05 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        helper_functions_enabled[static_cast<u32>(hf)] = enabled;
```suggestion
        helper_functions_enabled[static_cast<size_t>(hf)] = enabled;
```

2021-02-27 20:05 UTC, ReinUsesLisp commented on src/video_core/renderer_opengl/gl_shader_decompiler.cpp
> +        return helper_functions_enabled[static_cast<u32>(hf)];
```suggestion
        return helper_functions_enabled[static_cast<size_t>(hf)];
```

2021-03-26 06:23 UTC, lat9nq commented
Causes a regression on NVIDIA GPUs in BOTW.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6209718/yuzu_log.txt)

![Screenshot_2021-03-26_02-18-54](https://user-images.githubusercontent.com/22451773/112590976-928db400-8dfb-11eb-90d8-064544dd531b.png)

2021-07-09 19:57 UTC, Kelebek1 commented
Closed for Hades.

2021-07-09 19:57 UTC, closed without merging