InputCommon: Use an unique client id for each udp socket instance
yuzu-emu/yuzu pull request #6004
Opened 2021-02-27 15:33 UTC by german77

According to https://github.com/v1993/cemuhook-protocol each socket connection should have a unique client id. This should solve problems where test fails or you need to restart the server. Also removes the magic number 24872 that was used as client id for yuzu.

This is a candidate to be ported to citra since it has the same issue.

2021-02-27 17:17 UTC, v1993 requested changes
Lgtm, only one note

2021-02-27 17:17 UTC, v1993 commented on src/input_common/udp/client.cpp
> +        std::random_device device;
Since you get only a single number from generator, consider using just

```
return std::random_device()();
```

2021-02-27 19:41 UTC, lioncash commented on src/input_common/udp/client.cpp
> +        std::uniform_int_distribution<u32> distribution(0, static_cast<u32>(-1));
Note that in the future it's much more readable to use UINT32_MAX instead of casting -1

2021-02-27 19:46 UTC, v1993 commented on src/input_common/udp/client.cpp
> +        std::uniform_int_distribution<u32> distribution(0, static_cast<u32>(-1));
Wouldn't it be even better to use `std::numeric_limits<u32>::max()`? It's mostly a matter of style, so I wonder which is preferred in yuzu codebase.

2021-02-28 01:47 UTC, german77 commented on src/input_common/udp/client.cpp
> +        std::uniform_int_distribution<u32> distribution(0, static_cast<u32>(-1));
I did tried to go for a keyword for the max value but I couldn't find it.  So I used a cast. Next time I will use the keyword.

2021-02-28 10:29 UTC, v1993 requested changes

2021-02-28 10:29 UTC, v1993 commented on src/input_common/udp/client.cpp
> +        std::random_device{}();
```suggestion
        return std::random_device{}();
```
Missing `return` here.

2021-03-02 14:32 UTC, lioncash commented on src/input_common/udp/client.cpp
> +        std::uniform_int_distribution<u32> distribution(0, static_cast<u32>(-1));
@v1993 Either works, but UINT32_MAX is nice in non-generic code, as it's nicer to read.

2021-03-03 23:45 UTC, bunnei approved these changes

2021-03-03 23:45 UTC, merged