Friend: Stub GetPlayHistoryRegistrationKey
yuzu-emu/yuzu pull request #6113
Opened 2021-03-27 05:16 UTC by german77

Stubs GetPlayHistoryRegistrationKey used by BLAZBLUE CROSS TAG BATTLE

2021-03-27 05:47 UTC, Morph1984 commented on src/core/hle/service/friend/friend.cpp
> +        LOG_WARNING(Service_ACC, "(STUBBED) called bool={} uuid={}", bool_value, uuid.Format());
```suggestion
        const auto unknown_bool = rp.Pop<bool>();
        const auto uuid = rp.PopRaw<Common::UUID>();

        LOG_WARNING(Service_ACC, "(STUBBED) called, unknown_bool={}, uuid={}", unknown_bool, uuid.Format());
```

2021-03-27 13:40 UTC, ogniK5377 requested changes
Also change all the log classes in the file to `Service_Friend`, Thanks!

2021-03-27 13:40 UTC, ogniK5377 commented on src/core/hle/service/friend/friend.cpp
> +        // Stub used by BLAZBLUE CROSS TAG BATTLE
This can be omitted

2021-03-27 13:40 UTC, ogniK5377 commented on src/core/hle/service/friend/friend.cpp
> +        const auto bool_value = rp.Pop<bool>();
```suggestion
        const auto local_play = rp.Pop<bool>();
```

2021-03-27 13:40 UTC, ogniK5377 commented on src/core/hle/service/friend/friend.cpp
> +        LOG_WARNING(Service_ACC, "(STUBBED) called bool={} uuid={}", bool_value, uuid.Format());
```suggestion
        LOG_WARNING(Service_Friend, "(STUBBED) called local_play={} uuid={}", local_play, uuid.Format());
```

2021-03-27 13:43 UTC, ogniK5377 requested changes
Also, it looks as if only a buffer is written out, not any inline values and not a u32.

2021-03-27 13:43 UTC, ogniK5377 commented on src/core/hle/service/friend/friend.cpp
> +        rb.Push<u32>(0);
```suggestion
        IPC::ResponseBuilder rb{ctx, 2};
        rb.Push(RESULT_SUCCESS);
```

2021-03-27 14:23 UTC, german77 commented on src/core/hle/service/friend/friend.cpp
> +        LOG_WARNING(Service_ACC, "(STUBBED) called bool={} uuid={}", bool_value, uuid.Format());
Most logs here are Service_ACC Should I change them for Friend?

2021-04-10 03:49 UTC, bunnei approved these changes

2021-04-10 03:50 UTC, merged