Implement/Port Fastmem from Citra to Yuzu
yuzu-emu/yuzu pull request #6422
Opened 2021-06-07 00:30 UTC by FernandoS27

This Pull Request finally implements a long requested feature from Citra: Fastmem. Fastmem is the name we have given to emulating the MMU by using Host allocation instead of software MMU emulation. In the previous approach, we would emulate Guest virtual memory through a page table where we would store addresses to physical memory for each virtual page the application/game had. Whenever a game accessed memory, we would look into the emulated page table check if we have a valid physical mem address and then read the memory, if the physical address wasn't valid, the game would call an emulator fallback. All this costed around 10-15 instructions.

On fastmem, we use instead about 4 instructions: 3 for checking if the address is within the emulated address space (can be disabled with Unsafe CPU -> disable address space checks) and 1 instruction for memory read/write. In case of a Page Fault, dynarmic will invalidate the code block and recompile it under the first software approach. This is typical when dealing with GPU marked memory.

**Important note for windows users**: This PR only works for newest versions of Windows 10. Please make sure to update to latest version to avoid any inconveniences.

I do not take credit for most of this work, since I only advised and mixed everyone's efforts together. The credit goes to everyone above.

Credits:
- @MerryMage For implementing fastmem in dynarmic.
- @degasus For implementing Linux version of fastmem and original design.
- @ReinUsesLisp For Implementing Windows version of fastmem/host memory handling.
- @BreadFish64 For showing us on his gameboy emulator that placeholder memory could be aligned to 4kb, thus, avoid the biggest layback on windows MMU emulation: Windows page granularity for most part is 64kb.

2021-06-07 00:42 UTC, ReinUsesLisp commented on src/core/arm/dynarmic/arm_dynarmic_32.cpp
> +    config.far_code_offset = 400 * 1024 * 1024;
Probably an unintentional change.

2021-06-07 00:42 UTC, ReinUsesLisp commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +    config.far_code_offset = 400 * 1024 * 1024;
Probably an unintentional change.

2021-06-07 00:43 UTC, FernandoS27 commented on src/core/arm/dynarmic/arm_dynarmic_32.cpp
> +    config.far_code_offset = 400 * 1024 * 1024;
actually intentional, it was a bug. far_code offset is not suppose to be in the middle.

2021-06-07 00:43 UTC, FernandoS27 commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +    config.far_code_offset = 400 * 1024 * 1024;
Ditto.

2021-06-07 06:23 UTC, degasus commented on src/core/arm/dynarmic/arm_dynarmic_32.cpp
> +    config.far_code_offset = 400 * 1024 * 1024;
Also a related change: With fastmem enabled, we emit by far less code. Especially without bound checking, the far code cache does not fill up at all (bound checking is small, exiting the block however is not)

2021-06-07 06:35 UTC, degasus commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        config.fastmem_address_space_bits = address_space_bits;
cpuopt_unsafe_fastmem_check

2021-06-07 07:27 UTC, degasus commented
May I ask you to autosquash the fixup commit? How is the GPUThread change related to fastmem?

2021-06-07 07:32 UTC, lioncash commented on src/common/host_memory.h
> +    HostMemory(HostMemory& other) = delete;
```suggestion
    HostMemory(const HostMemory& other) = delete;
```

Ditto for the copy assignment operator

2021-06-07 07:32 UTC, lioncash commented on src/common/host_memory.cpp
> +static constexpr size_t PageAlignment = 0x1000;
Static can be removed here.

2021-06-07 07:32 UTC, lioncash commented on src/common/host_memory.cpp
> +        if (read)
These conditions should be braced

2021-06-07 08:57 UTC, otaku976 commented
Nice fix , but how much we need to wait for project Hades?

2021-06-07 09:17 UTC, FernandoS27 commented
> May I ask you to autosquash the fixup commit? How is the GPUThread change related to fastmem?

kinda in the protection of read part, changing that forced me to up to date the other stuffs,

2021-06-07 14:11 UTC, v1993 commented
I understand that this isn't a large concern for now, but it would be nice to disable fastmem if compiled for platform that doesn't support it instead of outright causing build error, given that yuzu can still work without fastmem just fine.

2021-06-07 14:59 UTC, FernandoS27 commented
> I understand that this isn't a large concern for now, but it would be nice to disable fastmem if compiled for platform that doesn't support it instead of outright causing build error, given that yuzu can still work without fastmem just fine.

Thanks for the feedback. I'll see to try to address this. Could you give some examples ? We do know there are few people trying to get yuzu into MacOS and likely Android. I'de love to add this implementatipons but I fully understand the case where there's an OS which is not supported.

2021-06-07 20:04 UTC, v1993 requested changes

2021-06-07 20:04 UTC, v1993 commented on src/common/host_memory.cpp
> +            Release();
Calling Release on every error seems a bit ugly to me. How about simple RAII wrapper that stores a reference to `HostMemory::Impl` and calls `Release()` on destruction unless deactivated? Something like

```
HostMemoryGuard hmguard{*this};
...
exiting here will call `Release()` from hmguard's destructor
...
On success:
hmguard.deactivate();
return;
```
This seems to be useful in Linux implementation as well since right now it also manually calls Release before throwing.

2021-06-07 21:06 UTC, MerryMage commented on src/common/host_memory.cpp
> +            Release();
`SCOPE_EXIT({ Release(); });` preferable

2021-06-10 06:39 UTC, degasus commented
> I understand that this isn't a large concern for now, but it would be nice to disable fastmem if compiled for platform that doesn't support it instead of outright causing build error, given that yuzu can still work without fastmem just fine.

This is sadly not as easy. The chance to use fastmem requires a special way to allocate the memory itself. So in the end, we can only support half of the API in a generic build. However good luck, this is likely one of the first place you want to touch after porting it to a new platform, and as long as the destination is not Windows, you can just pick the linux implementation :)

2021-06-11 11:12 UTC, Morph1984 commented on src/common/host_memory.cpp
> +    } catch (const std::bad_alloc& e) {
```suggestion
    } catch (const std::bad_alloc&) {
```

2021-06-11 12:32 UTC, Morph1984 commented on src/yuzu/configuration/configure_cpu.ui
> +           <string>Disable adress space checks</string>
```suggestion
           <string>Disable address space checks</string>
```

2021-06-11 18:25 UTC, lioncash approved these changes

2021-06-11 18:26 UTC, merged