yuzu qt, core: Support LayeredFS mods from SDMC directory
yuzu-emu/yuzu pull request #6471
Opened 2021-06-15 05:12 UTC by lat9nq

This was just a literal shower thought about making it easier to use [Ultimate Mod Manager](https://github.com/ultimate-research/UltimateModManager) on yuzu.

Adds to yuzu's Qt frontend a context menu option to dump the RomFS to either the normal directory, or to a subdirectory in the sdmc data directory (`yuzu/sdmc/atmosphere/titles/[title_id]/romfs`). In core, an extra singular mod is added to each game that has contents in this directory.

So now, to use UMM, it should be as easy as right clicking SSBU -> Dump RomFS -> Dump RomFS to SDMC Directory, then opening UMM and installing your mods, then booting SSBU.

2021-06-15 08:59 UTC, Morph1984 commented
With #6472, change it to `contents` instead of `titles`

2021-06-15 17:46 UTC, lat9nq commented
> With #6472, change it to `contents` instead of `titles`

Yup, this requires #6472, now. Thanks, Morph.

2021-06-15 21:13 UTC, lioncash reviewed
Just a few minor nits

2021-06-15 21:13 UTC, lioncash commented on src/core/file_sys/sdmc_factory.cpp
> +    if (title_id == 0 || (title_id & 0xFFF) == 0x800)
This should be braced.

2021-06-15 21:13 UTC, lioncash commented on src/core/hle/service/filesystem/filesystem.cpp
> +    if (sdmc_factory == nullptr)
Ditto

2021-06-15 21:13 UTC, lioncash commented on src/core/file_sys/patch_manager.cpp
> +            if (layeredfs)
Seems like this will never execute

2021-06-15 21:13 UTC, lioncash commented on src/core/file_sys/patch_manager.cpp
> +        if (IsDirValidAndNonEmpty(FindSubdirectoryCaseless(sdmc_mod_dir, "romfs")))
This should be braced

2021-06-23 03:07 UTC, Morph1984 approved these changes
Will merge after it's been tested for a bit in EA

2021-06-23 10:08 UTC, Morph1984 requested changes
This is to remind me to fix an issue that's been reported earlier by @OZtistic, do not merge until I've addressed this issue.
Untagging this PR for now

2021-06-28 04:28 UTC, Morph1984 approved these changes
Fix has been pushed, tagging this for testing.

2021-06-29 04:10 UTC, merged