hidbus: Implement hidbus and ringcon
yuzu-emu/yuzu pull request #6558
Opened 2021-07-04 23:51 UTC by german77

Implements the minimum necessary to get a Ring Controller working. This was intended to fix Ring Fit Adventure but seems like the game has other issues independent of the ringcon support.

It lacks support for any other hidbus device or any configuration since Ring Fit it's not working and no other game supports this special controller. Implementation will be improved when a game that actually uses this service exist and works.

Note: Starlink: Battle for Atlas is not supported

Closes #4911, #2721

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +
Unnecessary newline

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +
Unnecessary newline

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +constexpr auto hidbus_update_ns = std::chrono::nanoseconds{15 * 1000 * 1000}; // (15ms, 60Hz)
Maybe place the comment on top of the line instead of off to the side.

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +    HidbusBusHandle handle{
This can be merged with the line below it, assigning into the bus handle.

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +    // TODO: Assing and use handle values
```suggestion
    // TODO: Assign and use handle values
```

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +    u64 data_size = ctx.WriteBuffer(data);
```suggestion
    const u64 data_size = ctx.WriteBuffer(data);
```

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus.cpp
> +    std::vector<u8> data = ringcon.GetReply();
```suggestion
    const std::vector<u8> data = ringcon.GetReply();
```

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    const u32 command_id = data[0] + (data[1] << 8) + (data[2] << 16) + (data[3] << 24);
```cpp
const u32 command_id = u32{data[0]} + (u32{data[1]} << 8) + (u32{data[2]} << 16) + (u32{data[3]} << 24);
```

Otherwise this is a sign-conversion.

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    constexpr std::array<RingConCommands, 7> supported_commands = {
```suggestion
    static constexpr std::array supported_commands = {
```

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +            bool bit = crc & 0x80;
```suggestion
            bool bit = (crc & 0x80) != 0;
```

Otherwise this truncates to a bool

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +            if (data[index] & i) {
```suggestion
            if ((data[index] & i) != 0) {
```

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    std::vector<u8> data;
There should be a `static_cast(std::is_trivially_copyable_v<T>);` in this function.

2021-07-05 02:29 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +std::vector<u8> RingController::GetDataVector(const T reply) const {
```suggestion
std::vector<u8> RingController::GetDataVector(const T& reply) const {
```

2021-07-05 03:52 UTC, german77 commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    std::vector<u8> data;
I did not understand this one. `is_trivially_copyable_v` returns a bool. Should I add a check to avoid coping data that cannot be copied?

2021-07-05 03:52 UTC, Morph1984 commented on src/core/hle/kernel/kernel.cpp
> +    Kernel::KSharedMemory* hidbus_shared_mem;
```suggestion
    Kernel::KSharedMemory* hidbus_shared_mem{};
```

2021-07-05 03:52 UTC, Morph1984 commented on src/core/hle/service/hid/hidbus.cpp
> +// (15ms, 60Hz)
```suggestion
// (15ms, 66.6Hz)
```

2021-07-05 03:52 UTC, Morph1984 commented on src/core/hle/service/hid/hidbus.cpp
> +             "player_number={} is_valid={}",
```suggestion
             "called, t_mem_handle=0x{:08X}, polling_mode={}, abstracted_pad_id={}, bus_type={}, internal_index={}, player_number={}, is_valid={}",
```

Then let clang-format work its magic to format this properly, ditto for all other logging

2021-07-05 03:57 UTC, german77 commented on src/core/hle/service/hid/hidbus.cpp
> +             "player_number={} is_valid={}",
Uh not sure how that happen. Must the same clang that created those new lines.

2021-07-05 04:06 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    std::vector<u8> data;
err, I meant

```cpp
static_assert(std::is_trivially_copyable_v<T>);
```

not static_cast

2021-07-05 04:10 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.h
> +    enum class RingConCommands : u32_le {
```suggestion
    enum class RingConCommands : u32 {
```

Otherwise this won't work in cases the `u32_le` is a struct

2021-07-05 04:10 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.h
> +    std::vector<u8> GetReply();
```suggestion
    std::vector<u8> GetReply() const;
```

2021-07-05 04:27 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.h
> +    enum class DataValid : u32_le {
```suggestion
    enum class DataValid : u32 {
```

2021-07-05 04:44 UTC, german77 commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +    std::vector<u8> data;
Ah that makes a lot of sense now.

2021-07-05 04:52 UTC, german77 commented on src/core/hle/service/hid/hidbus/ringcon.h
> +    std::vector<u8> GetReply();
Get reply modifies the state of `command` otherwise it can return valid data even if the game din't request any

2021-07-05 05:23 UTC, cooperate commented
I'm just wondering if the remaining blocker for Ring Fit lies in the IR-sensor data.  Not sure how much overlap it shares with what's required but here are some projects / relevant threads that have IR Sensor support for the joycons.

https://github.com/switchbrew/switch-examples/blob/master/hid/irsensor/source/main.c
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/issues/47
https://github.com/erikmwerner/QJoyControl
https://github.com/CTCaer/jc_toolkit/releases
https://gbatemp.net/threads/tool-joy-con-toolkit.478560/

2021-07-05 06:35 UTC, lioncash commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +#include <cstring>
`<type_traits>` also needs to be included.

2021-07-05 09:11 UTC, bylaws commented
> I'm just wondering if the remaining blocker for Ring Fit lies in the IR-sensor data. Not sure how much overlap it shares with what's required but here are some projects / relevant threads that have IR Sensor support for the joycons.
> 
> https://github.com/switchbrew/switch-examples/blob/master/hid/irsensor/source/main.c
> [dekuNukem/Nintendo_Switch_Reverse_Engineering#47](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/issues/47)
> https://github.com/erikmwerner/QJoyControl
> https://github.com/CTCaer/jc_toolkit/releases
> https://gbatemp.net/threads/tool-joy-con-toolkit.478560/

Fwiw the IR sensor only has the image transfer protocol REd, there's still the point detection stuff and probably some others that need doing and I'm fairly sure that's what most games use

2021-08-03 14:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=6558) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=6558) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=6558) it.</sub>

2021-09-10 15:28 UTC, pktiuk commented
> This was intended to fix Ring Fit Adventure but seems like the game has other issues independent of the ringcon support.

What are the other issues with Ring Fit Adventure?

2021-09-10 19:53 UTC, german77 commented
Memory reads. Not sure what causes them

2021-09-10 20:28 UTC, pktiuk commented
Is there any issue for this?  
I was looking for it in [wiki page](https://yuzu-emu.org/game/), citra [forum](https://community.citra-emu.org/t/about-yuzu-run-ringfit-adventure/355044/3)  and github issues, but I couldn't find anything mentioning these problems.

2021-12-23 06:53 UTC, cooperate commented
Ring-fit relies on storage from the ring-con itself.  This data should be stored somewhere in yuzu.  If yuzu should ever connect natively through bluetooth to the ring-con itself, this data should be read from the ring-con.

2022-01-10 03:21 UTC, Morph1984 commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +        send_command_asyc_event->GetWritableEvent().Signal();
```suggestion
        send_command_async_event->GetWritableEvent().Signal();
```

2022-01-10 03:23 UTC, Morph1984 commented on src/core/hle/service/hid/hidbus/ringcon.cpp
> +        std::memcpy(&save_info, &data, sizeof(SaveCalData));
```suggestion
        std::memcpy(&save_info, data.data(), sizeof(SaveCalData));
```

2022-01-17 10:47 UTC, v1993 requested changes

2022-01-17 10:47 UTC, v1993 commented on src/yuzu/configuration/configure_ringcon.cpp
> +    }
```suggestion
    if (!input_setter || !event) {
        return;
    }
    event->ignore();
```

2022-03-22 14:11 UTC, zhengwz commented
Does the newly submitted code mean that we can play Ring Fit Adventure with ring? @german77

2022-03-29 06:47 UTC, zhengwz commented
Hello, I would like to know about the development progress of the real ring, I am really looking forward to it. @german77

2022-04-16 13:51 UTC, merged

2022-04-19 11:41 UTC, zhengwz commented
I would like to know whether the development of real ring support is still in progress?  @german77

2022-04-19 15:19 UTC, german77 commented
Yes. I got it working. Just need to cleanup the code

2022-04-19 15:28 UTC, cybik commented
For the record, I tested the latest mainline build with (presumed) ringcon support, and Ring Fit still does some odd magicks that force P2 into an unrecognized/unsupported state, because with the game active, forcing P2 left never works. It *always* gets deactivated again once I close the settings.

If that state is known, forget I said anything.