Support more PCM formats
yuzu-emu/yuzu pull request #6564
Opened 2021-07-06 14:06 UTC by Kelebek1

Adds a few more PCM formats to decode. Only one missing now is PCM24 due to it being awkward. Haven't seen s8 or s32 used in any games so far, but float is used rarely.

Fixes Ys IX audio.

2021-07-06 14:19 UTC, Morph1984 commented on src/audio_core/command_generator.cpp
> +    if constexpr (std::is_floating_point<T>::value) {
```suggestion
    if constexpr (std::is_floating_point_v<T>) {
```

2021-07-06 14:36 UTC, ogniK5377 approved these changes
Besides @Morph1984 lil nit, lgtm

2021-07-06 16:32 UTC, ogniK5377 requested changes

2021-07-06 16:32 UTC, ogniK5377 commented on src/audio_core/command_generator.cpp
> +            sample_buffer[mix_offset + i] = buffer[i * channel_count + channel] << 8;
now that I look back at it, these can be made more expressive. These samples should be remapped to the s16 range. 

```suggestion
            sample_buffer[mix_offset + i] = static_cast<s32>(static_cast<float>(buffer[i * channel_count + channel] / std::numeric_limits<s8>::max()) * std::numeric_limits<s16>::max();)
```

2021-07-06 16:32 UTC, ogniK5377 commented on src/audio_core/command_generator.cpp
> +            sample_buffer[mix_offset + i] = buffer[i * channel_count + channel] >> 16;
dito

2021-07-06 17:43 UTC, Kelebek1 commented on src/audio_core/command_generator.cpp
> +            sample_buffer[mix_offset + i] = buffer[i * channel_count + channel] << 8;
Isn't that what the shifts already do? Are there problems with some values? From what I tested they all came out ok.

2021-07-08 13:52 UTC, ogniK5377 approved these changes

2021-07-08 16:14 UTC, Morph1984 approved these changes

2021-07-08 16:14 UTC, merged