Alter downmixining to preserve front left/right channels
yuzu-emu/yuzu pull request #6569
Opened 2021-07-07 14:06 UTC by Kelebek1

Many games report 6 channel output while only providing data for 2. We only output 2-channel audio regardless, and in the downmixing, front left/right are only providing 36% of their volume. This is done assuming all of the other channels also contain valid data, but in a few games they don't. This PR alters the downmixing to preserve front left/right, so volume is not lost.

This improves Link's Awakening, New Super Mario Bros U, Disgaea 6, Super Kirby Clash.

Buffer raw pointers have been replaced with spans as well. This was mainly to aid debugging, as MSVC won't show elements of pointers, but will show the whole span.

2021-07-07 14:16 UTC, ogniK5377 requested changes

2021-07-07 14:16 UTC, ogniK5377 commented on src/audio_core/audio_renderer.cpp
> +        /*static_cast<float>(lf_channel) * coeff[2] +*/ static_cast<float>(br_channel) * coeff[3];
This should be undone, games provide constants for downmixing and choose to mix the LFE as they please

2021-07-07 14:16 UTC, ogniK5377 commented on src/audio_core/sink_context.cpp
> +        };
```suggestion
        downmix_coefficients = {
            0.3694f,   // front
            0.2612f, // center
            0.0f,   // lfe
            0.3694f, // back
        };
```
Might yield better results as this is what we had before. Is there any benefit to the above constants as opposed to what we had before?

2021-07-07 14:19 UTC, Kelebek1 commented on src/audio_core/audio_renderer.cpp
> +        /*static_cast<float>(lf_channel) * coeff[2] +*/ static_cast<float>(br_channel) * coeff[3];
Everything I could find kinda said just ignore it when downmixing to 2 channels. I didn't know what default coeff to use for it though. Do you have any ideas on what coefficient should be used for it?

2021-07-07 14:22 UTC, Kelebek1 commented on src/audio_core/sink_context.cpp
> +        };
Front can't be 0.36 or we're in the same position as before, the front will only get 36% of the output and volume will be stuck low. I got these numbers from googling around, and from section 7.8.2 in this doc: http://www.atsc.org/wp-content/uploads/2015/03/A52-201212-17.pdf

Also -3dB (pow10(-3 / 20)) just seems to be used everywhere, it's in this example on Wiki as well: https://en.wikipedia.org/wiki/Pan_law

2021-07-07 15:26 UTC, Morph1984 commented on src/audio_core/audio_renderer.cpp
> +    s16 fl_channel, s16 fr_channel, s16 fc_channel, [[maybe_unused]] s16 lf_channel, s16 bl_channel,
[[maybe_unused]] is no longer needed here since `lf_channel` is used below
```suggestion
    s16 fl_channel, s16 fr_channel, s16 fc_channel, s16 lf_channel, s16 bl_channel,
```

2021-07-07 16:17 UTC, Morph1984 commented on src/audio_core/audio_renderer.cpp
> +[[maybe_unused]] [[nodiscard]] static constexpr std::tuple<s16, s16> Mix6To2(
As Breadfish suggested on discord
```suggestion
[[maybe_unused, nodiscard]] static constexpr std::tuple<s16, s16> Mix6To2(
```

2021-07-07 18:16 UTC, Morph1984 commented
You may want to format your commit title more succinctly, The explanation for your change goes into the commit description itself.

For your current change you may want to state the following:
Commit TItle:
audio_core: Preserve front channel volume after 6 to 2 downmix
Commit Description:
Many games report 6 channel output while only providing data for 2. We only output 2-channel audio regardless, and in the downmixing, front left/right only provide 36% of their volume. This is done assuming all of the other channels also contain valid data, but in many games they don't. This PR alters the downmixing to preserve front left/right, so volume is not lost.

This improves volume in Link's Awakening, New Super Mario Bros U, Disgaea 6, Super Kirby Clash.

2021-07-08 13:51 UTC, ogniK5377 commented on src/audio_core/sink_context.cpp
> +        };
Fair point, can be kept then. Just wanted to make sure 👍

2021-07-08 13:52 UTC, ogniK5377 approved these changes

2021-07-08 16:09 UTC, Morph1984 approved these changes

2021-07-08 16:09 UTC, merged