Handle allocation failure in Staging and Streaming Buffer
yuzu-emu/yuzu pull request #6740
Opened 2021-07-26 21:10 UTC by K0bin

The Yuzu Vulkan renderer refused to start at some point and the logs had the following error:

```
[   4.066235] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_OUT_OF_DEVICE_MEMORY
[   4.066441] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:50: Failed to initialize GPU: Vulkan initialization error VK_ERROR_OUT_OF_DEVICE_MEMORY
```

I unfortunately don't know how to reproduce the problem since it was working at first, but I think Yuzu should handle those cases regardless.

The crash is caused by the fact that Yuzu tries to allocate both the stream buffer and staging buffers in host visible VRAM. On my system (which doesn't support resizable BAR) that's just 256 MB.

This PR makes Yuzu fall back to regular system memory if the allocation fails. It fixes the issue on my system.

2021-07-26 21:27 UTC, v1993 reviewed
Just to be clear - I'm not sure this is the correct solution.

2021-07-26 21:27 UTC, v1993 commented on src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
> +    if (device_local) {
```suggestion
u32 FindMemoryTypeIndex(const VkPhysicalDeviceMemoryProperties& props, u32 type_mask, bool try_device_local) {
    if (try_device_local) {
```

Since it doesn't guarantee that it will be device local.

2021-07-26 21:27 UTC, v1993 commented on src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
> +    std::optional<u32> type = FindMemoryTypeIndex(props, type_mask, HOST_FLAGS);
Any specific reason for not just moving declaration out of if block?

2021-07-26 21:27 UTC, v1993 commented on src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
> +    // stream_memory = memory_allocator_.TryAllocMemory(STREAM_FLAGS, requirements.memoryTypeBits, requirements.size);
Leftover testing code.

2021-07-26 21:28 UTC, ReinUsesLisp commented on src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
> +    auto stream_memory_info = VkMemoryAllocateInfo{
```suggestion
    VkMemoryAllocateInfo stream_memory_info{
```

2021-07-26 21:32 UTC, K0bin commented
Updated the PR according to reviews.

2021-07-26 21:33 UTC, v1993 requested changes

2021-07-26 21:33 UTC, v1993 commented on src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
> +        FindMemoryTypeIndex(props, type_mask, STREAM_FLAGS);
```suggestion
        type = FindMemoryTypeIndex(props, type_mask, STREAM_FLAGS);
```

Simple typo.

2021-07-26 21:34 UTC, v1993 commented
Also, you haven't incorporated Rein's feedback, sayin' just in case.

2021-07-26 21:36 UTC, K0bin commented
> Also, you haven't incorporated Rein's feedback, sayin' just in case.

Ah, my bad. I thought he just wanted to replace the `auto` with the actual type.

2021-07-26 21:38 UTC, ReinUsesLisp approved these changes

2021-07-26 21:41 UTC, v1993 approved these changes

2021-07-26 23:34 UTC, merged

2021-08-01 07:25 UTC, goldenx86 commented
@K0bin Can I mention you in the next Progress Report?

2021-08-01 08:14 UTC, K0bin commented
@goldenx86 Sure, I'd be love to be mentioned.