GPU: Prequeue frame swaps.
yuzu-emu/yuzu pull request #6787
Opened 2021-07-31 15:50 UTC by FernandoS27

The idea of this change is to fix an issue that was phantom added since I introduced the fence manager. Originally frame swaps were sent exactly when the fence was met. However, now fence release is delayed until the host gpu catches up, this causes swaps to be delayed further than they should.

This commit aims to solve that issue by prequeuing frames. 

This solves the bad frame pacing on MHR.

2021-07-31 16:29 UTC, Morph1984 commented on src/core/hle/service/nvflinger/nvflinger.cpp
> +void NVFlinger::PrequeeFrame(u32 buffer_queue_id, u32 slot) {
```suggestion
void NVFlinger::PrequeueFrame(u32 buffer_queue_id, u32 slot) {
```

2021-07-31 16:29 UTC, Morph1984 commented on src/video_core/gpu.cpp
> +            LOG_ERROR(HW_GPU, "Unknown, work request");
May be worth logging the unknown request type if it occurs, also break for the default case
```suggestion
            LOG_ERROR(HW_GPU, "Unknown work request type={}", request.type);
            break;
```

2021-07-31 17:04 UTC, v1993 commented
This PR causes flickering with black in HW: DE, audio gets glitchy as well. Vulkan, GTX 1650 Super.

2021-07-31 17:36 UTC, FernandoS27 commented
> This PR causes flickering with black in HW: DE, audio gets glitchy as well. Vulkan, GTX 1650 Super.

I'll investigate.

2021-07-31 17:37 UTC, Morph1984 commented
We have another report, this time with Fire Emblem Three Houses

2021-07-31 23:29 UTC, FernandoS27 commented
All regressions should be fixed now.

2021-08-01 05:11 UTC, ameerj commented on src/video_core/gpu.cpp
> +        frame_queue_items.push_back(item);
For consistency with other queue pushes in this file.
```suggestion
        frame_queue_items.emplace_back(*framebuffer, new_queue_id);
```

2021-08-01 05:11 UTC, ameerj commented on src/video_core/gpu.cpp
> +            frame_triggers[fence.id].push_back(trigger);
```suggestion
            frame_triggers[fence.id].emplace_back(new_id, fence.value);
```

2021-08-01 05:11 UTC, ameerj commented on src/video_core/gpu.h
> +        }
```suggestion
            : fence{fence_}, type{RequestType::Flush}, flush{addr_, size_} {}
```

2021-08-01 05:11 UTC, ameerj commented on src/video_core/gpu.h
> +        u64 fence;
missing newline

2021-08-01 05:11 UTC, ameerj commented on src/video_core/gpu.cpp
> +    auto& list = frame_triggers[syncpoint_id];
Is this threadsafe?

2021-08-01 14:58 UTC, v1993 commented
This is still causing flickering in HW: DE, but of very different manner:

1. You must have "unlimited framerate" option on, which is experimental and does not work nice for this game (still, it's a regression introduced by this PR)
2. Only title screen video is flickering (with white this time), menus are fine
3. This doesn't happen on Vulkan, only on OpenGL

2021-08-01 16:08 UTC, FernandoS27 commented
> 1. unlimited framerate

That's a hack no matter what. It's not considered a regression if it does not affect normal behavior. Games can act very differently under a "disabled vsync" which is what that option does. There's no guarantees about it.

2021-08-01 16:14 UTC, v1993 commented
Ah, I see then. Is there any explanation why this happens on OpenGL but not on Vulkan? Lucky timing differences?

2021-08-03 08:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=6787) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu?pullRequest=6787) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yuzu-emu/yuzu?pullRequest=6787) it.</sub>

2021-08-18 21:29 UTC, codbugpatrol commented
For me, after this commit Dragon Fighter Z, which was crashing badly, now besides crash it also seems to jumping frames. 
This is really noticible using a special attack, like gohan's kamehameha. Really noticible that is losing frames.

2021-09-01 15:53 UTC, ameerj requested changes
This PR causes a deadlock when booting homebrew

2021-10-04 20:25 UTC, codbugpatrol commented
@FernandoS27 , any news on this PR ? Did you also noticed the crashes after a while in DBFZ ? To reproduce, enter in practice mode, enter the match and start using special attacks, it will launch device loss.
[ 133.107316] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:669: Device loss occured!

2021-10-05 09:34 UTC, v1993 commented
This PR is intended to be superseded by another one, at which point this one will be closed. Please don't report issues that happen without PR in its discussion.

2022-05-18 13:50 UTC, Timmy5942 commented
> > 1. unlimited framerate
> 
> That's a hack no matter what. It's not considered a regression if it does not affect normal behavior. Games can act very differently under a "disabled vsync" which is what that option does. There's no guarantees about it.
> 
> What this PR does, is make the host send swap commands exactly where the game asks to use a buffer on. In the case of HW:DE it does not respect fencing and sends swaps before the command list is done, expecting to have enough time before vSync kicks in. The old behavior worked because we over delayed the swaps, this new behavior fixes games on normal behavior as it does the swas where it should do them.

2022-05-18 13:54 UTC, Timmy5942 commented
> [FernandoS27](https://github.com/FernandoS27)@ I wonder why when the GPU is set on High it fixes this problem?
> 
> #7945 "Zelda link's awakening: bowWow not rendering"
> 
> but slows down depending on video card used....
> 
> Maybe some think like a medium high, What happens in the Source code when GPU High is Enabled?
> 
> Might be an interesting look, What code you guys come up with?, I don't mind trying a test in a Manual Mingw build!
> 
> EDIT: Issue seams to be around "use asynchronous GPU emulation" when disabled slow bowWow rendering fine, Enabled Not fine, Disabled + Normal GPU still fine

Only way to do it while on GPU High

If to change nvflinger.cpp

s64 NVFlinger::GetNextTicks() const {
    static constexpr s64 max_hertz = 120LL;

to

s64 NVFlinger::GetNextTicks() const {
    static constexpr s64 max_hertz = 240LL;

This will keep game game speed in GPU High as is it was set on Normal, Normally it slower on High

Just not FPS.....

2022-10-06 20:09 UTC, FernandoS27 commented
superseded by YFC

2022-10-06 20:09 UTC, closed without merging