Tas configure ui nits
yuzu-emu/yuzu pull request #7045
Opened 2021-09-19 01:43 UTC by behunin

Text looked cramped on my pc (Ubuntu 21.04). Re-flowed text as well for nicer read.

2021-09-19 13:49 UTC, v1993 requested changes

2021-09-19 13:49 UTC, v1993 commented on src/yuzu/configuration/configure_tas.ui
> +        <height>506</height>
Those are rather nonstandard values and will vary per font used. Please consider making it scrollable instead.

2021-09-21 04:34 UTC, lioncash commented
Can you post a pair of before/after screenshots so the visual changes can be seen?

2021-09-23 16:29 UTC, bunnei approved these changes

2021-09-23 16:29 UTC, merged