Fix memroy leak
yuzu-emu/yuzu pull request #7091
Opened 2021-09-25 15:05 UTC by vonchenplus

1. Fix KScopedAutoObject object leak when SendSyncRequest
2. Fix thread memory leak
3. Fix share memory object leak

2021-09-26 10:45 UTC, FernandoS27 commented
Let me know when it's ready for testing.

2021-09-26 10:49 UTC, vonchenplus commented
> Let me know when it's ready for testing.

it's ready for testing

2021-09-26 16:33 UTC, FernandoS27 commented
Which source are you using for this ? It seems inaccurate. Best is to use the main source:
https://github.com/Atmosphere-NX/Atmosphere/tree/master/libraries/libmesosphere

we try to keep everything as close as possible since mesosphere is Hardware tested.

2021-09-27 01:08 UTC, vonchenplus commented
My changes do not add any third-party libraries

2021-09-28 19:49 UTC, bunnei commented on src/core/hle/service/acc/async_context.cpp
> +    compeletion_event = Kernel::KEvent::Create(system_.Kernel());
This and all others should use `KernelHelpers::ServiceContext::CreateEvent`

2021-09-28 19:50 UTC, bunnei commented on src/core/hle/kernel/k_process.cpp
> +    // shared_memory_list.push_back(shmem);
Remove

2021-09-28 19:51 UTC, bunnei commented on src/core/hle/kernel/k_process.cpp
> +    /* Free all shared memory infos. */
Comment style is incorrect (see one ones above)

2021-09-28 19:52 UTC, bunnei commented on src/core/hle/service/acc/async_context.cpp
> +IAsyncContext::~IAsyncContext() {
Here and elsewhere below should use `KernelHelpers::ServiceContext::CloseEvent`

2021-09-28 19:56 UTC, bunnei requested changes
Looks mostly fine -- thank you for tracking down these leaks!

The main comment I have is to use KernelHelpers::ServiceManager helper code for managing events for the HLE services.

2021-09-28 20:03 UTC, Morph1984 commented
In addition to the comments above - please fixup the `Keep share memory as close` commit with the `Fix share memory object leak` commit

2021-09-29 03:54 UTC, Morph1984 commented
I've replaced all `KAutoObject::Create(event)` with `KernelHelpers::ServiceContext::CreateEvent` in #7103

2021-09-29 04:22 UTC, vonchenplus commented
OK, I revert the relevant changes.

2021-09-29 16:40 UTC, bunnei approved these changes

2021-10-04 04:08 UTC, ameerj approved these changes

2021-10-04 04:09 UTC, merged