Project Kraken: Input rewrite
yuzu-emu/yuzu pull request #7255
Opened 2021-10-31 03:19 UTC by german77

Project kraken is a full input rewrite that will open the path to many requested features while reducing issues related to input.

Please report any issue with the input because there isn't a single file that is untouched by this PR. This includes controller configuration, applets, controller support and in game actions. Many workarounds were removed since they aren't needed anymore as emulation is more accurate.

This PR doesn't bring many changes noticeable by users but the code is like the difference between day and night. As an example here is the amount of effort you need to read controller data:
```
    auto* controller = system.HIDCore().GetEmulatedController(Core::HID::NpadIdType::Player1);
    controller->Connect();
    const auto buttons = controller->GetNpadButtons();
    if (buttons.a || buttons.b) {
        // Do something
    }
    if (buttons.x || buttons.y) {
        // Do something
    }
```

TODO:
- [ ] Finish documenting the code
- [ ] Cleanup Core::HID
- [ ] Rewrite TAS Update method

### Goals:

- Separate input subsystem from other projects
- Make input drivers scalable
- Make input event-based
- Aim for more accurate behavior on emulation
- Access controller data with minimal effort
- Create an emulated controller instead of accessing drivers directly
- Remove redundant code
- Simplify code
- Document the input side to make easier for new developers to implement a new input driver
- Make my life easier later after suffering with kraken now
- Make users surrender to the kraken

### User changes:

- Fixed dual joycon changing to any after opening the config window again
- Faulty analogs will not trigger when mapping
- All controllers now share the same config parameters
- Controller battery is now visible for controllers that support it
- Pressing a button will reconnect the first player automatically
- GC controller now supports real analog triggers with buttons. No more faking input.

    
### Input changes
Input common should only provide raw input data and not alter the values in any way.
- **Input Engine:** Core of every input driver. Stores and handles input events
- **Input Poller:**  Parses config strings and pulls data from the input engine
- **Input Mapping:**  Receives any kind of input event and creates a config string
- **Helpers:**  Help translating inputs into something easier to manage. Like a joystick from 5 buttons.
- **Drivers:**  Contain specific code to interact with a real controller
- **Main:**  Registers drivers and acts as a middle man for providing data from controllers
- Only keyboard, mouse and touch drivers can be accessed directly to provide an easy way to register Qt or SDL GUI input

	
### UI changes:

- Removes specific controller data
- Removes access directly to drivers 
- All config data need to be requested to the emulated controller
- All changes are applied to the emulated controller

	
### Core changes:

**HID services**
```
- Removes access to input config
- Obtain data only from the emulated controller
- Use a LIFO buffer ring
- Removes some hardcoded values
- Fixes a few differences in the shared memory
```

**HID**
Emulated controller:
```
- Reads config data
- Receives all driver events through an input poller
- Ensure that all data is correct at all times
- Stores two kinds of data. One with extra info from the config, Another with only the needed data for services
- Stores and alters controller config
```

Emulated console:
```
Same as emulated controller but contains only console data like touch or console motion
```

Emulated devices
```
Same as emulated controller but contains data from external usb devices like mouse or keyboard
```

Input converter
```
- Transforms raw values into the desired input type
- Converts any input type into another type like an analog to button or button to motion
- Returns only valid input data
- Doesn't store any data
- Applies any special config parameter like
      - Scaling data
      - Inverting values
      - Clamping values
      - Adds an offset

```

**HID core**
Manages emulated controllers, provides simple data like connected controllers or supported controller types. Allows for easy access to controller data from any place of the project

2021-10-31 03:41 UTC, ameerj commented on src/common/settings.h
> -    std::atomic_bool is_device_reload_pending{true};
Now that this is removed, we can remove the `<atomic>` header include from this file.

2021-10-31 03:41 UTC, german77 commented on src/common/settings.h
> -    std::atomic_bool is_device_reload_pending{true};
Should I remove it on this PR, or it needs other changes?

2021-10-31 03:44 UTC, ameerj commented on src/common/settings.h
> -    std::atomic_bool is_device_reload_pending{true};
You can remove it here. it _may_ require including the atomic header on other files that implicitly were including it because of including `settings.h`, but it should be fine addressing that in this PR.

2021-10-31 04:02 UTC, lioncash commented on src/input_common/drivers/touch_screen.h
> +        .guid = Common::UUID{""},
Please use `Common::UUID{Common::INVALID_UUID}` instead. This can be constructed at compile-time unlike the string overload. Ditto for other occurrences

2021-10-31 04:16 UTC, lioncash commented on src/core/hle/service/hid/ring_lifo.h
> +    std::size_t GetPreviuousEntryIndex() const {
```suggestion
    std::size_t GetPreviousEntryIndex() const {
```

2021-10-31 04:21 UTC, lioncash commented on src/input_common/drivers/mouse.cpp
> +    return "Bad Mouse";
I'd avoid putting UI name functions in parts of the codebase that aren't the frontend. These cannot be localized now. Ditto for other locations where similar UI functions exist

2021-11-01 20:51 UTC, lat9nq commented on src/core/hid/hid_core.h
> +#include "core\hid\hid_types.h"
```suggestion
#include "core/hid/hid_types.h"
```

2021-11-02 03:13 UTC, Morph1984 commented on src/core/hid/motion_input.h
> +    // Number of invalid secuential data
sequential

2021-11-06 02:14 UTC, german77 commented on src/input_common/drivers/tas_input.cpp
> +Tas::Tas(const std::string input_engine_) : InputCommon::InputEngine(input_engine_) {
I initialize the driver with the "driver name" and it's stored on the input engine class.  It's there a better method? The string can't be modified once the driver is created.

2021-11-06 02:32 UTC, lioncash commented
Just a bump to mention that https://github.com/yuzu-emu/yuzu/pull/7255#discussion_r739755278 still applies (since it's sandwiched between two outdated comments)

2021-11-06 02:33 UTC, lioncash commented on src/input_common/drivers/tas_input.cpp
> +Tas::Tas(const std::string input_engine_) : InputCommon::InputEngine(input_engine_) {
What I was asking was if you intended to pass the string by const reference instead of const by value

2021-11-06 05:08 UTC, german77 commented
I'm aware of it. Just too lazy to address it right now. I will probably do it this weekend

2021-11-09 16:23 UTC, liberodark commented
Stangely axis is inverted for left & right stick up/down is now down/up

2021-11-09 16:33 UTC, german77 commented
> Stangely axis is inverted for left & right stick up/down is now down/up but left/right is ok on sticks. Unfortunately yuzu won't let us change this during setup.

I'm aware of this issue and looking for a solution. You can right click any axis and invert them.

2021-11-10 07:03 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> +    // inverted?
I've checked this long ago, the order is correct

2021-11-10 07:03 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> +    // this is extra?
Yes, it likely is extra, so it can be removed (not sure why it was added here)

2021-11-10 07:28 UTC, Morph1984 commented on src/core/hid/hid_types.h
> +    Joycon_right = 1U << 4,
JoyDual, JoyLeft, JoyRight, etc like how it's formatted in switchbrew?

2021-11-10 07:31 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> -
?

2021-11-10 07:31 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> +    const auto applet_resource_user_id{rp.Pop<u64>()};
check this

2021-11-10 07:31 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> +    const auto applet_resource_user_id{rp.Pop<u64>()};
and this

2021-11-10 07:31 UTC, Morph1984 commented on src/core/hle/service/hid/hid.cpp
> +    const auto applet_resource_user_id{rp.Pop<u64>()};
and this

2021-11-14 05:41 UTC, Morph1984 commented on src/input_common/drivers/keyboard.cpp
> +        // Use the moddifier to press the key button equivalent
modifer

2021-11-15 02:30 UTC, lioncash commented on src/core/hid/hid_core.h
> +    const std::size_t available_controllers{10};
This still applies

2021-11-15 02:34 UTC, lioncash commented on src/core/hle/service/hid/ring_lifo.h
> +#include "common/swap.h"
This include doesn't seem to be needed anymore

2021-11-15 02:50 UTC, lioncash requested changes
Left some comments about the modifier handling

2021-11-15 02:50 UTC, lioncash commented on src/core/hle/service/hid/ring_lifo.h
> +        return (buffer_tail + total_buffer_count - 1) % total_buffer_count;
```suggestion
        return static_cast<size_t>((buffer_tail + total_buffer_count - 1) % total_buffer_count);
```

Otherwise this results in a sign conversion

2021-11-15 02:50 UTC, lioncash commented on src/core/hle/service/hid/ring_lifo.h
> +    s64 total_buffer_count = max_buffer_size;
```suggestion
    s64 total_buffer_count = static_cast<s64>(max_buffer_size);
```

2021-11-15 02:50 UTC, lioncash commented on src/core/hle/service/hid/ring_lifo.h
> +        return (buffer_tail + 1) % total_buffer_count;
```suggestion
        return static_cast<size_t>((buffer_tail + 1) % total_buffer_count);
```

2021-11-15 02:50 UTC, lioncash commented on src/input_common/drivers/gc_adapter.cpp
> +        break;
the breaks can be removed since a return precedes them

2021-11-15 02:50 UTC, lioncash commented on src/input_common/drivers/gc_adapter.cpp
> +        return "Unkown GC";
```suggestion
        return "Unknown GC";
```

2021-11-15 02:50 UTC, lioncash commented on src/yuzu/bootmanager.cpp
> +    int moddifier = 0;
```suggestion
    int modifier = 0;
```

2021-11-15 02:50 UTC, lioncash commented on src/yuzu/bootmanager.cpp
> +int GRenderWindow::QtModifierToSwitchModdifier(quint32 qt_moddifiers) {
```suggestion
int GRenderWindow::QtModifierToSwitchModdifier(quint32 qt_modifiers) {
```

2021-11-15 02:50 UTC, lioncash commented on src/yuzu/bootmanager.cpp
> +        const auto moddifier = QtModifierToSwitchModdifier(event->nativeModifiers());
```suggestion
        const auto modifier = QtModifierToSwitchModdifier(event->nativeModifiers());
```

Is there a reason you're using `nativeModifiers()` instead of `modifiers()`, [QGuiApplication::queryKeyboardModifiers()](https://doc.qt.io/qt-5/qguiapplication.html#queryKeyboardModifiers)? The former is going to return system-specific values so `nativeModifiers()` can't be reliably used for supporting platforms in a cross-platform manner. The latter (as well as `modifiers()` also has an [enum](https://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum)

2021-11-15 02:50 UTC, lioncash commented on src/yuzu/bootmanager.cpp
> +        const auto moddifier = QtModifierToSwitchModdifier(event->nativeModifiers());
```suggestion
        const auto modifier = QtModifierToSwitchModdifier(event->nativeModifiers());
```

2021-11-15 03:41 UTC, german77 commented on src/yuzu/bootmanager.cpp
> +        const auto moddifier = QtModifierToSwitchModdifier(event->nativeModifiers());
`modifiers()` doesn't specify if the key pressed was the left one or the right one. This is the same story for 
`nativeVirtualKey()` as Qt literally hides any key on the numpad.

It's not a big deal to use `modifiers()` we just lose accuracy on the keyboard emulation but nothing game breaking.

2021-11-15 03:44 UTC, german77 commented on src/yuzu/bootmanager.cpp
> +        const auto moddifier = QtModifierToSwitchModdifier(event->nativeModifiers());
Let me know if I should replace it.

2021-11-15 04:10 UTC, lioncash commented on src/yuzu/bootmanager.cpp
> +        const auto moddifier = QtModifierToSwitchModdifier(event->nativeModifiers());
It's probably preferable to replace it for the time being. I wouldn't be surprised if some OSes (let alone different input methods on Linux alone) have different native modifier codes

2021-11-19 00:34 UTC, heinermann commented on src/input_common/drivers/gc_adapter.cpp
> +GCAdapter::GCAdapter(const std::string input_engine_) : InputEngine(input_engine_) {
```suggestion
GCAdapter::GCAdapter(const std::string& input_engine_) : InputEngine(input_engine_) {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/drivers/mouse.cpp
> +Mouse::Mouse(const std::string input_engine_) : InputEngine(input_engine_) {
```suggestion
Mouse::Mouse(const std::string& input_engine_) : InputEngine(input_engine_) {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/drivers/sdl_driver.cpp
> +u8 SDLDriver::GetHatButtonId(const std::string direction_name) const {
```suggestion
u8 SDLDriver::GetHatButtonId(const std::string& direction_name) const {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/drivers/tas_input.cpp
> +Tas::Tas(const std::string input_engine_) : InputCommon::InputEngine(input_engine_) {
```suggestion
Tas::Tas(const std::string& input_engine_) : InputCommon::InputEngine(input_engine_) {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/drivers/touch_screen.cpp
> +TouchScreen::TouchScreen(const std::string input_engine_) : InputEngine(input_engine_) {
```suggestion
TouchScreen::TouchScreen(const std::string& input_engine_) : InputEngine(input_engine_) {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/drivers/udp_client.cpp
> +const Common::UUID UDPClient::GetHostUUID(const std::string host) const {
```suggestion
const Common::UUID UDPClient::GetHostUUID(const std::string& host) const {
```

2021-11-19 00:49 UTC, heinermann commented on src/input_common/input_engine.h
> +    virtual u8 GetHatButtonId([[maybe_unused]] const std::string direction_name) const {
```suggestion
    virtual u8 GetHatButtonId([[maybe_unused]] const std::string& direction_name) const {
```

2021-11-19 08:43 UTC, benderscruffy commented
just wondering how this could be implemented ????
in the game Anthill you need to pinch the screen with two fingers to zoom 
![010054c00d842000_2021-11-19_16-34-57-754](https://user-images.githubusercontent.com/2696404/142592557-a06ad5b1-2b36-46ee-94ad-2cc52042ccab.png)

2021-11-19 14:20 UTC, german77 commented
> just wondering how this could be implemented ???? in the game Anthill you need to pinch the screen with two fingers to zoom ![010054c00d842000_2021-11-19_16-34-57-754](https://user-images.githubusercontent.com/2696404/142592557-a06ad5b1-2b36-46ee-94ad-2cc52042ccab.png)

Yuzu supports multitouch for a long time. Please test it if you can or provide a save file

2021-11-19 16:24 UTC, german77 commented
Just tested. Touch is fully working on that game. On real touch screens. Via UDP or with mouse and keyboard

2021-11-20 14:01 UTC, EddyHg80 commented
Hi, since this is changing pretty much everything input-wise, have you considered to add the ability to map hotkeys to a controller input?
Might be handy for toggling speed limit on the go or pause emulation.

P.S: Thank you for your hard work on the emulator, I always loved your inut and controllers related updates.

2021-11-20 14:08 UTC, german77 commented
I already got controller hotkeys working. But I'm going to open a PR after this is merged. It's not the goal of kraken to add features

2021-11-20 14:10 UTC, EddyHg80 commented
> I already got controller hotkeys working. But I'm going to open a PR after this is merged. It's not the goal of kraken to add features

This is great news! Thank you!

2021-11-27 03:25 UTC, bunnei approved these changes

2021-11-27 10:51 UTC, FernandoS27 approved these changes

2021-11-27 10:52 UTC, merged

2021-11-27 12:34 UTC, benderscruffy commented
Bombslinger [010087300445a000]
gets to the title screen and say press any button to start
doesn't detect any buttons on the controller or keyboard

2021-11-27 15:08 UTC, german77 commented
Nice timing. I will check it out.

2021-11-28 01:47 UTC, varlesh commented
After this PR (830 release) on Linux Yuzu run as `yuzu:input:SDL` and impossible kill PID, also `killall -9 yuzu` not worked too -process not found.

2021-11-28 02:58 UTC, german77 commented
@benderscruffy Could you make an issue with this game. Seems like it's another issue unrelated to kraken that it's not easy to fix

@varlesh What distro and controller are you using? Are you compiling from source or using the AppImage or Flatpak

2021-11-28 03:26 UTC, varlesh commented
@german77 It's not flatpak or appimage, i'm use standalone version:
https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-830/yuzu-linux-20211127-c6ce901ae.tar.xz
Distro KDE Neon (Ubuntu 20.04), i think it's does not matter.
![image](https://user-images.githubusercontent.com/8083855/143727673-35c82559-4be1-4acb-8a59-f6513228d0b4.png)

2021-11-28 03:30 UTC, varlesh commented
827-release not have this problem and  run as `yuzu` process name and can be killed as PID or `killall yuzu`

2021-11-28 06:33 UTC, german77 commented
I will test tomorrow. To clarify things a bit the process you are trying to kill its not the main one. It's just a thread of the input side. I must have done something silly but first I need to reproduce the issue.

2021-11-30 02:47 UTC, benderscruffy commented
Dead Z Meat [0100A24011F52000]
cannot move the crosshair no matter what controller i choose

2021-11-30 03:03 UTC, german77 commented
@varlesh fixed in #7476

2021-11-30 03:36 UTC, german77 commented
> Dead Z Meat
This game uses motion to move the crosshair. Only single joycons work
![image](https://user-images.githubusercontent.com/5944268/143981325-b9a566e6-5eae-48cb-83e3-2c452a353d5c.png)

2021-11-30 03:42 UTC, benderscruffy commented
I did set it to single joy cons but using my gameshark controller wouldn't move the crosshair ???
Weird

2021-11-30 03:48 UTC, german77 commented
Yes. The crosshair only works with motion

2021-11-30 03:50 UTC, benderscruffy commented
ok thanks

2021-11-30 04:06 UTC, benderscruffy commented
can you check another game please
Spinnys Journey [01001E40136FE000]
stuck on the title screen 
doesn't detect any inputs

2021-11-30 04:12 UTC, benderscruffy commented
Flip Wars - 010095A004040000
![Screenshot 2021-11-30 121252](https://user-images.githubusercontent.com/2696404/143984493-89e3dc0a-5fe1-4798-8a78-e738d67c9776.png)

2021-11-30 05:25 UTC, german77 commented
I bought too many games today. give me a break :P

2021-11-30 05:48 UTC, benderscruffy commented
ok sorry

2021-11-30 16:20 UTC, german77 commented
Flip wars is interesting I managed to get in game by connecting another controller type every time this error appears. Seems like it configures the controllers all the time and forgets what controller was connected so it needs a constant reminder. I will make a HW to test if we do the same thing as the switch