core: Fix crash when exit app
yuzu-emu/yuzu pull request #7341
Opened 2021-11-15 14:44 UTC by vonchenplus

When a kernel object construct, it is registered into the KernelCore and unregistered after destruct.

A KThread kernel object is generated for each thread by GetHostDummyThread, and saved by thread local, including the main thread.

So when the main thread exits, the KThread object will be destructured, but by this time, the KernelCore object no longer exists and will cause a crash every time it exits.

The current solution is to save the registration information globally.

2021-11-15 16:09 UTC, lioncash requested changes
We've worked extremely hard over several years to remove global state from core. Please don't reintroduce it.

2021-11-15 19:46 UTC, bunnei commented
Thanks for tracking down the problem, but +1 with what Lioncash said -- we cannot be moving this state into globals. Can you find a better way to fix this? Thank you!

2021-11-16 11:24 UTC, v1993 commented on src/core/hle/kernel/kernel.cpp
> -} // namespace Kernel
Unrelated changle

2021-11-21 07:59 UTC, bunnei commented
@vonchenplus Thank you for tracking down the issue and providing a valid fix. After discussion with the team, we think the solution with #7359 is better, because it fixes the issue in the emulator core, instead of the Qt frontend (note -- SDL, and possibly other future frontends might have this problem).

2021-11-21 07:59 UTC, closed without merging