Core: Remake Core Timing
yuzu-emu/yuzu pull request #7454
Opened 2021-11-28 10:00 UTC by FernandoS27

This remakes core timing making it use more threads to improve it's accuracy while sacrificing ordering.

2021-11-28 11:37 UTC, v1993 requested changes

2021-11-28 11:37 UTC, v1993 commented on src/common/thread.cpp
> +        new_priority != ThreadPriority::Critical ? SCHED_OTHER : SCHED_FIFO;
1. You set `SCHED_FIFO` for non-critical threads and `SCHED_OTHER` for critical ones. Shouldn't it be the other way around?
2. `SCHED_FIFO` can't be used by normal users, this requires either root rights or `cap_sys_nice` capability . Consider logging errors from `pthread_setschedparam` call.

2021-11-28 11:55 UTC, Oschowa commented on src/common/thread.cpp
> +        new_priority != ThreadPriority::Critical ? SCHED_OTHER : SCHED_FIFO;
There are ways to configure a linux system to allow normal user processes to gain RT priority with SCHED_FIFO or SCHED_RR, e.g. Arch Linux has a package that makes it easy to do: https://wiki.archlinux.org/title/Realtime_process_management#Configuration  
  
However, according to the sched(7) [man page](https://man7.org/linux/man-pages/man7/sched.7.html):  
```
For threads scheduled under one of the normal scheduling policies
(SCHED_OTHER, SCHED_IDLE, SCHED_BATCH), sched_priority is not
used in scheduling decisions (it must be specified as 0).

Processes scheduled under one of the real-time policies
(SCHED_FIFO, SCHED_RR) have a sched_priority value in the range 1
(low) to 99 (high).
```
  
So trying to set any priority for SCHED_OTHER doesn't make sense. It could potentially fallback to setting a negative nice value for high but not critical priority if that seems important, but lowering nice values also requires a non-standard setup on the users part..

2021-11-28 11:57 UTC, FernandoS27 commented on src/common/thread.cpp
> +        new_priority != ThreadPriority::Critical ? SCHED_OTHER : SCHED_FIFO;
> 

1. the other way around. Normals are OTHER, Criticals are FIFO:
2. oh I didn't know that.

2021-11-28 12:13 UTC, Oschowa commented on src/common/thread.cpp
> +        new_priority != ThreadPriority::Critical ? SCHED_OTHER : SCHED_FIFO;
There is also https://github.com/heftig/rtkit fwiw which can be used by audio daemon's like pulseaudio and pipewire to gain realtime prio on systems where it's not available to user processes otherwise, but i'm not sure how much of a mess it would be to integrate.

2021-11-28 13:39 UTC, v1993 commented
This is currently causing build errors, namely

```
/usr/bin/ld: /tmp/ccu6Dgor.ltrans15.ltrans.o: in function `std::_MakeUniq<Core::System>::__single_object std::make_unique<Core::System>()':
<artificial>:(.text+0xe970): undefined reference to `__atomic_store_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::Pause(bool)':
<artificial>:(.text+0x640a): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x6452): undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::GetTimeMS()':
<artificial>:(.text+0x64bc): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x6528): undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::GetTimeNS()':
<artificial>:(.text+0x65ac): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x6618): undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::GetTimeUS()':
<artificial>:(.text+0x669c): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x6708): undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::GetClockCycles()':
<artificial>:(.text+0x678c): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x67f8): undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: /tmp/ccu6Dgor.ltrans111.ltrans.o: in function `Common::X64::NativeClock::GetCPUCycles()':
<artificial>:(.text+0x687c): undefined reference to `__atomic_load_16'
/usr/bin/ld: <artificial>:(.text+0x68e8): undefined reference to `__atomic_compare_exchange_16'
```

It seems that yuzu must link to `libatomic` to fix this.

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +            std::unique_lock<std::mutex> lk(event_type->guard);
```suggestion
            std::unique_lock lk(event_type->guard);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +                    std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
                    std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +                std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
                std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +        std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
        std::unique_lock main_lock(event_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/tests/core/core_timing.cpp
> +    std::unique_lock<std::mutex> lk(control_mutex);
```suggestion
    std::unique_lock lk(control_mutex);
```

2021-11-28 22:47 UTC, lioncash commented on src/core/core_timing.cpp
> +        std::unique_lock<std::mutex> main_lock(event_mutex);
```suggestion
        std::unique_lock main_lock(event_mutex);
```

2021-11-29 02:04 UTC, bunnei commented
Temporarily untagging because there are reports of regressions on 4C with regards to performance. @german77 believes it is this PR, not #7462. It will also be easier to separate any regressions if we leave the kernel PR tagged for alone for a little bit.

2022-06-28 20:45 UTC, Morph1984 commented on src/common/x64/native_clock.cpp
>      /// The clock cannot be more precise than the guest timer, remove the lower bits
Remove the comment since the inaccuracy mask was removed

2022-06-28 21:04 UTC, liamwhite requested changes

2022-06-28 21:04 UTC, liamwhite commented on src/core/core_timing.cpp
> +        std::unique_lock main_lock(event_mutex);
Is locking the mutex necessary here?

2022-06-28 21:04 UTC, liamwhite commented on src/core/core_timing.cpp
> +        if (pause_count == worker_threads.size()) {
Reimplementation of a barrier

2022-06-28 21:04 UTC, liamwhite commented on src/core/core_timing.cpp
> +        pause_count--;
Same here

2022-06-28 21:13 UTC, liamwhite commented on src/core/core_timing.cpp
> +        worker_threads.emplace_back(ThreadEntry, std::ref(*this));
Also, can we measure the benefit of having more than 4 HostTiming threads in the first place? Especially on manycore systems this is going to potentially cause a lot of contention.

2022-06-28 23:17 UTC, FernandoS27 commented on src/core/core_timing.cpp
> +        if (pause_count == worker_threads.size()) {
unlike std barrier, I need to be able to cancel a wait on it.

2022-06-28 23:18 UTC, FernandoS27 commented on src/core/core_timing.cpp
> +        pause_count--;
ditto.

2022-06-28 23:19 UTC, FernandoS27 commented on src/core/core_timing.cpp
> +    if (is_paused_ == paused_state.load(std::memory_order_relaxed)) {
yes as it's read unprotected somewhere else. that's why the order is relaxed anywhere within a critical section but acquire when reading outside a critical section.

2022-06-28 23:31 UTC, FernandoS27 commented on src/core/core_timing.cpp
> +        worker_threads.emplace_back(ThreadEntry, std::ref(*this));
> Also, can we measure the benefit of having more than 4 HostTiming threads in the first place? Especially on manycore systems this is going to potentially cause a lot of contention.

currently, it only allows up to 2. It does improve the numbers from the tests as each thread as a quantum in the scheduler, when ones quantum is gone, the other takes in and uses its quantum.

2022-06-28 23:34 UTC, liamwhite approved these changes

2022-06-30 10:38 UTC, merged