Input_common: Implement custom joycon driver
yuzu-emu/yuzu pull request #7486
Opened 2021-12-01 21:03 UTC by german77

Supersedes #4411. This is the forth attempt to get this thing working. This time I'm using the SDL_hidapi driver to connect to the joycons, so far has zero issues.

TODO:
- [ ] Ensure everything is handled correctly
- [ ] Add a setting to enable old SDL joycon driver
- [ ] Cleanup

Features:
- Buttons
- Joysticks
- Motion
- HD rumble
- Custom led number

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.h
> +    bool CheckDeviceAccess(std::size_t port, SDL_hid_device_info* device);
This should be moved into the cpp file, so that the SDL type doesn't need to be exposed

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.h
> +static constexpr u32 max_resp_size = 49;
Static isn't necessary here or on the line below

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.cpp
> +void SendData(JoyconHandle& joycon_handle, std::vector<u8> buffer, std::size_t size) {
```suggestion
void SendData(JoyconHandle& joycon_handle, std::span<const u8> buffer, std::size_t size) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.cpp
> +    std::vector<u8> buffer;
This can be joined with the declaration below

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.cpp
> +    for (std::size_t i = 0; i < 15; ++i) {
```suggestion
    for (std::size_t i = 0; i < serial_number.size(); ++i) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.cpp
> +    std::vector<u8> buffer;
This can be joined with the assignment below

2021-12-01 21:23 UTC, lioncash commented on src/input_common/helpers/joycon_protocol.cpp
> +std::vector<u8> SendSubCommand(JoyconHandle& joycon_handle, SubCommand sc, std::vector<u8> buffer,
```suggestion
std::vector<u8> SendSubCommand(JoyconHandle& joycon_handle, SubCommand sc, std::span<const u8> buffer,
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +    for (u8 port = 0; port < joycon_data.size(); ++port) {
```suggestion
    for (size_t port = 0; port < joycon_data.size(); ++port) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +s16 Joycons::GetRawIMUValues(std::size_t sensor, size_t axis, const std::vector<u8>& buffer) const {
```suggestion
s16 Joycons::GetRawIMUValues(std::size_t sensor, size_t axis, std::span<const u8> buffer) const {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +void Joycons::UpdateProPadInput(JoyconData& jc, const std::vector<u8>& buffer) {
```suggestion
void Joycons::UpdateProPadInput(JoyconData& jc, std::span<const u8> buffer) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +void Joycons::UpdateRightPadInput(JoyconData& jc, const std::vector<u8>& buffer) {
```suggestion
void Joycons::UpdateRightPadInput(JoyconData& jc, std::span<const u8> buffer) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +void Joycons::UpdateLeftPadInput(JoyconData& jc, const std::vector<u8>& buffer) {
```suggestion
void Joycons::UpdateLeftPadInput(JoyconData& jc, std::span<const u8> buffer) {
```

2021-12-01 21:23 UTC, lioncash commented on src/input_common/drivers/joycon.cpp
> +void Joycons::UpdateJoyconData(JoyconData& jc, std::vector<u8> buffer) {
```suggestion
void Joycons::UpdateJoyconData(JoyconData& jc, std::span<const u8> buffer) {
```

2021-12-28 12:02 UTC, v1993 requested changes
I'll give it a further look once it at least builds :stuck_out_tongue:.

2021-12-28 12:02 UTC, v1993 commented on src/input_common/helpers/joycon_protocol.cpp
> +            SDL_hid_read_timeout(joycon_handle.handle, buffer.data(), max_resp_size, timeout_time);
```suggestion
            SDL_hid_read_timeout(joycon_handle.handle, buffer.data(), max_resp_size, timeout_mili);
```

I'm sorry, but do you actually verify that it builds before pushing?

2021-12-28 12:35 UTC, v1993 commented
Build issues aside:

1. Selecting joycon in dropdown menu does not automatically assign motion to it. Motion also does not load from profile if saved (in certain cases only, it seems? may be an unrelated issue).
2. Looks like user calibration is not used, only factory one is read.
3. I'm not sure what happens, but connecting two joycons results in them going full disco with player leds.
4. For left joy-con: capture button is not mapped (not that it matters), default mappings for SL/SR are incorrect.
5. For right joy-con: SR mapping is incorrect.

2022-11-20 23:34 UTC, closed without merging