input/SDL: Update SDL hints
yuzu-emu/yuzu pull request #7577
Opened 2021-12-13 20:23 UTC by v1993

`SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED` is no longer needed thanks to new default in SDL 2.0.18.

`SDL_HINT_JOYSTICK_HIDAPI_XBOX` is reported to cause conflicts with native driver Xbox driver on Linux, and Xbox controllers don't benefit from hidapi anyways.

2021-12-13 21:19 UTC, german77 commented
HIDAPI is enabled by default for xbox on linux? This is a weird choice from SDL.

2021-12-13 21:29 UTC, luziferius commented
Came here from the discussion on the discord server.

Reason behind this PR: When compiling yuzu with SDL from externals, it crashes the `xpad` driver used on Linux for XBox 360 controllers. This does not happen when using the packaged libsdl2 2.0.18 from Debian Sid (by using the build option `-DYUZU_USE_EXTERNAL_SDL2=OFF`.)

Symptoms: 

- The system log contains `xpad 1-14:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -2`
- Related device files in `/dev/input` disappear. Afterwards, all applications including yuzu completely lose access to the game pad. Only way to get it back to working is to physically plug it out and in again.


Results when applying this patch:

Yuzu can still access the game pad. All other symptoms remain.


Also, plugging the controller out while yuzu runs, still crashes yuzu. Here’s a backtrace from a debug build of [24c4d24cdeb9be6f0b4b5d7c2ec16bba35e28ec1]:
```
(gdb) bt 
#0  0x00007ffff4c3035b in __pthread_clockjoin_ex (threadid=18446744072795170368, thread_return=0x0, clockid=0, abstime=0x0, block=true) at pthread_join_common.c:43
#1  0x0000555556442ff0 in SDL_SYS_WaitThread (thread=0x5555583114c0) at yuzu/externals/SDL/src/thread/pthread/SDL_systhread.c:300
#2  0x000055555630cca2 in SDL_WaitThread_REAL (thread=0x5555583114c0, status=0x7fffc9ffa440) at yuzu/externals/SDL/src/thread/SDL_thread.c:433
#3  0x000055555643d743 in LIBUSB_hid_close (dev=0x555558598500) at yuzu/externals/SDL/src/hidapi/libusb/hid.c:1451
#4  0x000055555643eb88 in hid_close (device=0x55555834b800) at yuzu/externals/SDL/src/hidapi/SDL_hidapi.c:925
#5  0x00005555564eda53 in HIDAPI_DriverXbox360_CloseJoystick (device=0x5555582864e0, joystick=0x55555834b310) at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c:321
#6  0x0000555556439c4d in HIDAPI_JoystickClose (joystick=0x55555834b310) at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1459
#7  0x00005555564388f8 in HIDAPI_JoystickDisconnected (device=0x5555582864e0, joystickID=0) at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:831
#8  0x00005555564ed9f1 in HIDAPI_DriverXbox360_UpdateDevice (device=0x5555582864e0) at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c:310
#9  0x0000555556439553 in HIDAPI_UpdateDevices () at yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:1229
#10 0x0000555556420728 in SDL_JoystickUpdate_REAL () at yuzu/externals/SDL/src/joystick/SDL_joystick.c:1544
#11 0x00005555562f3073 in SDL_PumpEvents_REAL () at yuzu/externals/SDL/src/events/SDL_events.c:766
#12 0x00005555562e6165 in SDL_PumpEvents () at yuzu/externals/SDL/src/dynapi/SDL_dynapi_procs.h:147
#13 0x000055555601cc03 in operator()() const (__closure=0x55555823c798) at yuzu/src/input_common/drivers/sdl_driver.cpp:427
#14 0x000055555602385c in std::__invoke_impl<void, InputCommon::SDLDriver::SDLDriver(const string&)::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#15 0x000055555602381f in std::__invoke<InputCommon::SDLDriver::SDLDriver(const string&)::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:96
#16 0x00005555560237cc in std::thread::_Invoker<std::tuple<InputCommon::SDLDriver::SDLDriver(const string&)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55555823c798)
    at /usr/include/c++/11/bits/std_thread.h:253
#17 0x00005555560237a0 in std::thread::_Invoker<std::tuple<InputCommon::SDLDriver::SDLDriver(const string&)::<lambda()> > >::operator()(void) (this=0x55555823c798)
    at /usr/include/c++/11/bits/std_thread.h:260
#18 0x0000555556023784 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<InputCommon::SDLDriver::SDLDriver(const string&)::<lambda()> > > >::_M_run(void) (this=0x55555823c790)
    at /usr/include/c++/11/bits/std_thread.h:211
#19 0x00007ffff4f96694 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007ffff4c2e927 in start_thread (arg=<optimized out>) at pthread_create.c:435
#21 0x00007ffff4cbe9e4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

2021-12-13 21:37 UTC, v1993 commented
> HIDAPI is enabled by default for xbox on linux? This is a weird choice from SDL.

See https://github.com/libsdl-org/SDL/blob/main/include/SDL_hints.h. The default is to use HIDAPI for everything if it's built. Fox Xbox controller, HIDAPI driver is off by default on Windows due to "full native" support with XInput, but it defaults to value of SDL_HINT_JOYSTICK_HIDAPI on other OSes.

As a matter of fact - it's actually off by default on Linux because HIDAPI drivers aren't built here, but since yuzu forces HIDAPI on (for motion for supported controllers), Xbox HIDAPI driver also ends up being turned on.

2021-12-14 00:07 UTC, german77 approved these changes

2021-12-14 00:12 UTC, german77 requested changes

2021-12-14 00:12 UTC, german77 commented on src/input_common/drivers/sdl_driver.cpp
> +    SDL_SetHint("SDL_HINT_JOYSTICK_HIDAPI_XBOX", "0");
You probably meant this or "SDL_JOYSTICK_HIDAPI_XBOX". The other text equivalent does nothing
```suggestion
    SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_XBOX, "0");
```

2021-12-14 10:36 UTC, luziferius commented on src/input_common/drivers/sdl_driver.cpp
> +    // Disable hidapi driver for xbox. Already deafault on Windows, this causes conflict with native
A typo in “default”?

2021-12-14 10:42 UTC, luziferius commented on src/input_common/drivers/sdl_driver.cpp
> +    SDL_SetHint("SDL_HINT_JOYSTICK_HIDAPI_XBOX", "0");
Can confirm that the proposed change actually fixes the issue. The `xpad` driver no longer dies when launching yuzu with this applied.

2021-12-14 16:12 UTC, german77 approved these changes

2021-12-14 16:12 UTC, merged