shaders: Add fixes for NVIDIA drivers 495+
yuzu-emu/yuzu pull request #7629
Opened 2021-12-25 01:25 UTC by ameerj

After running the new driver through our suite of [unit tests](https://github.com/ReinUsesLisp/nxgpucatch), The two main issues encountered by the newer NVIDIA drivers are negation of floating point values, and bitwise conversions of input attributes. This PR addresses both.

When negating floating point values, prior drivers allowed the following usage:
```glsl
float f1 = 42.0f;
float f2 = -f1;    // f2 equals -42.0f
```
However, the new drivers ignored negation in these cases. The work around is to simply subtract the value from `0.0` to achieve the same result.

The bitwise conversion bug was more subtle. Due to the `GetAttribute` OpCode's return value being an F32, integer attribute values are bitwise converted to F32's, which are then converted back to U32 values when they are being used, resulting in the following pattern:
```glsl
float f1 = intBitsToFloat(gl_VertexID);
uint instance_id = floatBitsToUint(f1);
```

On the new drivers, `instance_id` was always 0 for the integer shader inputs as tested in GLSL. The fix for this was to simply collapse the attribute retrieval to simply be `uint instance_id = uint(gl_VertexID);`. 

These issues mainly affected the GLSL backend, but the bitwise conversion fix has been added as an optimization pass within the IR and is applied to all backends as a result.

Please test the new driver thoroughly and report any more regressions with reproduction steps on all backends.

2021-12-25 09:03 UTC, Tatsh commented
I'll be trying this out later today.

2021-12-25 10:01 UTC, gidoly commented
<img width="1040" alt="yuzu_kiyCIemeGk" src="https://user-images.githubusercontent.com/66776795/147382686-b77ec365-cccc-4727-9a3d-353066aa124f.png">
aoc loading screen renders dark atm with last driver

2021-12-25 10:05 UTC, gidoly commented
https://user-images.githubusercontent.com/66776795/147382746-eb6e9d30-b7ef-45a7-b93d-b1b833fa2028.mp4

broken filter on astralchin it looks blocky atm

2021-12-25 10:10 UTC, gidoly commented
glsl
 botw icon broken on pouch screen
<img width="346" alt="yuzu_Z3lGLIvvKI" src="https://user-images.githubusercontent.com/66776795/147382808-cea118e8-56bc-4d57-b0d0-a95b8f198bbb.png">

2021-12-25 10:12 UTC, gidoly commented
glsl links awakening
![yuzu_dQQ6WXQeQU](https://user-images.githubusercontent.com/66776795/147382824-c47b056e-90ee-47b1-8a7d-aebb6ab461d9.jpg)
broken over world gfx

2021-12-25 10:17 UTC, gidoly commented
glsl pokemon sword broken
<img width="1040" alt="yuzu_lgS5hZnewM" src="https://user-images.githubusercontent.com/66776795/147382903-5ce40ad3-3bb6-4a48-a8fe-c7a6e75d6c20.png">

2021-12-25 10:21 UTC, gidoly commented
glsl luigi mansion
![yuzu_ibA4JFTTmo](https://user-images.githubusercontent.com/66776795/147382949-72b5c8db-a7bb-41b8-b7f9-88090d2c3c58.jpg)

2021-12-25 10:33 UTC, gidoly commented
glsl smtv
<img width="1040" alt="yuzu_GNcvmXod2r" src="https://user-images.githubusercontent.com/66776795/147383143-545cf85d-5935-46fe-b7ea-be8f83418197.png">

2021-12-25 10:37 UTC, gidoly commented
glsl

https://user-images.githubusercontent.com/66776795/147383205-55b035fd-71e5-453b-9f7b-b81493fd3548.mp4

broken grass on xenoblade titles

2021-12-25 12:06 UTC, DonelBueno commented
I'm also getting tons of regressions with this PR.

2021-12-25 13:22 UTC, v1993 requested changes

2021-12-25 13:22 UTC, v1993 commented on src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
> +        throw NotImplementedException("Get attribute {}", attr);
Probably better update error message in order to differentiate between `EmitGetAttributeU32` and `EmitGetAttribute` failures.

Ditto for other backends

2021-12-25 18:54 UTC, gidoly commented
> I'm also getting tons of regressions with this PR (Nvidia 497.29).

This pr removes auto detection of nvidia driver version
Which switch to glasm if you use recent driver. So it is glsl nvidia driver issue rather then regression caused by this pr

2021-12-26 00:03 UTC, gidoly commented
while emit_glsl_integer: Use negation work around commit fixes xenoblade grass it breaks brightness of title screen 

![yuzu_SyTEvvQ8nV](https://user-images.githubusercontent.com/66776795/147395766-5e8552e0-d8f0-497d-ac65-eb6e43826937.jpg)

save:
[bfsgame00.zip](https://github.com/yuzu-emu/yuzu/files/7776387/bfsgame00.zip)

2021-12-26 00:20 UTC, gidoly commented
additional report kirby star allies not render character models correctly

<img width="490" alt="yuzu_U1JbzqwzDv" src="https://user-images.githubusercontent.com/66776795/147395957-eb2a5850-5ac9-411e-b9ed-a238b21b29da.png">

<img width="339" alt="yuzu_r4ECG054W7" src="https://user-images.githubusercontent.com/66776795/147395958-a4c44a4f-8756-4725-97c0-da9f221272a7.png">

2021-12-26 14:11 UTC, LordVulkan commented
Hi, did you report this bug to NVIDIA? I have this strange feeling that they don't give a fuck about their OpenGL driver anymore, it has been broken for 2 months and they don't even recognize this as a bug in their release notes.

2021-12-26 20:06 UTC, FernandoS27 commented
> Hi, did you report this bug to NVIDIA? I have this strange feeling that they don't give a fuck about their OpenGL driver anymore, it has been broken for 2 months and they don't even recognize this as a bug in their release notes.

They are fully aware but it seems it's hard for them to find it for some reason.

2021-12-28 14:42 UTC, v1993 commented on src/shader_recompiler/profile.h
> +    /// Some drivers do not properly support floatBitsToUint when used on cbufs
This comment's structure seems to be somewhat different to surrounding ones

2021-12-29 20:57 UTC, gidoly commented
new issue found on glsl backend with last driver

glsl

![yuzu_ppxBnITjew](https://user-images.githubusercontent.com/66776795/147702824-11c5ba6a-8cd2-49cb-8440-ed0cdbca8a49.jpg)

vulkan

![yuzu_lsTujcIayw](https://user-images.githubusercontent.com/66776795/147702848-a003f477-26ed-46d5-8995-50efe2e03aae.jpg)

2022-01-02 23:39 UTC, merged