First Nugget: Reworked Garbage Collection to be smarter [originally from Project YFC]
yuzu-emu/yuzu pull request #7720
Opened 2022-01-16 05:59 UTC by FernandoS27

This PR adds a few fixes to GC from project YFC as well as a bunch of improvements.

Improvements:

- Rebalance minimum, expected and critical thresholds to be more fair for GPUs with a lot of memory while keeping it great for low memory GPUs.
- Add GPU Memory Usage querying for Vulkan on AMD, NVIDIA & Intel and OGL for NVIDIA. This means that instead of estimating memory usage, we'll use the correct amount to make better decisions on when to clean memory.
- Improved Memory Cleaning & Estimation on iGPUs.
- Made ASTC and converted formats less easier to clean. (Thanks to @sayanns2 for figuring it that out).
- Tuned cleaning aggressiveness accordingly.

This feature used to be part of Project YFC but since it has been brought to my attention that the GC issues are very heavy right now. I have decided to release it separately.

2022-01-16 07:00 UTC, v1993 commented on src/video_core/buffer_cache/buffer_cache.h
> +    const s64 mem_tresshold = std::min(device_memory, TARGET_THRESHOLD);
```suggestion
    const s64 mem_threshold = std::min(device_memory, TARGET_THRESHOLD);
```

2022-01-16 07:11 UTC, v1993 commented on src/video_core/texture_cache/image_base.h
> +    GCProtected = 1 << 12, ///< Protected from low-tier GC as they are costy to load back.
Probably better use "This image is protected from low-tier GC as it is costly to load back." to keep wording consistent. Also, not sure about name `GCProtected`, since it only protects from non-aggressive GC rather than preventing collection entirely. Maybe use `CostlyLoad` or such to denote reason for affecting GC (like `BadOverlap` and `Alias`) instead?

2022-01-17 06:27 UTC, v1993 commented on src/video_core/vulkan_common/vulkan_device.cpp
> +            mem_properties.memoryHeaps[element].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT != 0;
```suggestion
            (mem_properties.memoryHeaps[element].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) != 0;
```

While we're at it - fix a silly bug in this line.

2022-01-17 10:32 UTC, v1993 requested changes

2022-01-17 10:32 UTC, v1993 commented on src/video_core/vulkan_common/vulkan_device.cpp
> +                 (properties.deviceType & VK_PHYSICAL_DEVICE_TYPE_CPU) != 0;
[VkPhysicalDeviceType](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceType.html) is a enumeration, not bit flag. As such, you must compare values rather than testing for bits.

Found by static analysis with PVS-Studio.

2022-01-17 10:40 UTC, v1993 commented on src/video_core/vulkan_common/vulkan_device.cpp
> +    device_initial_usage = 0;
This is a local variable, so this line can be omitted.

2022-01-20 22:01 UTC, ameerj reviewed
few nits

2022-03-25 01:01 UTC, FernandoS27 commented on src/video_core/buffer_cache/buffer_cache.h
> +        total_used_memory = runtime.GetDeviceMemoryUsage();
too expensive.

2022-03-25 02:01 UTC, FernandoS27 commented on src/video_core/texture_cache/texture_cache.h
> +        expected_memory = static_cast<u64>(
I like it different as I can tune it accordingly. I'll look at this in the future.

2022-03-25 02:03 UTC, FernandoS27 commented on src/video_core/texture_cache/texture_cache.h
> +        critical_gc++;
every tick frame.

2022-03-25 02:03 UTC, FernandoS27 commented on src/video_core/vulkan_common/vulkan_device.h
> +    bool is_non_gpu{};                          ///< Is SoftwareRasterizer, FPGA, non-GPU device.
I just figured that if i was getting is_integrated, i should put the others as well.

2022-03-25 03:16 UTC, bunnei approved these changes

2022-03-25 03:16 UTC, merged