BufferCache: Find direction of the stream buffer increase.
yuzu-emu/yuzu pull request #7812
Opened 2022-01-31 09:07 UTC by FernandoS27

This avoids doubling the buffer but instead increase it only where it's needed.

2022-01-31 17:26 UTC, Morph1984 reviewed
These make the comparisons more concise

2022-01-31 17:26 UTC, Morph1984 commented on src/video_core/buffer_cache/buffer_cache.h
> +        bool goes_left = false;
```suggestion
        bool goes_left = overlap_cpu_addr < begin;
```

2022-01-31 17:26 UTC, Morph1984 commented on src/video_core/buffer_cache/buffer_cache.h
> +        bool goes_right = false;
```suggestion
        bool goes_right = overlap_end > end;
```

2022-02-01 20:20 UTC, ameerj requested changes
This is a naive and improper approach. You are not taking into account the historical expansion direction into account. 

Let's say we have a buffer that kept getting expanded to the right, but at the instance where its `stream_score` is above the threshold, it happens to be expanding to the left. Your logic will only expand it further to the left, despite being far more biased to expanding to the right.

Also, the existing logic isn't "doubling the buffer" size. it increases the buffer size by `PAGE_SIZE * 256` on both ends, which is 16MiB. This size increase is arbitrary though and can be tweaked.

2022-02-03 02:50 UTC, ameerj requested changes

2022-02-03 02:50 UTC, ameerj commented on src/video_core/buffer_cache/buffer_cache.h
> +            }
Your logic here is swapped
```suggestion
            if (goes_left) {
                begin -= PAGE_SIZE * 256;
                cpu_addr = begin;
            }
            if (goes_right) {
                end += PAGE_SIZE * 256;
            }
```

2022-02-03 02:56 UTC, ameerj commented on src/video_core/buffer_cache/buffer_cache.h
> +        bool goes_right = false;
these can also be made `const` and moved to the body of the if condition where they are actually being used.

2022-02-03 10:16 UTC, FernandoS27 commented on src/video_core/buffer_cache/buffer_cache.h
> +            }
you are confused, it's the other way around. The real overlap is the "find range", what it's called overlap in that function are the buffers that existed before it.

2022-02-03 12:12 UTC, ameerj commented on src/video_core/buffer_cache/buffer_cache.h
> +            }
Then use more intuitive variable names for these cases. `expand_left` and `expand_right`

2022-03-20 22:23 UTC, bunnei approved these changes

2022-03-20 22:23 UTC, merged