texture_cache: Amend unintended bitwise OR in SynchronizeAliases
yuzu-emu/yuzu pull request #7840
Opened 2022-02-02 19:40 UTC by lioncash

Amends an accidental bitwise OR with a logical OR.

This PR also adds another change where copy extents wouldn't have any scaling applied to them, since they weren't being iterated by reference, effectively making the loop dead-code. Looking into `CopyImage()` however, it seems it would apply the scaling if necessary anyways, making the code unnecessary (though, if my assumption is wrong, feel free to correct me).

2022-02-06 12:08 UTC, Dban1 requested changes
After this got merged, my FPS in PLA dropped from 50~55 FPS to about 35~40 FPS. Not sure which part is causing it exactly, but curious to see if anyone else can replicate the performance drop? This was merged into version 2479 of EA, I am using EA 2478 as comparison for the above

2022-03-13 16:59 UTC, lioncash commented on src/video_core/texture_cache/texture_cache.h
> -        CopyImage(image_id, aliased->id, copies);
Is this check not already done inside `CopyImage` within the `if (is_rescaled)` check?

2022-03-13 19:03 UTC, FernandoS27 commented on src/video_core/texture_cache/texture_cache.h
> -        CopyImage(image_id, aliased->id, copies);
the issue is that the copies are not rescaled and we don't really store them rescaled.

2022-03-13 22:06 UTC, lioncash commented on src/video_core/texture_cache/texture_cache.h
> -        CopyImage(image_id, aliased->id, copies);
Right, but what I'm asking is wouldn't keeping this code (and fixing it to be by reference) cause the texture to be upscaled twice, since there's also upscaling being done within `CopyImage()`?

2022-03-20 09:19 UTC, bunnei approved these changes

2022-03-20 09:19 UTC, merged