service: pm: Implement AtmosphereGetProcessInfo
yuzu-emu/yuzu pull request #7847
Opened 2022-02-03 19:45 UTC by tech-ticks

(Incomplete) implementation of `pm::dmnt::AtmosphereGetProcessInfo`, which is used by Skyline. See https://github.com/yuzu-emu/yuzu/issues/7392

2022-02-03 21:09 UTC, german77 requested changes

2022-02-03 21:09 UTC, german77 commented on src/core/hle/service/pm/pm.cpp
> +        LOG_DEBUG(Service_PM, "called, pid={:016X}", pid);
```suggestion
        LOG_WARNING(Service_PM, "(Partial Implementation) called, pid={:016X}", pid);
```

2022-02-03 21:09 UTC, german77 commented on src/core/hle/service/pm/pm.cpp
> +        rb.PushCopyObjects(*process);
```suggestion
        struct ProgramLocation {
            u64 program_id;
            u8 storage_id;
        };
        static_assert(sizeof(ProgramLocation) == 0x10, "ProgramLocation is an invalid size");

        struct OverrideStatus {
            u64 keys_held;
            u64 flags;
        };
        static_assert(sizeof(OverrideStatus) == 0x10, "OverrideStatus is an invalid size");

        OverrideStatus override_status{};
        ProgramLocation program_location{
            .program_id = (*process)->GetProgramID(),
            .storage_id = 0,
        };

        IPC::ResponseBuilder rb{ctx, 10, 1};
        rb.Push(ResultSuccess);
        rb.PushCopyObjects(*process);
        rb.PushRaw(program_location);
        rb.PushRaw(override_status);
```

2022-02-03 21:09 UTC, german77 commented on src/core/hle/service/pm/pm.cpp
> +        rb.PushCopyObjects(*process);
Is better to return empty responses rather than incomplete responses.

2022-02-04 00:47 UTC, german77 commented
Does skyline works with this implementation or something else is needed?

2022-02-04 00:50 UTC, tech-ticks commented
It currently crashes in `KCodeMemory::Initialize` (called via `svcCreateCodeMemory`), but I haven't yet investigated it any further.

2022-02-04 07:09 UTC, NiQR1 commented
why does it crash

2022-02-05 16:31 UTC, german77 approved these changes

2022-02-06 00:22 UTC, Morph1984 approved these changes

2022-02-06 00:22 UTC, merged