general: Reduce unused includes across the project
yuzu-emu/yuzu pull request #8048
Opened 2022-03-19 07:06 UTC by ameerj

This change aims to reduce compile-time churn caused by includes which go unused. 

This was achieved with the help of [Resharper C++](https://www.jetbrains.com/resharper-cpp/).

2022-03-19 07:51 UTC, lioncash requested changes

2022-03-19 07:51 UTC, lioncash commented on src/core/crypto/key_manager.h
> +namespace std::filesystem {
The standard explicitly forbids forward declaring standard types (except when provided, e.g. `<iosfwd>` and there's no guarantee this will always work (since these types can be moved into inline namespaces for versioning purposes and then exported in the interface depending on multiple factors).

I'd strongly suggest not doing this.

2022-03-20 05:52 UTC, lioncash reviewed
just two nits, but looks good otherwise

2022-03-20 05:52 UTC, lioncash commented on src/shader_recompiler/frontend/maxwell/translate/impl/half_floating_point_set.cpp
> +#include "common_funcs.h"
```suggestion
#include "common/common_funcs.h"
```

2022-03-20 05:52 UTC, lioncash commented on src/shader_recompiler/frontend/maxwell/translate/impl/half_floating_point_set_predicate.cpp
> +#include "common_funcs.h"
```suggestion
#include "common/common_funcs.h"
```

2022-03-20 06:18 UTC, ameerj commented on src/shader_recompiler/frontend/maxwell/translate/impl/half_floating_point_set.cpp
> +#include "common_funcs.h"
Thanks, good catch!

2022-03-20 06:23 UTC, ameerj commented on src/shader_recompiler/frontend/maxwell/translate/impl/half_floating_point_set.cpp
> +#include "common_funcs.h"
Ah wait sorry this was including a different `common_funcs.h`
https://github.com/yuzu-emu/yuzu/blob/master/src/shader_recompiler/frontend/maxwell/translate/impl/common_funcs.h

2022-03-20 06:28 UTC, lioncash approved these changes

2022-03-22 01:03 UTC, bunnei approved these changes

2022-03-22 01:03 UTC, merged