Vulkan: Use 3D helpers for MSAA scaling on NV drivers 510+
yuzu-emu/yuzu pull request #8076
Opened 2022-03-24 03:35 UTC by ameerj

NVIDIA Vulkan drivers 510+ crash when blitting MSAA images. Fall-back to 3D scale helpers for MSAA image scaling on these drivers.

Fixes crashes when scaling was enabled on titles such as `Monster Hunter Rise`, `Rune Factory 5`, `Sonic Colors Ultimate`, among others.

2022-03-24 21:41 UTC, FernandoS27 requested changes

2022-03-24 21:41 UTC, FernandoS27 commented on src/video_core/renderer_vulkan/blit_image.cpp
> +      blit_depth_stencil_frag(BuildShader(device, VULKAN_BLIT_DEPTH_STENCIL_FRAG_SPV)),
this shader does not work in NVIDIA since it cannot write stencil....

2022-03-24 21:41 UTC, FernandoS27 commented on src/video_core/renderer_vulkan/blit_image.cpp
> +      blit_depth_stencil_frag(BuildShader(device, VULKAN_BLIT_DEPTH_STENCIL_FRAG_SPV)),
Please only limit yourself to Resolves and Depth/stencil resolves.

2022-03-31 06:00 UTC, bunnei approved these changes

2022-03-31 06:00 UTC, merged

2022-05-07 05:14 UTC, jacky400 commented
@ameerj Just tested a recent game that it crash with 512.59 driver with vullkan backend and 2x scaler.