chore: add even more SPDX tags
yuzu-emu/yuzu pull request #8338
Opened 2022-05-15 00:21 UTC by Tachi107

This PR is a WIP, there are a few other files that should be tagged left.

While working on this I thought that you might be interested in making yuzu [REUSE](https://reuse.software) compliant. Basically it means that all source files have copyright information associated with them in a machine readable format. For text files you can add SPDX headers, while for binary assets (like images) you can either create different `filename.license` files containing their copyright information or put everything in a `.reuse/dep5` file. This would make it easier for third parties to understand how yuzu is licensed, and would also make license handling in the project less messy: no need to keep track of copyright information in `license.txt`, `dist/license.md`, etc, and if things get out of sync a CI job will immediately warn about it.

Follow-up to 01cf05bc75b1e47beb08937439f3ed9339e7b254

2022-06-08 19:50 UTC, Tachi107 commented
Hey @lioncash, I'm pinging you as you've reviewed my SPDX changes before. Do these patches look ok to you? I guess this PR is went unnoticed as it's been a draft for a while

2022-06-15 19:20 UTC, lioncash commented
@Tachi107 Will review later tonight, sorry about that

2022-06-15 19:23 UTC, Tachi107 commented
Don't worry, better late than never :D

2022-06-15 19:24 UTC, lioncash reviewed
Right after I said I'd review it later tonight I started reviewing it anyway (lol)

Just has one comment, but other than that it looks good

2022-06-15 19:24 UTC, lioncash commented on src/yuzu/configuration/configure.ui
> +SPDX-FileCopyrightText: 2018 yuzu Emulator Project
Are you certain these comments won't be removed by Qt Creator's UI editor?

If not certain, it'd probably be best to omit these from the ,ui files

2022-06-15 19:26 UTC, Tachi107 commented on src/yuzu/configuration/configure.ui
> +SPDX-FileCopyrightText: 2018 yuzu Emulator Project
Nope, I've never used Qt Creator. I can install it though, and if this is the case I can put the copyright information in `.reuse/dep5`

2022-06-15 19:27 UTC, lioncash commented on src/yuzu/configuration/configure.ui
> +SPDX-FileCopyrightText: 2018 yuzu Emulator Project
Sounds good!

2022-06-15 19:27 UTC, liamwhite requested changes

2022-06-15 19:27 UTC, liamwhite commented on .reuse/dep5
> +Comment: Make sure that this is accurate
(to make sure that we don't merge with these placeholders here)

2022-06-15 19:43 UTC, Tachi107 commented on .reuse/dep5
> +Comment: Make sure that this is accurate
Ops, thanks for spotting this

2022-06-15 19:43 UTC, Tachi107 commented on .reuse/dep5
> +Comment: Is the GPL good for a logo?
Here I chose the `GPL-2.0-or-later` because these files have no license notice and [GitHub's TOS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license) say that if no license is specified, the common convention of applying the same terms as the rest of the repository apply. Feel free to correct me though.

2022-06-15 20:40 UTC, Tachi107 commented on src/yuzu/configuration/configure.ui
> +SPDX-FileCopyrightText: 2018 yuzu Emulator Project
You're right, the comments get removed by Qt Creator :/
Fixed.

2022-06-15 20:44 UTC, Morph1984 commented
> As yuzu contributors do not have to sign a CLA or similar I couldn't assume that copyright ownership was of the "yuzu Emulator Project", so I used the name and/or email of the commit author instead.

Between 2019 and 2021 (inclusive), yuzu had a CLA, and thus copyright during this time would be assignable to the project

2022-06-15 20:52 UTC, Morph1984 commented
> Oh, ok. What were the terms of the CLA? Was copyright assigned to both the "yuzu Emulator Project" and the commiter?

This was the original wording:
When you agree to the yuzu Nintendo Switch Emulator Individual [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu) (CLA), you are effectively granting a copyright of any contribution that you make to the maintainers of the yuzu project. You still retain an equal copyright over your own work, and are free to use your own work as you please.

2022-06-15 20:56 UTC, Tachi107 commented
> When you agree to the yuzu Nintendo Switch Emulator Individual [Contributor License Agreement](https://cla-assistant.io/yuzu-emu/yuzu) (CLA), you are effectively granting a copyright of any contribution that you make to the maintainers of the yuzu project. You still retain an equal copyright over your own work, and are free to use your own work as you please.

What do you suggest me to do? Do I simply add an additional SPDX tag like `SPDX-FileCopyrightText: <year> yuzu Emulator Project` to the affected files or mark them _only_ with a single tag referring to the yuzu Emulator Project?

2022-06-15 21:22 UTC, Morph1984 commented
> What do you suggest me to do? Do I add an additional SPDX tag like `SPDX-FileCopyrightText: <year> yuzu Emulator Project` to the affected files or mark them _only_ with a single tag referring to the yuzu Emulator Project?

For the files where anyone was/is a member of the project itself, it is heavily implied that the copyright was owned by the project, so for these a single tag referring to the project is sufficient. In this case, Zach (Zach Hilman), lat9nq (toastUnlimited), FearlessTobi (Tobi), Its-Rei (Rei), James Rowe (jroweboy), and I are members of the project.

2022-06-15 21:24 UTC, Tachi107 commented
> In this case, Zach (Zach Hilman), lat9nq (toastUnlimited), FearlessTobi (Tobi), Its-Rei (Rei), James Rowe (jroweboy), and I are members of the project.

Oh ok, I wasn't sure about that. Thanks for clarifying!

2022-06-15 21:30 UTC, Tachi107 commented
I tried to address your feedback in the latest force-push :)
`.github/ISSUE_TEMPLATE/config.yml` hasn't been changed as in https://github.com/yuzu-emu/yuzu/pull/4198 no CLA was signed by the original author

2022-06-18 18:21 UTC, liamwhite approved these changes

2022-06-30 21:53 UTC, Tachi107 commented
Just rebased onto latest master. Is there something else I should do to get this merged?

2022-07-26 19:00 UTC, bunnei commented
@Tachi107 apologies -- somehow this fell under the radar. Do you mind rebasing one more time, and then we can get this merged? Thank you!

2022-07-26 22:24 UTC, Tachi107 commented
@bunnei no problem, I'll do it tomorrow (or today, depending on your timezone :)

2022-07-27 10:55 UTC, Tachi107 commented
Hey @bunnei, rebased and added missing copyright information of new files. Unless CI fails, I think this is now ready :D

2022-07-27 17:01 UTC, merged

2022-07-27 17:01 UTC, liamwhite commented
Merged, sorry for the long delay

2022-07-27 17:02 UTC, Tachi107 commented
Thanks for merging :tada: