vk_texture_cache: Fix the behavior of framebuffer layers
yuzu-emu/yuzu pull request #8363
Opened 2022-05-20 10:08 UTC by asLody

Some games bind render targets of a different size and expect it to work, so we'll compute the minimum size.

2022-05-25 03:23 UTC, liamwhite commented
@asLody which games does this fix?

2022-05-25 22:25 UTC, FernandoS27 approved these changes

2022-05-27 04:30 UTC, gidoly commented
it regress shin megami tensei 5

![yuzu_LR0NTzzYWy](https://user-images.githubusercontent.com/66776795/170629123-83e4fdbe-f153-4dbb-b674-a10f5e559f8b.jpg)

2022-05-30 01:13 UTC, Morph1984 requested changes
(to ensure this does not get accidentally merged)

2022-06-15 19:29 UTC, bunnei commented
@asLody any plans to investigate the above? Thank you!

2022-12-04 18:57 UTC, closed without merging