Project yuzu Fried Chicken (Y.F.C.) Part 1
yuzu-emu/yuzu pull request #8467
Opened 2022-06-15 23:56 UTC by FernandoS27

This is the very fundamental base of project YFC a project aimed at improving multiple aspects of GPU emulation that have been left in the oblivion.

Part 1 includes:
- Full rework of GPU Driver based on the Re and code from Skyline Emulator with full permission from @bylaws (please check that all crediting and copyright notices are correct).
- Full rework of GPU memory management.
- Initial implementation of GPU Channels, this fixes World of light in SSBU, Deltarune, among a bunch of other games.
- Fixes and accelerations to the DMA engine.
- A series of fixes for Vulkan, Buffer Cache, Shader Decompiler that affected multiple games.
- Rework host frame presentation to be a considerably smoother (fixes Xenoblade DE).

Part 1 does NOT include:
- Performance improvements. (main theme)
- Buffer Cache Rework. (this fixes FE: Warriors)
- Macro HLE Rework. DrawIndirect, DrawElementsIndirect, MultiDrawIndirect, etc (perf for MHR and Koemo tecmo games).
- Fencing Rework with asynchronous buffer and texture downloads.

These will be addressed in part 2.

This are further features that are partially done internally and will be released later after Part 2:
- Accelerate DMA.
- Unnormalized texture coords & rectangular textures.
- Rendering to / from ASTC textures (biggest pain of UE4 games).
- Host Conditional Rendering ? (still under consideration as it only seemed beneficial in 1 game and detrimental in others).

Credits:
- Bylaws (@bylaws ) & Skyline Emulator [Skyline Emulator](https://github.com/skyline-emu/skyline) for providing information on the RE of NVIDIA's kernel driver as well as being the base at which most of the DRV rework had been done.
- AsLody (@asLody ) For finding out the cause of the issues behind Yokai Watch 4, The Witcher 3, Hades, among others. Along some of the solutions applied here.
- Pharynx (@liamwhite ) and toastUnlimited (@lat9nq ) Linux help and compiling bugs fixes on GCC / Clang.
- yuzu Team & Testers for annoying me to rebase / release this as it has been done since April xD.

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +private:
Generally we put the public interface first

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +private:
Generally we put the public interface first

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +        unmapCallback{}; //!< Callback called when the mappings in an region have changed
```suggestion
        unmap_callback{}; //!< Callback called when the mappings in an region have changed
```

Also maybe put the doc comment above the member variable, so that clang-format doesn't give it this wonky wrapping

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +        [[no_unique_address]] ExtraBlockInfo extraInfo;
```suggestion
        [[no_unique_address]] ExtraBlockInfo extra_info;
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +        constexpr bool Valid() {
```suggestion
        constexpr bool Valid() const {
```

Ditto for the ones below.

Also if the constructors aren't constexpr, then these usages of constexpr don't do anything

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    std::mutex blockMutex;
```suggestion
    std::mutex block_mutex;
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    void MapLocked(VaType virt, PaType phys, VaType size, ExtraBlockInfo extraInfo);
```suggestion
    void MapLocked(VaType virt, PaType phys, VaType size, ExtraBlockInfo extra_info);
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +        Block(VaType virt_, PaType phys_, ExtraBlockInfo extraInfo_)
```suggestion
        Block(VaType virt_, PaType phys_, ExtraBlockInfo extra_info_)
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    FlatAddressSpaceMap(VaType vaLimit, std::function<void(VaType, VaType)> unmapCallback = {});
```suggestion
    explicit FlatAddressSpaceMap(VaType va_limit, std::function<void(VaType, VaType)> unmap_callback = {});
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    void Map(VaType virt, PaType phys, VaType size, ExtraBlockInfo extraInfo = {}) {
```suggestion
    void Map(VaType virt, PaType phys, VaType size, ExtraBlockInfo extra_info = {}) {
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    VaType vaLimit{VaMaximum}; //!< A soft limit on the maximum VA of the AS
Maybe make this set and retrieved from member functions so that all invariants are together in the private section of the class.

also `va_limit`

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    VaType vaStart; //!< The base VA of the allocator, no allocations will be below this
Ditto with giving this its own accessors

also `va_start`

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    VaType currentLinearAllocEnd; //!< The end address for the initial linear allocation pass, once
```suggestion
    VaType current_linear_alloc_end; //!< The end address for the initial linear allocation pass, once
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.h
> +    FlatAllocator(VaType vaStart, VaType vaLimit = Base::VaMaximum);
```suggestion
    explicit FlatAllocator(VaType va_start, VaType va_limit = Base::VaMaximum);
```

2022-06-16 00:57 UTC, lioncash commented on src/common/address_space.inc
> +
This entire file has a bunch of camelCase that should be transitioned over to `snake_case` since its in the main repository

2022-06-16 00:57 UTC, lioncash commented on src/common/multi_level_page_table.h
> +    [[nodiscard]] constexpr const BaseAddr& operator[](std::size_t index) const {
If the constructor isn't constexpr, then constexpr here doesn't do anything, ditto for the ones below

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/container.cpp
> +    ContainerImpl(Tegra::Host1x::Host1x& host1x_) : file{host1x_}, manager{host1x_} {}
```suggestion
   explicit ContainerImpl(Tegra::Host1x::Host1x& host1x_) : file{host1x_}, manager{host1x_} {}
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/container.h
> +    Container(Tegra::Host1x::Host1x& host1x);
```suggestion
    explicit Container(Tegra::Host1x::Host1x& host1x);
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/container.h
> +namespace Tegra {
This seems like it can be joined with the namespace below, like:

```cpp
namespace Tegra::Host1x {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/nvmap.cpp
> +    } catch ([[maybe_unused]] std::out_of_range& e) {
```suggestion
    } catch (std::out_of_range&) {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/nvmap.cpp
> +    } catch ([[maybe_unused]] std::out_of_range& e) {
```suggestion
    } catch (std::out_of_range&) {
```

Though it's kind of weird to not log out out of bounds attempts

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/nvmap.h
> +public:
Public interface should come first in the class declaration, followed by protected, and then private

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/nvmap.h
> +    NvMap(Tegra::Host1x::Host1x& host1x);
```suggestion
    explicit NvMap(Tegra::Host1x::Host1x& host1x);
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +namespace Tegra {
This can be joined with the namespace following it

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +    bool IsFenceSignalled(NvFence fence) {
```suggestion
    bool IsFenceSignalled(NvFence fence) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +    bool HasSyncpointExpired(u32 id, u32 threshold);
```suggestion
    bool HasSyncpointExpired(u32 id, u32 threshold) const;
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +    u32 AllocateSyncpoint(bool clientManaged);
```suggestion
    u32 AllocateSyncpoint(bool client_managed);
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.cpp
> +u32 SyncpointManager::ReserveSyncpoint(u32 id, bool clientManaged) {
```suggestion
u32 SyncpointManager::ReserveSyncpoint(u32 id, bool client_managed) {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.cpp
> +    for (u32 syncpointId : channel_syncpoints) {
```suggestion
    for (u32 syncpoint_id : channel_syncpoints) {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +        std::atomic<u32> counterMin; //!< The least value the syncpoint can be (The value it was
```suggestion
        std::atomic<u32> counter_min; //!< The least value the syncpoint can be (The value it was
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +        std::atomic<u32> counterMax; //!< The maximum value the syncpoint can reach according to the
```suggestion
        std::atomic<u32> counter_max; //!< The maximum value the syncpoint can reach according to the
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +        bool interfaceManaged; //!< If the syncpoint is managed by a host1x client interface, a
```suggestion
        bool interface_managed; //!< If the syncpoint is managed by a host1x client interface, a
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +        if (!(params.big_page_size & VM::SUPPORTED_BIG_PAGE_SIZES)) {
```suggestion
        if ((params.big_page_size & VM::SUPPORTED_BIG_PAGE_SIZES) == 0) {
```

Makes this a little more explicit and unlikely to be glossed over

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +    if (mapping->sparse_alloc)
These if-else statements should be braced

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +    } catch ([[maybe_unused]] const std::out_of_range& e) {
```suggestion
    } catch (const std::out_of_range&) {
```

Also weird to not log on out of bounds accesses here or use it as control flow

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +        } catch ([[maybe_unused]] const std::out_of_range& e) {
```suggestion
        } catch (const std::out_of_range&) {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +        if (Common::IsAligned(handle->align, vm.big_page_size))
These if else statements should be braced

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +    } catch ([[maybe_unused]] const std::out_of_range& e) {
```suggestion
    } catch (const std::out_of_range&) {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
> +        bool IsBeingUsed() {
```suggestion
        bool IsBeingUsed() const {
```

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
> +    static u32 next_id;
No mutable global lifetime variables.

This also introduces non-determinism between multiple execution runs in the same process.

Consider putting them in the System class within their own struct if you need something that lasts the entire lifecycle of the system. That or consider some other means of doing it

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
> +    static std::unordered_map<DeviceFD, u32> fd_to_id;
Ditto

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvhost_vic.h
> +    static u32 next_id;
Ditto

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/devices/nvmap.h
> +    nvmap(nvmap const&) = delete;
```suggestion
    nvmap(const nvmap&) = delete;
```

Is the formatting we use throughout the codebase. Ditto for the move assignment below

2022-06-16 00:57 UTC, lioncash commented on src/core/hle/service/nvdrv/nvdrv.h
> +    EventInterface(Module& module_);
```suggestion
    explicit EventInterface(Module& module_);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/channel_state.h
> +    ChannelState(s32 bind_id);
```suggestion
    explicit ChannelState(s32 bind_id);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/channel_state.cpp
> +ChannelState::ChannelState(s32 bind_id_) {
```suggestion
ChannelState::ChannelState(s32 bind_id_) : bind_id{bind_id_} {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/channel_state.cpp
> +    initiated = false;
This is already initialized in the class body

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/channel_state_cache.h
> +    ChannelInfo(Tegra::Control::ChannelState& state);
```suggestion
    explicit ChannelInfo(Tegra::Control::ChannelState& state);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/scheduler.h
> +    Scheduler(GPU& gpu_);
```suggestion
    explicit Scheduler(GPU& gpu_);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/scheduler.cpp
> +    std::unique_lock<std::mutex> lk(scheduling_guard);
```suggestion
    std::unique_lock lk(scheduling_guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/scheduler.cpp
> +    std::unique_lock<std::mutex> lk(scheduling_guard);
```suggestion
    std::unique_lock lk(scheduling_guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/control/scheduler.cpp
> +    auto it = channels.find(channel);
Should there be an assertion or something if nothing is found?

2022-06-16 00:57 UTC, lioncash commented on src/video_core/engines/maxwell_dma.h
> +        Swizzle GetComponent(size_t i) {
```suggestion
        Swizzle GetComponent(size_t i) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/gpu.cpp
> +    std::list<std::function<void(void)>> sync_requests;
```suggestion
    std::list<std::function<void()>> sync_requests;
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/host1x.h
> +    Host1x(Core::System& system);
```suggestion
    explicit Host1x(Core::System& system);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::function<void(void)>& action) {
```suggestion
    std::function<void()>& action) {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::unique_lock<std::mutex> lk(guard);
```suggestion
    std::unique_lock lk(guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::unique_lock<std::mutex> lk(guard);
```suggestion
    std::unique_lock lk(guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::unique_lock<std::mutex> lk(guard);
```suggestion
    std::unique_lock lk(guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::unique_lock<std::mutex> lk(guard);
```suggestion
    std::unique_lock lk(guard);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +    u32 GetGuestSyncpointValue(u32 id) {
```suggestion
    u32 GetGuestSyncpointValue(u32 id) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +    u32 GetHostSyncpointValue(u32 id) {
```suggestion
    u32 GetHostSyncpointValue(u32 id) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +        std::function<void(void)> action;
```suggestion
        std::function<void()> action;
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +        RegisteredAction(u32 expected_value_, std::function<void(void)>& action_)
```suggestion
        RegisteredAction(u32 expected_value_, std::function<void()>& action_)
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +        std::function<void(void)> func(action);
```suggestion
        std::function<void()> func(action);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +        std::function<void(void)> func(action);
```suggestion
        std::function<void()> func(action);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +    bool IsReadyGuest(u32 syncpoint_id, u32 expected_value) {
```suggestion
    bool IsReadyGuest(u32 syncpoint_id, u32 expected_value) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +    bool IsReadyHost(u32 syncpoint_id, u32 expected_value) {
```suggestion
    bool IsReadyHost(u32 syncpoint_id, u32 expected_value) const {
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/host1x/syncpoint_manager.h
> +                                std::function<void(void)>& action);
```suggestion
                                std::function<void()>& action);
```

2022-06-16 00:57 UTC, lioncash commented on src/video_core/memory_manager.h
> +    [[nodiscard]] inline std::size_t PageEntryIndex(GPUVAddr gpu_addr) const {
```suggestion
    [[nodiscard]] std::size_t PageEntryIndex(GPUVAddr gpu_addr) const {
```

Functions implemented in the class body are inline by default

2022-06-16 02:08 UTC, liamwhite commented on src/common/address_space.h
> +    VaType vaStart; //!< The base VA of the allocator, no allocations will be below this
This could conflict with the va_start macro. Perhaps a different name.

2022-06-16 02:11 UTC, liamwhite commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::function<void(void)>& action) {
Adding to that, are you sure you meant to take a std::function by reference?

2022-06-16 05:33 UTC, german77 commented
Lower resolutions than 1x will break the graphics

2022-06-16 09:40 UTC, gidoly commented
Fixes #8207 #8166 #8129 #7918 #7892 #7655 #7235 #7124 #7087 #7071 #6892 #6864 #6757 #6305
May fix #6893

2022-06-17 06:03 UTC, lat9nq commented
Causes a regression in Splatoon 2 with at least the NVIDIA driver, where switches in the single player campaign will spontaneously activate. In the video is Station E05 from the Octo Expansion DLC

https://user-images.githubusercontent.com/22451773/174234799-3c91df7d-5531-4149-a414-d133ee4d0591.mp4

2022-06-17 08:17 UTC, bylaws commented
@lat9nq are you able to bisect? Please let me know if nvdrv is at fault

2022-06-17 20:12 UTC, lat9nq commented
@bylaws I was only able to narrow it down to this:
[bisect.txt](https://github.com/yuzu-emu/yuzu/files/8931113/bisect.txt)
 
The skipped commits crash booting the game. Starting from `MemoryManager: initial multi paging system implementation` it crashes loading the level.

2022-06-18 00:37 UTC, gidoly commented
causes crash on metroid dread on title screen ~ before go ingame

2022-06-18 01:25 UTC, gidoly commented
another regression super mario maker 

https://user-images.githubusercontent.com/66776795/174417135-d479589d-7c98-4ded-a8cf-9716537abe2f.mp4

2022-06-18 09:19 UTC, gidoly commented
users on discord seems also reporting low performance than before on xenoblade 2

2022-06-18 12:54 UTC, Timmy5942 reviewed
LGTM, Sorry Need to merge for test in GIT GUI

2022-06-18 12:55 UTC, Timmy5942 approved these changes
LGTM, Sorry Need to merge for test in GIT GUI, Test 2

2022-06-18 18:33 UTC, Tachi107 requested changes
Some minor nitpicks about copyright/licensing headers (things that could be easily spotted with #8338 ;D )

2022-06-18 18:33 UTC, Tachi107 commented on src/common/address_space.cpp
> +// Refer to the license.txt file included.
Could you please change this and similar headers to use SPDX tags? Thanks :)

2022-06-18 18:33 UTC, Tachi107 commented on src/common/address_space.inc
> +// Copyright © 2021 Skyline Team and Contributors (https://github.com/skyline-emu/)
```suggestion
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/container.cpp
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/container.h
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/nvmap.cpp
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/nvmap.h
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/common/address_space.h
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/common/multi_level_page_table.h
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/common/multi_level_page_table.inc
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/syncpoint_manager.cpp
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/core/syncpoint_manager.h
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-FileCopyrightText: 2022 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
> +// or any later version Refer to the license.txt file included.
This has been relicensed from GPL-2.0-or-later to GPL-3.0-or-later. Is this intentional/required? (note that new contributions can be licensed under the GPL-2.0-or-later without issues, as yuzu as a whole can be distributed under the GPL-3.0-or-later and use Apache-2.0 files - I'm not a lawyer this is not legal advice etc etc)

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
> +// or any later version Refer to the license.txt file included.
Same as above

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/nvdata.h
> +// or any later version Refer to the license.txt file included.
License changed here too

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/nvdrv.cpp
> +// or any later version Refer to the license.txt file included.
Same as above

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/nvdrv.h
> +// or any later version Refer to the license.txt file included.
By the way, why do the copyright notices mention the year 2021 and not 2022?

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/core/hle/service/nvdrv/nvdrv_interface.cpp
> +// or any later version Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/channel_state.cpp
> +// Refer to the license.txt file included.
New file, why not 2022?

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/channel_state.h
> +// Refer to the license.txt file included.
Same as above

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/channel_state_cache.cpp
> +#include "video_core/control/channel_state_cache.inc"
Missing copyright header

```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later

#include "video_core/control/channel_state_cache.inc"
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/channel_state_cache.h
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/channel_state_cache.inc
> +
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later

```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/scheduler.cpp
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/control/scheduler.h
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/engines/puller.cpp
> +// Refer to the license.txt file included.
New file, why not 2022?

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/engines/puller.h
> +// Refer to the license.txt file included.
Same as above

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/control.cpp
> +// Refer to the license.txt file included.
Finally a new file with 2022 as the copyright year :D

```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/control.h
> +// or any later version Refer to the license.txt file included.
License changed

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/host1x.cpp
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/host1x.h
> +// Refer to the license.txt file included.
Oh wow 2022s are becoming consistent :)

```suggestion
// SPDX-FileCopyrightText: 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/syncpoint_manager.cpp
> +// Refer to the license.txt file included.
2021?

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/host1x/syncpoint_manager.h
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/texture_cache/texture_cache.cpp
> +// Refer to the license.txt file included.
```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/texture_cache/texture_cache.h
> +// or any later version Refer to the license.txt file included.
Here you mention "yuzu emulator team" (instead of "yuzu Emulator Project" btw) but then link to Skyline... I guess you meant to add copyright notices for both

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-18 18:33 UTC, Tachi107 commented on src/video_core/texture_cache/texture_cache_base.h
> +// or any later version Refer to the license.txt file included.
Same as above. And the license was changed too

```suggestion
// SPDX-FileCopyrightText: 2021 yuzu Emulator Project
// SPDX-FileCopyrightText: 2021 Skyline Team and Contributors <https://github.com/skyline-emu>
// SPDX-License-Identifier: GPL-3.0-or-later
```

2022-06-28 01:09 UTC, pacoa-kdbg commented
Artifact from Build #20220627.12
Present an issue where handheld performance gets tanked 

This is with intel iGPU (iris xe) 

![image](https://user-images.githubusercontent.com/29181120/176065150-57d3dd7c-ec43-463a-b2ce-2b25205e2b63.png)

Issue is already pressent at EA2804
![image](https://user-images.githubusercontent.com/29181120/176065238-3bd05f7d-e735-4916-bd00-89e6c5d5be64.png)


For reference this is on mainline 1067
![image](https://user-images.githubusercontent.com/29181120/176065278-a716578f-8735-4f97-8bed-4f69cb7b10ee.png)

2022-06-29 01:51 UTC, vonchenplus commented
The multi-channel implementation fixed the #6902

2022-06-30 00:39 UTC, Morph1984 commented on src/common/address_space.h
> +    VaType vaStart; //!< The base VA of the allocator, no allocations will be below this
Renamed to `virt_start`

2022-06-30 00:51 UTC, lightgod87 commented
Reporting another issue that could be possibly caused by YFC, as it doesn't happen in mainline.

With the Live-A-Live demo, when using Vulkan as the backend, it can potentially crash yuzu on loading screens. I have seen this happening on the loading screen to the chapter selection. This issue didn't happen in mainline, just so you know.

I'll attach the debug logs. The tests were done in EA2805 and mainline 1068. As for the specs:

OS: Windows 10 21H2
RAM: 32 GBs DDR4
GFX: Nvidia Geforce GTX 3060 Ti (Ampere)
Processor: AMD Ryzen 5 5600X

The drivers used were 512.xx and 516.xx, so the issue isn't driver-related.

[yuzu_log_mainline_debug_1068.zip](https://github.com/yuzu-emu/yuzu/files/9015498/yuzu_log_mainline_debug_1068.zip)
[yuzu_log_ea_debug_2805.zip](https://github.com/yuzu-emu/yuzu/files/9015499/yuzu_log_ea_debug_2805.zip)
[yuzu_log_ea_debug_2805_512.xx.zip](https://github.com/yuzu-emu/yuzu/files/9015500/yuzu_log_ea_debug_2805_512.xx.zip)

2022-07-01 15:11 UTC, FernandoS27 commented
@pacoa-kdbg @lightgod87 I have pushed some fixes. Please check if your regressions have been fixed.

2022-07-01 15:34 UTC, lightgod87 commented
> @pacoa-kdbg @lightgod87 I have pushed some fixes. Please check if your regressions have been fixed.

Issue still persists. I'll attach new log.

[yuzu_log_ea_debug_2811.zip](https://github.com/yuzu-emu/yuzu/files/9030013/yuzu_log_ea_debug_2811.zip)

2022-07-03 20:28 UTC, bajulador commented
I have a crash problem running Xenoblade Chronicles 2 with the latest EA builds. I did some tests and I noticed that the problem started with EA 2803 and so on. So I decided to walk around the world on the last EA build (EA2814) and the last one that the game ran fine (EA2801).

    OS: Windows 10
    CPU: Ryzen 3 2200G
    GPU: RX 570 4GB VRAM
    RAM: 16GB RAM

Here are the logs for a playthrough of around ~12 minutes each on EA2801 (I ran around the city Torigoth and headed to Gormott, then Mor Ardain and back to the city Argentum. I stopped the game and closed down Yuzu in both runs):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9035424/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9035458/yuzu_log.txt)

Here are the logs for EA2814 (Both crashed when I was still in Torigoth. So I didn't had the chance to even do the same route in EA 2801):
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9035432/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9035438/yuzu_log.txt)

I don't have a powerful PC, so I shouldn't be taken as a primary source for the development of Yuzu. I'm just glad and thankful for the work behind the emulator. The game is running fine in the Mainline builds btw.

2022-08-07 00:37 UTC, liamwhite commented
Super Mario Sunshine, when booted through the 3DAS launcher, reliably crashes with this branch due to hitting [this unreachable](https://github.com/FernandoS27/yuzu/blob/yfc-rel-1/src/core/hle/service/nvdrv/core/syncpoint_manager.cpp#L86). Confirmed on both Windows and Linux. I was unable to bisect due to most commits being unbuildable.

2022-08-14 06:51 UTC, merryhime commented on src/video_core/textures/decoders.cpp
> +            const u32 swizzled_y = pdep<SWIZZLE_Y_BITS>(line);
```suggestion
            const u32 swizzled_y = pdep<SWIZZLE_Y_BITS>(y);
```

2022-08-14 06:52 UTC, merryhime commented on src/video_core/textures/decoders.cpp
> +            u32 swizzled_x = 0;
Here, `const u32 x = (column + origin_x) * BYTES_PER_PIXEL;`, therefore we are starting with `origin_x * BYTES_PER_PIXEL` and incrementing by `BYTES_PER_PIXEL`.

```suggestion
            u32 swizzled_x = pdep<SWIZZLE_Y_BITS>(origin_x * BYTES_PER_PIXEL);
```

2022-08-14 06:53 UTC, merryhime commented on src/video_core/textures/decoders.cpp
> +                 ++column, incrpdep<SWIZZLE_X_BITS, 1>(swizzled_x)) {
```suggestion
                 ++column, incrpdep<SWIZZLE_X_BITS, BYTES_PER_PIXEL>(swizzled_x)) {
```

2022-08-24 00:20 UTC, lightgod87 commented
Good day,

As per gidoly's request, I tested the issue again. I checked in Vulkan. The first try was rather successful, the issue didn't happen, but then I tried again and the crash issue with Live-A-Live still appeared. Here's the log.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9411245/yuzu_log.txt)

This is from EA 2918, just in case.

2022-08-30 14:16 UTC, pacoa-kdbg commented
The problem with SMO handheld performance have been solved.
![image](https://user-images.githubusercontent.com/29181120/187460859-3b58af88-7d8c-4cd1-9be0-05d45a8e7e16.png)
![image](https://user-images.githubusercontent.com/29181120/187460920-21cc1993-5afb-4879-a119-8db722b854eb.png)

2022-08-31 16:09 UTC, FernandoS27 commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::function<void(void)>& action) {
> Adding to that, are you sure you meant to take a std::function by reference?

fixed

2022-08-31 16:59 UTC, liamwhite commented on src/video_core/host1x/syncpoint_manager.cpp
> +    std::function<void(void)>& action) {
still there
https://github.com/FernandoS27/yuzu/blob/5951b51399792ec70e9c7315e7d976646f0addc7/src/video_core/host1x/syncpoint_manager.cpp#L13-L15

2022-09-01 04:58 UTC, liamwhite approved these changes

2022-09-01 05:12 UTC, lat9nq commented
https://github.com/yuzu-emu/yuzu/pull/8467#issuecomment-1158522835

In response to the approval just now, this regression is still present.

2022-09-06 06:27 UTC, lat9nq commented
This causes a regression in Splatoon 3: Splatfest World Premiere, where stickers on various surfaces are missing.

Mainline:
![Screenshot from 2022-09-06 02-03-15](https://user-images.githubusercontent.com/22451773/188562124-d55b3052-07b7-49cd-9f8d-9c4a9bae22ae.png)

yfc-rel-1:
![Screenshot from 2022-09-06 02-25-57](https://user-images.githubusercontent.com/22451773/188562170-26edf796-64a1-480f-a610-6cd8d66c5632.png)

2022-09-18 00:14 UTC, lightgod87 commented
It seems like the loading issue with Live-A-Live got fixed. I didn't check which commit did it, but I checked in EA2963 and the issue didn't happen in Vulkan. I tried to replicate it like 3 times. There was another crash when I first tried, but it was after the loading screen and probably related to shaders. Otherwise, that issue got solved, it seems.

2022-10-06 19:29 UTC, merged

2023-02-22 18:53 UTC, leolink17 commented
Hello, did anyone find a solution for the problems in TRIALS OF MANA. It keeps crashin in loading screens after some time playing. Then the screen turns black like it's gonna start the loading, but does not, the fps gos to 0 and it keeps all time on black screen until we close the emulator, and start it again. It's happening on Yuzu in Windows and Linux versions.
Is someone with the same problem?