yuzu, network: Add room service and UI configuration
yuzu-emu/yuzu pull request #8541
Opened 2022-07-06 02:41 UTC by FearlessTobi

This is the first part of a series of Pull Requests, aiming to bring multiplayer functionality to yuzu.
It adds a new multiplayer room service which makes it possible to create sessions with other players using the yuzu QT interface and exchange network packets.
In order to achieve this, enet is added as a dependency.
Please note that this implementation is heavily based on the multiplayer room feature of Citra.

For now, there will be no UI or functional changes to the end user, as the multiplayer implementation is still incomplete.
However, the feature has already been tested in private and is confirmed to be working.

2022-07-06 03:10 UTC, Docteh commented on dist/license.md
> +qt_themes/default/icons/16x16/connected.png | CC BY-ND 3.0 | https://icons8.com
Are those icons only available with CC BY-ND? https://github.com/yuzu-emu/yuzu/issues/8077

2022-07-12 18:20 UTC, german77 commented on src/yuzu/multiplayer/lobby.cpp
> +                                      Settings::values.yuzu_token);
```suggestion
        if (!Settings::values.yuzu_username.GetValue().empty() &&
            !Settings::values.yuzu_token.GetValue().empty()) {
            WebService::Client client(Settings::values.web_api_url.GetValue(),
                                      Settings::values.yuzu_username.GetValue(),
                                      Settings::values.yuzu_token.GetValue());
```

2022-07-12 18:25 UTC, german77 commented on src/yuzu/multiplayer/host_room.cpp
> +#include "web_service/verify_user_jwt.h"
This file doesn't exist yet

2022-07-12 18:28 UTC, german77 commented on src/yuzu/multiplayer/chat_room.cpp
> +                                                 result.size()))
```suggestion
                                                 static_cast<uint>(result.size())))
```

2022-07-12 19:05 UTC, german77 commented on src/common/announce_multiplayer_room.h
> +        std::string game_name;
From my testing game update version is critical to guarantee success in the connection. It would be nice if it's displayed.

2022-07-12 21:27 UTC, german77 commented on src/common/announce_multiplayer_room.h
> +    virtual void AddPlayer(const std::string& username, const std::string& nickname,
Pass a `Member` object instead of the individual properties

2022-07-12 21:31 UTC, german77 commented on src/core/CMakeLists.txt
> +    internal_network/sockets.h
This needs to be moved up after hle/...

2022-07-12 21:42 UTC, german77 commented on src/network/network.cpp
> +// TODO(B3N30): Put these globals into a networking class
It's probably a good time to remove these globals

2022-07-12 21:57 UTC, german77 commented on src/network/room.h
> +constexpr u32 network_version = 4; ///< The version of this Room and RoomMember
This is the first version for yuzu. Unless the server backend also uses this value

2022-07-12 22:03 UTC, german77 commented on src/network/room.h
> +struct RoomInformation {
This struct has the same contents as AnnouceMultiplayerRoom::Room::Member, It's probably better to move it to common and share the same RoomInformation everywhere.

2022-07-12 22:05 UTC, german77 commented on src/network/room.h
> +struct GameInfo {
This can be moved to common as well. Add game update version since it's important.

2022-07-12 22:06 UTC, german77 commented on src/network/room.h
> +using MacAddress = std::array<u8, 6>;
This is already defined in AnnouceMultiplayerRoom

2022-07-12 22:08 UTC, german77 commented on src/network/room.h
> +    struct Member {
Use the member struct from `AnnouceMultiplayerRoom::Room`

2022-07-12 22:13 UTC, german77 commented on src/yuzu/configuration/config.cpp
> +void Config::SaveMultiplayerValues() {
This should go under SaveWebServiceValues. To keep stuff in the same order as they are declared

2022-07-12 22:14 UTC, german77 commented on src/yuzu/configuration/config.cpp
> +void Config::ReadMultiplayerValues() {
This should go under ReadWebServiceValues. To keep stuff in the same order as they are declared

2022-07-12 22:21 UTC, german77 commented on src/yuzu_cmd/yuzu.cpp
> +                 " Nickname, password, address and port for multiplayer\n"
If we add arguments here we should add them to the Qt version as well to keep everything consistent.

2022-07-12 22:24 UTC, german77 requested changes
Everything looks good. Needs some work on how the data room data is passed around the code

2022-07-15 23:51 UTC, german77 commented on src/common/announce_multiplayer_room.h
> +    u64 game_id;
```suggestion
    GameInfo game;
```

2022-07-15 23:52 UTC, german77 commented on src/common/announce_multiplayer_room.h
> +    u64 preferred_game_id;      ///< Title ID for the advertised game
```suggestion
    GameInfo preferred_game; ///< Game to advertise that you want to play
```

2022-07-22 02:33 UTC, FearlessTobi commented on dist/license.md
> +qt_themes/default/icons/16x16/connected.png | CC BY-ND 3.0 | https://icons8.com
I think they are, however since the Creative Commons license is non-revokable, it shouldn't be too big of an issue for now.

2022-07-22 14:32 UTC, FearlessTobi commented on src/yuzu_cmd/yuzu.cpp
> +                 " Nickname, password, address and port for multiplayer\n"
Narr and I have discussed this internally, and decided to postpone it to a follow-up PR.

2022-07-22 14:37 UTC, FearlessTobi commented
Compilation failure seems to be unrelated to this PR.

2022-07-23 06:31 UTC, bunnei approved these changes

2022-07-23 23:41 UTC, german77 approved these changes

2022-07-24 20:45 UTC, liamwhite requested changes
you also need to change all the license headers for the files you added

// SPDX-FileCopyrightText: Copyright 2022 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

2022-07-24 20:45 UTC, liamwhite commented on src/common/announce_multiplayer_room.h
> +    std::string verify_UID; ///< UID used for verification
verify_uid

2022-07-24 20:45 UTC, liamwhite commented on src/network/network.h
> +    std::shared_ptr<RoomMember> g_room_member; ///< RoomMember (Client) for network games
Should probably be m_room_member and m_room

2022-07-24 20:45 UTC, liamwhite commented on src/network/packet.h
> +    Packet& operator>>(bool& out_data);
iostreams-inspired interfaces aren't that great. Maybe the following would work?
```cpp
template <class... Types>
void ReadMany(Types&... t) {/*...*/}
template <class... Types>
void WriteMany(const Types&... t) {/*...*/}
```

2022-07-24 20:45 UTC, liamwhite commented on src/network/room.cpp
> +    /// This should be a std::shared_mutex as soon as C++17 is supported
we use c++20

2022-07-24 20:45 UTC, liamwhite commented on src/network/room.cpp
> +    mutable std::mutex verify_UID_mutex; ///< Mutex for verify_UID
verify_uid_mutex

2022-07-24 20:45 UTC, liamwhite commented on src/network/room.cpp
> +        char ip_raw[256];
shouldn't this be a uint8_t?

2022-07-24 20:45 UTC, liamwhite commented on src/network/room.h
> +    using UsernameBanList = std::vector<std::string>;
Maybe should be a set, for convenience of API use?

2022-07-24 20:45 UTC, liamwhite commented on src/network/room_member.cpp
> +    for (auto const& callback : callback_set)
missing braces

2022-07-24 20:45 UTC, liamwhite commented on src/yuzu/multiplayer/state.cpp
> +    if (host_room)
missing braces

2022-07-25 16:33 UTC, FearlessTobi commented on src/network/room.cpp
> +        char ip_raw[256];
`enet_address_get_host_ip` takes a char* as an argument, this is why it has that type.

2022-07-25 17:17 UTC, FearlessTobi commented on src/network/room.h
> +    using UsernameBanList = std::vector<std::string>;
I think for the sake of not complicating the Packet class further, it's okay to keep them as a vector for now.

2022-07-25 17:43 UTC, liamwhite reviewed
just one more thing

2022-07-25 17:43 UTC, liamwhite commented on src/network/room.cpp
> +        ip = ip_raw;
```suggestion
        std::array<char, 256> ip_raw{};
        enet_address_get_host_ip(&event->peer->address, ip_raw.data(), sizeof(ip_raw) - 1);
        ip = ip_raw.data();
```
and ditto for below

2022-07-25 18:36 UTC, FearlessTobi commented on src/network/room.cpp
> +        ip = ip_raw;
Done.

2022-07-25 18:38 UTC, liamwhite approved these changes

2022-07-25 22:31 UTC, merged