core, network: Add ability to proxy socket packets
yuzu-emu/yuzu pull request #8685
Opened 2022-07-30 17:49 UTC by FearlessTobi

This is the second part of a series of Pull Requests, aiming to bring multiplayer functionality to yuzu.
It adds the ability to proxy packets coming from our BSD socket implementation and therefore makes it possible to 
play "LAN-supported" games over the internet, without the need for external programs like Hamachi.
For routing it introduces the concept of "fake" ip-addresses. It is needed in order not to leak the users local ip-address and to make multi-instance multiplayer on the same device possible. 

The Pull Request also adds the dedicated-room build-target to make it easy for users to host their own server on either a local machine or a VPS.

Thanks a lot, especially to @german77 for helping me out a lot, @lat9nq for making the code compatible with Linux and everyone who helped me test the feature.

Please note that an LDN implementation is **not** part of this Pull Request.

2022-07-31 02:18 UTC, liamwhite requested changes

2022-07-31 02:18 UTC, liamwhite commented on src/core/internal_network/sockets.h
> +    SOCKET fd = INVALID_SOCKET;
Given that you just defined SOCKET and INVALID_SOCKET above, is this really necessary to conditionally compile?

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +// SPDX-FileCopyrightText: Copyright 2017 Citra Emulator Project
yuzu_room.cpp, yuzu_room.rc

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +    std::array<unsigned char, 512> output;
default initialize

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +    std::array<unsigned char, 512> output;
default initialize

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +    std::cout << "yuzu dedicated room " << Common::g_scm_branch << " " << Common::g_scm_desc
fmt::print

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Could not open ban list!\n\n";
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Ban list is not valid!\n\n";
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Could not save ban list!\n\n";
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +    file.flush();
It should automatically flush when going out of scope

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "max_members needs to be in the range 2 - "
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "port needs to be in the range 0 - 65535!\n\n";
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Ban list file not set!\nThis should get set to load and save room ban "
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "token is empty: Hosting a private room\n\n";
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "endpoint url is empty: Hosting a private room\n\n";
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +            std::cout << "Hosting a public room\n\n";
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +            std::cout << "Hosting a public room\n\n";
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Can not enable yuzu Moderators for private rooms\n\n";
LOG_WARNING

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +            std::cout << "Failed to create room: \n\n";
LOG_ERROR

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +        std::cout << "Room is open. Close with Q+Enter...\n\n";
LOG_INFO

2022-07-31 02:18 UTC, liamwhite commented on src/dedicated_room/yuzu-room.cpp
> +            std::this_thread::sleep_for(std::chrono::milliseconds(100));
I get that this is simpler than having a separate thread to wake you up when the room state changes or when new input is available from the console, but this is unpleasant.

2022-07-31 02:18 UTC, liamwhite commented on src/core/hle/service/nifm/nifm.cpp
> +void IGeneralService::CreateTemporaryNetworkProfile(Kernel::HLERequestContext& ctx) {
missing newline between function definitions

2022-07-31 13:02 UTC, lioncash commented on src/dedicated_room/yuzu-room.cpp
> +    Core::System system{};
It seems extremely suspect to need to construct the entire system state just to get the room network. Especially if that's all it's being used for

2022-07-31 13:02 UTC, lioncash commented on src/dedicated_room/yuzu-room.cpp
> +    if (port > 65535) {
```suggestion
    if (port > UINT16_MAX) {
```

2022-07-31 17:14 UTC, FearlessTobi commented on src/dedicated_room/yuzu-room.cpp
> +// SPDX-FileCopyrightText: Copyright 2017 Citra Emulator Project
Since this code was ported with minimal changes from Citra, the copyright header needs to be preserved.

2022-08-15 21:57 UTC, german77 approved these changes

2022-08-15 22:43 UTC, liamwhite approved these changes

2022-08-16 18:37 UTC, bunnei approved these changes

2022-08-16 18:49 UTC, merged

2022-08-17 15:05 UTC, unuruu5760 commented
Local play still not working in luigi's mansion 3 scarescraper.