ldn: Add better stubs and more data types
yuzu-emu/yuzu pull request #8731
Opened 2022-08-07 21:59 UTC by FearlessTobi

This PR brings better stubs to our LDN service, adds more data types and introduces error codes that will be needed in further PRs.

Thanks to @Morph1984 and @german77 for doing a lot of the heavy lifiting for this PR.

2022-08-07 22:35 UTC, liamwhite requested changes

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +#undef CreateEvent
?

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    if (rc.IsError()) {
condition is not possible

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    if (rc.IsError()) {
not possible

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    if (rc.IsError()) {
not possible

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    if (rc.IsError()) {
not possible

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    std::vector<NetworkInfo> networks_info{};
`network_infos` might be better

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    const auto security_config{rp.PopRaw<SecurityConfig>()};
Prefer to PopRaw once into a struct (will need a different struct definition for each possibility of is_private)

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    const auto network_Config{rp.PopRaw<NetworkConfig>()};
Wrong case

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    [[maybe_unused]] const auto securityConfig{rp.PopRaw<SecurityConfig>()};
Prefer to PopRaw once into a struct
Also `security_config`

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    NetworkInfo networkInfo{};
`network_info`

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +    std::vector<u8> read_buffer = ctx.ReadBuffer();
seems to be const

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +        LOG_ERROR(Service_LDN, "Network isn't initialized, rc={}", rc.raw);
Log this in InitializeImpl instead

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.cpp
> +        LOG_ERROR(Service_LDN, "Network isn't initialized, rc={}", rc.raw);
Log this in InitializeImpl instead

2022-08-07 22:35 UTC, liamwhite commented on src/core/hle/service/ldn/ldn.h
> +class IUserLocalCommunicationService final
Will this be used by code outside the service implementation? If not, consider moving to the .cpp file

2022-08-07 23:01 UTC, german77 commented on src/core/hle/service/ldn/ldn.cpp
> +    if (rc.IsError()) {
Most of these conditions contain the result of GetNetworkInfo. Which is not implemented in this PR

2022-08-08 13:03 UTC, lioncash commented on src/core/hle/service/ldn/ldn_types.h
> +public:
`public:` can be omitted here.

2022-08-08 13:03 UTC, lioncash commented on src/core/hle/service/ldn/ldn_types.h
> +    bool operator==(const SessionId& b) const {
This can be defaulted as:

```cpp
bool operator==(const SessionId&) const = default;
```

which has the benefit of auto-generating `operator!=` for logical symmetry

2022-08-12 12:39 UTC, liamwhite approved these changes

2022-08-12 12:40 UTC, merged