kernel: Add thread pinning on CPU exceptions.
yuzu-emu/yuzu pull request #8758
Opened 2022-08-13 05:02 UTC by bunnei

2022-08-13 09:44 UTC, merryhime commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        // Load KExceptionContext
I feel this would be more suited to being in `ReturnException`. (Also grab the correct pc; `thread_context.pc` would likely be out of sync.)

2022-08-13 14:34 UTC, liamwhite requested changes

2022-08-13 14:34 UTC, liamwhite commented on src/core/arm/arm_interface.cpp
> +            Kernel::Arch::Arm64::HandleException(system.Kernel(), exception_context_);
If HandleException takes the scheduler lock, then scheduling may occur here. This will change the current JIT state. This is important if the JIT was performing a syscall or stopping on a breakpoint, as it will cause the later function callsthat deal with breakpoints and syscalls to misbehave.

2022-08-13 14:36 UTC, liamwhite commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        // Load KExceptionContext
The intent is that this condition will be checked any time a thread returns from user mode. See [here](https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libmesosphere/source/arch/arm64/kern_exception_handlers.cpp#L551)

2022-08-13 15:02 UTC, merryhime commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        // Load KExceptionContext
Sure, but I think we only break execution ("return from user mode") if `ReturnException` is called.

2022-08-13 18:43 UTC, liamwhite commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        // Load KExceptionContext
It cannot occur in ReturnException because HandleException can take the scheduler lock, which may cause scheduling to occur and thus cause the JIT to be run again by a different KThread while this thread inside a callback.

2022-08-13 19:45 UTC, merryhime commented on src/core/arm/dynarmic/arm_dynarmic_64.cpp
> +        // Load KExceptionContext
Clearly HandleException cannot happen there. I was refering to the context loading.

2023-07-17 13:37 UTC, turbervillejoseph approved these changes

2023-12-06 15:42 UTC, closed without merging