network: Fixes and improvements to the room feature
yuzu-emu/yuzu pull request #8822
Opened 2022-08-27 03:02 UTC by FearlessTobi

This PR contains some small changes to improve the stability and UX of the yuzu rooms feature.
Please review commit-by-commit.

2022-08-28 03:21 UTC, Docteh commented
I looked through the 10 commits, eyes glazing over on the 7th but the rest all seems fine to me.

2022-08-28 04:34 UTC, liamwhite requested changes

2022-08-28 04:34 UTC, liamwhite commented on src/core/hle/service/ldn/ldn_types.h
> +    }
```suggestion
    u8 length{};
    std::array<char, SsidLengthMax + 1> raw{};

    Ssid() = default;

    Ssid(std::string_view data) {
        std::strncpy(raw.data(), data.c_str(), SsidLengthMax);
        length = static_cast<u8>(std::min(data.size(), SsidLengthMax));
    }
```
Is storing the length necessary if the string is null terminated?

2022-08-28 04:34 UTC, liamwhite commented on src/core/hle/service/ldn/ldn_types.h
> +        return (length == b.length) && (std::memcmp(raw.data(), b.raw.data(), length) == 0);
`operator==` is defined for std::array

2022-08-28 04:34 UTC, liamwhite commented on src/dedicated_room/yuzu_room.cpp
> +    }
```suggestion
    while (token.size() % 4 != 0) {
        token.push_back('=');
    }
```
where did 3 come from? the RFC says
```
                                                   Since all base64
   input is an integral number of octets, only the following cases can
   arise: (1) the final quantum of encoding input is an integral
   multiple of 24 bits; here, the final unit of encoded output will be
   an integral multiple of 4 characters with no "=" padding, (2) the
   final quantum of encoding input is exactly 8 bits; here, the final
   unit of encoded output will be two characters followed by two "="
   padding characters, or (3) the final quantum of encoding input is
   exactly 16 bits; here, the final unit of encoded output will be three
   characters followed by one "=" padding character.
```

2022-08-28 04:34 UTC, liamwhite commented on src/yuzu/multiplayer/chat_room.cpp
> +        return QStringLiteral("%1\n      %2 %3")
Do any of these need translation notes?

2022-08-28 05:26 UTC, Docteh commented on src/yuzu/multiplayer/chat_room.cpp
> +        return QStringLiteral("%1\n      %2 %3")
Qstringliteral avoids the translation layer, maybe the template used to combine strings could be made translatable? Could always wait for someone to ask for it...

2022-08-28 17:03 UTC, FearlessTobi commented on src/yuzu/multiplayer/chat_room.cpp
> +        return QStringLiteral("%1\n      %2 %3")
I don't think this needs a translation.

2022-08-28 17:32 UTC, FearlessTobi commented on src/core/hle/service/ldn/ldn_types.h
> +    }
Yes, as this struct has been taken from the Switch LDN service implementation.
Also, std::string_view doesn't support calling c_str() on it.

2022-08-28 20:39 UTC, liamwhite approved these changes

2022-09-01 03:36 UTC, lioncash commented on src/core/hle/service/ldn/ldn_types.h
> +    Ssid(std::string data) {
```suggestion
    explicit Ssid(std::string_view data) {
```

2022-09-01 03:36 UTC, lioncash commented on src/core/hle/service/ldn/ldn_types.h
> +        std::memcpy(raw.data(), data.data(), length);
```suggestion
        data.copy(raw.data(), length);
```

2022-09-01 03:36 UTC, lioncash commented on src/yuzu/multiplayer/chat_room.cpp
> +        if (version.isEmpty()) {
This if-else seems like it can just be collapsed to:

```cpp
if (!version.isEmpty()) {
    version_string = QStringLiteral("(%1)").arg(version);
}
```

since version_string will already be an empty string if `version` is empty because of how the default constructor for `QString` works.

2022-09-01 03:36 UTC, lioncash commented on src/yuzu/multiplayer/state.h
> +#include "core/core.h"
This include can be a forward declaration

2022-09-01 03:36 UTC, lioncash commented on src/yuzu/multiplayer/lobby.h
> +#include "core/core.h"
This can be a forward declaration

2022-09-01 03:36 UTC, lioncash commented on src/yuzu/multiplayer/host_room.h
> +#include "core/core.h"
This can be a forward declaration

2022-09-01 03:36 UTC, lioncash commented on src/yuzu/multiplayer/direct_connect.h
> +#include "core/core.h"
This can be a forward declaration

2022-09-02 17:24 UTC, bunnei approved these changes

2022-09-02 17:24 UTC, merged