Add option "Accept any Internet access"
yuzu-emu/yuzu pull request #8898
Opened 2022-09-13 15:33 UTC by noneistaken

This setting, which you can change at runtime unlike "Network Interface", is a workaround for Splatoon 3.
Along with the Project London pull request and the "Enable Auto-Stub" option enabled, this should allow the user to at least enter The Shoal and create a LAN lobby (not a LDN lobby which errors out for some reason).
I have not tested if this allows users to enter each others' games, since I don't have a computer with enough memory to run 2 Yuzu instances.

To elaborate on using this option/toggle:
- **Uncheck** "Accept any Internet access" and **check** "Enable Auto-Stub"
- Launch Splatoon 3
- Once you enter the game, **check** "Accept any Internet access"
- Enter the Shoal
- Hold ZL+ZR+Left Stick to enter LAN mode
- You should be able to create a room now.

2022-09-13 15:38 UTC, noneistaken commented
(The forced push was to get rid of a typo from porting these changes from Early Access to master.)

2022-09-13 16:16 UTC, noneistaken commented
Forgot to make this more clear, but one should rebase this to either the London pull request or Early Access for it to actually be useful.

2022-09-13 16:16 UTC, FearlessTobi requested changes
I'm not a big fan of this solution to be honest. 
For the most of the network requests, data from the network interfaces is needed for them to be sucessful.
Just reporting that internet is available, when there's no interface to make requests with is not a great solution.

This is also the reason why LDN doesn't work with your changes.

2022-09-13 16:20 UTC, noneistaken commented
> I'm not a big fan of this solution to be honest. For the most of the network requests, data from the network interfaces is needed for them to be sucessful. Just reporting that internet is available, when there's no interface to make requests with is not a great solution.
> 
> This is also the reason why LDN doesn't work with your changes.

I'm aware, this is only meant to be a workaround for those who do not wish to wait for a proper solution. If this isn't to your liking, please close the PR.

2022-09-21 18:02 UTC, noneistaken commented
Stale, closing

2022-09-21 18:02 UTC, closed without merging