YFC - Fermi2D: Rework blit engine and add a software blitter.
yuzu-emu/yuzu pull request #9194
Opened 2022-11-06 02:49 UTC by FernandoS27

This PR aims to fix the issues with ASTC texture mipmap uploads on many games. This has been a feature I've really wanted to be part of the original YFC release but I struggled long to get it working as I originally intended.

Originally, I was confused by our texture cache and I though games were actually rendering the ASTC mipmaps. It turns out that nope, the mipmaps were being uploaded through Fermi2D engine (since NVIDIA driver implements block linear to block linear texture copy with that). This puzzled me a lot initially but at the end I decided to add a software blitter as fallback when GPU acceleration is unnecessary. It still need tweaking and some features.

This fixes the texture corruption in a bunch of games:
- Blue Fire.
- A Hat in Time.
- The Witcher 3.
- Darksiders 3.
- Diablo II Resurrected (character hair).
- Dragon Quest XI.
- Life is Strange: True Colors.
- Yoshi's Crafted World.
-  Fist: Forged in Shadow Torched.
- likely other UE4 games.
- Kirby Start Allies: Depth of field.

Also fixes BGR issues in:
- Turok 2.
- Doom64
- Ys IX: Monstrum Nox.

It's still a draft and some work needs to be done.

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/blitter.cpp
> +void NeighrestNeighbor(std::span<u8> input, std::span<u8> output, u32 src_width, u32 src_height,
```suggestion
void NeighrestNeighbor(std::span<const u8> input, std::span<u8> output, u32 src_width, u32 src_height,
```

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/blitter.cpp
> +void NeighrestNeighborFast(std::span<f32> input, std::span<f32> output, u32 src_width,
```suggestion
void NeighrestNeighborFast(std::span<const f32> input, std::span<f32> output, u32 src_width,
```

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/blitter.cpp
> +void Bilinear(std::span<f32> input, std::span<f32> output, size_t src_width,
```suggestion
void Bilinear(std::span<const f32> input, std::span<f32> output, size_t src_width,
```

Maybe also leave a comment saying why this is included even though it's commented out.

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/blitter.cpp
> +    const auto process_pitch_linear = [](bool unpack, std::span<u8> input, std::span<u8> output,
```suggestion
    const auto process_pitch_linear = [](bool unpack, std::span<const u8> input, std::span<u8> output,
```

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/blitter.h
> +    SoftwareBlitEngine(MemoryManager& memory_manager_);
```suggestion
    explicit SoftwareBlitEngine(MemoryManager& memory_manager_);
```

2022-11-06 02:54 UTC, lioncash commented on src/video_core/engines/sw_blitter/converter.h
> +    virtual void ConvertTo(std::span<u8> input, std::span<f32> output) = 0;
This should also have a virtual destructor, otherwise it's undefined behavior to use this class polymorphically (which it is).

2022-11-06 02:54 UTC, FernandoS27 commented on src/video_core/engines/sw_blitter/blitter.cpp
> +void Bilinear(std::span<f32> input, std::span<f32> output, size_t src_width,
it's still a draft

2022-11-06 02:56 UTC, lioncash commented on src/video_core/engines/sw_blitter/converter.h
> +    virtual void ConvertTo(std::span<u8> input, std::span<f32> output) = 0;
It also seems like `input` can be a `std::span<const u8>` (unless I read all the cases wrong).

2022-11-06 02:56 UTC, lioncash commented on src/video_core/engines/sw_blitter/converter.h
> +#pragma once
This should go at the top of the file, otherwise the headers above it can be erroneously included twice.

2022-11-17 00:49 UTC, liamwhite requested changes

2022-11-17 00:49 UTC, liamwhite commented on src/video_core/engines/sw_blitter/blitter.cpp
> +void NeighrestNeighbor(std::span<const u8> input, std::span<u8> output, u32 src_width,
🐴

2022-11-17 00:49 UTC, liamwhite commented on src/video_core/engines/sw_blitter/converter.cpp
> +// SPDX-FileCopyrightText: Copyright 2022 yuzu Emulator Project
Commit the script used to generate converter.cpp in this directory to generate_converter.py, and provide instructions on how to run it.

2022-11-24 23:22 UTC, Morph1984 approved these changes

2022-11-25 02:47 UTC, liamwhite approved these changes

2022-11-25 02:48 UTC, merged

2022-12-01 07:44 UTC, Abyss777111 commented
there are no pokemons in the list and smt 5 there is also a texture problem