network: play together in different room
yuzu-emu/yuzu pull request #9213
Opened 2022-11-08 12:38 UTC by SmileYik

create a room named PostOffice, it accepts and forwards packets from a game room to another game room and made different room's players can play together.

2022-11-08 16:45 UTC, lioncash commented on src/network/room.h
> +    bool HasMailBox();
```suggestion
    bool HasMailBox() const;
```

2022-11-08 16:45 UTC, lioncash commented on src/network/room.cpp
> +bool Room::SetupMailBox(const std::string& server_address, u16 server_port) {
```suggestion
bool Room::SetupMailBox(std::string server_address, u16 server_port) {
```

2022-11-08 16:45 UTC, lioncash commented on src/network/room.cpp
> +    room_impl->post_office.address = server_address;
```suggestion
    room_impl->post_office.address = std::move(server_address);
```

2022-11-08 16:45 UTC, lioncash commented on src/network/room.cpp
> +        const u8 WaitPacket = 10; ///< Wait post office's reply max times.
If this is always const, it can be turned into a static constexpr member, making the struct a little smaller.

```suggestion
        static constexpr u8 WaitPacket = 10; ///< Wait post office's reply max times.
```

2022-11-08 16:45 UTC, lioncash commented on src/network/room_post_office.cpp
> +    RoomPostOfficeImpl() {}
```suggestion
    RoomPostOfficeImpl() = default;
```

2022-11-08 16:45 UTC, lioncash commented on src/network/room_post_office.cpp
> +        if (mailbox.peer)
This should be braced

2022-11-08 16:45 UTC, lioncash commented on src/network/room_post_office.h
> +#include <array>
A lot of the includes here seem like they can be moved into the cpp file, since a lot of these seem to be unused in the header.

2022-11-08 16:45 UTC, lioncash commented on src/network/room.cpp
> +inline void Room::RoomImpl::HandlePostOfficeConnection(const ENetEvent* event) {
Ditto

2022-11-08 16:45 UTC, lioncash commented on src/network/room.cpp
> +    post_office.address = "";
```suggestion
    post_office.address.clear();
```

2022-11-08 16:46 UTC, lioncash commented on src/network/network.cpp
> +        if (m_room_post_office->GetState() == RoomPostOffice::State::Open)
This should be braced

2022-11-08 19:03 UTC, FearlessTobi requested changes
Apart from issues with the code that were already pointed out above, I'm really trying to think of a usecase where this feature would really be useful or needed.
As far as I understand, the "post office" is meant to connect different rooms together, but I can't find many situations where you can't just make a bigger room to fit more players into it.

2022-11-08 23:02 UTC, SmileYik commented
> Apart from issues with the code that were already pointed out above, I'm really trying to think of a usecase where this feature would really be useful or needed.
> As far as I understand, the "post office" is meant to connect different rooms together, but I can't find many situations where you can't just make a bigger room to fit more players into it.

In China, players who use the campus network or other network providers' networks when playing Animal Crossing connect to a single operator's line room server, and it is easy to loss connection, made crash the island and lose their save progress due to the abnormal network of the player who joined the island.
And I think the online experience would be better when players connect to a room server that is more network-friendly to their own network and join other room's people's games while playing.

2023-08-21 19:59 UTC, FearlessTobi commented
Thank you for your contribution, but I don't think this code has the chance of being merged into yuzu anytime soon.
I understand the problem with connection losses, especially in China, but we need a different solution than this.

Thank you for your understanding.

2023-08-21 19:59 UTC, closed without merging