Add CPU core count to log files
yuzu-emu/yuzu pull request #9231
Opened 2022-11-11 20:17 UTC by goldenx86

[GetLogicalProcessorInformation](http://msdn.microsoft.com/en-us/library/ms683194) is used for Windows, which is a chore and a half.
Linux checks for the existence of SMT, as @liamwhite suggested.

2022-11-11 20:22 UTC, FearlessTobi commented
Should this maybe into common/cpu_detect?

2022-11-11 20:34 UTC, v1993 requested changes

2022-11-11 20:34 UTC, v1993 commented on src/yuzu/main.cpp
> +    std::ifstream smt("/sys/devices/system/cpu/smt/active");
This most definitely needs a change. Shouldn't you read contents contents of file to check if SMT is actually enabled (because you can turn it off by e.g. writing `0` to this very file)? And if you actually *don't* need to do that (seems unlikely to me), there are better ways for checking if files exists than trying to open it (not sure what exact FS API yuzu's code standards suggest to use here, I'd personally go with `std::filesystem::exists`).

2022-11-11 20:54 UTC, goldenx86 commented on src/yuzu/main.cpp
> +    std::ifstream smt("/sys/devices/system/cpu/smt/active");
What do you think of it now?

2022-11-11 21:03 UTC, v1993 commented on src/yuzu/main.cpp
> +    std::ifstream smt("/sys/devices/system/cpu/smt/active");
Looks reasonable. Have you verified that results are correct if you turn SMT off?

2022-11-11 23:32 UTC, goldenx86 commented on src/yuzu/main.cpp
> +    std::ifstream smt("/sys/devices/system/cpu/smt/active");
Yup, toast confirmed it with and without HT.

2022-11-11 23:35 UTC, v1993 approved these changes

2022-11-12 00:20 UTC, goldenx86 commented
Moved to common/x64/cpu_detect.

2022-11-12 02:29 UTC, Morph1984 commented on src/common/x64/cpu_detect.cpp
> +    }
```suggestion
    // Get the buffer length.
    std::vector<SYSTEM_LOGICAL_PROCESSOR_INFORMATION> buffer;
    DWORD length;
    GetLogicalProcessorInformation(nullptr, &length);
    if (GetLastError() != ERROR_INSUFFICIENT_BUFFER) {
        LOG_ERROR(Frontend, "Failed to query core count.");
        return std::nullopt;
    }
    list.resize(length / sizeof(SYSTEM_LOGICAL_PROCESSOR_INFORMATION));
    // Now query the core count.
    if (!GetLogicalProcessorInformation(buffer, &length)) {
        LOG_ERROR(Frontend, "Failed to query core count.");
        return std::nullopt;
    }
    return std::count_if(buffer.cbegin(), buffer.cend(), [](const auto& proc_info) { return proc_info.Relationship == RelationProcessorCore;  });
```

2022-11-12 03:16 UTC, lioncash approved these changes

2022-11-12 03:19 UTC, merged