shader: Implement miss attribute layer
yuzu-emu/yuzu pull request #9253
Opened 2022-11-17 14:48 UTC by vonchenplus

Fix Pokemon Scarlet/Violet Black screen.

![image](https://user-images.githubusercontent.com/3349963/202477742-1dc8fbe3-2671-4c0a-809b-2c67efc66710.png)

2022-11-17 14:54 UTC, liamwhite requested changes

2022-11-17 14:54 UTC, liamwhite commented on src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
> +        layer = DefineInput(*this, U32[1], false, spv::BuiltIn::Layer);
`layer` is already used for the output layer; theoretically if a stage both reads from and writes to the layer (e.g. with ShaderViewportIndexLayerEXT), wouldn't this cause problems? I would suggest defining a new variable as `input_layer` here.

2022-11-17 14:54 UTC, liamwhite commented on src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
> +        return ctx.OpBitcast(ctx.F32[1], ctx.OpLoad(ctx.U32[1], ctx.layer));
See comment about `input_layer`

2022-11-17 15:00 UTC, vonchenplus commented on src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
> +        layer = DefineInput(*this, U32[1], false, spv::BuiltIn::Layer);
According to the opengl documentation, there will be no simultaneous reading or writing

2022-11-17 23:24 UTC, liamwhite approved these changes

2022-11-19 03:04 UTC, merged

2022-12-14 22:24 UTC, yvancadi commented
can i get the link of thge game

2022-12-14 22:31 UTC, v1993 commented
> can i get the link of thge game

Sure! https://www.nintendo.com/store/products/pokemon-scarlet-switch/ and https://www.nintendo.com/store/products/pokemon-violet-switch/

2022-12-14 22:39 UTC, yvancadi commented
the link of the game on yuzu