Configuration: Add per-game input profiles
yuzu-emu/yuzu pull request #9273
Opened 2022-11-19 21:10 UTC by ameerj

This enables setting custom input profiles per-game. 

Per-game profiles also apply the controller type (i.e. Pro Controller, Handheld, GameCube) that was selected when the profile was saved.

This acts as a temporary compromise until proper Per-Game Input configurations are implemented.

![image](https://user-images.githubusercontent.com/52414509/202871502-f7df1104-3043-4c1b-845d-8c24510162d1.png)

2022-11-20 09:40 UTC, bunnei commented
Nice to see this change! Tagging for EA to get more eyes on this.

2022-11-20 12:31 UTC, Tachi107 commented on src/yuzu/configuration/configure_input_per_game.cpp
> +// SPDX-License-Identifier: GPL-2.0-or-later
Do these files really come from Citra or this is just a copy-paste thing?

2022-11-20 19:05 UTC, ameerj commented on src/yuzu/configuration/configure_input_per_game.cpp
> +// SPDX-License-Identifier: GPL-2.0-or-later
Good catch!

2022-11-20 21:04 UTC, BSoDGamingYT commented
This change while it seems great, doesn't seem to work as one would expect. 

For example...I am testing Pokemon Lets' Go, which only works with the handheld. So I make a profile for Handheld > select my controller > save the profile. 

Now when I load the game, it loads the profile and sets me to Handheld...but there is no input because there is no stored input device. For it to work, I need to go to configure > controls > manually set the input device (Dualsense controller)

2022-11-23 19:54 UTC, german77 commented
This PR seems to always select Handheld regardless of the current config or per game profile. From I can tell `IsCustomConfig()` always returns true even when no custom profile is set.

2022-11-23 22:13 UTC, ameerj commented
> This PR seems to always select Handheld 

Should be fixed now

> Also make the window a bit wider so it fits all tabs.

I don't have this issue on my monitor. If you have a fix feel free to push to this PR.

2022-11-23 23:34 UTC, german77 commented on src/yuzu/configuration/config.cpp
> +    }
```suggestion
    if (controller_type == Settings::ControllerType::Handheld) {
        Settings::values.use_docked_mode.SetValue(false);
    }
```
Altering the global state on read makes difficult to track since config file doesn't match with what really happens.

2022-11-23 23:59 UTC, german77 commented on src/yuzu/configuration/config.cpp
> +        Settings::values.use_docked_mode.SetGlobal(!IsCustomConfig());
```suggestion
```
I did a bit of testing. We don't need to change the global setting of docked mode. Since if a handheld profile is selected it will always be overridden with `docked=false` no matter the config. Otherwise we keep weird behaviors like always having handheld mode enabled as I described earlier.

If you really want to store the docked mode. I suggest to add an actual checkbox to Qt.

2022-11-24 00:14 UTC, german77 commented on src/yuzu/configuration/config.cpp
> +    WriteGlobalSetting(Settings::values.use_docked_mode);
```suggestion
    // Disable docked mode if handheld is selected
    const auto controller_type = Settings::values.players.GetValue()[0].controller_type;
    if (controller_type == Settings::ControllerType::Handheld) {
        Settings::values.use_docked_mode.SetGlobal(!IsCustomConfig());
        Settings::values.use_docked_mode.SetValue(false);
    } else {
        Settings::values.use_docked_mode.SetGlobal(true);
    }
    WriteGlobalSetting(Settings::values.use_docked_mode);
```
We can set the global state here when handheld is selected. To allow setting and restoring the config when the game is running or stopped.  

If any other profile is used other than handheld we should keep the global value. Otherwise we need to display this setting on the Qt interface to notify the user that it will be overridden by the custom config .

2022-11-24 00:18 UTC, german77 requested changes
Everything looks fine but docked mode needs to be fixed. See the individual comments.

2022-11-24 17:09 UTC, german77 approved these changes

2022-11-26 09:19 UTC, v1993 requested changes
Qt complains about duped entries yet again...

```
Automatic MOC and UIC for target yuzu
AutoUic: /home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout1'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout2'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout3'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout4'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout5'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout6'.
/home/v/compile/yuzu/src/yuzu/configuration/configure_input_per_game.ui: Warning: The name 'input_profile_layout' (QHBoxLayout) is already in use, defaulting to 'input_profile_layout7'.
```

2022-12-04 18:38 UTC, merged