shader_recompiler: add gl_Layer translation GS for older hardware
yuzu-emu/yuzu pull request #9363
Opened 2022-11-30 22:21 UTC by liamwhite

Should fix rendering of Pokemon Scarlet on Maxwell v1 and older Nvidia cards.

Also experimentally seems to fix it on RadeonSI (well, it displays _something_, whereas before it was just black), but RadeonSI reports support for GL_ARB_shader_viewport_layer_array even though it is broken, and I didn't bother to add another workaround for this particular case, since radv should be much better for this game anyway.

2022-11-30 22:25 UTC, goldenx86 commented
I suspect the AMD drivers have a similar issue. You don't get much out of the Windows driver in OpenGL.

2022-12-01 00:05 UTC, MysticExile commented
![Screenshot_2022-12-01_004843](https://user-images.githubusercontent.com/30736337/204934178-ed44d6f4-3e2f-4379-b319-422730170e20.png)
![Screenshot_2022-12-01_005812](https://user-images.githubusercontent.com/30736337/204934184-f88d5fff-1527-48b2-8571-746529d2fe30.png)
Confirmed that this fixes the <Maxwell V1 issues
Merging this PR will close #9264

2022-12-01 02:14 UTC, vonchenplus commented
We should only simulate when we need to use gl_layer, instead of simulating at any time

2022-12-01 02:15 UTC, liamwhite commented
@vonchenplus  Is this not sufficient?
```cpp
    if (requires_layer_emulation) {
        program.requires_layer_emulation = true;
        program.emulated_layer = emulated_layer;
        program.info.stores.Set(IR::Attribute::Layer, false);
        program.info.stores.Set(emulated_layer, true);
    }
}
```

2022-12-01 02:32 UTC, vonchenplus requested changes

2022-12-01 02:32 UTC, vonchenplus commented on src/shader_recompiler/ir_opt/layer_pass.cpp
> +    }
Move to CollectShaderInfoPass

2022-12-01 02:32 UTC, vonchenplus commented on src/shader_recompiler/frontend/ir/program.h
> +    bool requires_layer_emulation{};
move to program.info

2022-12-01 02:32 UTC, vonchenplus commented on src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
> +        .requires_layer_emulation = !device.IsExtShaderViewportIndexLayerSupported(),
rename to support_viewport_index_layer

2022-12-01 14:33 UTC, vonchenplus commented on src/shader_recompiler/frontend/maxwell/translate_program.cpp
> +    program.info.stores.Set(source_program.info.emulated_layer, false);
why want to store pre-stage layer_attr?

2022-12-01 14:33 UTC, vonchenplus commented on src/shader_recompiler/frontend/maxwell/translate_program.cpp
> +IR::Program GenerateLayerPassthrough(ObjectPool<IR::Inst>& inst_pool,
```suggestion
IR::Program GenerateGeometryPassthrough(ObjectPool<IR::Inst>& inst_pool,
```

2022-12-01 14:33 UTC, vonchenplus commented on src/shader_recompiler/ir_opt/layer_pass.cpp
> +    const auto emulated_layer = EmulatedLayerAttribute(program.info.stores);
```suggestion
    const auto layer_attribute = EmulatedLayerAttribute(program.info.stores);
```

2022-12-01 14:52 UTC, liamwhite commented on src/shader_recompiler/frontend/maxwell/translate_program.cpp
> +    program.info.stores.Set(source_program.info.emulated_layer, false);
This is removing it from the outputs.

2022-12-01 14:53 UTC, vonchenplus approved these changes

2022-12-02 19:08 UTC, merged