common: Add ScratchVector Class
yuzu-emu/yuzu pull request #9453
Opened 2022-12-16 05:37 UTC by ameerj

This class acts as a wrapper around `std::vector` for cases where default initialization is not needed.

It makes use of std::vector `reserve` instead of `resize`, since `resize` default initializes the underlying data, and has some overhead when reducing the size of the vector.

`reserve`, on the other hand, is a no-op unless the vector capacity is growing, so it avoids the user needing to check the size and skip resizing if the desired capacity is less than the current capacity.

The common use case for this would be in hot code where the vector is passed into a memcpy for reading or writing, especially when the buffer is reused during the lifetime of the owning object.

2022-12-16 06:21 UTC, lioncash requested changes
std::vector can't be used as a flat buffer, just because it has capacity allocated for it. stdlib assertions, if enabled, will cause this to abort, and in some cases. throw exceptions.

2022-12-16 06:21 UTC, lioncash commented on src/common/scratch_vector.h
> +class ScratchVector {
So, what is this supposed to add that a normal std::vector can't?

The interface doesn't seem to have a way to insert items into it directly, and just because the capacity is set doesn't mean you can freely index it like a flat buffer. If you enable stdlib assertions it'll abort on you for doing that in most cases (because it's undefined behavior), especially so if it's containing types that have a meaningful constructor.

If you need a scratch buffer, you're better equipped plunking these down into Common (until we move to C++23):

```cpp
template<class T>
requires (!std::is_array_v<T>)
std::unique_ptr<T> make_unique_for_overwrite()
{
    return std::unique_ptr<T>(new T);
}

template<class T>
requires std::is_unbounded_array_v<T>
std::unique_ptr<T> make_unique_for_overwrite(std::size_t n)
{
    return std::unique_ptr<T>(new std::remove_extent_t<T>[n]);
}

template<class T, class... Args>
requires std::is_bounded_array_v<T>
void make_unique_for_overwrite(Args&&...) = delete;
```

and just using them in tandem with `std::unique_ptr`, since they allow for the same thing without any of the drawbacks

2022-12-16 06:38 UTC, ameerj commented on src/common/scratch_vector.h
> +class ScratchVector {
How would you grow the buffer in this case? Having to free the old buffer, then reallocate a new bigger buffer has a significant perf impact. 
std::vector's reserve handles reallocations for growth much more efficiently.

2022-12-16 06:58 UTC, lioncash commented on src/common/scratch_vector.h
> +class ScratchVector {
That still doesn't change that what's being done here is undefined behavior and will literally make the program [abort](https://godbolt.org/z/5xhrz345c) over it) in certain instances.

If a growth factor is a concern, then that should be wrapped around a unique_ptr instead. std::vector is, by design, not meant to be used as a flat buffer without initialization and all three std lib implementations we use have assertion checks to make sure that stays the case. Regardless of how efficient it is, you cannot use std::vector for this purpose.

2022-12-19 18:14 UTC, ameerj commented
@liamwhite ping to request your review

2022-12-19 18:26 UTC, liamwhite commented on src/common/scratch_buffer.h
> +          buffer{std::make_unique_for_overwrite<T[]>(initial_capacity)} {}
Shouldn't these be Common::make_unique_for_overwrite?

2022-12-19 18:36 UTC, ameerj commented on src/common/scratch_buffer.h
> +          buffer{std::make_unique_for_overwrite<T[]>(initial_capacity)} {}
Good catch!

2022-12-19 23:50 UTC, lioncash commented on src/common/scratch_buffer.h
> +    [[nodiscard]] T& operator[](size_t i) {
This should probably also have a const variant

2022-12-19 23:50 UTC, lioncash commented on src/common/scratch_buffer.h
> +            buffer = Common::make_unique_for_overwrite<T[]>(buffer_capacity);
In the event an existing sized buffer gets further resized, this will obliterate data that was in the buffer, which is pretty unexpected

you likely want to transfer the existing data in the buffer over to the new larger allocated buffer using the ranged version of [std::move](https://en.cppreference.com/w/cpp/algorithm/move)

2022-12-20 00:28 UTC, ameerj commented on src/common/scratch_buffer.h
> +            buffer = Common::make_unique_for_overwrite<T[]>(buffer_capacity);
This was intentional since this is a scratch memory buffer, used for temporary data storage. Keeping the old data around adds overhead that is not necessary for the use cases I had in mind.

Would it be preferred instead that this class be a generic `NoInitVector`, and has two resize methods: one that keeps the data intact during resize, and one that obliterates it if the user does not care for it?

2022-12-22 23:44 UTC, liamwhite approved these changes

2022-12-25 01:26 UTC, merged