Add stacktrace symbol demangling
yuzu-emu/yuzu pull request #9613
Opened 2023-01-13 21:14 UTC by Kelebek1

Adds symbol demangling in the printed stacktrace for logs. Impl is LLVM's from https://github.com/llvm-mirror/llvm/tree/master/lib/Demangle which I think is compatible license-wise? 

![Untitled](https://user-images.githubusercontent.com/34639600/212420223-ccbe11e3-e834-4e61-8244-d1a02d07cdd6.png)

2023-01-13 21:18 UTC, Tachi107 commented
Instead of bundling the LLVM source files, why not link to libllvm?

2023-01-13 22:08 UTC, liamwhite commented
Bundling the entirety of libllvm wouldn't be useful on platforms that don't otherwise use llvm.

2023-01-13 22:21 UTC, Tachi107 commented
Makes sense... Apparently llvm's build script produces a standalone libLLVMDemangle static library, but you cannot tell it to only build a particular lib.

2023-01-14 02:19 UTC, liamwhite commented
Since this code is taken with minimal modifications from llvm, the relevant source files should live under externals/ instead src/common/.

2023-01-14 14:21 UTC, liamwhite commented on src/common/demangle.cpp
> +namespace llvm {
`#include <Demangle.h>`

2023-01-14 14:21 UTC, liamwhite commented on src/common/demangle.cpp
> +        return pos > 0 && pos <= 4 && name[pos] == 'Z';
pos > 0 is tautologically true because it is an unsigned type, therefore name[pos] can be an out of bounds array access

2023-01-14 14:21 UTC, liamwhite commented on src/core/arm/arm_interface.cpp
the `#include <cxxabi.h>` can be removed now

2023-01-14 16:57 UTC, liamwhite commented on src/common/demangle.cpp
> +    return ret;
Should be able to rewrite this as
```cpp
char* demangled = nullptr;
SCOPE_EXIT({ std::free(demangled); });

if (is_itanium(mangled)) {
   demangled = llvm::itaniumDemangle(mangled.c_str(), nullptr, nullptr, nullptr)
}

if (demangled) {
   return demangled;
} else {
   return mangled;
}
```

2023-01-14 19:34 UTC, Kelebek1 commented on src/common/demangle.cpp
> +namespace llvm {
Doesn't work, it can't be found.

2023-01-14 19:36 UTC, Kelebek1 commented on src/common/demangle.cpp
> +        return pos > 0 && pos <= 4 && name[pos] == 'Z';
I didn't write this code, it comes from llvm: https://github.com/llvm-mirror/llvm/blob/master/lib/Demangle/Demangle.cpp#L16

I just had to use my own version of it since we don't want the Microsoft stuff regardless or if Itanium is valid or not.

2023-01-14 19:54 UTC, Kelebek1 commented
I covered the out of bounds cases of size == 0 and pos being >= name.size, which I think are the only possible cases?

2023-01-14 20:01 UTC, merryhime commented on src/common/demangle.cpp
> +    return demangled;
Returning a `free`d pointer?

2023-01-14 20:35 UTC, liamwhite commented on src/common/demangle.cpp
> +namespace llvm {
I pulled your branch and it works fine for me...

2023-01-14 21:52 UTC, Tachi107 requested changes
Mostly licensing nitpicks. I have a question though, which version of LLVM are this files from? If these have been copied from the [llvm-mirror/llvm](https://github.com/llvm-mirror/llvm) repo they are a bit outdated, as development has been moved to [llvm/llvm-project](https://github.com/llvm/llvm-project) (in the `llvm` directory of the repo)

2023-01-14 21:52 UTC, Tachi107 commented on LICENSES/LLVM-exception.txt
> +==============================================================================
Including the full Apache License 2.0 + LLVM exception shouldn't be necessary; you can simply substitute this file with <https://github.com/spdx/license-list-data/blob/main/text/LLVM-exception.txt>

2023-01-14 21:52 UTC, Tachi107 commented on externals/demangle/Demangle.h
> +// SPDX-FileCopyrightText: Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
Listing the used license in `SPDX-FileCopyrightText` is redundant, as it's specified in `SPDX-License-Identifier`. I think that "Part of the LLVM Project" should suffice. (also applies to the other files)

2023-01-14 21:52 UTC, Tachi107 commented on externals/demangle/LICENSE.TXT
> +==============================================================================
Copying the license here too isn't needed, as everything is available in the top-level `LICENSES` directory

2023-01-22 16:53 UTC, liamwhite approved these changes

2023-01-22 18:13 UTC, merged