Move to Clang Format 15
yuzu-emu/yuzu pull request #9705
Opened 2023-01-29 20:54 UTC by behunin

Depends on https://github.com/yuzu-emu/build-environments/pull/69

2023-01-29 21:52 UTC, FearlessTobi requested changes
Please also update the Windows clang-format binary.

2023-01-29 22:55 UTC, behunin commented
> Please also update the Windows clang-format binary.

https://github.com/yuzu-emu/ext-windows-bin/pull/34

2023-01-29 23:34 UTC, liamwhite approved these changes

2023-01-30 00:52 UTC, Morph1984 approved these changes

2023-01-30 00:52 UTC, merged