YFC - Engines: Implement Accelerate DMA Texture.
yuzu-emu/yuzu pull request #9786
Opened 2023-02-12 02:31 UTC by FernandoS27

This implements host acceleration of the DMA engine. This is used in many games to download textures. Only implemented in Vulkan.

This improves performance in:
- Metroid Prime Remaster.
- Super Mario Sunshine.
- Super Mario Galaxy.

Among others.

2023-02-12 04:36 UTC, liamwhite commented
Regresses rendering in Super Mario Galaxy
![010049900f546003_2023-02-11_23-25-09-021](https://user-images.githubusercontent.com/9658600/218293193-17d401ea-1f3b-45ec-a397-52e6963201bf.png)

Intended is this
![010049900f546003_2023-02-11_23-35-41-066](https://user-images.githubusercontent.com/9658600/218293198-9101ada2-3821-484d-9fcd-6631b86b4a47.png)

2023-02-12 07:48 UTC, Kelebek1 commented on src/video_core/texture_cache/image_info.cpp
> +}
Aren't these all wrong? R16G16_UINT is 32 bits total, so only 4 bytes, not 8? Same with all the ones follwing this.R16G16B16A16_UINT is 64 bits -> 8 bytes, not 16.

2023-02-12 14:40 UTC, FernandoS27 commented on src/video_core/texture_cache/image_info.cpp
> +}
oh that code is a left over, it's not really used xD.

2023-02-12 14:43 UTC, Kelebek1 commented on src/video_core/texture_cache/image_info.cpp
> +}
> oh that code is a left over, it's not really used xD.

Looks like it is used? It's used set the image's format in ImageInfo::ImageInfo, `format` is used in various places.

2023-02-12 15:24 UTC, FernandoS27 commented on src/video_core/texture_cache/image_info.cpp
> +}
yeah but I always pass bytes per pixel as 1.

2023-02-12 16:17 UTC, FernandoS27 commented
> Regresses rendering in Super Mario Galaxy ![010049900f546003_2023-02-11_23-25-09-021](https://user-images.githubusercontent.com/9658600/218293193-17d401ea-1f3b-45ec-a397-52e6963201bf.png)
> 
> Intended is this ![010049900f546003_2023-02-11_23-35-41-066](https://user-images.githubusercontent.com/9658600/218293198-9101ada2-3821-484d-9fcd-6631b86b4a47.png)

I need a save for this.

2023-02-12 21:24 UTC, v1993 commented on src/video_core/texture_cache/util.cpp
> +            if (False(options & RelaxedOptions::FormatBpp)) {
Since there are no `else` blocks, how about merging these two `if`s into one?

2023-02-12 21:40 UTC, liamwhite commented on src/video_core/texture_cache/image_info.cpp
> +    rescaleable &= size.height > 256;
```suggestion
    rescaleable = block.depth == 0 && size.height > 256;
```

2023-02-12 21:40 UTC, liamwhite commented on src/video_core/texture_cache/image_info.cpp
> +        return PixelFormat::A8B8G8R8_UINT;
The others are RGBA, but this one is ABGR

2023-02-13 09:27 UTC, FernandoS27 commented on src/video_core/texture_cache/image_info.cpp
> +        return PixelFormat::A8B8G8R8_UINT;
doesn't matter

2023-02-18 03:14 UTC, gidoly commented
![yuzu-msvc-verify-pr09786-20230212-5a226fc27_8yupgUuAMf](https://user-images.githubusercontent.com/66776795/219828792-c9f3fcee-c375-4bea-9ede-ceaffdde2ddd.jpg)
breaks shinmegami tensei 5 graphic when using gpu normal for loading area

2023-02-20 04:22 UTC, ameerj requested changes

2023-02-20 04:22 UTC, ameerj commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +        image->ScaleDown(true);
You scale down but never scale back up

2023-02-20 04:22 UTC, ameerj commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    };
A lot of this boilerplate can be deduplicated between `ImageToBuffer` and `BufferToImage` and should not be Vulkan specific. 

You should be able to move these functions out to buffer or texture cache. Then you can make a `BufferImageCopy` and use the existing `Image::UploadMemory` and `Image::DownloadMemory` functions.

2023-02-20 07:26 UTC, FernandoS27 commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    };
To be frank, I just took the experimental code from yfc 2 and published it. As I didn't have time to refactor. These are all valid points but I'll likely leave most of it for a future refactor.

2023-02-20 07:27 UTC, FernandoS27 commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +        image->ScaleDown(true);
It's intended but I'll revise this behavior.

2023-02-24 14:24 UTC, liamwhite commented
Breaks star bit interactions in Super Mario Galaxy on Nvidia Turing
https://user-images.githubusercontent.com/9658600/158484032-f81ea05b-73fa-4552-b24c-a09256dd4c61.mp4

AMD is unaffected

2023-03-05 10:00 UTC, FernandoS27 commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    };
I'll leave this for a further PR.

2023-03-05 14:09 UTC, liamwhite approved these changes

2023-03-05 14:30 UTC, merged