Re-add the invalidate_texture_data_cache register
yuzu-emu/yuzu pull request #9802
Opened 2023-02-14 00:24 UTC by Kelebek1

This register seems to be real, and stops the undefined behaviour flickering on XC3 terrain. This seems to have been removed by accident.

2023-02-14 00:46 UTC, liamwhite approved these changes

2023-02-14 01:24 UTC, vonchenplus requested changes

2023-02-14 01:24 UTC, vonchenplus commented on src/video_core/engines/maxwell_3d.cpp
> +    case MAXWELL3D_REG_INDEX(invalidate_texture_data_cache):
Add invalidate_texture_data_cache method to IsMethodExecutable, Otherwise method will not be invoke

2023-02-15 01:13 UTC, vonchenplus approved these changes

2023-02-15 05:27 UTC, goldenx86 commented
Testing seems to show this is a partial solution.
Depending of camera angles, the behaviour changed from showing a mix of both textures, to showing only one of them.

![1](https://user-images.githubusercontent.com/42481638/218940501-19fd05b3-0de9-4aa5-8626-23ad3d69eaa8.png)
![2](https://user-images.githubusercontent.com/42481638/218940506-77671283-64b8-40d4-92a3-8981502e0cb3.png)

Here's the same wall texture in Breath of the Wild, just at different camera angles.

2023-02-15 13:06 UTC, AaronKelley commented
I did a build based on this PR for testing myself, and it seems to have made things notably better in XC3, but like @goldenx86 said it's a partial solution.  Some spots where I was able to reproduce terrain flickering before seem to have been fixed, but I'm still able to spot some.  It seems more like geometry flickering than texture flickering most of the time, though, so it might be a different issue...  (I cannot reproduce it in OpenGL, only Vulkan.  2× scaling / high accuracy, GeForce RTX 3080 Ti.)

![Animation2](https://user-images.githubusercontent.com/404829/219035083-ba24f52e-8bea-4c89-8c56-a7bc29f0e95b.gif)
![Animation1](https://user-images.githubusercontent.com/404829/219035063-34f35467-3ad3-49cc-b6cb-244193fb06a3.gif)

2023-02-16 20:27 UTC, bunnei approved these changes

2023-02-16 20:27 UTC, merged