Partial LTO
yuzu-emu/yuzu pull request #9872
Opened 2023-02-27 04:13 UTC by goldenx86

To save on RAM, and even improve performance a little bit, let's enable LTO only in the 2 critical projects that need it, core and video_core.

2023-02-27 09:19 UTC, FernandoS27 commented
Squash those commits. You are over commiting for a few miserable lines.

2023-02-27 21:01 UTC, FernandoS27 requested changes
Squash the commits and rebase like a normal human being (don't merge master, use git rebase for god's sake)

2023-02-27 21:46 UTC, FernandoS27 approved these changes

2023-02-27 22:26 UTC, goldenx86 commented
> Squash the commits and rebase like a normal human being (don't merge master, use git rebase for god's sake)

Ur ugly.

2023-02-27 22:38 UTC, merged

2023-02-28 00:56 UTC, Moonlacer commented
> > Squash the commits and rebase like a normal human being (don't merge master, use git rebase for god's sake)
> 
> Ur ugly.

I second this motion

2023-02-28 01:27 UTC, jbeich commented on .ci/templates/build-msvc.yml
> +- script: refreshenv && mkdir build && cd build && cmake -E env CXXFLAGS="/Gw /GA /Gr /Ob2" cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_POLICY_DEFAULT_CMP0069=NEW -DENABLE_LTO=ON -DYUZU_USE_BUNDL
Still uses `ENABLE_LTO` after it was renamed to `YUZU_ENABLE_LTO`